### ISSUE TITLE
Google Chrome Recognizes as Malware

### ISSUE THREAD

**Issue by wjdavis5** [Screetsec/TheFatRat#1]
I zip up the resulting .EXE (generated one for Windows) and emailed it to myself. When I try to download it, google chrome recognizes the zip file as malware

![image](https://cloud.githubusercontent.com/assets/2580575/17281729/f2f840b0-576b-11e6-85dc-fbd57a3191e6.png)

**Comment by Screetsec** [comment]
what you use ? slowbutpowerfull ?

**Comment by Screetsec** [comment]
if you choose number 1 , its just create backdoow with msfvenom not bypass av ( standart )  . 
i will update fatrat for custom encoding msfvenom . still waiting yaaa

**Comment by cacaocaca** [comment]
I have look this problem first with myself Google watch your file .exe  and look it as no secure becouse nobody have download it and  this file no is famous so you can solve if zip again 2 time  if google look  again as no secure change compression no use zip but use always 2 time if you want be more secure ;)

**Comment by cacaocaca** [comment]
Screetsec virustotal is Google https://en.wikipedia.org/wiki/VirusTotal do you think when you download virus with chrome he distribute sample as virustotal ?

**Comment by SNDTiger** [comment]
i have only one word !

Fuck Virus-Total

Wait! they was 2 words :p
