### ISSUE TITLE
external 

### ISSUE THREAD

**Issue by tidilihatim** [Screetsec/TheFatRat#10]
hi thx for your great work , i have a qst is this working with exetrnal pc/mobile(android) bcz i try it with external mobile and it's not working even if i change my local ip to external ip :/ ps:its work great with local phone

**Comment by Screetsec** [comment]
read port forwading

**Comment by tidilihatim** [comment]
I already have two port open 4444/4547 and i check it in canyouseeme me its open and i already test it with another backdoor its work but when i test it witk apk its not working for external phones :/
