### ISSUE TITLE
aarch64

### ISSUE THREAD

**Issue by godimdhruv** [Screetsec/TheFatRat#100]
Plz solve this issue I m using kali nethunter in yureka plus arm 64
the problem which shows on my screen after type command chmod +x setup.sh && ./setup.sh
"System will not proceed because none of the architecture are present
X86_64 l i386 l i486 l i586 li686
Report This arch : aarch64 into fatrat issue on github
Press any key to continue"

**Comment by peterpt** [comment]
execute on your fatrat folder while connected to internet : 
chmod +x update && ./update && chmod +x setup.sh && ./setup.sh

and everything will be fine .
Thanks for posting your device architeture .

**Comment by godimdhruv** [comment]
its get updated but still same problem persist, please help. SS of my
screen is attached.
Thank you for your reply

On May 5, 2017 11:17 AM, "peterpt" <notifications@github.com> wrote:

execute on your fatrat folder while connected to internet :
chmod +x update && ./update && chmod +x setup.sh && ./setup.sh

and everything will be fine .
Thanks for posting your device architeture .

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Screetsec/TheFatRat/issues/100#issuecomment-299385676>,
or mute the thread

**Comment by godimdhruv** [comment]
its get updated but still same problem persist, please help. SS of my
screen is attached.
Thank you for your reply
![Uploading Screenshot_20170505-160224.png…]()
![screenshot_20170505-160418](https://cloud.githubusercontent.com/assets/28412670/25746481/5621fb24-31c1-11e7-83a2-3b2aa29cd968.png)

**Comment by peterpt** [comment]
just to test , write on fatrat folder : 
git pull

and execute ./setup again .

**Comment by godimdhruv** [comment]
![screenshot_20170505-184031](https://cloud.githubusercontent.com/assets/28412670/25746772/8c3ca802-31c2-11e7-8626-f1e046795cfd.png)
![screenshot_20170505-184120](https://cloud.githubusercontent.com/assets/28412670/25746811/b2c2c2d6-31c2-11e7-8a86-f73bfb786f74.png)

**Comment by godimdhruv** [comment]
Still : (

**Comment by peterpt** [comment]
interesting .
write on your kali terminal this : 

uname -m

and post here the print screen .

But before that , write ./update again on fatrat folder .

**Comment by godimdhruv** [comment]
![screenshot_20170505-190205](https://cloud.githubusercontent.com/assets/28412670/25747537/6d3e1f64-31c5-11e7-844c-d4518faa7970.png)

**Comment by peterpt** [comment]
humm .
we have to do some changes first .

**Comment by godimdhruv** [comment]
tell me what I have to do to make it run I ll follow whatever steps you say

**Comment by peterpt** [comment]
wait , no stress .
Connect to internet and write in fatrat folder again : 
1st -  git pull
2nd - ./setup.sh

then get the print screen from your terminal here .
I am doing changes in realtime here to fatrat scripts , so everytime i make any change you have to update your fatrat like i write before .

**Comment by godimdhruv** [comment]
![screenshot_20170505-193012](https://cloud.githubusercontent.com/assets/28412670/25748654/7282b166-31c9-11e7-9e3f-c4ec321ce1cb.png)
![screenshot_20170505-193122](https://cloud.githubusercontent.com/assets/28412670/25748679/7f2ab7e2-31c9-11e7-9b32-1b79ff3c2860.png)

**Comment by peterpt** [comment]
well , for some unknow reason your fatrat was not updated and i have no idea what is the problem .
To solve this problem you have to delete your fatrat folder and clone everything again from github .
I say this because my latest changes do not appear in your latest run , and the problem is not on fatrat , but somehow there .

Latest changes i made , the setup script should inform you if you were connected to internet , and by your print screen it does not show anything .
This means that your files are still in same position like you cloned the first time .
We had a previous issue minutes ago with arm7 devices that user was able to update his atrat properly and setup script continued : 
https://github.com/Screetsec/TheFatRat/issues/101

Remove your curent fatrat folder and clone everything again from github .
The proceed with the normal instalation procedures .

To do that , do like this .
get out from your current fatrat directory and write :  

1st - rm -rf TheFatRat
2nd - git clone https://github.com/Screetsec/TheFatRat.git
3rd - chmod +x setup.sh
4th - ./setup.sh

**Comment by godimdhruv** [comment]
I m outside home and not on wifi can I get u you later after installing it again in an hour or so

**Comment by peterpt** [comment]
i will check this here again later .

**Comment by godimdhruv** [comment]
![screenshot_20170507-070915](https://cloud.githubusercontent.com/assets/28412670/25777340/217c6c3c-32f8-11e7-9c83-237549130337.png)
![screenshot_20170507-071108](https://cloud.githubusercontent.com/assets/28412670/25777344/47282188-32f8-11e7-9b67-9225ec391b16.png)
![screenshot_20170507-071136](https://cloud.githubusercontent.com/assets/28412670/25777353/92839360-32f8-11e7-8e02-b48755bf0c98.png)
__
![screenshot_20170507-071136](https://cloud.githubusercontent.com/assets/28412670/25777358/ba00f3f6-32f8-11e7-967e-ec120b9e3398.png)
![screenshot_20170507-071150](https://cloud.githubusercontent.com/assets/28412670/25777364/defdbe1e-32f8-11e7-8078-3ae41b0102cd.png)
![screenshot_20170507-071448](https://cloud.githubusercontent.com/assets/28412670/25777368/17a75a7c-32f9-11e7-8697-8685402ef1b9.png)
![screenshot_20170507-071638](https://cloud.githubusercontent.com/assets/28412670/25777379/498b9b8e-32f9-11e7-80e3-9741ac018873.png)
![screenshot_20170507-071721](https://cloud.githubusercontent.com/assets/28412670/25777384/5ecae4be-32f9-11e7-97fb-de3d3777d249.png)
![screenshot_20170507-073209](https://cloud.githubusercontent.com/assets/28412670/25777391/8523b636-32f9-11e7-9f40-4e86220c8371.png)
![screenshot_20170507-073352](https://cloud.githubusercontent.com/assets/28412670/25777397/a6024c78-32f9-11e7-9da4-9326f26f4c56.png)

**Comment by peterpt** [comment]
fatrat was not builded to run over a terminal window .
It is more than obvious (if you think a little) , that windows from Xterm and zenity will not popup under that current environment .
Is basically the same thing as you try to open from that shell a firefox window .
You cant !!!

To install an run fatrat on your that android system , you must connect thru a vnc client to a session from your android to your kali in your android , and then setup and run fatrat from there .

https://forums.kali.org/showthread.php?25351-How-to-remote-desktop-your-Nethunter-from-other-linux-Desktop

this topic was created by me sometime ago , but the same way you connect from any other desktop to your nethunter , you will also be able to connect with an vnc client app grom google play to a session on your device .
And then from there you can run any graphic program in your linux device .

I though that you knew that .

**Comment by godimdhruv** [comment]
now a new problem arises as I run setup.sh everything went fine untill the last step all tools installed except mingw32 I tried 3-4 time but still problem persist

**Comment by godimdhruv** [comment]
![screenshot_20170508-235607](https://cloud.githubusercontent.com/assets/28412670/25819320/3ad47edc-344b-11e7-833a-76e271752dd0.png)

**Comment by peterpt** [comment]
what is your OS distribution ?

**Comment by godimdhruv** [comment]
![screenshot_20170509-022344](https://cloud.githubusercontent.com/assets/28412670/25824949/b017aeae-345e-11e7-9ad9-ae348d50482b.png)

**Comment by godimdhruv** [comment]
My cpu is arm 64 but I m using kali in phone yureka plus via nethunter

**Comment by godimdhruv** [comment]
android:/root/Desktop # su   
root@kali:~/Desktop# cat /proc/version
Linux version 3.10.105-AR_Beast���-R4 (root@kali:~/Desktop# cat /etc/*-release
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2017.1"
VERSION_ID="2017.1"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.kali.org/"
SUPPORT_URL="http://forums.kali.org/"
BUG_REPORT_URL="http://bugs.kali.org/"
root@kali:~/Desktop# cat /proc/version
Linux version 3.10.105-AR_Beast���-R4 (Ayush@Beast) (gcc version 6.3.1 20170226 (UBERTC-6.x.x) ) #1 SMP PREEMPT Thu Apr 13 15:15:19 IST 2017
root@kali:~/Desktop# uname -m
aarch64
root@kali:~/Desktop# lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling
root@kali:~/Desktop# arch
aarch64

**Comment by godimdhruv** [comment]
Mingw installed by this command. 
apt-get install -f

**Comment by godimdhruv** [comment]
![screenshot_20170509-085519](https://cloud.githubusercontent.com/assets/28412670/25835795/702968b4-349f-11e7-8448-128a7ee79345.png)

**Comment by godimdhruv** [comment]
![screenshot_20170509-094253](https://cloud.githubusercontent.com/assets/28412670/25836578/a791072a-34a5-11e7-821d-e6f07bebefd1.png)

**Comment by peterpt** [comment]
post here your config file from fatrat.
It is located in config/config.path

**Comment by godimdhruv** [comment]
********************************************************************************************************
** Configuration Paths for TheFatRat , do not delete anything from this file or program will not work **
**       if you need to reconfig your tools path , then run ./setup.sh in (TheFatRat directory) .     **
********************************************************************************************************
jarsigner
unzip
keytool
/root/TheFatRat/tools/android-sdk/zipalign
/root/TheFatRat/tools/proguard5.3.2/lib/proguard
/root/TheFatRat/tools/android-sdk/dx
/root/TheFatRat/tools/android-sdk/aapt
/root/TheFatRat/tools/apktool2.2.2/apktool
d2j-dex2jar
msfconsole
msfvenom
backdoor-factory
searchsploit

**Comment by godimdhruv** [comment]
![screenshot_20170509-141933](https://cloud.githubusercontent.com/assets/28412670/25848522/580a9116-34d8-11e7-907c-2ceb664b6ed7.png)

**Comment by peterpt** [comment]
that is a minor bug , i will correct it in some hours .

**Comment by godimdhruv** [comment]
![screenshot_20170509-164612](https://cloud.githubusercontent.com/assets/28412670/26022201/f6c6a15c-378d-11e7-80e3-ce8799e159e6.png)

**Comment by peterpt** [comment]
The script running at that stage is backdoor apk , and by the error , it looks that "msfvenom is not working properly in your device .

In your terminal write "msfvenom" to see if it opens independently .

However , the new version of fatrat that we are building we will get rid of zenity and fatrat will be fully terminal mode .

**Comment by godimdhruv** [comment]
![screenshot_20170513-123727](https://cloud.githubusercontent.com/assets/28412670/26023447/fe5b66a6-37aa-11e7-9982-a3ba27f51416.png)
It will be awasome fatrat purely in terminal

**Comment by godimdhruv** [comment]
Is this the problem

**Comment by peterpt** [comment]
no , msfvenom is running independently .

Now , do 2 things .

1st : post at pastebin the full content of apk.log in /logs folder in fatrat
https://pastebin.com/

2nd : post also the full content of your config.path file in /config folder of fatrat in another pastebin file .

Then drop here the both links from pastebin

**Comment by godimdhruv** [comment]
https://pastebin.com/wKZYsqgc
https://pastebin.com/fxsaqHUY

**Comment by peterpt** [comment]
Ok , now we are getting somewhere .
According to apk log , it popup a error about the payload you selected .

I need you to do these things : 

1st - look in /config folder , there should be there a file called apk.temp .
I need you to post the content of that file here (you can omit your ip /domain when posting here) 

2nd - I need you to try another payload to see if the same error appears .

Note : apk.tmp file it is still there and it is only deleted when you start to compile another rat.apk file .

(basically i need to know which payload was and if all data in that file it is in their specific order .)

After this point if we can get anywhere , then "if possible" , post here the apk so i can try here , and the payload you selected that gave you that error .

**Comment by godimdhruv** [comment]
https://pastebin.com/2bTvTEjW

**Comment by godimdhruv** [comment]
Sure i ll btw i really appriciate what u are doing ...thanx man for ur help😊

**Comment by godimdhruv** [comment]
Sorry wait a sec dont try that link

**Comment by godimdhruv** [comment]
I dont followed ur steps i ll make sure i do it as u say

**Comment by peterpt** [comment]
according to that last link , the payload was not in the config file where backdoor apk will read .
I  need to do these tests to determine if it is a bug or anything else .
Try the first payload on zenity when it pops up .

**Comment by godimdhruv** [comment]
![screenshot_20170513-222136]
![_20170518_090025](https://cloud.githubusercontent.com/assets/28412670/26185929/81387fa2-3b7d-11e7-9d8d-246d1e280941.JPG)
(https://cloud.githubusercontent.com/assets/28412670/26185732/4dd091b4-3b7c-11e7-9ae8-d512335f576b.png)
![screenshot_20170513-223310](https://cloud.githubusercontent.com/assets/28412670/26185758/6cc685ce-3b7c-11e7-9ba1-cacf90c61c73.png)
![screenshot_20170514-154605](https://cloud.githubusercontent.com/assets/28412670/26185884/2d02c8fc-3b7d-11e7-9b84-42a1eeed1780.png)

**Comment by peterpt** [comment]
dont write apk for file extension .
Fatrat only asks you for the name of the file you want to create .
Never in fatrat put the extension ahead of filename , because fatrat will do that automatically .

Eventually , the issue may be related to zeinity variable not been grab somehow because you are working on a remote device , that can influence some how the error , my advice to you is to wait a bit for 1.9.4 version .
1.9.4 will not have zenity .

**Comment by Hades44** [comment]
Plz brother help me..I'm using kali nethunter am facing some problems to install fatrat..Am not able to install DX,Aapt,Apktool..
Plz brother's help me..how can I fix this problem!!

**Comment by hardik708012** [comment]
Hello i have some problame an installing thefatratmaster in my kali nethunter i am using
Redmi note 3
