### ISSUE TITLE
No Internet Connection 

### ISSUE THREAD

**Issue by DeakRDR** [Screetsec/TheFatRat#102]
![screenshot_20170505-232104](https://cloud.githubusercontent.com/assets/19996103/25753615/c7e28d3c-31ee-11e7-84d7-d6ca748bc33d.png)

I just cloned TheFatRat and I'm getting this **No Internet Connection** when I'm doing setup.sh

**Comment by peterpt** [comment]
try on terminal : 
ping google.com

**Comment by DeakRDR** [comment]
![screenshot_20170506-095235](https://cloud.githubusercontent.com/assets/19996103/25769012/12ba60ac-3242-11e7-8ffa-949bfbee8467.png)

**Comment by peterpt** [comment]
You have some problem in your dns forwarder from your router .
The problem you are experiencing is not related with fatrat .

**Comment by DeakRDR** [comment]
I can actually open Google in browser... I can browse web normally... I have pretty good wifi ..

**Comment by peterpt** [comment]
look , the problem you have is not related to fatrat , you should search over internet why you can not ping the hostname , we do not give support for problems on your OS that are not related to our tool .
https://askubuntu.com/questions/455338/ping-unknown-host-google-com-but-ips-works-fine
