### ISSUE TITLE
Press any key to continue

### ISSUE THREAD

**Issue by Kaicastledine** [Screetsec/TheFatRat#109]
Hello,

Another small bug that I've found.

![image](https://cloud.githubusercontent.com/assets/11678433/25888767/50d6bffa-355f-11e7-9513-7e1a73f93bce.png)

Will only register "Enter" any of the other keys don't continue.

Kind Regards

**Comment by peterpt** [comment]
There are a lot of simple bugs that need to be fixed .
I personally already found a few more complicated that that one .
However , we will fix it in next version .
