### ISSUE TITLE
Cleanup Option 

### ISSUE THREAD

**Issue by Kaicastledine** [Screetsec/TheFatRat#110]
Hello,

When confirming to cleanup payload folders if you enter  Y instead of y The program exits.

Kind Regards

**Comment by peterpt** [comment]
yup , i missed that option when i was fixing that issue .
However , i will not fix it now .
It will be fixed in 1.9.4 version that we are building .
That and other "real" issues posted here will be fixed in next version .
Thanks for pointing that out .

**Comment by Kaicastledine** [comment]
Thats fine just thought id raise anything I found as I went along.

 Many thanks
