### ISSUE TITLE
Armv7

### ISSUE THREAD

**Issue by DeakRDR** [Screetsec/TheFatRat#111]
Just got rid of **No internet Connection** issue by going into VNC then running setup.sh

But now this.....
![screenshot_20170510-185149](https://cloud.githubusercontent.com/assets/19996103/25896537/1f3676d6-35b7-11e7-98dd-f0c44d4eb31f.png)

And I also tried that Command it gave me but didn't work too

**Comment by peterpt** [comment]
apt-get remove --purge mingw32 && apt-get remove --purge mingw-w64 && apt-get install -f -y && apt-get autoremove 

Then execute setup again .

**Comment by jeycamon** [comment]
Amigos me ayudan a solucionar esto ????
![screenshot_2017-09-30-14-37-53](https://user-images.githubusercontent.com/32280482/31048874-03d74f40-a5ed-11e7-8f71-196efca6e4f2.png)

**Comment by peterpt** [comment]
We do not give support for Armv6 and Armv7 devices , which is your case .
Buy a computer , install linux and then install fatrat there .
