### ISSUE TITLE
Fatrat Generate Backdoor Error

### ISSUE THREAD

**Issue by HarindraSanka** [Screetsec/TheFatRat#115]
When I'm trying to create a backdoor using option number 5 (creating a backdoor using original APK)
I'm getting this error:-
[!] Check your environment and configuration. Couldn't find: d2j-jar2dex
Press any key to continue to return to fatrat menu

Please Help.
Thanks!
![fatrat err](https://cloud.githubusercontent.com/assets/28838847/26284105/1ae97e32-3e51-11e7-829c-f5cf98c8ea7c.jpg)

**Comment by peterpt** [comment]
provide the file config.path in your "config" folder .
For that error to appear is because there was an error in setup script .

use pastebin.com to post data of the file .
