### ISSUE TITLE
Can't Connect to internet

### ISSUE THREAD

**Issue by eraxtr4** [Screetsec/TheFatRat#116]
i following the  tutorials after use this command "chmod +x setup.sh && ./setup.sh" always apear 

"Checking for internet connection
  You are not connected to the Internet
  This script requires an active Internet connection"

my connection is good and work fine, but when i trying to install always failed to connect my internet .. can you fix this issue ? and explain to me step by step how to fix this

**Comment by peterpt** [comment]
write on your terminal : 

ping -c 1 google.com

and get a print screen from the output and post it here .

Then after that write this command : 

ping -c 1 8.8.4.4 

and get a print screen again from the output and post it here .

**Comment by kdelia12** [comment]
got same problem help me

**Comment by kdelia12** [comment]
![image](https://cloud.githubusercontent.com/assets/27549262/26516051/329dcdfe-42ab-11e7-91a6-e6b5b0398f9d.png)
 help

**Comment by peterpt** [comment]
well , you really have a problem in your OS on the routing interface .
if you can not ping a server then how do you expect setup script  be able to download the necessary packages for fatrat to work .
You should check out on the internet why you can not ping a server using a terminal command .
We do not give support for any OS internal issues .
Usually if there is a firewall app installed , you have to allow the terminal to access the web , in case not , then search on the web why is that happening .
What you have is not a fatrat issue .
Here it is a print screen of my terminal doing the same commands : 

![ping](https://cloud.githubusercontent.com/assets/7487321/26520057/5aca54b2-4299-11e7-9343-303b63b56f7f.png)
