### ISSUE TITLE
is every feature available on MacOS?

### ISSUE THREAD

**Issue by macuser876** [Screetsec/TheFatRat#117]
like, screenshot, voice recording, and how is the UI?
here is a real one specifically designed for mac users
http://macspy423ho54vap.onion

**Comment by peterpt** [comment]
fatrat creates a remote administrative tool server on the target that will connect your selected ip or domain when you are building it .
All commands to target are done thru a metasploit-framework session on msfconsole .
when the target connects to your ip and if msfconsole is opened with that specific rat then you will recieve a message that a specific ip is open for session .
After that point you can do whatever you want to that specific OS , no matter is it is windows , linux or mac , but everything is done thru msfconsole commands .
Fatrat is not a generic windows R.A.T. with GUI where you have a button for every option available .
In fatrat , everything must be done by hand on metasploit , all is needed after session to target is opened is to write "help" on msfconsole , and all possible commands to target will be printed .
