### ISSUE TITLE
Zenity:21125 WARNING

### ISSUE THREAD

**Issue by AnonxUser** [Screetsec/TheFatRat#118]
I am using NetHunter with VNC session on OnePlusOne, everything installs correctly except this warning:
![screenshot_2017-05-26-17-29-55 1](https://cloud.githubusercontent.com/assets/28981002/26494176/2aec839e-4250-11e7-8ca0-5c17bb86022c.png)
If I ignore it then I get errors while creating (most) payloads.
For Eg: I get #85

**Comment by peterpt** [comment]
You dont get errors creating the payloads , what you receive are zenity warnings .
Don`t worry , those are just warnings and not fatal errors .
When a fatal error appears it just shuts down the current script , and that is not happening .
However , zenity GUI will not appear in next version of fatrat .

**Comment by AnonxUser** [comment]
No GUI? excellent!
Thank you,
when is it coming up?

**Comment by peterpt** [comment]
very soon .
