### ISSUE TITLE
Configuration file does not exist, run setup.sh first for config

### ISSUE THREAD

**Issue by estavex** [Screetsec/TheFatRat#120]
This pops up every time I run ./fatrat
I ran ./setup.sh multiple times and tried various ways to install everything and everything is installed, but it just won't run the fatrat. Why?

**Comment by peterpt** [comment]
Because something went wrong during the setup and some package have not been installed correctly , when that happens , setup remove the current created config file to avoid problems with missing tools paths in config file.
fatrat knows that each specific line in config belongs to a tool , and have its path there , if by some reason some package is not installed correctly , then it is not written in config file , then next package ahead will be placed on  last package path field .
That will break fatrat , and then it is removed by safety until everything went well on setup.

on your logs folder there should be a file called "check" , if you open that file and you see a 0 , then it is because something went wrong during the instalation , and setup marked that file to check at the end .

check out in logs folder the file "setup.log"
and compare with this one at : 
https://pastebin.com/qWNr0n6a

see what your setup missed to fill in it .

Or paste here your setup.log and i will check it out .

**Comment by ESTAVEX** [comment]
Yes, I do get 0 in the "check" file. I did ./update and then ./setup.sh again, but it's the same error.

When I run ./setup.sh, I get
touch: cannot touch 'Vectors/TheFatRat/logs/setupo.log': No such file or directory
./setup.sh: line 1033: $log: ambiguous redirect
./setup.sh: line 1034: $log: ambiguous redirect
./setup.sh: line 1035: $log: ambiguous redirect
./setup.sh: line 1036: $log: ambiguous redirect

Followed by the normal installation of setup.sh. Not sure if that part is causing the problem, and I don't see any setup.log file in my fatrat folder.

**Comment by peterpt** [comment]
you are right .
do an update again or clone fatrat again and then check out the log .
i just fixed now that error

**Comment by ESTAVEX** [comment]
It seems to be the same error. The log still outputs 0.

**Comment by peterpt** [comment]
Post here your setup.log in the same folder .

**Comment by ESTAVEX** [comment]
Ok I checked, it still didn't create any setup.log file.

The uname -a command outputs:
Linux phantom 4.9.0-kali3-amd64 #1 SMP Debian 4.9.18-1kali1 (2017-04-04) x86_64 GNU/Linux

**Comment by peterpt** [comment]
Interesting that i am unable to create that error here .
Well , i made some changes in the code which will also work fine for other users and may fix our issue .
do an update or write in your terminal in fatrat folder : 

rm -f setup.sh
wget https://raw.githubusercontent.com/Screetsec/TheFatRat/master/setup.sh
chmod +x setup.sh
./setup.sh

**Comment by ESTAVEX** [comment]
Still no changes.

**Comment by peterpt** [comment]
clone this git anywhere to your computer
https://github.com/peterpt/test.git

then apply these commands : 
chmod +x tt.sh
./tt.sh

Then let me know what it pops up .

**Comment by estavex** [comment]
just
simple
test
log
worked

It created a test.log file, wrote that text in it and printed in terminal.

**Comment by peterpt** [comment]
do an ./update and execute setup again .

It is not common the problem you have in your linux for redirect text to variables , most of linux OS allow a simple redirect , but yours is giving you issues .

I have serious doubts if you are able to execute many other bash scripts in shells that you may clone from github from other tools .

**Comment by eman2cool** [comment]
When i run the setup.sh and the things are installing , Monodelevop stays red and wont install. Then when i try to run ./fatrat this shows up Configuration file does not exists , run setup.sh first for config .

**Comment by peterpt** [comment]
you are using kali linux right ?

**Comment by sktone007** [comment]
i have the same problem than eman2cool but i think it is kali linux, because after that,  i intall thefatrat in linux and works good

**Comment by peterpt** [comment]
just update your fatrat by writing in fatrat directory : ./update

Then execute setup.sh , in the end of the setup if some package is broken then setup will display it .

**Comment by Saketkr21** [comment]
@peterpt hiii,
" apt-get remove --purge monodevelop && apt-get autoremove && apt-get install -f "
this do not run in my linux
" E: Unable to locate package monodevelop "
this msg comes when i run above command.
Please help!!!

**Comment by nik13904** [comment]
I cannot perform ./update in my folder it's written update permission denied.

**Comment by Ouss-Ben** [comment]
i've compare "setup.log" with this one at  https://pastebin.com/qWNr0n6a , nd i haven't found this lines 
/usr/bin/monodevelop
/usr/bin/i686-w64-mingw32-gcc
/usr/local/sbin/fatrat

any solution !!﻿

**Comment by peterpt** [comment]
Well , thats look complicated , maybe it is an impossible fix  .
Unless you search on closed issues why you are not able to install monodenvelop and mingw .
If you do that , then maybe you find your solution .

**Comment by Ouss-Ben** [comment]
@peterpt  how can i install monodenvelop and mingw !?

**Comment by shreepoornaadarsh** [comment]
Simple thing...If permission is deneid then right click on setup.sh file and in permissions allow all the permissions and rewrite the code in terminal and hit enter

**Comment by agussulaiman97** [comment]
why is this, can anyone help me?
 [ * ] Checking for internet connection
 [ ✔ ]::[Internet Connection]: CONNECTED!
 [ ✔ ] Xterm.............................[ found ]
 [ ✔ ] Dns-Utils ........................[ found ]
 [ X ] Mono-Denvelop Utils -> not found! 
 [ ! ]  Installing Mono-Denvelop Utils
 [ x ] Mono-Denvelop Utils
 [ ✔ ] Gcc compiler......................[ found ]
 [ ✔ ] Apache2 ..........................[ found ]
 [ ✔ ] Gnome Terminal....................[ found ]
 [ ✔ ] UPX Compressor....................[ found ]
 [ ✔ ] Ruby..............................[ found ]
 [ ✔ ] Openssl...........................[ found ]
 [ ! ] Installing tools dependencies
cp: cannot stat '/etc/apt/sources.list': No such file or directory
cp: cannot stat '/etc/apt/sources.list': No such file or directory

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/issues/355

**Comment by RKS1412** [comment]
xterm -> OK
Dns-Utils -> OK
Mono-Denvelop Utils -> OK
GCC -> OK
Apache2 -> OK
Gnome Terminal -> OK
UPX -> OK
Ruby -> OK
Openssl -> OK
jarsigner (default-jdk)-> Not OK
Unzip -> OK
keytool -> Not OK
mingw-w64 -> Not OK
mingw-32 -> Not OK
DX -> OK
Aapt -> OK
Apktool -> OK
Baksmali -> OK
Metasploit (msfconsole) -> Not OK
Metasploit (msfvenom) -> Not OK
Backdoor-factory -> Not OK
Searchsploit -> Not OK
Was not possible to install The Packages Labeled (Not Ok) in this list above
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)
before running fatrat setup script again

**Comment by peterpt** [comment]
Dont bring up the dead people
