### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by georgy7** [Screetsec/TheFatRat#121]
Why you've made the software that make backdoors & malware? What was your motivation?

**Comment by peterpt** [comment]
see it om a different perspective .
- 1st : Antivirus companies don't get out of business (more jobs to people).
- 2nd : fix software security (software builders)
- 3rd : For fun
- 4th :  to improve programming skills

At least this is free , and everyone can access it , even antivirus builders , while there are other entities that build more dangerous malware than us .

Fatrat can be used for you to test your network security (windows , linux) and by looking how the rats works you can develop counter measures .

Fatrat can be used for good , like if you want to connect to a remote station , the rats will only connect to a specific ip or domain  , and will not be opened to everyone on the web .

Fatrat is a remote administrative tool , which it can not be considered 100% malware , however depending on the use you give to it , it can be used as malware .
I personally never ever test fatrat outside my lan , or even infected anyone with a rat made by me in fatrat .

You can see the negative point of this tool , but if you want you can also see the positive point of it .
At least fatrat backdoors are not builded to encrypt all your data like the latest "wannacry" Ransomware .
https://en.wikipedia.org/wiki/WannaCry_ransomware_attack

**Comment by georgy7** [comment]
Okay.
Thanks for your response.

**Comment by enkeyz** [comment]
It's a really good software for pentesters, ethical hackers. No need to tinker, just run this script. Saves a lot of time.

**Comment by peterpt** [comment]
The use of this tool is total responsibility of the user , we expect that this tool can be use more for good than bad .
However and i believe that is important to write here that fatrat is just a script that use multiple tools not originally made by us .
The main engine of fatrat is Metasploit framework , and then we use other tools additionally made by other 
users on github .
The readme file of fatrat is very explicit on that .
