### ISSUE TITLE
For Noobs - Take screenshot & upload to github

### ISSUE THREAD

**Issue by peterpt** [Screetsec/TheFatRat#124]
This video shows how to take a screenshot of your linux desktop and upload image to github .
https://youtu.be/mGXFVxDlWgU

**Comment by Konhumy** [comment]
root@kali:~# ls /usr/local/share/dex2jar/lib
ls: cannot access '/usr/local/share/dex2jar/lib': No such file or directory

root@kali:~# ls /usr/local/sbin/d2j-*
ls: cannot access '/usr/local/sbin/d2j-*': No such file or directory



Its showing No such directory
