### ISSUE TITLE
Monodevelop won't install

### ISSUE THREAD

**Issue by SudoTori** [Screetsec/TheFatRat#127]
So I did all the commands to install FatRat but it fails to use setup.sh because Monodevelop won't install
I tried changing repositories and I get this error
W: The repository 'http://download.mono-project.com/repo/debian wheezy InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.

**Comment by peterpt** [comment]
i will close your issue , and you can follow this other related issue : 
https://github.com/Screetsec/TheFatRat/issues/126

post your problem in that link , and do what i asked other user to do .
