### ISSUE TITLE
Binary Operator Expected

### ISSUE THREAD

**Issue by Patrickology** [Screetsec/TheFatRat#128]
Ok so I tried to embed a Metasploit Payload in an original .apk file but after entering the path the the apk file and hitting enter I got this message:

![image](https://cloud.githubusercontent.com/assets/28252390/26704852/3f15ace2-4732-11e7-886a-31b8782c3073.png)

What's up with that? Am I missing something or do I need to use a different original apk?

Thanks in advance!

**Comment by peterpt** [comment]
my guess for that error to happen could be related to that space in the source directory between Telegram and Desktop .
Move your apk to a directory without spaces , or previous directories without spaces .

ex : /root/Downloads/apks/AuroraDark.apk

**Comment by Patrickology** [comment]
Thanks, will try that and let you know.

**Comment by Patrickology** [comment]
That was the trick Peter!

![image](https://cloud.githubusercontent.com/assets/28252390/26705131/7161064a-4734-11e7-9970-3a2c7b47a192.png)

Moving on from here.
