### ISSUE TITLE
Session close with migrate process

### ISSUE THREAD

**Issue by cacaocaca** [Screetsec/TheFatRat#13]
Sorry for my language i m italian i have try today option Create FUD 100% BACKDOOR and used easybinder " worked always for me" for binder it with one pic and i have set so migrate proccess on msfconsole but the problem is   when i run the file  generate with easybinder with name pippo.exe he open prompt of windows with name powerfull.exe so he create session on metasploit and migrate the process correct but when i close the prompt of windows powerfull.exe the session are dead .. I have test it direct on my kali linux with wine but think is it same maybe thanks for your support ..

**Comment by Screetsec** [comment]
try create backdoor with PwnWinds in thefatrat :))

**Comment by cacaocaca** [comment]
Yes work with PwnWinds so if detected of Kaspersky and powerfull no .. So i ask do you can fix it so with powerfull that migrate right and hidden prompt while run it ? Becouse if i use binder with example vlc no is much good while i open show me vlc installation and prompt windows .. Thanks for your work and for your fantastic grafich on thefatrat is really  good
