### ISSUE TITLE
Can't install monodevelop when using ./setup.sh

### ISSUE THREAD

**Issue by SudoTori** [Screetsec/TheFatRat#131]
![image](https://cloud.githubusercontent.com/assets/29129828/26706650/0378b058-4737-11e7-90fc-b9ad56b188c8.png)
![image](https://cloud.githubusercontent.com/assets/29129828/26706652/09558910-4737-11e7-9ad1-747d365e0728.png)
![image](https://cloud.githubusercontent.com/assets/29129828/26706655/0cb72672-4737-11e7-850d-fd22d50d5659.png)
![image](https://cloud.githubusercontent.com/assets/29129828/26706656/0f00b8f8-4737-11e7-82ec-9574911f11ea.png)
Sorry for not taking screenshots but its easily readable anyways... So I always get this error and can't do anything else with it... when it checks for monodevelop and it says its not installed it doesn't even show any output from the terminal to download it

**Comment by Elements01** [comment]
take a look here i had the same issue this fixed it
https://github.com/Screetsec/TheFatRat/issues/126

**Comment by peterpt** [comment]
Did you installed recently kali linux ?

**Comment by gasparkali123** [comment]
help me plis, my English is bad but It happens to me too, I installing recently kali linux

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/issues/126#issuecomment-305626835

**Comment by wazidchoudhary** [comment]
please help me also i also recently install kali linux
and monodevelop is installing in fatrat
