### ISSUE TITLE
Cant Install dex2jar 2.0

### ISSUE THREAD

**Issue by Konhumy** [Screetsec/TheFatRat#132]
![img_20170602_161320](https://cloud.githubusercontent.com/assets/29133596/26722815/50d20728-47af-11e7-93cd-1137f2923102.jpg)
Check ScreenShot .
I am using USB LIVE PERSISTENT KALI LINUX 2017.1 64 bit OS

**Comment by Konhumy** [comment]
![photopictureresizer_170602_164654223-600x800](https://cloud.githubusercontent.com/assets/29133596/26723705/66f562a8-47b3-11e7-9107-e4ba2c86764d.jpg)

Its Showing Above Error
Plz help me

**Comment by peterpt** [comment]
you are using an old version of fatrat
execute ./update  or clone again the fatrat git to your computer
