### ISSUE TITLE
false error for internet connection

### ISSUE THREAD

**Issue by gearcapitan** [Screetsec/TheFatRat#135]
![kali linux-2017-06-06-12-22-47](https://user-images.githubusercontent.com/13740942/26842580-ee446fae-4ab2-11e7-9cd3-e9d57e6e9932.png)

**Comment by peterpt** [comment]
Why do you create this issue ?
This is not an error in the code .
Fatrat displayed the exact message of the problem .

We do not give support for your linux OS , you can find that support on your linux OS forum .

"Press [ENTER] key to contiue" says everything .
