### ISSUE TITLE
Problems with payloads that do not connect

### ISSUE THREAD

**Issue by gearcapitan** [Screetsec/TheFatRat#136]
![kali linux-2017-06-06-12-35-43](https://user-images.githubusercontent.com/13740942/26843114-b8e8351e-4ab4-11e7-9cca-57b2ac8c7aa7.png)
![windows 10 x64 kaspersky-2017-06-06-12-35-37](https://user-images.githubusercontent.com/13740942/26843113-b8e500a6-4ab4-11e7-91db-35aa212ede9b.png)

It's not my network !, other payload generators work correctly
None of the payloads for windows works for me

**Comment by peterpt** [comment]
yup , you are right , however we did not developed the powerstager script , but i created a new issue at powerstager main github to see if the main builder can check out what is happening .

**Comment by peterpt** [comment]
well , it looks that was a powerstager issue , i already updated the new version of it to fatrat , now the exe connects to your msfconsole , but is having a few issues to open the session .
However , that will be fixed today or tommow in fatrat code , i have to make some changes in the main fatrat script .

You can follow that main  issue in original powerstager repository at https://github.com/z0noxz/powerstager/issues/8

I marked this issue as a bug for now , and as soon as i fix fatrat code and test it , i will make it solved .
When you see this issue witht he label solved then update your fatrat .

**Comment by peterpt** [comment]
Issue fixed and tested : 
https://youtu.be/4xkiAPDXfPM
