### ISSUE TITLE
Configuration file does not exists , run setup.sh first for config .

### ISSUE THREAD

**Issue by technogamer29** [Screetsec/TheFatRat#138]
can anyone please tell me how to solve this
Configuration file does not exists , run setup.sh first for config .

**Comment by peterpt** [comment]
1st - update your fatrat .
2nd - even after the update and running setup.sh if that message still occurs ,then it means that some package was not possible to be installed .
Setup will say in the end which package was not installed  .

**Comment by technogamer29** [comment]
Monodevelop -> Not OK
THIS ONE !

**Comment by peterpt** [comment]
you are using kali and you dont have any repositories on your sources.list .

Check this thread and follow the steps of the others .
https://github.com/Screetsec/TheFatRat/issues/126

**Comment by technogamer29** [comment]
I DID IT BUT NO LUCK still showing
Configuration file does not exists , run setup.sh first for config

**Comment by peterpt** [comment]
what did you did exactly from other thread ?

**Comment by peterpt** [comment]
1st - learn how to take a print screen and upload to github .

2nd - open your terminal and write : 
uname -a

and then after that write this : 
cat /etc/apt/sources.list

upload the image to here .

**Comment by technogamer29** [comment]
![screenshot from 2017-06-10 16-34-17](https://user-images.githubusercontent.com/29302253/27002414-8a7ab4b0-4daf-11e7-88bf-ca75488037bd.png)
ok^^

**Comment by technogamer29** [comment]
please HELP me with this  PETERPT

**Comment by mrdelt4** [comment]
Also tried installing the setup but turns out I need libgrnome but then I need to install other packages as well when trying to download monodevelop

**Comment by peterpt** [comment]
do this :  
apt-get remove --purge monodevelop && apt-get autoremove -y && apt-get install -f

- Then get me the final output from those instructions before .

After that , write this  : 
- apt-get install monodevelop

and get a print screen from it .

**Comment by technogamer29** [comment]
i didn't get u mrdelt4....?? 😯

**Comment by technogamer29** [comment]
ok peterpt

**Comment by mrdelt4** [comment]
nah just a problem i'm having with monodevelop

**Comment by technogamer29** [comment]
![screenshot from 2017-06-10 18-34-48](https://user-images.githubusercontent.com/29302253/27003208-5a6f5814-4dc0-11e7-88e1-24f753285617.png)
IT WORKED

BRO THANK U SO MUCH !!!.. +1:

**Comment by peterpt** [comment]
good .
Did you realized what was happening ?

**Comment by technogamer29** [comment]
yea monodevlop was the prob..
bt thank u so much bro..

**Comment by peterpt** [comment]
i know , but do you know why monodevelop was giving issues ?

**Comment by technogamer29** [comment]
no

**Comment by peterpt** [comment]
that is what i was trying to get from you .
I will explain to you and to all others that may read this thread what happened : 
Conflicting packages in monodevelop was the issue , user try to install monodevelop before from other repository .

* apt-get remove --purge monodevelop 
(This command removed completly any faulty monodevelop version installed on user system)

* apt-get autoremove -y 
(This command removed packages that were connected to that version of monodevelop)

* apt-get install -f
(This command fixed any other conflicted packages in user system)

* apt-get install monodevelop
(This command installed monodevelop from user original repository and not any other one)

**Comment by technogamer29** [comment]
oh k thanks..

**Comment by technogamer29** [comment]
bro for hook point selection which point should i choose any r anything specific??

**Comment by peterpt** [comment]
some hook points may not compile , you have to test some if it fails to compile .
selecting an hook point in apk will mean that the victim will only activate the payload to connect to you when that code instruction is loaded in the victim app or game .
But if you are doing it to test for yourself then you can avoid that and go directly to msfvenom menu and compile the apk rat only in android submenu  .

**Comment by holaweyxd** [comment]
Hi, I also have the same problem (Configuration file does not exist, run setup.sh first for config.)
install the repositories and update thefatrat, but still I get the problem.
what should I do to solve.
uname -a ( Linux kali 4.9.0-kali3-amd64 #1 SMP Debian 4.9.18-1kali1 (2017-04-04) x86_64 GNU/Linux )

**Comment by zayne24** [comment]
i have the same issue , but am not able to solve it with the above solution ..help!!
![screenshot from 2018-02-12 16-34-07](https://user-images.githubusercontent.com/36405598/36094073-dcf503aa-1012-11e8-9481-8aa19d9d28ff.png)
