### ISSUE TITLE
monodevelop not installing 

### ISSUE THREAD

**Issue by mrdelt4** [Screetsec/TheFatRat#139]
So I tried everything looked at every problem repos and all that.
When I tried apt-get install MonoDevelop says  I need to install libgnome2.24 
but then I need to install more packages?

running Linux Mint Mate

**Comment by peterpt** [comment]
must be some problem with your linux repository , because by default it should install every package needed automatically .

do this : 
- apt-get install aptitude && apt-get install -f -y && apt-get autoremove -y && aptitude install monodevelop

**Comment by mrdelt4** [comment]
ok

**Comment by mrdelt4** [comment]
No sorry still not working

**Comment by peterpt** [comment]
look , i am not clairvoyant to guess what is happening there .
1st - learn how to get print screens :  https://github.com/Screetsec/TheFatRat/issues/124

Then write on your terminal : 
- apt-get install monodevelop
 
and get me a print screen .

**Comment by muzammiljunaid** [comment]
![evedence2](https://user-images.githubusercontent.com/8277253/27011520-9496c98e-4ed6-11e7-8ec7-678f692c03fa.png)

**Comment by muzammiljunaid** [comment]
just stuck on Monodevelop :(

**Comment by peterpt** [comment]
explain to me why you are trying to install monodevelop wheezy like that ?
To install a specific version of some package it must be done by its version .
https://askubuntu.com/questions/92019/how-to-install-specific-ubuntu-packages-with-exact-version

And that version must exists in the repository of your linux OS distribution .

your solution is this one , exactly like this : 
- apt-get remove --purge monodevelop && apt-get autoremove -y && apt-get install -f -y && apt-get update -y && apt-get upgrade && apt-get dist-upgrade && apt-get install monodevelop

**Comment by muzammiljunaid** [comment]
nope not helping still got the error :(
![evidence7](https://user-images.githubusercontent.com/8277253/27011623-f59d3c66-4ed8-11e7-9ff1-7e2824beedf7.png)
![evidence9](https://user-images.githubusercontent.com/8277253/27011625-fecbc8d4-4ed8-11e7-9438-6e03fabb9f05.png)

**Comment by muzammiljunaid** [comment]
Any clue what should i do now ??

**Comment by peterpt** [comment]
look closely to what happened .
What do you think is missing there ?
Dont you see that you do not have any repositories from Kali in your sources.list ?

follow this thread : 
https://github.com/Screetsec/TheFatRat/issues/126#issuecomment-305626835

**Comment by muzammiljunaid** [comment]
thanks man for help i manage to install it :) you were right that repositories were not added on sources.list

**Comment by Hades44** [comment]
Plz brother help me..I'm using kali nethunter am facing some problems to install fatrat..Am not able to install DX,Aapt,Apktool..
Plz brother's help me..how can I fix this problem!!

**Comment by Eclipsium** [comment]
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/ubuntu xenial main" | sudo tee /etc/apt/sources.list.d/mono-official.list
sudo apt-get update

sudo apt-get install mono-devel
sudo apt-get install monodevelop
sudo ./setup.sh

Its help me (ElemetratyOS)

**Comment by johntherippe** [comment]
Mr Peterpt please help me i tried.. 
I M Using Nethunter i hv Command 
sudo apt-get install monodevelop
But Unable to locate pkg please any Solution this issue fix it please please pleae

**Comment by peterpt** [comment]
monodenvelop is not used anymore , setup does not install it anymore , you are problably using an old version of fatrat .
Update it .

**Comment by kiran244668** [comment]
Mono denvelop is not ok in my computer please help.... I wanna install fatrat

**Comment by sagesta** [comment]
had same problem...what i did was to update my repositories and ran fatrat setup again

**Comment by Jsimpki** [comment]
> monodenvelop is not used anymore , setup does not install it anymore , you are problably using an old version of fatrat .
> Update it .

You claim this but the latest version still is trying to install it and giving a not OK. Maybe it's time to update your files? I am having the same issue as everyone else and I cloned it with git clone command straight from this github
