### ISSUE TITLE
Serious problems with Kaspersky

### ISSUE THREAD

**Issue by gearcapitan** [Screetsec/TheFatRat#143]
![kali linux-2017-06-12-10-55-08](https://user-images.githubusercontent.com/13740942/27042825-b6028bb2-4f5d-11e7-9e5e-bdd1122c800b.png)
![windows 10 x64 kaspersky-2017-06-12-10-55-03](https://user-images.githubusercontent.com/13740942/27042826-b607eb8e-4f5d-11e7-9908-069376188216.png)

**Comment by peterpt** [comment]
That is a not a serious problem , a serious problem is if you break your leg for a stupid thing .
Powerstager was recently added to fatrat , most of its functions where not implemented in fatrat main  script .
download the original code for powerstager at : 
https://github.com/z0noxz/powerstager
and make your rat there using the switch --obfuscation and that serious problem that you are speaking will probably disappear .

I am doing changes in fatrat code here but they will not be implemented right away .
