### ISSUE TITLE
create FUD backdoor with avoid v1.2

### ISSUE THREAD

**Issue by marcelo321** [Screetsec/TheFatRat#147]
i just wanted to know what is this option on the menu, the number 3 of the list. i tried to create a backdoor there but at the end it just create numbers and no .exe file. i am interested in that option because it let you decide the from 1 to 5 the stealth mode

i don't know what to write when it says: "type the desire label for the autorun files :"

and at the end i get binari numbers and not an .exe file, pls help, do i need to do something with that binaries?

**Comment by peterpt** [comment]
"i don't know what to write when it says: "type the desire label for the autorun files :"

What about writing any name , like "test" .
Avoid creates a backdoor payload for you to insert in a cdrom or in any other media device , and when that media is plugged in into a computer , it will execute the autorun .

**Comment by marcelo321** [comment]
i'll look at it, the backdoor payload should be located in thfatrat/output like every other backdoor created by fatrat right?

**Comment by marcelo321** [comment]
ill post every option i have:

TYPE THE DESIRED OUTPUT FILENAME : TEST

TYPE THE DESIRED LABEL FOR THE AUTORUN FILES : TEST

Set LHOST IP: 181.***.****
 
  Set LPORT: 4444

No platform was selected, choosing Msf::Module::Platform::Windows from the payload
No Arch selected, selecting Arch: x86 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 354 bytes

Normal [ 400K payload ]  - [ fast compile ]  

 2. Stealth [ 1-2 MB payload ] - [ fast compile ] 

 3. Super Stealth - [ 10-20MB payload ] 

 4. Insane Stealth - [ 50MB payload ] 

 5. Desperate Stealth - [ 100MB payload ] 

 TYPE THE NUMBER IF YOU WANT :  5

[-] Desperate Stealth selected, please wait a few minutes

[-] Generating random seed for padding...please wait

[                                                                        [ 011                                                                    [ 011001                                                                 [ 01100111                                                               [ 011001110                                                              [ 01100111001                                                            [ 01100111001001                                                         [ 01100111001001001                                                      [ 0110011100100100111                                                    [ 011001110010010011101                                                  [ 0110011100100100111011100                                              [ 01100111001001001110111001101                                          [ 01100111001001001110111001101010                                       [ 01100111001001001110111001101010101                                    [ 011001110010010011101110011010101010101                                [ 0110011100100100111011100110101010101011                               [ 011001110010010011101110011010101010101101010                          [ 01100111001001001110111001101010101010110101001                        [ 0110011100100100111011100110101010101011010100101011                   [ 0110011100100100111011100110101010101011010100101011100                [ 011001110010010011101110011010101010101101010010101110010              [ 011001110010010011101110011010101010101101010010101110010101           [ 0110011100100100111011100110101010101011010100101011100101010          [ 01100111001001001110111001101010101010110101001010111001010101010      [ 011001110010010011101110011010101010101101010010101110010101010101     [ 011001110010010011101110011010101010101101010010101110010101010101010  ]
Press [ENTER] key to return to menu

there is no file created, i don't know if it is created somewhere or what...

**Comment by peterpt** [comment]
That specific backdoor will be placed on "autorun" folder in fatrat .

**Comment by marcelo321** [comment]
thank you very much!

**Comment by peterpt** [comment]
you were right .
There was some bugs in fatrat code .
I already have fixed them .
I am rebuilding the script update from fatrat , so to update only the fatrat script do like this : 
- open a terminal and to your fatrat directory
- write these commands : 
rm fatrat
wget https://raw.githubusercontent.com/Screetsec/TheFatRat/master/fatrat
chmod +x fatrat

- and you have your fatrat script updated

**Comment by StoneAaron1** [comment]
But how do I turn on the listener?

**Comment by anoprivate15** [comment]
I  have successfully  created a backdoor and it is only detectable by 4 av but don't know what payload it's using so i don't know how to listen for the backdoor

**Comment by AleksanteriA** [comment]
> anoprivate15

Did you find a listener for that?

**Comment by bakalilinux** [comment]
there is no rc file can be generation, and if no one, How to create a listener for this backdoor?

**Comment by jamuntest-sudo** [comment]
i think because its for windows , just use the windows meterpreter

**Comment by jamuntest-sudo** [comment]
like windows/x64/meterpreter/reverse_tcp or http/https
