### ISSUE TITLE
can't bind an apk 

### ISSUE THREAD

**Issue by Hacker-EG** [Screetsec/TheFatRat#149]
i can't bind an apk file it is get error in these tools 
1-Backdoor-apk 0.2.2
2-old Fatrat method 

touch: cannot touch 'security/TheFatRat/config/apk.tmp': No such file or directory
./fatrat: line 3742: $apkconfig: ambiguous redirect
./fatrat: line 3743: $apkconfig: ambiguous redirect
./fatrat: line 3744: $apkconfig: ambiguous redirect
./fatrat: line 3745: $apkconfig: ambiguous redirect
./fatrat: line 3746: $apkconfig: ambiguous redirect
./backdoor_apk: line 159: $LOG_FILE: ambiguous redirect
./backdoor_apk: line 149: $LOG_FILE: ambiguous redirect
 
[!] Check your environment and configuration. Couldn't find: backdoor-factor

**Comment by peterpt** [comment]
what is your OS distro .

**Comment by An0nUD4Y** [comment]
I am using PARROT OS........ same issue here

**Comment by Screetsec** [comment]
not detail information , closed
