### ISSUE TITLE
Can't create persistence in android apk payload

### ISSUE THREAD

**Issue by waahtech** [Screetsec/TheFatRat#150]
[*] Creating RAT Apk File...done.
 
[*] Decompiling RAT APK file...done.
 
[*] Decompiling original APK file...done.
 
[*] Merging permissions of original and payload projects...done.
 
[*] Running proguard on RAT APK file...done.
 
[*] Decompiling obfuscated RAT APK file...done.
 
[*] Creating new directories in original project for RAT smali files...done.
 
[*] Copying RAT smali files to new directories in original project...done.
 
[*] Fixing RAT smali files...done.
 
[*] Obfuscating const-string values in RAT smali files...done.
 
[*] Locating smali file to hook in original project...done.
 
[*] Adding hook in original smali file... 
done.
 
[*] Adding persistence hook in original project...done. ********* **BUT NO PERSISTENCE CREATED**
 
[*] Recompiling original project with backdoor...done.
 
[*] Generating RSA key for signing...done.
 
[*] Signing recompiled APK...done.
 
[*] Verifying signed artifacts...done.
 
[*] Aligning recompiled APK...done.
 
[*] Backdoor apk created sucefully 
Your RAT apk was successfully builded and signed , it is located here :
 /root/TheFatRat/backdoored/app_backdoor.apk

Hello Developers i tested lots of apks, exe etc..
and I appreciate your effort on THEFATRAT project....

I want to ask can we create persistence backdoor using fatrat for android APKs.

I tested the APKs generated by fatrat, i found that no persistence was created using fatrat ..

help me out... Thanksss

**Comment by peterpt** [comment]
We did not developed the main scripts for android backdoor apk builds , but "persistence backdoor" is not what you think it is .
You must somehow think that "persistence backdoor" is a startup option , in some androids apks may be if they startup in android boot , but most apks by default do not startup at boot .
What you want can be build in msfvenom menu in creating an android payload only .
If you install that msfvenom apk payload in an android device then you can be sure it will startup at boot .

I advise you and all others to read the README file on fatrat .

**Comment by Nisthar** [comment]
@waahtech Which version of apktool do you use?

I use 2.2.0 and i am getting error `Failed to recompile original project`
