### ISSUE TITLE
Can't install TheFatRat

### ISSUE THREAD

**Issue by AHMEDMAHER132000** [Screetsec/TheFatRat#151]
Xterm -> OK
Dns-Utils -> OK
GCC -> OK
Monodevelop -> OK
Apache2 -> OK
Gnome Terminal -> OK
UPX -> OK
Ruby -> OK
Openssl -> OK
Jarsigner -> OK
Unzip -> OK
Keytool -> OK
Mingw64 -> OK
DX -> Not OK
Aapt -> Not OK
Apktool -> Not OK
Dex2Jar -> OK
Metasploit -> OK
Backdoor-Factory -> OK
Searchsploit -> OK
Was not possible to install The Packages Labeled (Not Ok) in this list above
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)
before running fatrat setup script again

i tried to use the command to solve the problem but it doesn't word
i tried to solve the problem but i failed

**Comment by peterpt** [comment]
Write on your terminal these commands : 

find /usr/ -name dx
find /usr/ -name aapt

and post here the output in a print screen

**Comment by vizhax** [comment]
![screenshot from 2017-07-13 19-08-50](https://user-images.githubusercontent.com/30150756/28169047-c3c72208-67fe-11e7-8d37-e0dfc7aae7f7.png)
is this ok???

**Comment by peterpt** [comment]
It looks that you do not have any repositories in your sources.list .
Check out your linux distribution codename and add the repositories in your sources.list , so fatrat can install monodevelop .
