### ISSUE TITLE
Install fatrat

### ISSUE THREAD

**Issue by TheSuperXD** [Screetsec/TheFatRat#154]
I have a proble installing monodevelop of thefatrat who can help me?

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/issues?q=is%3Aissue+is%3Aclosed

**Comment by TheSuperXD** [comment]
Thanks it works but now i cant enter in kali linux i unistall and install again but when i start kali linux appears a black screen and a white bar what i can do?

**Comment by peterpt** [comment]
That issue is not related to fatrat .
http://forums.kali.org/
