### ISSUE TITLE
Icons not applying

### ISSUE THREAD

**Issue by Like50Wizards** [Screetsec/TheFatRat#155]
I have given TheFatRat an icon in the icons folder named, 'autorun.ico'.
Any compiled .exe in output on a Windows machine displays the default _this-file-has-no-icon-but-this-will-do_ replacement from Windows.

Am i missing something?

**Comment by peterpt** [comment]
most of the latest icons in fatrat are for the next update of it to be used with powerstage fud creation , right now the autorun.ico you used it is only applied on avoid backdoor creation in fatrat menu .
