### ISSUE TITLE
Kali Linux Rolling incompatible

### ISSUE THREAD

**Issue by r3cursive123** [Screetsec/TheFatRat#16]
Wasn't sure where to put this as I am new to GitHub. I am running Kali Linux rolling 4.6.0-kali1-amd64 and had trouble running your scripts. Just wanted to add the fix I applied in case others are troubled. By the way, great work here.

Problem 1: When first running the program it finds the mingw installation but then right after it fails and says it isn't installer.
Solution: I noticed that in the fatrat program it is checking for the mingw installation twice so then; edit the fatrat program and comment out the second mingw check (specifically lines 266-283)

Problem 2: Compiling was failing when running the Powerfull option
Solution: edit the powerfull.sh script file and replace all instances of this string '586-mingw32msvc-gcc' with this string 'i686-w64-mingw32-gcc'

After those simple tweaks, all is well. Thanks again for writing this, very helpful.

**Comment by Screetsec** [comment]
will be update , but my solution you can run setup.sh for install mingw32 ( 32bit )
