### ISSUE TITLE
Fatrat is not installing

### ISSUE THREAD

**Issue by Ashish882** [Screetsec/TheFatRat#161]
I am trying to installed it in my android with debain gnuroot
I do all command propaly put at last when I put command ./fatrat it give error

"" 32 line error IP..
66 line error host"" some what like this than

Configuration file does not exit .run setup.sh fist to config.
What I do now

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/issues/159

**Comment by Ashish882** [comment]
Ok

**Comment by Ashish882** [comment]
Why you close

**Comment by peterpt** [comment]
If you read https://github.com/Screetsec/TheFatRat/issues/159  then you know .
