### ISSUE TITLE
How to run thefatrat in termux

### ISSUE THREAD

**Issue by Ashish882** [Screetsec/TheFatRat#164]
How I can't the fatrat in  android without error in termux.

**Comment by superyeimi** [comment]
You have to install first Fedora 25 and install TheFatRat on it. I did it and works :)

**Comment by Ashish882** [comment]
I have fedora what is fedora 25 ?

**Comment by Ashish882** [comment]
With fedora this error every time
![screenshot_20170820-234902](https://user-images.githubusercontent.com/30336226/29497235-5b55b866-8602-11e7-9e65-64234827a7e7.png)

**Comment by peterpt** [comment]
buy a computer .
We are unable to test fatrat on android devices with fedora linux installed .

**Comment by Ashish882** [comment]
I understand but @superyeimi has installed I asking him to tell how he do it with fedora

**Comment by superyeimi** [comment]
Fedora25 is a version, you should found a vid on youtube explaining how to install easy. Then install thefatrat following the steps with fedora open. Here a screenshot https://ibb.co/buzc95

**Comment by Ashish882** [comment]
OK I wait I try

**Comment by Ashish882** [comment]
Can you guide me how to install fedora 25 in termux any link @superyeimi

**Comment by superyeimi** [comment]
I really dont know, i tried and works, maybe we have different architechtures but i dont know

**Comment by Hades44** [comment]
Plz brother help me..I'm using kali nethunter am facing some problems to install fatrat..Am not able to install DX,Aapt,Apktool..
Plz brother's help me..how can I fix this problem!!

**Comment by johnsmith7123** [comment]
Hey bro sup ......you still need help or what??

On Nov 8, 2017 7:28 AM, "Hades44" <notifications@github.com> wrote:

Plz brother help me..I'm using kali nethunter am facing some problems to
install fatrat..Am not able to install DX,Aapt,Apktool..
Plz brother's help me..how can I fix this problem!!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Screetsec/TheFatRat/issues/164#issuecomment-342723233>,
or mute the thread

**Comment by bhindamahey** [comment]
Anybody tell me how to install thefatarat in termux

**Comment by Screetsec** [comment]
script setup.sh is not avalaible  for android (termux) you can install manualy for depend

**Comment by MC45892** [comment]
You can use kali nethunter after installing it on android do nh kex in you termux then install nethunter kex vnc app you can get it on the nethunter store then connect to it after doing that install all required packages then clone TheFatRat repo then do

```bash
chmod +x setup.sh
./setup.sh
```

After finishing the setup you can run it with gui or directly from termux by doing
```bash
nh
sudo fatrat
```

if need more help on installing nethunter follow the offical nethunter document from kali.org

I think this should work or I just made up a garbage...

I am still new to hacking, programming and any IT related stuff...

Hope this helps somebody......

**Comment by MC45892** [comment]
![Screenshot_2021-06-13-19-19-39-319_com termux](https://user-images.githubusercontent.com/76612351/121809956-87208b00-cc7c-11eb-8391-3d09d050ad4e.jpg)

I got it working lol

**Comment by BlackPanther1976** [comment]
Can Anyone help me to install TheFatRat in Termux with Android
I am Facing many problems to install it 
Please Help me🥺🥺
