### ISSUE TITLE
Old School bugg. But can't solve the problem.

### ISSUE THREAD

**Issue by Lazarusprogrammierer** [Screetsec/TheFatRat#165]
Hello,

FatRat and Kali are new to me. So I don't know what the problem is. I installed Kali Linux on the VM Box successful. Then I tried to install fatrat:

chmod +x setup.sh
chmod +x fatrat
chmod +x powerfull.sh
chmod +x update

./update
./setup.sh

-> 
everything OK, but not:

DX
Aapt
Apktool
Dex2Jar

So I searched on the internet how to solve the problem.
I tried to reinstalled the packages
(informations from https://github.com/Screetsec/TheFatRat/issues/151)

I also tried to write things to sources.list
But this doesn't work

what kind of information do you need?

**Comment by peterpt** [comment]
chmod +x setup.sh && ./setup.sh
then if any problem appears , upload the install.log file that it is on "logs" folder in fatrat to here .
To upload a file use option bellow the text "when you are writing the issue" where it says "sellecting them" .
Or drag that file to the text folder .

**Comment by Lazarusprogrammierer** [comment]
[install.txt](https://github.com/Screetsec/TheFatRat/files/1184861/install.txt)
That's the log. i need to rename it to .txt

**Comment by peterpt** [comment]
rm -f /usr/local/sbin/dx && rm -f /usr/local/sbin/aapt && rm -f /usr/local/sbin/aapt && rm -f /usr/local/sbin/apktool && rm -f /usr/local/sbin/d2j-* && rm -rf usr/local/share/dex2jar && apt-get remove --purge dx aapt apktool dex2jar -y && apt-get autoremove && apt-get install -f

After these commands , run setup.sh from fatrat and everything will be ok

**Comment by Lazarusprogrammierer** [comment]
Nope. it doesn't work!
Still the same problem.

**Comment by Lazarusprogrammierer** [comment]
The Programm tells me that 0 are new installed and 61 left to install...

**Comment by Lazarusprogrammierer** [comment]
file:///root/Bilder/Bildschirmfoto%20von%20%C2%BB2017-07-29%2013-22-50%C2%AB.png

**Comment by Lazarusprogrammierer** [comment]
https://www.imagebanana.com/s/777/vtlhDGzU.html

**Comment by peterpt** [comment]
next time upload your image to github using this manual : 
https://github.com/Screetsec/TheFatRat/issues/124

According to your picture setup will start the installation , i need to know what happens in the end of setup.sh .

Lets setup run itself until the end and post here the picture when it finishes .
