### ISSUE TITLE
mingw32

### ISSUE THREAD

**Issue by Geniusalamri** [Screetsec/TheFatRat#17]
[!]::[Check Dependencies]:
[✔]::[Check User]: root
[✔]::[Internet Connection]: connected!
[✔]::[apache2 Server Kali ]: installation found!
[✔]::[msfconsole]: installation found!
[✔]::[msfvenom]: installation found!
[✔]::[Zenity]: installation found!
[x]::[warning]:this script require mingw32 installed to work

[!]::[please wait]: please run setup.sh ....

I have this problem, what should I do?

**Comment by Screetsec** [comment]
please readme.md first
