### ISSUE TITLE
Original apk backdooring doesn't work

### ISSUE THREAD

**Issue by DarkFighterLuke** [Screetsec/TheFatRat#170]
The process of backdooring an original apk is done, but when I install the apk on the phone the app crashes and the connection doesn't start.
It happen with all apps that i try to backdoor.
How to solve?

**Comment by peterpt** [comment]
Some apks have their code protected , or were already manipulated before you download them , by default using a downloaded apk from google play it is more advised to avoid issues , however if the apk is very recent then some issues may appear when you try to install it .
If you want to test an apk payload on a phone then : 

- Select option 01 from main menu (Create Backdoor with msfvenom)
- Then select option 3 on the submenu (Signed Android >> fatrat.apk)

and install the compiled apk on the device you want to test .

**Comment by DarkFighterLuke** [comment]
@peterpt you're wrong, there's something in new payloads that doesn't work if embedded. I tried with original apks of older apps versions and it doesn't work with it too.
So I think I have to notice metasploit community about this bug...

**Comment by peterpt** [comment]
Generating an apk using msfvenom there is no need for any app to embedded the payload in it .

Basically metasploit only creates the payload as an apk , nothing more is created .
You are confusing out this subject .

watch this video : 
https://www.youtube.com/watch?v=AyzsSaRE7ZQ
