### ISSUE TITLE
FatRat Not connection of internet

### ISSUE THREAD

**Issue by SkyHacker143** [Screetsec/TheFatRat#173]
I am using kali net hunter
In Vnc viewer after ./setup.sh
Error shows you are not connected to internet

**Comment by SkyHacker143** [comment]
![screenshot_2017-08-29-11-24-13-211_com realvnc viewer android](https://user-images.githubusercontent.com/31435684/29812597-c12a7f78-8cc4-11e7-8098-5abba67860b6.png)

**Comment by peterpt** [comment]
just because your android is connected to internet , it does not mean that your net hunter it is connected too .
buy a computer .

**Comment by SkyHacker143** [comment]
I also have a computer
But I want to use nethunter in my mobile
In vnc viewer i can use apt get install and git clone
But in browser I cant browse anything
In terminal when i try to ping google.com
Then i got error
Temporary failure in name resolution
Plz solve this issue

**Comment by peterpt** [comment]
The issue you have is not related to fatrat script .
The issue you have is related to your kali nethunter , seek for help on kali forums .

**Comment by Hades44** [comment]
Plz brother help me..I'm using kali nethunter am facing some problems to install fatrat..Am not able to install DX,Aapt,Apktool..
Plz brother's help me..how can I fix this problem!!

**Comment by hardik708012** [comment]
I got that problams too i got that too not
Connected to the internet

**Comment by hardik708012** [comment]
Help me

**Comment by Hades44** [comment]
You open UXTerm (terminal)and type "su".. Then you enter thefatrat
master..and type ./setup.sh..
Problem will be fix!!!

**Comment by hardik708012** [comment]
Teminal sey command not found

**Comment by Hades44** [comment]
You give me screen shoots

**Comment by hardik708012** [comment]
I send screen shoots to gmail

**Comment by hardik708012** [comment]
This problem
