### ISSUE TITLE
setup.sh don't start - Kali Linux Raspberry Pi (Kali Pi)

### ISSUE THREAD

**Issue by StarkNull** [Screetsec/TheFatRat#176]
Hi ! 
I wanted to try the TheFatRat framework but don't wan't to reboot my laptop to go on my own KaliLinux. So I tryed on my Raspberry pi and I think than the RPi architecture isn't supported. I post the error message than TheFatRat tell me to post.

> ___________         __  __________          __
> \_   _____/_____  _/  |_\______   \_____  _/  |_
>  |    __)  \__  \ \   __\|       _/\__  \ \   __\
>  |     \    / __ \_|  |  |    |   \ / __ \_|  |
>  \___  /   (____  /|__|  |____|_  /(____  /|__|
>      \/         \/              \/      \/
>                  ____    ________
>                 /_   |  /   __   \
>                  |   |  \____    /
>                  |   |     /    /
>                  |___| /\ /____/
>                        \/
> 
>           Setup Script for FATRAT 1.9.5
> 
>  Setup will not proceed because none of these archs were detected
> 
>  x86_64|i386|i486|i586|i686|aarch64|armv7l
> 
>  Report this arch:  **armv6l**  into fatrat issues on github
> 
> Press any key to continue
> 
> root@kali:~/w/TheFatRat#
> 

I hope my post is useful, and sorry for my english.

**Comment by peterpt** [comment]
you should not use fatrat on an RPI , some of its tools are heavy and the RPI may not be hable to handle them .
And this without even mention that most of its dependencies may not exist in kali armv6 repository and you will flood this github with issues that we are unable to solve .
Eventually in future we will remove armv7 too from fatrat

**Comment by R3DDY97** [comment]
Yeah 
now its not supporting armv7 too

**Comment by Sumantsh99** [comment]
Setup will not proceed because none of these archs were detected

x86_64|i386|i486|i586|i686|aarch64|armv7l

Report this arch: armv7l into fatrat issues on github

**Comment by peterpt** [comment]
not fixed .
Buy a laptop or a desktop .
your device arch is not supported due multiple installation & running issues in fatrat .

**Comment by Sumantsh99** [comment]
How to Install mono develop in armv7l kali linux
