### ISSUE TITLE
can't install TheFatRat(monodevelop,mingw) help me please

### ISSUE THREAD

**Issue by lachin58** [Screetsec/TheFatRat#178]
im installed kali linux 32bit in vmware for work with TheFatRat
but have problem,
cant install TheFatRat
search all old problem but not solve my pro
![screenshot from 2017-09-05 10-32-47](https://user-images.githubusercontent.com/29653518/30048490-b1b3259c-922b-11e7-8332-12a834a5aa2f.png)
blem

**Comment by peterpt** [comment]
Look in arquived issues , you will find a solution for your problem .

**Comment by sasatefa2009** [comment]
flatpak install --user --from https://download.mono-project.com/repo/monodevelop.flatpakref
sudo apt-get install mingw32

**Comment by peterpt** [comment]
I already replyed this issue 100x before to other users .
You are unable to install those packages because you tried to install them before without success .
This means that when setup tries to install the package it is stopped by a corrupt installation that was not fixed before .

apt-get remove --purge monodevelop mingw32 mingw-w64 -y && apt-get autoremove -y

Then run setup.sh again .

Note : My guess is that you have your sources.list file empty , like all others , but that is not a problem because fatrat will fill the repositories to install these tools .

**Comment by lachin58** [comment]
thnQ all . i m succeed. but have any problem. go to new issue

**Comment by ananthram252** [comment]
still not working.. showing same problem..
uanble to install monodevelop and mingw-64w

**Comment by ananthram252** [comment]
i cant able to install fatrat...showing unable to found monodevelop and mingw-w64..
please help me out
![untitled](https://user-images.githubusercontent.com/33496456/32619263-3cdbe616-c5a0-11e7-9bc6-7fc686a3c34d.png)

**Comment by peterpt** [comment]
echo "deb http://old.kali.org/kali sana main non-free contrib" >> /etc/apt/sources.list
echo "deb-src http://old.kali.org/kali sana main non-free contrib" >> /etc/apt/sources.list
echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" >> /etc/apt/sources.list
echo "deb-src http://http.kali.org/kali kali-rolling main contrib non-free" >> /etc/apt/sources.list
apt-get update
apt-get remove --purge monodevelop mingw32 mingw-w64 && apt-get autoremove -y 
apt-get install monodevelop mingw32 mingw-w64 -y

Then after this run fatrat setup

**Comment by usmantanoli** [comment]
Sir After that is got this Problem 

E: Unable to locate package monodevelop
E: Unable to locate package mingw32
E: Unable to locate package mingw-w64

**Comment by shubhamdalavi20** [comment]
E: Unable to locate package mingw32

**Comment by shubhamdalavi20** [comment]
how to solve this 
E: Unable to locate package mingw32

**Comment by akashkannan1105** [comment]
unable to locate package its coming

**Comment by DemonMan123** [comment]
I'm getting the same problem.

**Comment by Abcde123lkjh** [comment]
I'm facing the same problem. What should I do now?

![Kali-Linux-2018 4-vbox-amd64  Running  - Oracle VM VirtualBox 8_4_2019 9_27_10 AM (2)](https://user-images.githubusercontent.com/53537931/62419308-c94d0e80-b69a-11e9-838d-a2cb744a2cba.png)
![Kali-Linux-2018 4-vbox-amd64  Running  - Oracle VM VirtualBox 8_4_2019 9_27_10 AM (3)](https://user-images.githubusercontent.com/53537931/62419309-c9e5a500-b69a-11e9-95b8-d9cf82b326df.png)
![Kali-Linux-2018 4-vbox-amd64  Running  - Oracle VM VirtualBox 8_4_2019 9_25_37 AM (2)](https://user-images.githubusercontent.com/53537931/62419310-ca7e3b80-b69a-11e9-89b9-e00dd31f6b3d.png)

**Comment by peterpt** [comment]
https://askubuntu.com/questions/1109982/e-could-not-get-lock-var-lib-dpkg-lock-frontend-open-11-resource-temporari

**Comment by shubhankarbis007** [comment]
hey the problem with mingw32 is that it is no longer supported for newer version of linux or kali.
Try this command instead sudo apt install mingw-w64
after running this command again run the setup.sh file it should work

**Comment by shubhamdalavi20** [comment]
I will help you, tonight, could you mail me back tonight?
