### ISSUE TITLE
armv71 can't succes install thefatrat

### ISSUE THREAD

**Issue by vhirgo** [Screetsec/TheFatRat#185]
Setup Script for FATRAT 1.9.5

 Setup will not proceed because none of these archs were detected

 x86_64|i386|i486|i586|i686|aarch64

 Report this arch:  armv7l  into fatrat issues on github

Press any key to continue

**Comment by peterpt** [comment]
armv6 & 7 were disabled from fatrat installation .

**Comment by cipiricus** [comment]
if you want to install FatRat on Raspberry Pi you must have third version because it's equipped with armv8 arch 64 bit ARM CPU
