### ISSUE TITLE
JarSigner NOT OK

### ISSUE THREAD

**Issue by ITLerner** [Screetsec/TheFatRat#189]
Hello ! I am using Linux 4.3.0- kali-amd64 . i download and installed fatrat . after running setup.sh I am finding this error. (Screenshot attached) . Please help me how can i fix jarsigner Not OK issue.
![issue](https://user-images.githubusercontent.com/32157902/30684090-50362cba-9ec9-11e7-8738-1464fb0f3d24.jpg)

**Comment by peterpt** [comment]
that is happening because you are using openjdk-7 in your system .
Try to remove openjdk-7-jdk from your system and do an autoremove with your apt .
Then run setup again .

**Comment by ITLerner** [comment]
Thank you very much for your prompt reply, time and help. Issue resolved. Regards

**Comment by hacker950** [comment]
still i get jarsigner (default-jdk)-> Not OK ,im using kali in termux via mobile to acess TheFatRat

**Comment by hacker950** [comment]
> still i get jarsigner (default-jdk)-> Not OK ,im using kali in termux via mobile to acess TheFatRat

**Comment by rinxhen17** [comment]
Sudo apt get update and sudo apt-get install default-jdk 
This will fix your problem

**Comment by ThePickwickian** [comment]
Hi,
I am having the same problem and I have followed all the above steps and am still getting that error.

**Comment by Guardsword** [comment]
jarsigner (default-jdk)-> Not OK

I am getting a similar error as below. I removed open jdk as explained above. When I try to reinstall, its again installing the open JDK itself. So I cancelled it. Can I proceed with reinstalling the same. My environment is Kali 2020.2 on a VMWare. Please help.

**Comment by justinbanner** [comment]
> Sudo apt get update and sudo apt-get install default-jdk
> This will fix your problem
I had the same issue, I tried what you said and it worked for me!!
Thank you!!
