### ISSUE TITLE
The created FUD does not work on 64 bit Windows 7/10.

### ISSUE THREAD

**Issue by dev227** [Screetsec/TheFatRat#19]
Hello!

First, it's really great tool.
I tested it on 32 bit Windows 7 on virtual machine - no problems, everything works.
But tried to test it in normal environment, on my PCs, both are 64 bits, Windows 7 and Windows 10.
It crashes about 3 seconds after launch, does not even estabilish a connection.

Screens:
![image](https://cloud.githubusercontent.com/assets/22943096/19532368/b34dde2a-963b-11e6-97db-c95b75a26f80.png)

![image](https://cloud.githubusercontent.com/assets/22943096/19532412/e53eca48-963b-11e6-87db-84c08ec27163.png)

**Comment by Screetsec** [comment]
not work in 64 bit you right  l, you can use pwnwind in thefatrt for bypas antivirus
