### ISSUE TITLE
setup.sh dont start in armv7 ??

### ISSUE THREAD

**Issue by ikelirawan** [Screetsec/TheFatRat#190]
Why i run setup.sh dont start in armv7??

**Comment by ikelirawan** [comment]
Setup Script for FATRAT 1.9.5                                       Setup will not proceed because none of these archs were detected             x86_64|i386|i486|i586|i686|aarch64                                           Report this arch:  armv7l  into fatrat issues on github                     Press any key to continue

**Comment by peterpt** [comment]
armv7 and armv6 (android devices) are not supported by fatrat .
