### ISSUE TITLE
application compatibility error..fatrat not working in windows 7 64 bit

### ISSUE THREAD

**Issue by mateo24xx** [Screetsec/TheFatRat#193]
i choose option 2 "" Create Fud 100% Backdoor with Fudwin 1.0
but it want work i receive this error " the version of this file is not compatible with the version of windows your running............""
i read here that this problem is old but i can find the answer .
if someone can help solution this?
here you have picture of problem
![payloadincomp](https://user-images.githubusercontent.com/24534204/31228488-fe634fa6-a9dd-11e7-8ac1-d6ee37092b86.PNG)

**Comment by peterpt** [comment]
What message would you expect when running the backdoor on windows ?
something like this : "Congratulations , you just installed a backdoor on your windows" ?

**Comment by AayushZ** [comment]
> What message would you expect when running the backdoor on windows ?
> something like this : "Congratulations , you just installed a backdoor on your windows" ?

Does it mean it was just shown to fool the user and the backdoor is running?

**Comment by peterpt** [comment]
yes
