### ISSUE TITLE
./SETUP.SH ERROR :(

### ISSUE THREAD

**Issue by pelusa31416** [Screetsec/TheFatRat#194]
When I reach the moment to write ./setup.sh, it says this:

Was not possible to install The Packages Labeled (Not Ok) in this list above
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)
before running fatrat setup script again

root@kali:~/TheFatRat#﻿

What should I do?

**Comment by peterpt** [comment]
Check closed issues , and you find your solution around there .
