### ISSUE TITLE
Problem !!!!

### ISSUE THREAD

**Issue by captinluigi** [Screetsec/TheFatRat#195]
I gotta problem with Fatrat 1.9.5 64 bit kali linux 
while i statr Setup.sh this messages are appear :+1: 

Checking type of shell ....
[local]
 [ * ] Checking for internet connection
 [ X ]::[Internet Connection]: LOCAL ONLY!
 [X] Your Internet is not working correctly!
 [*] Checking ....
 You are connected to your local network but not to the web .
 Check if your router/modem gateway is connected to the web .

 Setup will not continue , you are only connected to your local lan.

 Setup will stop because :
 Ping google.com = Failed
 Ping google DNS = Failed

 Press [ENTER] key to continue

i tryed more than 20 times but i can't find any solution help please

**Comment by cyian-1756** [comment]
It looks like it's failing because it can't connect to the internet. Connect to the internet and run it again

**Comment by peterpt** [comment]
We do not give support to Linux OS issues .

**Comment by captinluigi** [comment]
cyian-1756
i have an connection internet for firefox browser but i can't any connection with fatrat ?

**Comment by peterpt** [comment]
Dont be ridiculous , it is not fatrat ,  it is all your terminal connections .
Do "ping google.pt" and you will see why fatrat gives that error .
That problem is related to your linux OS and we do not give support to linux OS , only fatrat  and its bugs .
