### ISSUE TITLE
Kali Linux moto

### ISSUE THREAD

**Issue by salamancageek** [Screetsec/TheFatRat#196]
How I can install TheFatRat en Kali Linux 1 (moto) if it can be installed in backtrack?

**Comment by peterpt** [comment]
Backtrack !!!, Kali moto is not backtrack , from backtrack came kali linux and not the other way around .
Yes , it works on kali linux 1.1.0a because i have here a VM with kali 1.1.0a where fatrat is working perfectly .

**Comment by salamancageek** [comment]
When I install it, system crash. It must be Kali Rolling Repositories. So I can´t

**Comment by peterpt** [comment]
Edit setup.sh with any file editor in linux .
delete lines 506 & 507 
then save the file and execute it .
Fatrat will not use kali rooling repositories , will only use kali sana .
