### ISSUE TITLE
cat: powershell_attack.txt: No such file or directory

### ISSUE THREAD

**Issue by n1ete** [Screetsec/TheFatRat#197]
cant create any payloads with script anymore i get always the same error in the shell

`cat: powershell_attack.txt: No such file or directory
rm: cannot remove 'unicorn.rc': No such file or directory
mv: cannot stat 'powershell_attack.txt': No such file or directory
`
its weird because i created allready a bat windwos payload succsessfull with it
please advice ;)

**Comment by n1ete** [comment]
sorry, my fault! i did something wrong in the rhost field in kombination with ngrok

**Comment by hdawg12** [comment]
i'm having same issue. it says "cat: powershell_attack.txt: No such file or directory"  What did you do to fix it?

**Comment by aregooo** [comment]
Does anyone know how to fix this?
