### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by 007newborn** [Screetsec/TheFatRat#198]
Please tell how to uninstall fatrat and everything else installed by it.

**Comment by peterpt** [comment]
Where is the location of your fatrat installation directory ?

**Comment by 007newborn** [comment]
/home/downloads.

**Comment by peterpt** [comment]
open a terminal and write : 
cd /
rm -rf /home/downloads/TheFatRat
rm -f /usr/local/sbin/d2j-*
rm -f /usr/local/sbin/dx
rm -f /usr/local/sbin/aapt
rm -f /usr/local/sbin/apktool
rm -rf /usr/local/share/dex2jar
rm -f /usr/share/applications/TheFatRat.desktop
rm -f /usr/local/sbin/fatrat

**Comment by anivibez** [comment]
on the topic of uninstalling fatrat mine is showing access denied

**Comment by anivibez** [comment]
please how can i solve that
