### ISSUE TITLE
couldnot locate original apk

### ISSUE THREAD

**Issue by 007newborn** [Screetsec/TheFatRat#199]
i am trying to create backdoor using original apk but while entering the file path : -

1) it doesnot autocompletes the path when hitting tab while entering manually
2)shows up "File does not exist , make sure you write the right path of it." error when i drag the apk file to terminal from /root/Downloads .
3)shows up "couldnot open *.apk. archieve type not supported" when setting path from any other location.

**Comment by Screetsec** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/issues.md
