### ISSUE TITLE
[!] Failed to align recompiled APK 

### ISSUE THREAD

**Issue by dpounraj** [Screetsec/TheFatRat#204]
Hi,

I have raised new issue for already closed case: https://github.com/Screetsec/TheFatRat/issues/140
This issue is still seen in new version. But based on database the issue is closed.

Could you please check the issue and resolve the solution. 
Thanks in advance.

ISSUE:

[ ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ ]
+------------------------------+
| [ 1 ] Use Backdoor-apk 0.2.2 |
| [ 2 ] Use old Fatrat method |
+------------------------------+

Select Tool to create apk : 1

[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ ]$
Generate Backdoor
+------------++-------------------------++-----------------------+
| Name || Descript || Your Input
+------------++-------------------------++-----------------------+
| LHOST || The Listen Addres || 192.168.0.5
| LPORT || The Listen Ports || 4444
| OUTPUTNAME || The Filename output || app_backdoor.apk
| PAYLOAD || Payload To Be Used || android/meterpreter/reverse_tcp
+------------++-------------------------++-----------------------+

[*] Creating RAT Apk File...done.

[*] Decompiling RAT APK file...done.

[*] Decompiling original APK file...done.

[*] Merging permissions of original and payload projects...done.

[*] Running proguard on RAT APK file...done.

[*] Decompiling obfuscated RAT APK file...done.

[*] Creating new directories in original project for RAT smali files...done.

[*] Copying RAT smali files to new directories in original project...done.

[*] Fixing RAT smali files...done.

[*] Obfuscating const-string values in RAT smali files...done.

[*] Locating smali file to hook in original project...done.

[*] Adding hook in original smali file...
done.

[*] Adding persistence hook in original project...done.

[*] Recompiling original project with backdoor...done.
date: invalid date ‘Sun Mar 03 05:23:22 2041’

[*] Generating RSA key for signing...done.

[*] Signing recompiled APK...done.

[*] Verifying signed artifacts...done.

[] Aligning recompiled APK...done.
[!] Failed to align recompiled APK***

This error appears when use method 5 to create the payload pleas fix this the system is Kali GNU/Linux Rolling 32-bit

Thanks,
Deepan

**Comment by suyash324** [comment]
have you find its solution bro????

**Comment by Screetsec** [comment]
Install the new version
