### ISSUE TITLE
./setup.sh permission denied

### ISSUE THREAD

**Issue by germanh2** [Screetsec/TheFatRat#205]
cannot gain access to the setup tools or to run the program

**Comment by peterpt** [comment]
chmod +x setup.sh && ./setup.sh

**Comment by germanh2** [comment]
thank you!

**Comment by germanh2** [comment]
OK, so now that I can get it. I receive multiple packages that are not getting downloaded. Then it says that this version is obsolete. How do i write this in to update fatrat?
