### ISSUE TITLE
You are connected to your local network but not to the web 

### ISSUE THREAD

**Issue by abiy22** [Screetsec/TheFatRat#206]
school admin block from pinging any websites on the router so, is there any way i could install fat rat without ping google or stop fat rat from pinging google rather just download its files.because fat rat directly goes to ping google rather than download its files.it stops because it can't ping google.

**Comment by peterpt** [comment]
I made some changes to the code in how fatrat will detect if user is connected to internet .
Clone again the fatrat git , and it will work fine now .
