### ISSUE TITLE
Failed to Decompile Original APK 

### ISSUE THREAD

**Issue by JadeAldemir** [Screetsec/TheFatRat#207]
![untitled](https://user-images.githubusercontent.com/33772466/33227795-80b0a80c-d1cd-11e7-9632-6e3de13e2726.png)

**Comment by Nisthar** [comment]
@JadeAldemir Update apktool. its a bug in apktool.

**Comment by peterpt** [comment]
We did not build backdoor apk , we just implement it in fatrat (check credits in fatrat) , if you want just to test an apk backdoor in your android device then use msfvenom like it is in this video .
https://www.youtube.com/watch?v=4xkiAPDXfPM
