### ISSUE TITLE
[x] There was an error creating your FUD rat with Powerstager .

### ISSUE THREAD

**Issue by bhostzider** [Screetsec/TheFatRat#208]
Hi, 
I have an error while creating a FUD backdoor with fudwin, powerstager.
Everything is updated.
Kali linux.
Here the fudwin.log:

/usr/bin/x86_64-w64-mingw32-gcc
Traceback (most recent call last):
  File "tools/power.py", line 19, in <module>
    import names
ImportError: No module named names

may someone help me please ?

Thanks

**Comment by peterpt** [comment]
pip install names

**Comment by bhostzider** [comment]
Thank you. It works better now!
