### ISSUE TITLE
There was an error in the creation of your RAT APK file. I select use old fatrat method

### ISSUE THREAD

**Issue by Ezox** [Screetsec/TheFatRat#212]
![thefatrat2](https://user-images.githubusercontent.com/34248555/33571873-aa931e28-d931-11e7-92df-ce523ca72583.png)

**Comment by peterpt** [comment]
we did not build the xripts that merge the payloads with the originals apks , new apks have new evading techniques to avoid fatrat tools .
Backdoor apk original source is from : 
https://github.com/dana-at-cp/backdoor-apk

try his new version and see if it works .

We are unable to do anything about this , we just implemented the code to facilitate user interface to that tool .
