### ISSUE TITLE
github FATRAT 

### ISSUE THREAD

**Issue by iidioms** [Screetsec/TheFatRat#213]
i m not able to download this ??? why???

**Comment by trollmad3** [comment]
@iidioms What does it say when your downloading it?

**Comment by noirecat** [comment]
can you try using git clone? or downloaded the zip?

**Comment by tanjirhassan** [comment]
Yes

**Comment by noirecat** [comment]
it's work or cannot download it?

**Comment by tanjirhassan** [comment]
I download it but when it running at the middle time the pc can't work.

**Comment by noirecat** [comment]
did you try to run TheFatRat in another pc?

**Comment by tanjirhassan** [comment]
No but try .

**Comment by Screetsec** [comment]
Give me details problem in here , you can download file using git clone or download wi zip files
