### ISSUE TITLE
Configuration file does not exists , run setup.sh first for config .

### ISSUE THREAD

**Issue by christmex** [Screetsec/TheFatRat#216]
why this happen?,if i setup again mingw64 not ok,and if i type "./fatrat" then say "Configuration file does not exists , run setup.sh first for config ." . how it work?

**Comment by peterpt** [comment]
while every package that fatrat needs is not installed then main config file is not written by the setup script .
This way avoids errors when running fatrat .

**Comment by christmex** [comment]
so wht i can do to repair it?

**Comment by peterpt** [comment]
well , instead asking for what to do , you should search into closed issues in fatrat for the solution for that .
However , it is interesting that for everyone with issues in fatrat installation they always create a new issue for a problem that someone already asked before and we gave the solution at that time .

I already told everything in this lat statement .

Look into : https://github.com/Screetsec/TheFatRat/issues?q=is%3Aissue+is%3Aclosed
