### ISSUE TITLE
The script is installing mingw-w64 on 32bit os

### ISSUE THREAD

**Issue by rupansh** [Screetsec/TheFatRat#220]
Title says it all. I even manually installed mingw32 on ParrotOS but it keeps trying to install the 64 bit version for some reason. Please help! I have been trying all kinds of fixes since an hour or so

**Comment by peterpt** [comment]
Without both mingw32 & 64bit fatrat is unable to create windows FUD exes .
I have no idea if you know , but you can install ming 64 on a 32bit system .
Basically you need both mingw architectures installed to run fatrat

**Comment by rupansh** [comment]
Hi can you help me in installing it manually then? for some reason the script is not installing it

**Comment by peterpt** [comment]
run setup from fatrat and post here a screenshot from the error .

**Comment by rupansh** [comment]
fixed by manually installing sorry for late reply! My PC wasn't working properly
