### ISSUE TITLE
Not able to configure

### ISSUE THREAD

**Issue by vijaydohare** [Screetsec/TheFatRat#225]
I have cloned the repository and just executed following command
    chmod +x setup.sh && ./setup.sh

following error occurred
    setup.sh: 3: setup.sh: Syntax error: "(" unexpected

**Comment by peterpt** [comment]
right here it is working like a charm .
You should try to clone again to a different directory and repeat the procedure .
What linux distro are you using ?

**Comment by vijaydohare** [comment]
Ok i'll clone it again
And i tried this on ubuntu desktop 17 as well as on kali basic linux.

**Comment by vijaydohare** [comment]
Finally solved the issue
As @peterpt already said here is no issue in the setup.sh
Actually i downloaded cloned the the repository in windows 7 that's why fileformat of setup.sh set to windows CRLF, i changed it back to LF

`:set fileformat=unix`

Finally saved it, and it worked
