### ISSUE TITLE
Fatrat Bricks Ubuntu

### ISSUE THREAD

**Issue by originalabhay** [Screetsec/TheFatRat#228]
This problem happend in _Xubuntu, Ubuntu and Lubuntu_
after  installation of  fatrat is done, when ever i reboot my pc, after selecting ubuntu from grub the splash screen get stuck to dev/sda/clean and nothing happens after that.
**I gave root access and everything!**

**Comment by peterpt** [comment]
Surelly that is some kind of different issue you must have there , right here i dont have any issue with fatrat and to be honest , there is no code in fatrat that could break grub boot , the partition , or whatever you may think .

The code is open source , this means that everyone can look inside the fatrat scripts and see what the script does , this is not Windows .

**Comment by originalabhay** [comment]
This happened so many times... Suerly i dual boot with windows!

**Comment by peterpt** [comment]
No comments .
I also run here a dual boot and never had any issue with this tool or any other that could lead to a lost of boot config , and if you notice , you are the only case in years .
One thing i can be sure , i will not be the person that will help you find out what is the problem with your linux with that excuse .
My advice to you is to not use Linux , or as alternative , use linux in windows in a VM image .
