### ISSUE TITLE
mingw32 parrot

### ISSUE THREAD

**Issue by nithilin** [Screetsec/TheFatRat#230]
setup on parrot Linux parrot 4.14.0-parrot7-amd64 #1 SMP Parrot 4.14.7-1parrot7 (2017-12-28) x86_64 GNU/Linux

still problem with install mingw32
 [ X ] Mingw-32 -> not found

**Comment by wtf123000** [comment]
![screenshot at 2018-01-08 13-44-45](https://user-images.githubusercontent.com/35235800/34691569-319f8970-f47a-11e7-87a5-3252ed92f6fe.png)
![screenshot at 2018-01-08 13-44-24](https://user-images.githubusercontent.com/35235800/34691570-31b56d94-f47a-11e7-8e14-19cf92c5c192.png)
![screenshot at 2018-01-08 13-44-20](https://user-images.githubusercontent.com/35235800/34691571-31e1d73a-f47a-11e7-8fac-5b4e2f3f3297.png)
Please look at the right window, you can see the errors when trying to install on ParrotOS

**Comment by wtf123000** [comment]
Also please disregard the left window, that has nothing to do with the install.

**Comment by nithilin** [comment]
yes
this is exactly my problem

**Comment by wtf123000** [comment]
I tried to add kali rolling repo but it is still throwing same errors. tried to edit setup.sh to remove kali.old repo. still throwing same errors

**Comment by wtf123000** [comment]
Ok I found you a solution: go to https://packages.debian.org/jessie/all/mingw32 and download the package at the bottom of the page. When it downloads, right click it and click Open with GDebi Package Installer, then install it. Do the same for https://packages.debian.org/jessie/all/mingw32-binutils 

then run ./setup.py again. FatRat will install in Parrot.

**Comment by wtf123000** [comment]
By the way nithilin, this issue has been solved x100 times. You should search the solved issues, it's there dozen's of times.

**Comment by nithilin** [comment]
is dont work for me

**Comment by arth3m1s** [comment]
thank you wtf123000
thats work

**Comment by SheesAli** [comment]
Watch this video
https://www.youtube.com/watch?v=CXvTKtYdm3Q

**Comment by demauye** [comment]
i will try

**Comment by Screetsec** [comment]
update script setup.sh you can install mingw easy
