### ISSUE TITLE
There was an error creating your FUD rat with Powerstager

### ISSUE THREAD

**Issue by oyekanwahab** [Screetsec/TheFatRat#232]
i have this error from fudwin.log

`usr/bin/x86_64-w64-mingw32-gcc`
`Traceback (most recent call last):`
 ` File "tools/power.py", line 19, in <module>`
   ` import names`
`ImportError: No module named names`

have installed `names` but it still gives me same issue
am running on ubuntu 16.04

have checked if name is running 
  `root@boss:~# names`
  `Antonia Thompson`

**Comment by peterpt** [comment]
run on your terminal : 
pip install names

**Comment by oyekanwahab** [comment]
i have names installed

**Comment by peterpt** [comment]
no you dont have it , names is not an app that you can call from your terminal like you show in one of your posts .
(names) for powerstager in fatrat is a module to run in python .
