### ISSUE TITLE
hello i tried all solution and youtube videos but cant solve this error mingw-32 not isntalled on parrot os latest

### ISSUE THREAD

**Issue by kimyunz** [Screetsec/TheFatRat#233]
xterm -> OK
Dns-Utils -> OK
GCC -> OK
Apache2 -> OK
Gnome Terminal -> OK
UPX -> OK
Ruby -> OK
Openssl -> OK
Monodevelop -> OK
Jarsigner -> OK
Unzip -> OK
Keytool -> OK
Mingw64 -> OK
mingw-32 -> Not OK
DX -> OK
Aapt -> OK
Apktool -> OK
Dex2Jar -> OK
Metasploit -> OK
Backdoor-Factory -> OK
Searchsploit -> OK
Was not possible to install The Packages Labeled (Not Ok) in this list above
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)
before running fatrat setup script again

**Comment by sungod88** [comment]
I forgot the link but someone posted this same issue a few days ago. you can download those dependencies separate and install them to get past this issue. Check the issues page for similar post

**Comment by jagathrajah** [comment]
Even i too got the same but try to stay calm reinstall it there is a chance to got
 install

**Comment by jagathrajah** [comment]
but i installed in kalilinux 2017.3 on 28.1.18 i entered the code to configure and slept it installed properly so be calm dont hurry

**Comment by tom3005** [comment]
Download and install mingw32 from here. Had the same problem.

https://packages.debian.org/wheezy/amd64/mingw32/download

**Comment by peterpt** [comment]
just search on closed issues for the solution for this issue , don't create new issues based on an issue that was already solved before on another user .
