### ISSUE TITLE
Updation of tools to latest Versions (specially apktool, aapt, other related to android)

### ISSUE THREAD

**Issue by duckkar** [Screetsec/TheFatRat#234]
Firstly, I want to say that this is a very powerful and easy to use tool.. No tool can be on the internet can be compared to its simplicity..
I opened this issue as I want to highlight that many tool used in fatrat are **outdated**. Yesterday i was trying to make a backdoor apk but every time it says unable to recompile.. And after many hours of finding I found that apktool is not decompiling properly... 
First, I used apt-get install apktool to upgrade my version but then also it shows version **2.2.2**.. 
After much frustration and I replaced **apktool** file in fatrat/tools to the latest version **2.3.1**. And Amazing everything worked fine... So its my humble request to all the developers to update all the tools to their latest versions(esp. tools related to android) It will help us a lot...
And I also Want to highlight that FUD created by PwnWinds are detected by many antivirus. When i scanned them on nodistribute.com Almost every FUD is detected by 16/30 antivirus..
SO if these tools can also be updated it will help noobs like me very much..
And after all, **THANKS** For This **GREAT** tool and upgrading makes it a lot better...

**Comment by peterpt** [comment]
Here t is the thing , you are right , however even if you were able to decompile the apk it does not mean that you are able to merge the payload on that apk , and even if fatrat says that everything was done , then you will probably have issues installing the apk on the android devices .
Maybe you should try to do the process manually , https://null-byte.wonderhowto.com/how-to/embed-metasploit-payload-original-apk-file-part-2-do-manually-0167124/

however , using the manual process the antivirus will detect , backdoor apk in fatrat have the ability to hide the payload from antivirus , but it is not working fine at this moment with recent apks .
