### ISSUE TITLE
Help creating stageless FUD bat payload

### ISSUE THREAD

**Issue by just678** [Screetsec/TheFatRat#235]
Hi, i changed the payload creation of fatrat from windows/meterpreter/reverse_tcp to windows/meterpreter_reverse_tcp, fatrat is able to create the payload but when i run the bat file, the pc isnt able to run the file completly, i think that this happen because the bat file is too large, can i change something in your code to make a smaller stageless bat file ??
thanks in advance

**Comment by peterpt** [comment]
It takes sometime to the victim connect to the attacker .
Watch the tests here :
https://youtu.be/ZA7DCsGISmU
