### ISSUE TITLE
Can't Install dx (package unmet dependencies)

### ISSUE THREAD

**Issue by stormweather** [Screetsec/TheFatRat#241]
file:///root/Pictures/Screenshot%20from%202018-02-07%2001-30-11.png

How can I resolve this? Is this an OS problem? Thank you!

**Comment by peterpt** [comment]
we are unable to see your picture , when it is located in your computer and not on github .
Next time make sure you see this video first to know how it is done : 
https://www.youtube.com/watch?v=mGXFVxDlWgU
