### ISSUE TITLE
[x] There was an error creating your FUD rat with Powerstager .

### ISSUE THREAD

**Issue by th3j0ker** [Screetsec/TheFatRat#242]
Hello!
so, i've tried everything but my problem is not yet solved (blah blah)..
here goes the data
----------------------------------------fudwin.log----------------------------------------

/usr/bin/x86_64-w64-mingw32-gcc
Traceback (most recent call last):
  File "tools/power.py", line 19, in <module>
    import names
ImportError: No module named names

----------------------------------------setup.log-----------------------------------------

| Tools paths configured in (setup.sh) for TheFatRat |
                                                
/usr/bin/xterm
/usr/bin/dig
/usr/bin/gcc
/usr/sbin/apache2
/usr/bin/gnome-terminal
/usr/bin/upx
/usr/bin/ruby
/usr/bin/openssl
/usr/bin/monodevelop
/usr/bin/jarsigner
/usr/bin/unzip
/usr/bin/keytool
/root/j0ker-db/Scripts/TheFatRat/tools/android-sdk/zipalign
/root/j0ker-db/Scripts/TheFatRat/tools/proguard5.3.2/lib/proguard
/usr/bin/x86_64-w64-mingw32-gcc
/usr/bin/i586-mingw32msvc-gcc
/usr/local/sbin/dx
/usr/local/sbin/aapt
/usr/local/sbin/apktool
/usr/local/sbin/d2j-dex2jar
msfconsole
msfvenom
backdoor-factory
searchsploit
/usr/local/sbin/fatrat

****** things tried ******

1.) apt-get install mingw-w64 <-- already exists, so does 32 (not a problem)

2.) pip install names <-- which gives something like this on terminal

"Requirement already satisfied: names in /usr/local/lib/python3.6/dist-packages"

thats it..

thank you.

**Comment by peterpt** [comment]
the problem is that you installed names module for python 3.6 but not for python 2.7 witch is the one that powerstager works

try , (pip2 install names) .
In case you do not have pip2 then you must set a virtual environment for python , so you can use python 2.7 when using fatrat .
Basically all python scripts in fatrat work with python 2.7 .

https://itsfoss.com/python-setup-linux/

**Comment by th3j0ker** [comment]
that worked!....thanks...

**Comment by adada111** [comment]
can

**Comment by adada111** [comment]
can you tell me how to slove it?
