### ISSUE TITLE
Solved... TheFatRat Installation Issue... :-) [ mingw-32 & mingw-w64 ] (Plss Help Me with This... Tried All the things you discussed with others... Stuck with this from 3 days...)

### ISSUE THREAD

**Issue by ragavravi** [Screetsec/TheFatRat#244]
![32 64](https://user-images.githubusercontent.com/36502238/36301793-17b2117e-132c-11e8-9b78-1d80a016d34e.PNG)

![2](https://user-images.githubusercontent.com/36502238/36302053-04f669a8-132d-11e8-91bb-d8f13ece97ed.PNG)

![3](https://user-images.githubusercontent.com/36502238/36302060-098646d2-132d-11e8-8aa2-980660ed8017.PNG)

**Comment by ragavravi** [comment]
![4](https://user-images.githubusercontent.com/36502238/36303242-765b9baa-1331-11e8-8d3b-30cd66d67c51.PNG)

**Comment by peterpt** [comment]
With those repositories in your sources.list file , write in terminal : 

apt-get update -y && apt-get install mingw32 && apt-get install mingw-w64 -y

After the installation , run setup.sh from fatrat and everything should be fine .
permissions to run fatrat script are only given after a succefull setup instalation

**Comment by ragavravi** [comment]
Still the same error...


![12](https://user-images.githubusercontent.com/36502238/36309432-8e12906e-134a-11e8-9ec6-2611a8cf0030.PNG)

![13](https://user-images.githubusercontent.com/36502238/36309436-923d9e22-134a-11e8-94d2-9d1b83880092.PNG)

**Comment by ragavravi** [comment]
Can the problem be with the Repositories...?
![14](https://user-images.githubusercontent.com/36502238/36309538-0cc6f792-134b-11e8-99f7-55c0b4c8465d.PNG)

**Comment by peterpt** [comment]
yup , it is

The right one are : 

deb http://http.kali.org/kali kali-rolling main contrib non-free
deb-src http://http.kali.org/kali kali-rolling main contrib non-free
deb http://old.kali.org/kali sana main non-free contrib
deb-src http://old.kali.org/kali sana main non-free contrib

write these repositories in your sources list .
then after this , write this in your terminal : 
wget https://http.kali.org/kali/pool/main/k/kali-archive-keyring/kali-archive-keyring_2018.1_all.deb && dpkg -i kali-archive-keyring_2018.1_all.deb

then , do the process all over again by installing mingw as it was written before .

**Comment by ragavravi** [comment]
It Worked...
FatRat Installed...
Thank You so so much @peterpt ...

Will Upload All The Screenshots so others facing the Same Issue could get Help from it... :-)

**Comment by ragavravi** [comment]
Repositories...
![20](https://user-images.githubusercontent.com/36502238/36340139-74b53a6a-13fc-11e8-8889-8081132f152d.PNG)

Updates...
![21](https://user-images.githubusercontent.com/36502238/36340140-859977ce-13fc-11e8-8143-e78075bf11dc.PNG)

![22](https://user-images.githubusercontent.com/36502238/36340143-a06a569a-13fc-11e8-9290-116f0f96e9de.PNG)

![23](https://user-images.githubusercontent.com/36502238/36340144-a0a2bc60-13fc-11e8-803c-88e49364a817.PNG)

![24](https://user-images.githubusercontent.com/36502238/36340145-a0daf792-13fc-11e8-98f7-f5343136a5a2.PNG)

![25](https://user-images.githubusercontent.com/36502238/36340146-a113b1f4-13fc-11e8-8ef0-27091ddc262a.PNG)

![26](https://user-images.githubusercontent.com/36502238/36340147-a14eea3a-13fc-11e8-9a90-5605b859f6ce.PNG)

Found - mingw32 & mingw-w64
![27](https://user-images.githubusercontent.com/36502238/36340159-debe91ae-13fc-11e8-8a43-feea6f24d54e.PNG)

TheFatRat Installed...
![28 fatrat](https://user-images.githubusercontent.com/36502238/36340161-e5cac18e-13fc-11e8-934f-49fb5afdfc9d.PNG)


Thanks Again @peterpt ... :-)

**Comment by peterpt** [comment]
great , have fun ;)

**Comment by ragavravi** [comment]
Thanks a lot...

Opening a New Issue on " Unfortunately app has stopped"

I hope you'll Help me with the same too... :-)

**Comment by SheesAli** [comment]
Try this
https://www.youtube.com/watch?v=CXvTKtYdm3Q

**Comment by ragavravi** [comment]
The problem is already Solved @SheesAli ...
Thanks to @peterpt , just follow what he mentioned from the Start...

**Comment by mianumar** [comment]
I have Same Problem

**Comment by AmanTyagi2432** [comment]
Tried All the things you tell @peterpt 
but 
![Screenshot from 2019-07-13 19-31-03](https://user-images.githubusercontent.com/52859453/61172775-41964780-a5a7-11e9-81d8-767adea59976.png)

**Comment by AmanTyagi2432** [comment]
plzz help me @peterpt , @ragavravi 

The following NEW packages will be installed:
  g++-mingw-w64 g++-mingw-w64-x86-64 gcc-mingw-w64 gcc-mingw-w64-x86-64 mingw-w64 mingw-w64-x86-64-dev
0 upgraded, 6 newly installed, 0 to remove and 2122 not upgraded.
Need to get 64.9 MB of archives.
After this operation, 370 MB of additional disk space will be used.
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 mingw-w64-x86-64-dev all 6.0.0-3 [3454 kB]
Get:2 http://ftp.harukasan.org/kali kali-rolling/main amd64 gcc-mingw-w64-x86-64 amd64 8.3.0-6+21.3~deb10u1 [35.8 MB]                                
Get:2 http://ftp.harukasan.org/kali kali-rolling/main amd64 gcc-mingw-w64-x86-64 amd64 8.3.0-6+21.3~deb10u1 [35.8 MB]                                
Err:2 http://ftp.harukasan.org/kali kali-rolling/main amd64 gcc-mingw-w64-x86-64 amd64 8.3.0-6+21.3~deb10u1                                          
  Could not connect to ftp.harukasan.org:80 (211.219.253.179), connection timed out Could not connect to ftp.harukasan.org:80 (14.49.100.116), connection timed out Could not connect to ftp.harukasan.org:80 (14.49.100.37), connection timed out Could not connect to ftp.harukasan.org:80 (14.49.99.238), connection timed out [IP: 211.219.253.179 80]
Err:3 http://ftp.harukasan.org/kali kali-rolling/main amd64 g++-mingw-w64-x86-64 amd64 8.3.0-6+21.3~deb10u1
  Unable to connect to ftp.harukasan.org:http: [IP: 211.219.253.179 80]
Err:4 http://ftp.harukasan.org/kali kali-rolling/main amd64 g++-mingw-w64 all 8.3.0-6+21.3~deb10u1
  Unable to connect to ftp.harukasan.org:http: [IP: 211.219.253.179 80]
Err:5 http://ftp.harukasan.org/kali kali-rolling/main amd64 gcc-mingw-w64 all 8.3.0-6+21.3~deb10u1
  Unable to connect to ftp.harukasan.org:http: [IP: 211.219.253.179 80]
Err:6 http://ftp.harukasan.org/kali kali-rolling/main amd64 mingw-w64 all 6.0.0-3
  Unable to connect to ftp.harukasan.org:http: [IP: 211.219.253.179 80]
Fetched 3454 kB in 8min 7s (7095 B/s)              
E: Failed to fetch http://ftp.harukasan.org/kali/pool/main/g/gcc-mingw-w64/gcc-mingw-w64-x86-64_8.3.0-6+21.3~deb10u1_amd64.deb  Could not connect to ftp.harukasan.org:80 (211.219.253.179), connection timed out Could not connect to ftp.harukasan.org:80 (14.49.100.116), connection timed out Could not connect to ftp.harukasan.org:80 (14.49.100.37), connection timed out Could not connect to ftp.harukasan.org:80 (14.49.99.238), connection timed out [IP: 211.219.253.179 80]
E: Failed to fetch http://ftp.harukasan.org/kali/pool/main/g/gcc-mingw-w64/g++-mingw-w64-x86-64_8.3.0-6+21.3~deb10u1_amd64.deb  Unable to connect to ftp.harukasan.org:http: [IP: 211.219.253.179 80]
E: Failed to fetch http://ftp.harukasan.org/kali/pool/main/g/gcc-mingw-w64/g++-mingw-w64_8.3.0-6+21.3~deb10u1_all.deb  Unable to connect to ftp.harukasan.org:http: [IP: 211.219.253.179 80]
E: Failed to fetch http://ftp.harukasan.org/kali/pool/main/g/gcc-mingw-w64/gcc-mingw-w64_8.3.0-6+21.3~deb10u1_all.deb  Unable to connect to ftp.harukasan.org:http: [IP: 211.219.253.179 80]
E: Failed to fetch http://ftp.harukasan.org/kali/pool/main/m/mingw-w64/mingw-w64_6.0.0-3_all.deb  Unable to connect to ftp.harukasan.org:http: [IP: 211.219.253.179 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by jmkim** [comment]
@AmanTyagi2432

Could you please retry now? Seems your problem is related to Kali mirror server status, which was down at that time and now solved.

**Comment by Gabrielkim1** [comment]
Hello
I have a similar problem

xterm -> OK
Dns-Utils -> OK
Mono-Denvelop Utils -> OK
GCC -> OK
Apache2 -> OK
Gnome Terminal -> OK
UPX -> OK
Ruby -> OK
Openssl -> OK
jarsigner (openjdk-8-jdk)-> Not OK
Unzip -> OK
keytool -> Not OK
mingw-w64 -> Not OK
mingw-32 -> Not OK
DX -> OK
Aapt -> OK
Apktool -> OK
Baksmali -> OK
Metasploit -> OK
Backdoor-Factory -> OK
Searchsploit -> OK
Was not possible to install The Packages Labeled (Not Ok) in this list above
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)
before running fatrat setup script again
I have tried to follow the steps but it has not worked for me

**Comment by newpaney145** [comment]
i am confused about source.list file ..please tell me where i need to store this file in kali linux directory

**Comment by peterpt** [comment]
sources.list is located in /etc/apt/sources.list .
Do not revive old topics .
