### ISSUE TITLE
mingw32 & mingw-w64 not found

### ISSUE THREAD

**Issue by l0sk3** [Screetsec/TheFatRat#247]
Okey, so i had issue with mingw32 not found so i looked it up on issue #8 and it only made it worse... After following code apt-get remove --purge mingw-w64 i deleted mingw-w64... what do i do now?

>

**Comment by ragavravi** [comment]
This could be All You need...

https://github.com/Screetsec/TheFatRat/issues/244

**Comment by l0sk3** [comment]
Oh it worked... Thanks a lot

**Comment by ragavravi** [comment]
Njoy... ;-)
