### ISSUE TITLE
Can I use android app made from android studio for fatrat?

### ISSUE THREAD

**Issue by niteshlekhi** [Screetsec/TheFatRat#251]
I developed an app in android studio and I want to embed backdoor in it using FatRat. Is it possible to do that and if yes, how?
TIA.

**Comment by peterpt** [comment]
On normal circunstances you can , however the apk backdoor scripts are not working well for new apks builded in recent android SDK .

**Comment by niteshlekhi** [comment]
That's why...mine is developed recently and its not working. So its not possible to do it? :(

**Comment by datteroandrea** [comment]
I have the same problem.
