### ISSUE TITLE
Unable to use dynamic DNS

### ISSUE THREAD

**Issue by r00tk3rnel** [Screetsec/TheFatRat#257]
So I recently attempted using fudwin in order to create a backdoor. And I am also attempting to install the backdoor on another device (I own the device) on another network. Unfortunately I can only use this backdoor on LAN therefore I portforwarded and setup a NO-IP DNS. When I set this DNS as the listening host-ip, I would always receive an error stating "There was an error creating your FUD rat with powerstager."Does anybody know how to fix this?

Additional Information:
OS: I am running Kali 2018.1

**Comment by peterpt** [comment]
There is no way to fix it , powerstager does not allow dns names , only ips .
