### ISSUE TITLE
Gnome fail after install fatrat

### ISSUE THREAD

**Issue by ajsurkhi** [Screetsec/TheFatRat#258]
When i try to install FATRAT by executing script setup.sh, on KALI LINUX 2017 & kali 2016 and Kali 2.0 lite edition, it download some package mingw32 mingw64  and install. After restart gnome wont load it shows some error message. please help?
screenshot a
![image](https://user-images.githubusercontent.com/37826684/37951849-83769472-31bb-11e8-832f-18a5334071c9.png)
s follows:

**Comment by ajsurkhi** [comment]
![image](https://user-images.githubusercontent.com/37826684/37951795-4f05e512-31bb-11e8-876c-179896683988.png)

**Comment by peterpt** [comment]
That have nothing to do with fatrat , and fatrat packages do not mess with your OS .

**Comment by alohe** [comment]
it  dose  i  have  the  same problem  too  right  after fatrat  is  done ...  my computer just frozz   and  i  restarted it  and  the  same  thing  just  poped  up
