### ISSUE TITLE
[!] Failed to decompile original APK file

### ISSUE THREAD

**Issue by Lasoitem** [Screetsec/TheFatRat#259]
hiii...i can't decompile original APK file..
help anyone help overcome the problem

   J  \.|'.\/ \                  				
    | |_.|. | | |   [--]   Backdoor Creator for Remote Acces [--] 	
     \__.' .|-' /   [--]  Created by: Edo Maland (Screetsec) [--]	
     L   /|o'--'\   [--]            Version: 1.9.6           [--]	
     |  /\/\/\   \  [--]          Codename: Whistle          [--]    
     J /      \.__\ [--]   Follow me on Github: @Screetsec   [--]	
     J /      \.__\ [--]   Dracos Linux : @dracos-linux.org  [--]	
     |/         /   [--]    				     [--]		
       \      .'\.  [--]     SELECT AN OPTION TO BEGIN:      [--]  
    ____)_/\_(___\. [--] .___________________________________[--]	
   (___._/  \_.___)'\_.-----------------------------------------/	

  
	[01]  Create Backdoor with msfvenom
	[02]  Create Fud 100% Backdoor with Fudwin 1.0
	[03]  Create Fud Backdoor with Avoid v1.2  
	[04]  Create Fud Backdoor with backdoor-factory [embed] 
	[05]  Backdooring Original apk [Instagram, Line,etc] 
	[06]  Create Fud Backdoor 1000% with PwnWinds [Excelent] 
	[07]  Create Backdoor For Office with Microsploit 
	[08]  Trojan Debian Package For Remote Acces [Trodebi] 
	[09]  Load/Create auto listeners  
	[10]  Jump to msfconsole  
	[11]  Searchsploit  
	[12]  File Pumper [Increase Your Files Size] 
	[13]  Configure Default Lhost & Lport 
	[14]  Cleanup  
	[15]  Help  
	[16]  Credits  
	[17]  Exit  

 | LPORT      ||  The Listen Ports       || 4444
 | OUTPUTNAME ||  The Filename output    || app_backdoor.apk
 | PAYLOAD    ||  Payload To Be Used     || android/meterpreter/reverse_tcp
  +------------++-------------------------++-----------------------+

 
[*] Creating RAT Apk File...done.
 
[*] Decompiling RAT APK file...done.
 
[*] Decompiling original APK file...done.
 [!] Failed to decompile original APK file

Press [ENTER] key to continue to return to fatrat menu

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md

**Comment by Lasoitem** [comment]
| LPORT      ||  The Listen Ports       || 4444
  | OUTPUTNAME ||  The Filename output    || app_backdoor.apk
  | PAYLOAD    ||  Payload To Be Used     || android/meterpreter/reverse_tcp
  +------------++-------------------------++-----------------------+


 
[*] Creating RAT Apk File...done.
 
[*] Decompiling RAT APK file...done.
 
[*] Decompiling original APK file...done.
 [!] Failed to decompile original APK file

Press [ENTER] key to continue to return to fatrat menu

still Failed to decompile original APK file 
:(
===============================================

/ ___| |__   ___  ___| | _(_)_ __   __ _             
 | |   | '_ \ / _ \/ __| |/ / | '_ \ / _\ |            
 | |___| | | |  __/ (__|   <| | | | | (_| |  _   _   _ 
  \____|_| |_|\___|\___|_|\_\_|_| |_|\__/ | (_) (_) (_)
                                     	|___/    
-- -- +=[(c) 2016-2017 | dracos-linux.org | Linuxsec.org | Hacker Indonesia 
-- -- +=[ Author: Screetsec < Edo Maland >  ]=+ -- -- 
 
 [!]::[Check Dependencies]:
 [✔]::[Distro]: Kali
 [✔]::[Release]: kali-rolling
 [✔]::[Check User]: root
 [✔]::[Terminal]: local
 [✔]::[Internet Connection]: CONNECTED!
 [✔]::[Apache2 Server Kali ]: Installation found!
 [✔]::[Ruby]: Installation found!
 [✔]::[Apktool]: Installation found!
 [✔]::[Aapt]: Installation found!
 [✔]::[Msfconsole]: Installation found!
 [✔]::[Msfvenom]: Installation found!
 [✔]::[Mingw32]: Installation found!
 [✔]::[Backdoor-factory]: Installation found!
 [✔]::[Xterm]: Installation found!

**Comment by Lasoitem** [comment]
Setup Script for FATRAT 1.9.5       

               32Bit OS detected

 Checking type of shell ....
[local]
 [ * ] Checking for internet connection
 [ ✔ ]::[Internet Connection]: CONNECTED!
 [ ✔ ] Xterm.............................[ found ]
 [ ✔ ] Dns-Utils ........................[ found ]
 [ ✔ ] Gcc compiler......................[ found ]
 [ ✔ ] Apache2 ..........................[ found ]
 [ ✔ ] Gnome Terminal....................[ found ]
 [ ✔ ] UPX Compressor....................[ found ]
 [ ✔ ] Ruby..............................[ found ]
 [ ✔ ] Openssl...........................[ found ]
 [ ! ] Installing tools dependencies
 [ ✔ ] Jarsigner (java)..................[ found ]
 [ ✔ ] Unzip.............................[ found ]
 [ ✔ ] Keytool (java)....................[ found ]
 [ ✔ ] Zipalign 
 [ ✔ ] Proguard 
 [ ✔ ] Mingw-w64 Compiler................[ found ]
 [ ✔ ] Mingw-32 Compiler................[ found ]
 [ ✔ ] DX 1.8
 [ ✔ ] Aapt v0.2-3821160
 [ ✔ ] Apktool v.2.2.2
 [ ✔ ] Dex2Jar 2.0
 [ ✔ ] Metasploit-Framework..............[ found ]
 [ ✔ ] Backdoor-Factory..................[ found ]
 [ ✔ ] Searchsploit......................[ found ]


 Reactivating your original repositories

**Comment by peterpt** [comment]
There is no solution for that , i already replied hundred of times before to this subject .
Eventually in future we will problably remove the merge rat apk with original apk tools until we find a better solution for it .
Create only the rat without merging it with the original apk using msfvenom and install it on your device for testing .
https://www.youtube.com/watch?v=PfUaCz-nzsU
