### ISSUE TITLE
why my fatrat has no internet connection

### ISSUE THREAD

**Issue by ericmcwhite** [Screetsec/TheFatRat#26]
why I got a warning this script need a active internet connection?

**Comment by samkushwah** [comment]
i am also facing this problem when i try to install fatrat it says
internet connection is offline 
 this script need a active internet connection

**Comment by peterpt** [comment]
the problem is not related to fatrat but related to your OS that is unable to ping hostnames .
This means that you can ping ips but not hostnames .
Search on google for a solution to that problem , that is not a fatrat issue .
