### ISSUE TITLE
ruby: warning: shebang line ending with \r may cause problems

### ISSUE THREAD

**Issue by Lasoitem** [Screetsec/TheFatRat#260]
```
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 10087 bytes
Saved as: /root/TheFatRat/temp/payload.apk
Generating 2,048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 10,000 days
	for: CN=Android Debug, O=Android, C=US
[Storing /root/TheFatRat/temp/debug.keystore]
```

**Comment by Screetsec** [comment]
its not problem

**Comment by AnonymousTTA** [comment]
Lasoitemm, these people are being indifferent to you, I have got your same problem I am finding a solution to it I will let you know ;)

**Comment by peterpt** [comment]
There is no problem at all , stop flooding the issues with junk questions .
Without the sign certificate , you are all unable to install anything on your android device .

**Comment by AnonymousTTA** [comment]
Peterpt, I know it doesn't show us as a problem indeed it says "may", I actually have this warning and at the end it didn't success by ending saying:
Apk-embed-payload.rb:190:in 'initialize' : No such file or directory @ rb_sysopen - original/androidManifest.xml (Errno::ENOENT)

If you find a solution to it you would be helpful.
