### ISSUE TITLE
Configuration file does not exist, run setup.sh first for config 

### ISSUE THREAD

**Issue by Ouss-Ben** [Screetsec/TheFatRat#263]

**Comment by Ouss-Ben** [comment]
![image](https://user-images.githubusercontent.com/38252418/38565350-fb577470-3cd8-11e8-9988-cd3f722627d8.png)
------------------
![image](https://user-images.githubusercontent.com/38252418/38565540-7b619b14-3cd9-11e8-8f90-cf38c8ff43de.png)

**Comment by sammymwangangi** [comment]
i have the same issue
