### ISSUE TITLE
Payload stop working

### ISSUE THREAD

**Issue by RusskiyMir** [Screetsec/TheFatRat#264]
I compile payload with fudwin (2 option, slow but powerfull) but if i start it in windows hi gives error and stop working, this what i get this
![2018-04-12 00-39-35](https://user-images.githubusercontent.com/38323384/38683129-d008690e-3e7d-11e8-851d-df6bca28a86c.png)
during compilation i no have troubles, and set up all right. thank you in advance.

**Comment by inarrizabalaga** [comment]
Same error

**Comment by p0wer0ff** [comment]
Same error
