### ISSUE TITLE
plzz help plzz

### ISSUE THREAD

**Issue by Ouss-Ben** [Screetsec/TheFatRat#265]
i've prblm just with mingw-w64 any solution plz :cry: 

![image](https://user-images.githubusercontent.com/38252418/38761545-adef1f26-3f7b-11e8-96a2-7fe682d0fa89.png)

**Comment by Ouss-Ben** [comment]
@peterpt @Screetsec

**Comment by peterpt** [comment]
Did you notice a file inside the fatrat git called troublesshoot ?

https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md

**Comment by Ouss-Ben** [comment]
yes i do ... the same probleme :disappointed:  , why u close my issue :open_mouth:

**Comment by Ouss-Ben** [comment]
@peterpt

**Comment by Ouss-Ben** [comment]
@peterpt sry bruh but the same :( 
![image](https://user-images.githubusercontent.com/38252418/38784139-9a57fbbe-4105-11e8-9568-c6add15bdeea.png)
