### ISSUE TITLE
"Unable to resolve hostnames ping"

### ISSUE THREAD

**Issue by CubeFaces** [Screetsec/TheFatRat#268]
![screenshot_nethunter terminal_20180502-222538](https://user-images.githubusercontent.com/38924977/39547770-1319594a-4e48-11e8-9b1f-9b70222496f7.png)
So, I keep getting this error when I try to run TheFatRat setup.sh on my phone, not sure why, any ideas on how to fix this?

**Comment by CubeFaces** [comment]
When I click enter, I get this
![screenshot_nethunter terminal_20180502-222609](https://user-images.githubusercontent.com/38924977/39547856-53f5ae5a-4e48-11e8-90c7-c96a7c553cf8.png)
Any help would be appreciated. 😁

**Comment by CubeFaces** [comment]
@peterpt i hope i added enough info about my problem, hope you can help me, thanks in advance 😄
[install.log](https://github.com/Screetsec/TheFatRat/files/1969205/install.log)

**Comment by peterpt** [comment]
You should not use fatrat in an android device for multiple reasons :

Fatrat uses heavy tools like metasploit , mingw , backdoor-factory
We had in the past multiples issues in trying to install dependencies on a based android device 

As far as i know we do not support android devices , even if a kali linux OS is running on the side of the android kernel .

Install the script in a desktop computer or a laptop .
