### ISSUE TITLE
Hidden Backdoor

### ISSUE THREAD

**Issue by stephanodesouza** [Screetsec/TheFatRat#271]
I was monitoring with wireshark my connections and found that besides the ip of my test machine the BAT generated by the tool was opening a connection to another IP that I discovered to be from Indonesia (180.253.31.125), which is considered by the same country as the developers. Could someone tell me why?

Google translator PT-BR / ENG

**Comment by peterpt** [comment]
I was thinking in giving a long explanation to your ridiculous affirmation , but i will not waste my time on that .
Fatrat is open source code so everyone can look how things work  : 
https://github.com/Screetsec/TheFatRat/blob/master/fatrat
