### ISSUE TITLE
  [x] There was an error in the creation of the payload .

### ISSUE THREAD

**Issue by Maneesh9063** [Screetsec/TheFatRat#272]
[*] Creating RAT payload with msfvenom
./fatrat: line 4144: $log: ambiguous redirect
 
[x] There was an error in the creation of the payload .
Check log file at : /root/Desktop/My Soft/TheFatRat-master/logs/apk-old.log
Press [ENTER] key to continue to return to fatrat menu

please help me to get out of this nothing is working in my fatrat ;(

**Comment by ramesh1258** [comment]
same here 
[x] There was an error in the creation of the payload .
Check log file at : /root/Desktop/TheFatRat-master/logs/apk-old.log
Press [ENTER] key to continue to return to fatrat menu

**Comment by Maneesh9063** [comment]
Iam using ngrok

**Comment by netnull** [comment]
I've also the same problem

**Comment by netnull** [comment]
And im also using ngrok

**Comment by BackSpoofer** [comment]
[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++     ]
 [*] Builing your powerstage rat for windows with the following values

   Target        : Windows 64 Bit
   Your IP/Host  : 192.168.43.204
   Your Port     : 1234
   Rat Filename  : game.exe
   Icon filename : vlc.ico

 
[x] There was an error creating your FUD rat with Powerstager .
 
Press [ENTER] key to continue to return to fatrat menu
 


i am also having the same problem

**Comment by peterpt** [comment]
Maneesh9063 this error : "./fatrat: line 4144: $log: ambiguous redirect" means that fatrat needs a lot of code rewritten , fatrat have 6000 lines of code , this means that every line that have : $log without like : "$log" needs to be fixed , and when i say $log i mean all other variables declared in the script starting with $ , also the color codes , that will take a while to be done and will probably be done by stages .

BackSpoofer , powerstager created a log file everytime it runs , so in your log folder should be there the reason , look for pstager.log in log files and post it here .
