### ISSUE TITLE
There was an error compiling APK 

### ISSUE THREAD

**Issue by netnull** [Screetsec/TheFatRat#274]
Hello, 
im using ngrok and thefatrat but at the end of the process i get this error:
Failed to recompile original project with backdoor

https://pastebin.com/EDxuC4AF
here the content of my logs. 
Any suggestions? 

Thank you :)

**Comment by netnull** [comment]
Someone can help me? I dunno how to solve this problem...

**Comment by Screetsec** [comment]
Update to the new version
