### ISSUE TITLE
Why one must be root to run the fatrat script?

### ISSUE THREAD

**Issue by ghost** [Screetsec/TheFatRat#275]
It makes no sense to me a program like this to be necessary to be run as root. Can anyone explain to me why is it necessary?

**Comment by r58iiz** [comment]
Root allows user to install and change the contents of the system. if given access to anyone in a system like LINUX, the results would be disastrous. AND yes this program requires root because it works the same way as METASPLOIT.

**Comment by Screetsec** [comment]
Read this how submit [Issue](https://github.com/Screetsec/TheFatRat/blob/master/issues.md)
