### ISSUE TITLE
Java exception when recompiling apk

### ISSUE THREAD

**Issue by ghost** [Screetsec/TheFatRat#277]
Versions:
**Metasploit: 4.16.59-dev
Ruby: 2.5.1p57
Java: OpenJDK 1.8.0
Fatrat: 1.9.6**

Reproducing it:
>[05]  Backdooring Original apk [Instagram, Line,etc] 

>insert LHOST, LPORT, path to original apk

>payload 3  [ 3 ] android/meterpreter/reverse_tcp  

>tool 1 [ 1 ] Use Backdoor-apk 0.2.2

last lines of output:

 

> [*] Creating RAT Apk File...done.
>  
> [*] Decompiling RAT APK file...done.
>  
> [*] Decompiling original APK file...done.
>  
> [*] Merging permissions of original and payload projects...done.
>  
> [*] Running proguard on RAT APK file...done.
>  
> [*] Decompiling obfuscated RAT APK file...done.
>  
> [*] Creating new directories in original project for RAT smali files...done.
>  
> [*] Copying RAT smali files to new directories in original project...done.
>  
> [*] Fixing RAT smali files...done.
>  
> [*] Obfuscating const-string values in RAT smali files...done.
>  
> [*] Locating smali file to hook in original project...done.
>  
> [*] Adding hook in original smali file... 
> done.
>  
> [*] Adding persistence hook in original project...done.
>  
> [*] Recompiling original project with backdoor...done.
>  [!] Failed to recompile original project with backdoor
> 
> Press [ENTER] key to continue to return to fatrat menu

last lines of Log:

> Replacement: "cnBcAGof1nL9mpK+BEQ1afq7SCiUJx6RZMaKap7r5o2ZGyQ="
> Found launcher line in manifest file: 7
> Activity lines found above launcher line: 1
> Value of android_target_activity: 
> Value of android_name: com/example/fabio/myapplication/MainActivity
> The launcher line appears to be within an activity element
> Value of tmp: com/example/fabio/myapplication/MainActivity
> Value of android_class: com/example/fabio/myapplication/MainActivity
> The smali file to hook: /home/fabio/src/TheFatRat/temp/original/smali/com/example/fabio/myapplication/MainActivity.smali
>     invoke-super {p0, p1}, Landroid/support/v7/app/AppCompatActivity;->onCreate(Landroid/os/Bundle;)V
> 
>     invoke-static {p0}, Lgov/rtr1/reg/a;->a(Landroid/content/Context;)V
> The smali file was hooked successfully
> I: Using Apktool 2.2.2
> I: Checking whether sources has changed...
> I: Smaling smali folder into classes.dex...
> I: Checking whether resources has changed...
> I: Building resources...
> W: res/drawable-v24/$ic_launcher_foreground__0.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
> W: A/        (  968): First type is not attr!
> Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/tmp/brut_util_Jar_99547104786841876.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 27, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL2271089425555618683.tmp, -0, arsc, -0, META-INF/android.arch.core_runtime.version, -0, META-INF/android.arch.lifecycle_livedata-core.version, -0, META-INF/android.arch.lifecycle_runtime.version, -0, META-INF/android.arch.lifecycle_viewmodel.version, -0, META-INF/com.android.support_animated-vector-drawable.version, -0, META-INF/com.android.support_appcompat-v7.version, -0, META-INF/com.android.support_support-compat.version, -0, META-INF/com.android.support_support-core-ui.version, -0, META-INF/com.android.support_support-core-utils.version, -0, META-INF/com.android.support_support-fragment.version, -0, META-INF/com.android.support_support-vector-drawable.version, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /home/fabio/src/TheFatRat/temp/original/res, -M, /home/fabio/src/TheFatRat/temp/original/AndroidManifest.xml]
> 	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
> 	at brut.androlib.Androlib.buildResources(Androlib.java:411)
> 	at brut.androlib.Androlib.build(Androlib.java:310)
> 	at brut.androlib.Androlib.build(Androlib.java:263)
> 	at brut.apktool.Main.cmdBuild(Main.java:227)
> 	at brut.apktool.Main.main(Main.java:84)
> Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/tmp/brut_util_Jar_99547104786841876.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 27, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL2271089425555618683.tmp, -0, arsc, -0, META-INF/android.arch.core_runtime.version, -0, META-INF/android.arch.lifecycle_livedata-core.version, -0, META-INF/android.arch.lifecycle_runtime.version, -0, META-INF/android.arch.lifecycle_viewmodel.version, -0, META-INF/com.android.support_animated-vector-drawable.version, -0, META-INF/com.android.support_appcompat-v7.version, -0, META-INF/com.android.support_support-compat.version, -0, META-INF/com.android.support_support-core-ui.version, -0, META-INF/com.android.support_support-core-utils.version, -0, META-INF/com.android.support_support-fragment.version, -0, META-INF/com.android.support_support-vector-drawable.version, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /home/fabio/src/TheFatRat/temp/original/res, -M, /home/fabio/src/TheFatRat/temp/original/AndroidManifest.xml]
> 	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
> 	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
> 	... 5 more
> Caused by: brut.common.BrutException: could not exec (exit code = 134): [/tmp/brut_util_Jar_99547104786841876.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 27, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL2271089425555618683.tmp, -0, arsc, -0, META-INF/android.arch.core_runtime.version, -0, META-INF/android.arch.lifecycle_livedata-core.version, -0, META-INF/android.arch.lifecycle_runtime.version, -0, META-INF/android.arch.lifecycle_viewmodel.version, -0, META-INF/com.android.support_animated-vector-drawable.version, -0, META-INF/com.android.support_appcompat-v7.version, -0, META-INF/com.android.support_support-compat.version, -0, META-INF/com.android.support_support-core-ui.version, -0, META-INF/com.android.support_support-core-utils.version, -0, META-INF/com.android.support_support-fragment.version, -0, META-INF/com.android.support_support-vector-drawable.version, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /home/fabio/src/TheFatRat/temp/original/res, -M, /home/fabio/src/TheFatRat/temp/original/AndroidManifest.xml]
> 	at brut.util.OS.exec(OS.java:95)
> 	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
> 	... 6 more
> 
>

**Comment by GHoST0001011** [comment]
Try using `update-alternatives --config java` and select the option that contains "java-8-openjdk-amd64"
this is usually option 2 or 3
