### ISSUE TITLE
[!] Failed to recompile original project with backdoor

### ISSUE THREAD

**Issue by suyash324** [Screetsec/TheFatRat#278]
[*] Creating RAT Apk File...done.
 
[*] Decompiling RAT APK file...done.
 
[*] Decompiling original APK file...done.
 
[*] Merging permissions of original and payload projects...done.
 
[*] Running proguard on RAT APK file...done.
 
[*] Decompiling obfuscated RAT APK file...done.
 
[*] Creating new directories in original project for RAT smali files...done.
 
[*] Copying RAT smali files to new directories in original project...done.
 
[*] Fixing RAT smali files...done.
 
[*] Obfuscating const-string values in RAT smali files...done.
 
[*] Locating smali file to hook in original project...done.
 
[*] Adding hook in original smali file... 
done.
 
[*] Adding persistence hook in original project...done.
 
[*] Recompiling original project with backdoor...done.
 [!] Failed to recompile original project with backdoor

Press [ENTER] key to continue to return to fatrat menu

**Comment by SphiwokuhleS** [comment]
Same thing my side

**Comment by ju11ba** [comment]
any body please how to solve this, i am jsut begginer

**Comment by glenn2148** [comment]
backdoor-apk should be dropped from downloading if they cant fix it

**Comment by CristoDDario** [comment]
I continue to have the exact same problem. 
Still no solution?

**Comment by pickuphackerscall** [comment]
**🛑🛑🛑 Here is The FIX 2019..**  https://youtu.be/QfyYWioLEk4
Full Video by FirstClickin. **Solved** now file is Recompiling without **Error**
