### ISSUE TITLE
armv7l arch not supported

### ISSUE THREAD

**Issue by Kp691** [Screetsec/TheFatRat#280]
I tried ./update but no use getting same result

************************************
 **   Updating Fatrat from Github  **                             ************************************
HEAD is now at 6e38eab Update troubleshoot.md
From https://github.com/Screetsec/TheFatRat                       * branch            master     -> FETCH_HEAD
Already up to date.                                               *************************
 **   Update Completed  **

___________         __  __________          __
\_   _____/_____  _/  |_\______   \_____  _/  |_
 |    __)  \__  \ \   __\|       _/\__  \ \   __\
 |     \    / __ \_|  |  |    |   \ / __ \_|  |
 \___  /   (____  /|__|  |____|_  /(____  /|__|
     \/         \/              \/      \/
                 ____    ________
                /_   |  /   __   \
                 |   |  \____    /
                 |   |     /    /
                 |___| /\ /____/
                       \/

          Setup Script for FATRAT 1.9.5

 Setup will not proceed because none of these archs were detected
 x86_64|i386|i486|i586|i686|aarch64

 Your linux arch:  armv7l  is not supported

Press any key to continue

**Comment by flappar** [comment]
I have installed the previous version

Il Lun 11 Giu 2018, 14:28 Kp691 <notifications@github.com> ha scritto:

**Comment by Kp691** [comment]
I have tried steps according to previous issues but getting same result

**Comment by peterpt** [comment]
Forget it , get a desktop pc with linux and install fatrat there .
