### ISSUE TITLE
Support for armv7l 

### ISSUE THREAD

**Issue by Kp691** [Screetsec/TheFatRat#282]
Can it get support???

**Comment by peterpt** [comment]
There is no support for that architecture , This is why fatrat says "Not supported" when you try to install it .
I believe that is more than obvious .

**Comment by Kp691** [comment]
I have read many issues related to armv7l ..some of them u have solved and some u say it is not supported...so plz tell me..
Bcz I don't hav a PC or laptop

**Comment by peterpt** [comment]
Again , Armv7 or 6 is not supported .
