### ISSUE TITLE
MingW32 compiler problem

### ISSUE THREAD

**Issue by ll3N1GmAll** [Screetsec/TheFatRat#287]
Thanks for this great tool. I noticed in the setup is failing because it relies on the older MingW32 compiler. Making changes to your tool to support the newer gcc-mingw-w64-i686 compiler should resolve many of the issues for payload compilation that your users may be experiencing.

**Comment by Screetsec** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md
