### ISSUE TITLE
Payload not appearing in output.

### ISSUE THREAD

**Issue by etrnlnetshadow** [Screetsec/TheFatRat#289]
I am creating a payload that uses the second option in Pwnwinds to generate an exe. Everything runs as it should in the console, but the payload does not generate into the output. I checked the root folder as well as the master folder in my home account. Is there a different location for the output I should be looking in?
I should mention I am using Kali 2018.2 fully updated and upgraded. 
![pwn](https://user-images.githubusercontent.com/39320689/42122652-e76360d6-7c12-11e8-9e68-ef83255b94ba.PNG)

**Comment by etrnlnetshadow** [comment]
Ok so from my lack of experience I didn't realize that the payload generates into program.cs. You have to compile program.cs into an exe manually.

**Comment by peterpt** [comment]
Fixed in last update , update your fatrat and run setup.sh again .
watch this video https://youtu.be/ZA7DCsGISmU?t=6318 to see the fixes .

**Comment by Ozone2** [comment]
> Ok so from my lack of experience I didn't realize that the payload generates into program.cs. You have to compile program.cs into an exe manually.

Could u tell me where did u found your backdoors/payloads created by fatrat, i am too much pissed with this problem
