### ISSUE TITLE
Problem making file backdoor for Android

### ISSUE THREAD

**Issue by a-zamani** [Screetsec/TheFatRat#290]
Hello.
When I'm creating a "backdoor" file for Android
After choosing Hook 5 Fat, it does not get the "backdoor" file and it does not fix it!
The steps I take:

- [05]  Backdooring Original apk [Instagram, Line,etc] .
- I use "NGROK" for "LPORT" and "LHOST".
-  Path : /root/Desktop/flappybird.apk
- [ 2 ] Use old Fatrat method 
- [ 3 ] android/meterpreter/reverse_tcp 
- Hook 5

========================
ruby: warning: shebang line ending with \r may cause problems
[+] Infected file /root/Desktop/TheFatRat-master/temp/app_backdoored.apk ready. 
\e[1;31m 
[x] There was an error in the creation of your RAT APK file , the possible reasons are :
- The architecture of the file is not for android
- The original APK is protected
- It was not possible to inject the payload in the hook you selected (in this case select a different hook point)
===========================
Thank U :)

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md

**Comment by a-zamani** [comment]
thanks for your response
But my problem is not resolved

**Comment by peterpt** [comment]
And will never be because we did not build the tools that build the merged apks .
You can use the payload creation only and install it in your android device to satisfy your curiosity .
Follow the same procedure in this video .
https://www.youtube.com/watch?v=PfUaCz-nzsU
