### ISSUE TITLE
Can't Install with Kali linux 2018.1

### ISSUE THREAD

**Issue by RickyRGT** [Screetsec/TheFatRat#291]
But i don't no to downgrade my version.
any solusion?

**Comment by RickyRGT** [comment]
xterm -> OK
Dns-Utils -> OK
GCC -> OK
Apache2 -> OK
Gnome Terminal -> OK
UPX -> OK
Ruby -> OK
Openssl -> OK
Jarsigner -> OK
Unzip -> OK
Keytool -> OK
mingw-w64 -> Not OK
mingw-32 -> Not OK
DX -> OK
Aapt -> OK
Apktool -> OK
Dex2Jar -> OK
Metasploit -> OK
Backdoor-Factory -> OK
Searchsploit -> OK
Was not possible to install The Packages Labeled (Not Ok) in this list above
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)
before running fatrat setup script again

**Comment by doortack** [comment]
I manual had to install mingw-w64 for my FatRat. 

On modern Debian derivatives, including Mint, mingw32 is no longer available; it has been replaced by mingw-w64:

###  sudo apt install mingw-w64  ###

should work.
   or 
http://mingw-w64.org/doku.php/download
for other distos

**Comment by RickyRGT** [comment]
thanks you... it's work for me.
