### ISSUE TITLE
Very Impressed!

### ISSUE THREAD

**Issue by doortack** [Screetsec/TheFatRat#293]
Brother you are very good programmer. This is the first time in almost a year where I ran into programs as good and as stable as yours. I love FatRat and use it daily. I started to believe that all the dedicated programmers had left GitHub. I've had absolutely no problems with FatRat and I've tested it on Mint, Kali, Android, and Windows so far. I'm looking forward to trying your other programs. I'll let you know what I think. Keep up the good work, Brother.

**Comment by Screetsec** [comment]
thanks dude  ❤️
