### ISSUE TITLE
There was an error creating your FUD rat with Powerstager .

### ISSUE THREAD

**Issue by sidranji** [Screetsec/TheFatRat#296]
Hi,
Recently  installed fatrat , showing following error " There was an error creating your FUD rat with Powerstager " , upgraded kali linux , tried pip/pip2 install names , apt-get install mingw-w64. 

here go the logs

Fudwin Logs

/usr/bin/x86_64-w64-mingw32-gcc
Traceback (most recent call last):
  File "tools/power.py", line 19, in <module>
    import names
ImportError: No module named names

-------------------------------------------------------------------------

Setup Logs

| Tools paths configured in (setup.sh) for TheFatRat |
------------------------------------------------------
                                                      
/usr/bin/xterm
/usr/bin/dig
/usr/bin/gcc
/usr/sbin/apache2
/usr/bin/gnome-terminal
/usr/bin/upx
/usr/bin/ruby
/usr/bin/openssl
/usr/bin/jarsigner
/usr/bin/unzip
/usr/bin/keytool
/home/test/TheFatRat/tools/android-sdk/zipalign
/home/test/TheFatRat/tools/proguard5.3.2/lib/proguard
/usr/bin/x86_64-w64-mingw32-gcc
/usr/bin/i686-w64-mingw32-gcc
/usr/local/sbin/dx
/usr/local/sbin/aapt
/usr/local/sbin/apktool
/usr/local/sbin/d2j-dex2jar
msfconsole
msfvenom
backdoor-factory
searchsploit
/usr/local/sbin/fatrat

pls help......

**Comment by sidranji** [comment]
And Python Version  2.7.15

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md
