### ISSUE TITLE
cmd shell

### ISSUE THREAD

**Issue by jteslaxxx** [Screetsec/TheFatRat#3]
When run payload on Windows machine cmd shell stays open!! Just for information!
And some feature request, add meterpreter/reverse_tcp_dns like option! 
Thanks and cool automation script!

**Comment by Screetsec** [comment]
oke its will be update . btw now im still update this tool for more features i wilii add some payload list for windows

**Comment by Mixiawe** [comment]
wow cool

**Comment by sigkali12** [comment]
What are you talking to me
