### ISSUE TITLE
thefatrat not detect metasploit - gentoo

### ISSUE THREAD

**Issue by oscarandrea** [Screetsec/TheFatRat#30]
launching the setup.sh script as root which command does not detect my installation of Metasploit in 
`/usr/local/bin/msfconsole`
and unfortunately I have to run the root script. As seen in the screen if you launch which regular user there are no problems, while root you.
I am on gentoo hardened
screenshot:
http://imgur.com/aRMdaBQ

**Comment by peterpt** [comment]
probably your /usr/local/bin/ is not commented on system Path .
Check out this pull request i made witch allow you to input manually the paths of those tools in case they were not detected .

https://github.com/Screetsec/TheFatRat/pull/40

To use this pull you will have to clone completely the fatrat git in my account , until master add it to main git .

https://github.com/peterpt/TheFatRat

**Comment by Screetsec** [comment]
wait will be update dude

**Comment by oscarandrea** [comment]
yes yes, I also bypassed knowing the python, it was right to report
