### ISSUE TITLE
 There was an error in the creation of your RAT APK file , the possible reasons are :

### ISSUE THREAD

**Issue by shashankgupta7** [Screetsec/TheFatRat#302]
Hello guys, I'm getting some error in fatrat, Someone please help me, I've tried everything but no luck, I'm using Fatrat on parrot os installed on Virtualbox and I'm using VPN service to port forward. Please help me.

[x] There was an error in the creation of your RAT APK file , the possible reasons are :

The architecture of the file is not for android
The original APK is protected
It was not possible to inject the payload in the hook you selected (in this case select a different hook point)
Check log file at : /root/TheFatRat-master/logs/apk-old.log`

**Comment by peterpt** [comment]
Backdooring apks is working at 10% or less , best way is to create an apk backdoor payload only with msfvenom to have some fun with the android devices .

**Comment by NaheelSalman** [comment]
But a backdoor apk gives sessions on touching the MainActivity icon so we couldn't do any thing until the person don't touch app icon and other weak point is that if we use doorback it will be on user screen and if we hide this app to save from deletion so the next time the user is unable to touch app icon as well as we are unable to get meterpreter sessions,,,,, #peterpt if you knew how to overcome it share it please :)

**Comment by NaheelSalman** [comment]
@peterpt

**Comment by NaheelSalman** [comment]
first of all Thanks to @peterpt for reply back now to the topic that i have tested that scirpt this requires a root permission in that device for running on reboot....!!
So to have a persistant session with this above link we have a root access over that device,,,, so it means if there is no root there will be no persistant access over that device ..... so therefore now i'm finding a new way to get permanent access and as i got i will share here ....!!!
