### ISSUE TITLE
back door with FudWin

### ISSUE THREAD

**Issue by HoveringPilot** [Screetsec/TheFatRat#303]
when i try to create a back door with FudWin 1.0 and at the end of the powerstager when it starts to build the rat it stops and i get an error saying "there was an error creating your FUD rat with Powerstager". I try with both 32 and 64 bit and they dont work

**Comment by peterpt** [comment]
read the troubleshoot text in main git directory .
For that to happen , you probably have t install the module "names" with pip , or there is some issue with your mingw 32bit & 64bit installation .
Powerstager requires both mingw packages .
