### ISSUE TITLE
Apache2 -> Not found

### ISSUE THREAD

**Issue by h20o** [Screetsec/TheFatRat#304]
Hey, i'm trying to install thefatrat but i got error and i can't install

apache2 -> not found

first time install is all ok installed some packages like php, php-curl etc
but then i got 
apache2 -> not found

im using: debian 9.4 x64

**Comment by peterpt** [comment]
apache have many names since wheezy .
At first was apache , then went to apache2 and it looks that some people are reporting that also have the name "httpd" .
Creating a symlink would solve the problem .
But first you must know what do you have installed , witch one from the 3 .

**Comment by peterpt** [comment]
if you really have apache2 with another name on your linux then do this :
1st - find where is the executable for your apache2 (httpd)

then create a symlink like this :

ln -s Location_of_httpd_bin /usr/local/sbin/apache2

tip : by default tools installed by apt or that come already installed in a fresh system are usually located in /usr/bin/  folder  , in case you dont find it there then write this on terminal :
updatedb && locate httpd 

it will be show an huge list of files and direcotries with that name , your binary should be in an "bin" or "sbin" folder , with there are 3 of each , ex for sbin :

/sbin  -> System binaries
/usr/sbin -> user system binaries (unless essential packages that make OS work then it will be here)
/usr/local/sbin -> this is when it is placed if you compile the binary manually with default settings
