### ISSUE TITLE
Powerfull.sh bug  How to solve this?

### ISSUE THREAD

**Issue by alienwaresoldier** [Screetsec/TheFatRat#31]
Hi screetsec,

I got this bug:
How to solve this?
![gcc-mingw32](https://cloud.githubusercontent.com/assets/23095736/22286736/7910bd2a-e2f0-11e6-90da-987a4b3b4a7f.png)
![gcc-mingw32powerfullpart](https://cloud.githubusercontent.com/assets/23095736/22286737/79154a16-e2f0-11e6-8b43-944249b00256.png)
![powerfullshpart2](https://cloud.githubusercontent.com/assets/23095736/22286749/805b5cca-e2f0-11e6-86ea-f95a81d54468.png)

**Comment by anononamemo** [comment]
I think you was been thoose not relevated version your PC, you need
reinstal module

2017-01-25 13:23 GMT+03:00 Alienwaresoldier <notifications@github.com>:

**Comment by alienwaresoldier** [comment]
Okay i will reinstall this thanks,I let you know if it works,do you mean I must reinstall fatrat?

**Comment by Screetsec** [comment]
reinstall thefatrat :)

**Comment by alienwaresoldier** [comment]
Okay :)

**Comment by alienwaresoldier** [comment]
Not working same story.

/root/Desktop/TheFatRat/./powerfull.sh: line 207: i586-ming32msvc-gcc: command not found.

I have reinstalled TheFatRat as you said.

**Comment by anononamemo** [comment]
Sorry, now I think can’t help you, I work in kalilinux 2016.2 x64 and when i use the fat rat all whas right

**Comment by alienwaresoldier** [comment]
Okay bro thanks for your help and quick reply.

**Comment by anononamemo** [comment]
If you need anything else, write me)

**Comment by alienwaresoldier** [comment]
I will do no problem,nice to meet you :+1:

**Comment by Screetsec** [comment]
oh maybe you must runnng setup.sh 

cd setup 
chmod +x setup.sh 
./setup.sh

**Comment by alienwaresoldier** [comment]
I will try,okay. Let you know if it works.

**Comment by alienwaresoldier** [comment]
Working after I installed this new version 1.8 thanks.
You can now close this solved thread :+1:
