### ISSUE TITLE
grep: /root/Desktop/TheFatRat/temp/original/smali/irm.smali: No such file or directory done.

### ISSUE THREAD

**Issue by redclippersbd** [Screetsec/TheFatRat#314]
Dear sir,
I am facing this problem when create apk original backdoor on FatRat .
Here's the full process line
 [*] Creating RAT Apk File...done.
 [*] Decompiling RAT APK file...done.
 [*] Decompiling original APK file...done.
 [*] Merging permissions of original and payload projects...done.
 [*] Running proguard on RAT APK file...done.
 [*] Decompiling obfuscated RAT APK file...done.
 [*] Creating new directories in original project for RAT smali files...done.
 [*] Copying RAT smali files to new directories in original project...done.
 [*] Fixing RAT smali files...done.
 [*] Obfuscating const-string values in RAT smali files...done.
 [*] Locating smali file to hook in original project...done.
 [*] Adding hook in original smali file... 
 
grep: /root/Desktop/TheFatRat/temp/original/smali/irm.smali: No such file or directory
done.
 [!] Failed to add hook

Looking for a solution from you.............

**Comment by Screetsec** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/issues.md
