### ISSUE TITLE
Unable to create any payload in Fatrat in Kali Linux

### ISSUE THREAD

**Issue by BackSpoofer** [Screetsec/TheFatRat#322]
[*] Creating RAT payload with msfvenom
./fatrat: line 2117: $log: ambiguous redirect
 
There was a problem in the creation of your rat apk file , make sure your metasploit is running correctly
 
Press [ENTER] key to return to fatrat menu

please help

**Comment by Screetsec** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/issues.md

**Comment by deepak2041** [comment]
how to solve....i have same problem plz reply

**Comment by dilligithub** [comment]
> [*] Creating RAT payload with msfvenom
> ./fatrat: line 2117: $log: ambiguous redirect
> 
> There was a problem in the creation of your rat apk file , make sure your metasploit is running correctly
> 
> Press [ENTER] key to return to fatrat menu
> 
> please help

Same problem

**Comment by REY-AKA-RJDJ0261** [comment]
Make sure u used "apt-get dist-upgrade && apt-get install -f && apt-get update && apt-get upgrade"

**Comment by REY-AKA-RJDJ0261** [comment]
Then try

**Comment by PrithwishDGP** [comment]
@rjdj0261 I tried but it is still not working

**Comment by ANONYMOUSLYXXX** [comment]
[*] Creating RAT payload with msfvenom
./fatrat: line 2117: $log: ambiguous redirect

There was a problem in the creation of your rat apk file , make sure your metasploit is running correctly

Press [ENTER] key to return to fatrat menu

please help
