### ISSUE TITLE
establish connection, but no RAT window, just reverse_tcp meterpreter

### ISSUE THREAD

**Issue by spidey1991** [Screetsec/TheFatRat#332]
Does the program display a screen?

Everything works fine, I connect android/meterpreter/reverse_tcp through the load listener (9) but when it establishes the connection, it just gives me the regular meterpreter commands, is there a window that is supposed to pop up so I can have remote access?

**Comment by peterpt** [comment]
lol , what windows was you expecting ?
It works like that as you told , after that point you can do whatever you want because you have a remote shell .

**Comment by spidey1991** [comment]
so it works just like msfvenom? I'm confused now.

**Comment by spidey1991** [comment]
Okay thanks, I thought a screen would pop up something a windows tech would use for example.
