### ISSUE TITLE
setup.sh : failed to install backdoor-factory

### ISSUE THREAD

**Issue by bree29** [Screetsec/TheFatRat#333]
Hi ! Here what I've done
`# git clone https://github.com/Screetsec/TheFatRat.git`
`# cd TheFatRat/ && chmod +x setup.sh && ./setup.sh`

then the install fails since it cannot install bacdoor-factory from the kali repo

obviously, I cannot execute `./fatrat` (with the chmod +x before) since i need to run `./setup.sh` again

[install.log](https://github.com/Screetsec/TheFatRat/files/2684063/install.log)
[setup.log](https://github.com/Screetsec/TheFatRat/files/2684064/setup.log)

Someone have an idea ? I bet its an easy one, but can't get it

(Ubuntu OS with this session)

**Comment by peterpt** [comment]
Write these commands in this order on your terminal :
1st - mkdir /opt && cd /opt && git clone https://github.com/secretsquirrel/the-backdoor-factory.git 
2nd - cd the-backdoor-factory && pip install pefile capstone

After this point run setup.sh and when you get to backdoor factory , select the option to insert manually 
and write this after that option : /opt/the-backdoor-factory/backdoor.py

and then pess enter , and everything will be fine .

**Comment by bree29** [comment]
Hi ! It worked perfectly, thank you :)

**Comment by 8-ctrl** [comment]
these command won't work it says that "bash: pip: command not found"

**Comment by 8-ctrl** [comment]
I'm using Deepin

**Comment by bree29** [comment]
> these command won't work it says that "bash: pip: command not found"

Install Python :-)
https://tecadmin.net/install-python-3-7-on-ubuntu-linuxmint/

**Comment by peterpt** [comment]
apt-get install python-pip

**Comment by Gabrielkim1** [comment]
/opt/the-backdoor-factory/backdoor.py to me it has not worked after following your steps
Enter The Path of your backdoor-factory instalation
 ex : /opt/backdoor-factory/backdoor.py

 PATH : /opt/the-backdoor-factory/backdoor.py

 It was not possible to found backdoor-factory executable in : /opt/the-backdoor-factory/backdoor.py

 Make sure you write the right path of your instalation

**Comment by peterpt** [comment]
somehow there must be something wrong with your cloned git , fatrat looks into that path to see if the file exists , in case it not exists with that name then pops up that error .

**Comment by riyadh3931** [comment]
Hello @peterpt, I am facing the same problem as @Gabrielkim1. What can I do? I am totally new to Linux. Please help.

 Select one of the options bellow                                                                                 
 +-----------------------------------------------------+                                                          
 | [ 1 ] Setup Backdoor-Factory Path Manually          |                                                          
 | [ 2 ] Install Backdoor-Factory from Kali Repository |                                                          
 +-----------------------------------------------------+                                                          
                                                                                                                  
 Option : 1                                                                                                       

 Enter The Path of your backdoor-factory instalation
 ex : /opt/backdoor-factory/backdoor.py                                                                           
                                                                                                                  
 PATH : /opt/backdoor-factory/backdoor.py                                                                         

 It was not possible to found backdoor-factory executable in : /opt/backdoor-factory/backdoor.py
                                                                                                                  
 Make sure you write the right path of your instalation                                                           
                                                                                                                  
 Press [ENTER] key to try again .

**Comment by peterpt** [comment]
kali still have backdoor factory to be installed using apt command .
http://http.kali.org/kali/pool/main/b/backdoor-factory/

This means that using the option "install from kali repository" will work perfectly , unless your sources.list are empty .

**Comment by Mr54N** [comment]
Select one of the options bellow
 +-----------------------------------------------------+
 | [ 1 ] Setup Backdoor-Factory Path Manually          |
 | [ 2 ] Install Backdoor-Factory from Kali Repository |
 +-----------------------------------------------------+

 Option : 1

 Enter The Path of your backdoor-factory instalation
 ex : /opt/backdoor-factory/backdoor.py

 PATH :  /opt/the-backdoor-factory/backdoor.py
 [ X ] searchsploit  -> not found

 Select one of the options bellow
 +-------------------------------------------------+
 | [ 1 ] Setup Searchsploit Path Manually          |
 | [ 2 ] Install Searchsploit from Kali Repository |
 +-------------------------------------------------+

 Option :


how do i get searchsploit while in /opt folder it's not there. help me!
use Archlinux Endevour OS

**Comment by BLACKBEAST0202** [comment]
> /opt/the-backdoor-factory/backdoor.py

This work for me.Just you have to remove /opt dir. Then give the cmd mkdir /opt && cd /opt && git clone https://github.com/secretsquirrel/the-backdoor-factory.git and follow the further step .
It will execute the cmd.

**Comment by m1l2ie** [comment]
update to the latest version of kali linux mine is version 2023.2. update and upgrade the os. then sudo apt install backdoor-factory.then run 2 option in fatrat  (Install Backdoor-Factory from Kali Repository)

**Comment by septhis215** [comment]
thank you it work wonders!

**Comment by matt090-cpu** [comment]
> kali still have backdoor factory to be installed using apt command . http://http.kali.org/kali/pool/main/b/backdoor-factory/
> 
> This means that using the option "install from kali repository" will work perfectly , unless your sources.list are empty .

w

**Comment by matt090-cpu** [comment]
what can i do if my source list is empty
