### ISSUE TITLE
File Pumping

### ISSUE THREAD

**Issue by dsx12** [Screetsec/TheFatRat#335]
After selecting file pumper and selecting apk the apk is not usable and the target android device does not install...

Any solutions?

**Comment by dsx12** [comment]
The error I receive is "There was a problem parsing the package." front my android device.

**Comment by Screetsec** [comment]
Read this how submit [Issue](https://github.com/Screetsec/TheFatRat/blob/master/issues.md)

**Comment by Screetsec** [comment]
File pumping not work and apk extensions
