### ISSUE TITLE
TheFatRat error

### ISSUE THREAD

**Issue by Xrexo** [Screetsec/TheFatRat#338]
/usr/bin/x86_64-w64-mingw32-ld: i386 architecture of input file `icons/icon.res' is incompatible with i386:x86-64 output
collect2: error: ld returned 1 exit status

PLZ, help, i can't figure out what is happening, why there is such kind of error??

**Comment by peterpt** [comment]
you were probably using the pwnwinds options , that bug is fixed in new version
update your fatrat
