### ISSUE TITLE
Fatrat exe stopped working on 64 bit windows os! 

### ISSUE THREAD

**Issue by Anonymousismyname** [Screetsec/TheFatRat#34]
Fatrat exe stops when it is executed on win64 os. 
I saw 2 or 3 issues that were closed with the same issue.but i cant find the answer. 
Leave a proper reply to solution. Thanx

**Comment by vibadaznoza** [comment]
Yes it should be good. I can't understand me too why the .exe crashs.

**Comment by Screetsec** [comment]
https://github.com/Screetsec/TheFatRat/issues/5

**Comment by Screetsec** [comment]
try some features :) https://www.youtube.com/watch?v=6skLV6zPnec&t=2s
