### ISSUE TITLE
Embed Payload in Latest apk's

### ISSUE THREAD

**Issue by mrgenius000** [Screetsec/TheFatRat#340]
Can Anyone know about it???????

**Comment by mrgenius000** [comment]
now one  is here who's solve this problem

**Comment by radiator303** [comment]
**I think these few steps will help:**


- if not already existing, install _this_ stuff separately
`
apt-get install lib32stdc++6
`
`
apt-get install lib32ncurses5
`
`
apt-get install lib32z1
`

- check apktool for latest version:
  https://ibotpeaches.github.io/Apktool/install/
  and update ~/thefatrat/tools/apktool2.2.2/ with newly
  downloaded two files (apktool.jar + apktool / see link above...)

- configure java to update its alternative to jdk8 
`
update-alternatives --config java
`
  
  choosse java-8-open-jdk by pressing the corresponding number
  (probably "2", but in my case "3" ...whatsoever - do it.)

- restart ur dish 


**Anyway - this won't solve the whole issue, but you'll compile definitely more apks than before...**

**Comment by dilligithub** [comment]
Mine
