### ISSUE TITLE
No Payload in output folder (except *.bat)

### ISSUE THREAD

**Issue by 5trohm** [Screetsec/TheFatRat#348]
I got a problem with my outputfile i greated with PwnWinds.
If i Create a bat file+Powershell i get the file in the output-folder.
if i want to make a exe file with apache + powershell  (windows/meterpreter/reverse_tcp ) i got no output but the script says `  Backdoor Saved To output Folder 
 Press [ENTER] key to continue ......... 
`
i hit enter, nothing in output folder nore in backdoored/output

if i do the ssame and get an *.bat everything works fine and i got the file in my output

**Comment by peterpt** [comment]
One of the problems that we did in fatrat was that no matter what execution it does creating backdoor files , in the end it always says that file was created even if was not , however this happens only in some menus .
I will look closely into your issue as soon as i get some free time , witch is not easy

**Comment by peterpt** [comment]
Fixed in 1.9.7.
Update your fatrat
