### ISSUE TITLE
Payload doesn't created on kali linux rolling 1

### ISSUE THREAD

**Issue by rielinux** [Screetsec/TheFatRat#35]
Payload flash_player.exe doesn't created on kali linux rolling 1
I've all depedencies

cp: cannot stat '/root/TheFatRat/output/output/fatrat_backdoored.apk': No such file or directory
java.io.FileNotFoundException: /root/TheFatRat/backdoored/apkembed.apk (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:145)
	at com.android.signapk.SignApk.main(SignApk.java:320)
rm: cannot remove 'backdoored/apkembed.apk': No such file or directory

Help me omm ....

**Comment by jcherqui** [comment]
:+1:

**Comment by Screetsec** [comment]
are you embed executable file ?

**Comment by rielinux** [comment]
i follow your tutorial at indonesian backtrack forum, so...yes it was embedded

**Comment by Screetsec** [comment]
you using optional for embed android not exe

**Comment by rielinux** [comment]
Thank you man, now it works.... :+1:

**Comment by dakil3165** [comment]
hola alguien  me puede ayudar con kali lunix no funciono cuando quiero crear una apk  me sale 
Error: Invalid Payload Selected 
como pudeo arreglar ese problema 
gracias
