### ISSUE TITLE
Multiple port forwarding issues

### ISSUE THREAD

**Issue by niloy007** [Screetsec/TheFatRat#351]
I used on Android payload (over wan )
lport - 4444
msfconsole
lport - 4444
successfully connected 

- windows payload (over wan )
lport 4445
msf
llport 4445
not working....  why is that 

do i need to change the port for every victim while creating payload or single payload would do fine for every victim..

**Comment by peterpt** [comment]
define windows wan port ?

**Comment by peterpt** [comment]
Define wan port ?
also payloads for android does not work on windows by the fact that android payloads are on apks , while in windows are in exe ,vbs , ps , bat , etc.....

**Comment by peterpt** [comment]
And the listener in msfconsole if it configured for android device then will not respond to a windows connection , when a target connects to the msfconsole then msfconsole interprets the communication of that victim as it was previous configured to do so . And no , you can not use 1 single port to listen all types of targets in msfconsole , you should create a specific port for every OS if you want it to work .

**Comment by niloy007** [comment]
To check it further
I created a windows payload 
To test in vmware with
Freash windows 64
Whenever i deploy the exe file it shows an error 

ApacheSever command line util stopped working 

Something like that...
