### ISSUE TITLE
There was an error creating your FUD rat with Powerstager

### ISSUE THREAD

**Issue by niloy007** [Screetsec/TheFatRat#352]
For some reason i cant make windows payload to work
1. Powerstager failed 
fudwin.log

  Working...Traceback (most recent call last):
  File "tools/power.py", line 2962, in <module>
    main(sys.argv[1:])
  File "tools/power.py", line 2949, in main
    compile_source()
  File "tools/power.py", line 2694, in compile_source
    Print.add_name_value("File signature", hashlib.md5(open(output, "rb").read()).hexdigest(), Print.info)
IOError: [Errno 2] No such file or directory: 'newpwer'

python version 2.7.15

2. slow but powerfull 

when i deply the exe to my victims pc, a cmd box comes and pwerfull.exe stopped working...

3. usual create backdoor with msfvenom ,
the output .exe does nothing... 
i installed in a freash vmware 64 windows 7 
a error comes - 
ApacheBench Command line utility has stopped working.. 

its really driving me nut...

**Comment by peterpt** [comment]
I believe you have an issue in your python environment.
Try original powerstager from here https://github.com/z0noxz/powerstager

**Comment by evo2048** [comment]
Same problem here, I get the same error. How can I acces fudwin.log?

**Comment by peterpt** [comment]
Fudwinlog can be found in fatrat directory /logs .

dont use names with spaces , slashes , it is not required to write .exe in the filename .

example of filename for powerstager : myfile
dont use : "myfile.exe"  , or "my file.exe" , or "my file" , or "~/myfile"

**Comment by evo2048** [comment]
@peterpt If I don't write payload.exe, it give's me the same error, but the output name is payload.exe.exe. Don't know why.

**Comment by coolswing** [comment]
@evo2048 got the same issues, if i try to create a file named "hello" it crash with the error:

`Traceback (most recent call last):
  File "tools/power.py", line 2962, in <module>
    main(sys.argv[1:])
  File "tools/power.py", line 2949, in main
    compile_source()
  File "tools/power.py", line 2694, in compile_source
    Print.add_name_value("File signature", hashlib.md5(open(output, "rb").read()).hexdigest(), Print.info)
IOError: [Errno 2] No such file or directory: 'hello'`

but if i try with hello.exe i got the payload hello.exe.exe (btw i've try it on a win10 vm and it got detected quite fast as trojan)

**Comment by peterpt** [comment]
it would be interesting to see if the problem persists in new released version of fatrat .
Despite the fact that we made no changes at all to powerstager script because this issue does not happen to everyone , we changed the output directory to your home folder /root/Fatrat_generated
, delete your current version and clone the new version , then run setup script and run fatrat .
Then the first thing you should do is to try exactly as you did before with powerstager .

Yes , it is identified as a trojan because noobs like to upload the backdoors to virustotal just to see if they get passed clean , and what happens is that virustotal analyses as also shares the uploaded files with antivirus companies witch they look deep into the exe .
The result of that is that you get your exe detected .
There is nothing we can do about it , because stupidity have no limits in this planet .

**Comment by coolswing** [comment]
It seems to be fixed on this version, thx.

**Comment by hydrox59** [comment]
> it would be interesting to see if the problem persists in new released version of fatrat .
> Despite the fact that we made no changes at all to powerstager script because this issue does not happen to everyone , we changed the output directory to your home folder /root/Fatrat_generated
> , delete your current version and clone the new version , then run setup script and run fatrat .
> Then the first thing you should do is to try exactly as you did before with powerstager .
> 
> Yes , it is identified as a trojan because noobs like to upload the backdoors to virustotal just to see if they get passed clean , and what happens is that virustotal analyses as also shares the uploaded files with antivirus companies witch they look deep into the exe .
> The result of that is that you get your exe detected .
> There is nothing we can do about it , because stupidity have no limits in this planet .

Yes it's real problem, but where testing No Distribute, dont work ?

**Comment by peterpt** [comment]
https://nodistribute.com/

**Comment by hdawg12** [comment]
is there a new version of fatrat?  I can't find it

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md
