### ISSUE TITLE
Unable to locate package monodevelop

### ISSUE THREAD

**Issue by hadestech** [Screetsec/TheFatRat#356]
Doing a new install with Parrot. Have tried several time to install. keep getting the error.
Unable to locate package monodevelop. I have also attempted to correct running / sudo apt-get remove --purge monodevelop && apt-get autoremove && apt-get install -f 
The response I get is /
 Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package monodevelop

**Comment by m1lw0rm** [comment]
Im use ParrotOS long time, this can help to fix your problem.

```
sudo apt install apt-transport-https dirmngr

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

echo "deb https://download.mono-project.com/repo/ubuntu vs-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-vs.list

sudo apt update
```

make sure you copy this command perfectly, in step 3 make sure you copy all command

**Comment by peterpt** [comment]
You are using an old version of fatrat .
Fatrat does not install monodevenlop full anymore .
Fatrat only installs thse 2 packages requires : mono-mcs & mono-devel

So , these packages can be found in debian repositories :
https://packages.debian.org/stretch/mono-mcs

&

https://packages.debian.org/stretch/mono-devel

So , to finish this ridiculous issue , you just need to add stretch repository to your sources.list and run setup.sh from fatrat , this only after you delete your old version and get the new one from github .

Debian stretch repositories :

deb http://deb.debian.org/debian/ stable main contrib non-free
deb-src http://deb.debian.org/debian/ stable main contrib non-free
deb http://deb.debian.org/debian/ stable-updates main contrib non-free
deb-src http://deb.debian.org/debian/ stable-updates main contrib non-free
deb http://deb.debian.org/debian-security stable/updates main
deb-src http://deb.debian.org/debian-security stable/updates main
deb http://ftp.debian.org/debian stretch-backports main
deb-src http://ftp.debian.org/debian stretch-backports main

2h:30m video https://www.youtube.com/watch?v=ZA7DCsGISmU
