### ISSUE TITLE
No output file from PwnWinds with Payload 

### ISSUE THREAD

**Issue by shatobr** [Screetsec/TheFatRat#358]
when I try to use PwnWinds with meterpreter payload I dont get output file

**Comment by peterpt** [comment]
You need to be more specific with that with some print screens , and explain the whole process you did until you got to that point , so we can test it here .

**Comment by shatobr** [comment]
Hi, please find attached screen shots, I am running Kali 19.2
Linux kali 4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03)
x86_64 GNU/Linux

Regards and thank you for your support
RS

**Comment by peterpt** [comment]
nothing here , you should learn how to upload something to github when you are creating an issue .
https://www.youtube.com/watch?v=mGXFVxDlWgU

**Comment by peterpt** [comment]
Whatever it was it is now fixed in 1.9.7 version . Update your fatrat
