### ISSUE TITLE
no output file screenshots

### ISSUE THREAD

**Issue by shatobr** [Screetsec/TheFatRat#359]
![fatrat1](https://user-images.githubusercontent.com/47064198/58737282-ed584f00-83ce-11e9-8d78-852cc9386f3d.PNG)
![fatrat2](https://user-images.githubusercontent.com/47064198/58737292-f3e6c680-83ce-11e9-880f-b10a8d8dbda9.PNG)
![fatrat3](https://user-images.githubusercontent.com/47064198/58737294-f77a4d80-83ce-11e9-8103-a1187f681457.PNG)
![fatrat4](https://user-images.githubusercontent.com/47064198/58737296-f9dca780-83ce-11e9-994f-9c2caf2a60bd.PNG)
![fatrat5](https://user-images.githubusercontent.com/47064198/58737298-fd702e80-83ce-11e9-9056-e91fd7ea6855.PNG)
![fatrat6](https://user-images.githubusercontent.com/47064198/58737301-006b1f00-83cf-11e9-83da-23b237984599.PNG)
![fatrat7](https://user-images.githubusercontent.com/47064198/58737308-052fd300-83cf-11e9-8f23-67ef5d552c54.PNG)

**Comment by johndoe0924** [comment]
Greatly appreciated. I'm here if u need

**Comment by peterpt** [comment]
It was fixed in latest release , update your fatrat version .
