### ISSUE TITLE
 application always get ' unfortunately app has stopped ' 

### ISSUE THREAD

**Issue by e403** [Screetsec/TheFatRat#36]
after android app injection and install the final app i always get ' unfortunately app has stopped ' 
i use parrot sec os linux 3.4
i download apk from googleplay , apkpure .... any site 
and it still the problem !!

**Comment by anasbousselham** [comment]
I have the same problem

**Comment by i-amgeek** [comment]
I am facing same problem too.

**Comment by eminmammadov** [comment]
@i-amgeek what is problem?

**Comment by i-amgeek** [comment]
@eminmammadov I tried backdooring few APKs like UC browser, flappybird. Apps got installed without any problem but as I try to open any of them, it says 'Unfortunately App has Stopped'.
