### ISSUE TITLE
Mingw-w32 Not found 

### ISSUE THREAD

**Issue by rockmeup** [Screetsec/TheFatRat#362]
Since there has been changes to mingw 
Officially there is no 32 only 64 is being rolled out Pls update the setup.sh

**Comment by coolswing** [comment]
same issue, 
cat logs/fudwin.log:

`/usr/bin/x86_64-w64-mingw32-gcc
Traceback (most recent call last):
  File "tools/power.py", line 19, in <module>
    import names
ImportError: No module named names
`

**Comment by peterpt** [comment]
https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=mingw32

fatrat needs the 32bit compiler to run some of the backdoors inside , specially powerstager , case mingw 32bit is not in user system then powerstager will not run .
Eventually when i get some time i will check if 64bit package of mingw delivers the 32bit compiler inside .
