### ISSUE TITLE
configuration file does not exists, run setup.sh first for config

### ISSUE THREAD

**Issue by saikiran994** [Screetsec/TheFatRat#363]
i tried to run in 2019.2 in kali linux but its showing configuration file does not exists, run setup.sh first for config. actually i tried every commends which are provide  in Readme.md still iam getting error. how to solve it?
![Screenshot from 2019-07-02 21-14-39](https://user-images.githubusercontent.com/37449869/60526683-6f110480-9d0e-11e9-9bfc-77d298136130.png)

**Comment by peterpt** [comment]
You have run setup , but if there was some issue in installing some package then this issue will happen .
You should look up witch package is not installing when you run setup.sh and then solve that issue first .

**Comment by kidBuuReborn** [comment]
i also ran into an issue her but i did go to run the setup however my terminal tells me i have no internet connection and script cannot run without internet connection however i am already connected to the internet hence im able to successfully run the ping cmd

**Comment by peterpt** [comment]
you need netcat installed : apt-get install netcat

**Comment by kidBuuReborn** [comment]
i gave up on fatrat, decided to just go with routersploit, fatrat required
too many packages that i felt were unnecessary
