### ISSUE TITLE
Error in creation of RAT APK file

### ISSUE THREAD

**Issue by Lucas03lescure** [Screetsec/TheFatRat#365]
![Screenshot_20190717-223543_Gallery](https://user-images.githubusercontent.com/42495586/61409838-5d6d5680-a8e3-11e9-9ab0-77d058b3bdd1.jpg)

**Comment by Lucas03lescure** [comment]
In apk-old.log:
WARNING: linker: Warning: unable to normalize "null"
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 10094 bytes
Saved as: /root/TheFatRat/temp/payload.apk
Generating 2,048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 10,000 days
	for: CN=Android Debug, O=Android, C=US
[Storing /root/TheFatRat/temp/debug.keystore]


Please help

**Comment by Screetsec** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/issues.md
