### ISSUE TITLE
dex2jar 2.0 > Not Ok

### ISSUE THREAD

**Issue by mahbuboalam** [Screetsec/TheFatRat#366]
I had an issue when I was running ./setup.sh in fat rat. I tried to install dex2jar manually but didn't work (I guess because it was the latest version of dex2jar) fat rat demanded for dex2jar 2.0

Please help me to solve the issue.
![Screenshot from 2019-07-30 05-19-21](https://user-images.githubusercontent.com/50797570/62095939-c4a3e700-b2a3-11e9-94ad-3cf7974d393a.png)
![Screenshot from 2019-07-30 05-18-42](https://user-images.githubusercontent.com/50797570/62095948-ccfc2200-b2a3-11e9-8cfa-63e694e87cd8.png)

**Comment by peterpt** [comment]
in log files should be a file called apt.log , post it here .
In case there is none then clone again the fatrat and use with the latest update .
