### ISSUE TITLE
Can't install monodevelop & mingw32 for TheFatRat

### ISSUE THREAD

**Issue by Abcde123lkjh** [Screetsec/TheFatRat#367]
I was trying to install TheFatRat on my Kali Linux machine on VirtualBox. But it shows that monodevelop and mingw32 is not okay and due to that TheFatRat is not installed. Someone please help me.
Then I tried to install monodevelop and mingw32 but then it shows another problem.
Please somebody help me.

![Kali-Linux-2018 4-vbox-amd64  Running  - Oracle VM VirtualBox 8_4_2019 9_25_37 AM (2)](https://user-images.githubusercontent.com/53537931/62419332-585a2680-b69b-11e9-9c71-3f90779a8951.png)
![Kali-Linux-2018 4-vbox-amd64  Running  - Oracle VM VirtualBox 8_4_2019 9_27_10 AM (2)](https://user-images.githubusercontent.com/53537931/62419333-58f2bd00-b69b-11e9-99fa-e7dcb625cae6.png)
![Kali-Linux-2018 4-vbox-amd64  Running  - Oracle VM VirtualBox 8_4_2019 9_27_10 AM (3)](https://user-images.githubusercontent.com/53537931/62419334-58f2bd00-b69b-11e9-97c9-9ab23305d5cd.png)

**Comment by peterpt** [comment]
you should really update your fatrat .
You guys come here still using an old version of the release asking for help .
