### ISSUE TITLE
Remote And Local Shell Type Detection

### ISSUE THREAD

**Issue by kmahyyg** [Screetsec/TheFatRat#370]
I'm working on my remote Kali VPS, and connect to its desktop with GUI using X2GO. X2go is a remote desktop software based on X11 forwarding of SSH, but much faster, cost less, and much more stable.

So could you please just let the user know it cannot be run on the remote shell but and let user choose if they still want to continue?

**Comment by peterpt** [comment]
the problem is not you but everyone else that will use a shell remotely to run the script , and then everything will be messed up on the screen , and then they will start to create issues based on that .
So to avoid that we will not change it . 
Do it yourself on fatrat main script .
