### ISSUE TITLE
There was an error creating your FUD rat with Powerstager .

### ISSUE THREAD

**Issue by kaloyantihomirov** [Screetsec/TheFatRat#372]
Hi,

when I try to generate a backdoor with Powerstager 0.2.5, here is what I get:

> There was an error creating your FUD rat with Powerstager .

Let me give you the log.

`/usr/bin/x86_64-w64-mingw32-gcc
  [38;5;160m   ___                       __ _                        [0m
  [38;5;161m  / _ \_____      _____ _ __/ _\ |_ __ _  __ _  ___ _ __ [0m
  [38;5;162m / /_)/ _ \ \ /\ / / _ \ '__\ \| __/ _` |/ _` |/ _ \ '__|[0m
  [38;5;163m/ ___/ (_) \ V  V /  __/ |  _\ \ || (_| | (_| |  __/ |   [0m
  [38;5;164m\/    \___/ \_/\_/ \___|_|  \__/\__\__,_|\__, |\___|_|   [0m
  [38;5;130m   _ __  _   _                           [38;5;164m|___/[38;5;130m           [0m
  [38;5;131m  | '_ \| | | |                                          [0m
  [38;5;132m _| |_) | |_| |  A payload stager using PowerShell       [0m
  [38;5;133m(_) .__/ \__, |  Created by z0noxz                       [0m
  [38;5;134m  |_|    |___/                                           [0m
  
  Working...Traceback (most recent call last):
  File "tools/power.py", line 2962, in <module>
    main(sys.argv[1:])
  File "tools/power.py", line 2949, in main
    compile_source()
  File "tools/power.py", line 2694, in compile_source
    Print.add_name_value("File signature", hashlib.md5(open(output, "rb").read()).hexdigest(), Print.info)
IOError: [Errno 21] Is a directory: 'output'`

**Comment by peterpt** [comment]
use a different name , you are using a name that exists in that location , or is an existent filename or a directory with that name .

IOError: [Errno 21] Is a directory: 'output'`
