### ISSUE TITLE
[x] There was an error creating your FUD rat with Powerstager

### ISSUE THREAD

**Issue by Hacker49350** [Screetsec/TheFatRat#373]
tell me where is the log file so I can show it to you.

**Comment by peterpt** [comment]
in logs folder inside fatrat directory .
The name should be "fudwin.log"

**Comment by Hacker49350** [comment]
It's his 
/usr/bin/x86_64-w64-mingw32-gcc
Traceback (most recent call last):
  File "tools/power.py", line 19, in <module>
    import names
ImportError: No module named names

**Comment by peterpt** [comment]
Write in your terminal.    Pip install names
