### ISSUE TITLE
cannot run setup because file setup.sh say no internet connection

### ISSUE THREAD

**Issue by kidBuuReborn** [Screetsec/TheFatRat#375]
im unable to run script due to no internet connection, however i am connected hence successful run of ifconfig as well as ping, theres no way a internet connection doesnt exist, i even opened an alternate window and ran a extra tcp through ngrok and setup.sh for the fatrat, still says the same "no internet connection, script cannot run without internet connection" can anyone tell me why and how to fix, and i dont want to know how to fix without the why, i prefer to understand all issues and solutions thoroughly...in my error message its also telling me im missing lines 72 73 74 and 75

**Comment by peterpt** [comment]
run on your terminal "apt-get install netcat"   , and then run setup again .

netcat by default is available on every linux distribution .

**Comment by hydrox59** [comment]
Hello, nodistibute dont work, you have à free alternative plzz ? Thanks by
advance and its possible have 100 % fud ?

**Comment by kidBuuReborn** [comment]
i was able to solve the no internet connection, but now im at another
standstill a few of the phgs arent installing under the setup.sh a few of
them i was able to find out a way around them and id just gon around them
and done a manual instalation of those particular packages, but 3 of those
packages are giving me issues, the monodevelop, keytools (java) and
jarsigner(java), the issues monodevelop gave me was all o could find was a
.rpm file to download and this wasnt compatible with my linux i believe as
lonux could never locate the package after download to install it and with
the keytools and jarsigner, from my searches last night i believe i will
need to install java for these packages and those issues will be what i
will be in pursuit of tonoght, thanks for answering my comment about the
internet connection, i should have deleted the comment after i solved the
issue, my apologies
