### ISSUE TITLE
WSL PROBLEM INSTALL THEFATRAT FIX THIS!

### ISSUE THREAD

**Issue by IGotHacked999** [Screetsec/TheFatRat#378]
`Checking type of shell ....
[local]
 [ * ] Checking for internet connection
 [ X ]::[Internet Connection]: OFFLINE!
 [X] Your Internet is not working correctly!
 [*] Checking ....
 [X] Your linux OS is not able to resolve
 hostnames over terminal using ping !!

 Search on the web : (unable to resolve hostnames ping) to find a solution

 Setup will continue , but is not garantee that apt package management
may work properly , or even if it can resolve hostnames .

 Setup will continue because :
 Ping google.com = Failed
 Ping google DNS = Success

 Press [ENTER] key to continue

`
![image](https://user-images.githubusercontent.com/55454039/65282857-853d9c80-db68-11e9-99b0-db681815eb2f.png)

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/issues/375

**Comment by crackplatoonbd** [comment]
sudo apt install netcat-traditional
