### ISSUE TITLE
[x] There was an error creating your FUD rat with Powerstager .

### ISSUE THREAD

**Issue by kalibeginner** [Screetsec/TheFatRat#379]
when I try to create a backdoor on fatrat with powersatger i get

> [x] There was an error creating your FUD rat with Powerstager .

my fudwin is 

> /usr/bin/x86_64-w64-mingw32-gcc
>   [38;5;160m   ___                       __ _                        [0m
>   [38;5;161m  / _ \_____      _____ _ __/ _\ |_ __ _  __ _  ___ _ __ [0m
>   [38;5;162m / /_)/ _ \ \ /\ / / _ \ '__\ \| __/ _` |/ _` |/ _ \ '__|[0m
>   [38;5;163m/ ___/ (_) \ V  V /  __/ |  _\ \ || (_| | (_| |  __/ |   [0m
>   [38;5;164m\/    \___/ \_/\_/ \___|_|  \__/\__\__,_|\__, |\___|_|   [0m
>   [38;5;130m   _ __  _   _                           [38;5;164m|___/[38;5;130m           [0m
>   [38;5;131m  | '_ \| | | |                                          [0m
>   [38;5;132m _| |_) | |_| |  A payload stager using PowerShell       [0m
>   [38;5;133m(_) .__/ \__, |  Created by z0noxz                       [0m
>   [38;5;134m  |_|    |___/                                           [0m
>   
>   Working...Traceback (most recent call last):
>   File "tools/power.py", line 2962, in <module>
>     main(sys.argv[1:])
>   File "tools/power.py", line 2949, in main
>     compile_source()
>   File "tools/power.py", line 2694, in compile_source
>     Print.add_name_value("File signature", hashlib.md5(open(output, "rb").read()).hexdigest(), Print.info)
> IOError: [Errno 2] No such file or directory: 'google'

my setup is

> /usr/bin/xterm
> /usr/bin/dig
> /usr/bin/mcs
> /usr/bin/gcc
> /usr/sbin/apache2
> /usr/bin/gnome-terminal
> /usr/bin/upx
> /usr/bin/ruby
> /usr/bin/openssl
> /usr/bin/jarsigner
> /usr/bin/unzip
> /usr/bin/keytool
> /root/TheFatRat/tools/android-sdk/zipalign
> /root/TheFatRat/tools/proguard5.3.2/lib/proguard
> /usr/bin/x86_64-w64-mingw32-gcc
> /usr/bin/i686-w64-mingw32-gcc
> /usr/local/sbin/dx
> /usr/local/sbin/aapt
> /usr/local/sbin/apktool
> /usr/local/sbin/d2j-dex2jar
> msfconsole
> msfvenom
> backdoor-factory
> searchsploit

please help me

**Comment by kalibeginner** [comment]
why did you close my issue

**Comment by kalibeginner** [comment]
why

**Comment by kalibeginner** [comment]
why

**Comment by peterpt** [comment]
just update your fatrat .
The problem are these multiple reasons when you are writing the output name for file :

1st = blablabla/google    (The script can not create directories , you must write only a filename)

or
2nd = you wrote : google (but somehow there is a file in output directory already with that name)
this is why : IOError: [Errno 2] No such file or directory: 'google'


However i changed the main code to detect if you are using a directory name before the filename and also to check if the filename you are writing already exists .

This is why i say : update fatrat .

**Comment by kalibeginner** [comment]
Thanks to answer me 
I gonna try what you juste say
To update fatrat i just need to do 
apt-get update in fatrat repesitory ?

**Comment by peterpt** [comment]
in fatrat directory write this : git pull

our update script is not working correctly , i have to check that when i get some time free here .

**Comment by kalibeginner** [comment]
Thanks a lot i gonna try

Envoyé de mon iPod

**Comment by kalibeginner** [comment]
I'm a beginner on kali so I don't know if it's normal but when I try to uptade fatrat with the command     " apt-get update " in fatrat directory the program ping to kali linux rolling and not to fatrat so maybe the problem for the uptdate comes from here. 
I've also tryed git pull but it didn't work : /
I don't reminds me of the result but i will send you the answer later

**Comment by peterpt** [comment]
where is your fatrat installed ?
write here the full directory

**Comment by kalibeginner** [comment]
Sorry but I'm not sure to know how i can find the full directory

**Comment by kalibeginner** [comment]
when i try git pull in fatrat directory i get this :



   remote: Enumerating objects: 53, done.remote: Counting objects: 100% (53/53), done.remote: Compressing objects: 100% (29/29), done.remote: Total 74 (delta 37), reused 24 (delta 24), pack-reused 21Unpacking objects: 100% (74/74), done.Since https://github.com/Screetsec/TheFatRat4465c41..3cae954 master -> origin / master* [new label] 1.9.6 -> 1.9.6* [new label] 1.9.7 -> 1.9.7Update 88bcd8a..3cae954error: Your local changes to the following files would be overwritten by the merge:fatratsetup.shupdatePlease validate or postpone your changes before the merge.abandonment


and when i try apt-get update i get this :


   Received from: 1 http://archive-4.kali.org/kali kali-rolling InRelease [30.5 kB]Received from: 2 http://archive-4.kali.org/kali-rolling / main i386 Packages [16.5 MB]Received from: 3 http://archive-4.kali.org/kali kali-rolling / main amd64 Packages [16.6 MB]Received from: 4 http://archive-4.kali.org/kali-rolling / non-free amd64 Packages [191 kB]Received from: 5 http://archive-4.kali.org/kali-rolling / non-free i386 Packages [167 kB]Received from: 6 http://archive-4.kali.org/kali-rolling / contrib amd64 Packages [108 kB]Received from: 7 http://archive-4.kali.org/kali-rolling / contrib i386 Packages [99.2 kB]33.7 MB received in 5s (6446 kb / s)Reading package lists ... Done


should i uninstall fatrat and reinstate it ?








Le 2 octobre 2019 à 9:02, Arthur Galmiche <arthgalmiche@icloud.com> a écrit :


Sorry but I'm not sure to know how i can find the full directory

Le 30 sept. 2019 à 17:07, peterpt <notifications@github.com> a écrit :



where is your fatrat installed ?
write here the full directory

**Comment by kalibeginner** [comment]
I deleted fatrat and install it again, I update it with
./update && chmod +x setup.sh && ./setup.sh

and it worked perfectly

I'v also tryed git pull and I'v got :

already update

so I tryed to create a backdoor bur i get always the same problem :
 
[x] There was an error creating your FUD rat with Powerstager .




Le 30 septembre 2019 à 17:07, peterpt <notifications@github.com> a écrit :



where is your fatrat installed ?
write here the full directory

**Comment by peterpt** [comment]
Do this :
Delete your fatrat directory

-the on a shell write :
git clone  https://github.com/Screetsec/TheFatRat.git
- then do this:
cd TheFatRat && chmod +x setup.sh && ./setup.sh

then let fatrat install itself automatically .
Then do again what you were trying to do .

The reason for this steps is because fatrat was updated recently , and a git pull at this time will not work , and setup must be run again because there was many changes in the main script .
