### ISSUE TITLE
TheFatRat: Directory Error

### ISSUE THREAD

**Issue by Rameshverm** [Screetsec/TheFatRat#382]
I There is a error messaged running fatrat, please help

Error Message:-

./fatrat: line 4531: $output/ip.txt: No such file or directory
cat: '$output/ip.txt': No such file or directory
./fatrat: line 4535: $output/apache_com.c: No such file or directory

rm: cannot remove '$output/apache_com.c': No such file or directory
rm: cannot remove '$output/ip.txt': No such file or directory

There was an error creating the backdoor

**Comment by peterpt** [comment]
just delete your repository and clone it again and run setup.sh and everything will be fine .

**Comment by Screetsec** [comment]
Fixing in variable , done
