### ISSUE TITLE
Mono-Denvelop Utils Not okay.

### ISSUE THREAD

**Issue by skyrim20101** [Screetsec/TheFatRat#384]
Hello,
 
I'm currently trying to install TheFatRat however i get to a bit where it can install Mono-Denvelop Utils and says its Not OK.
I have been looking at other forums on fixes but none have worked. I really need help, im very confused will trying to fix this for a few hours now and no luck. Everything else installs apart from the Mono-Denvelop Utils. 
Thank you.

**Comment by philosofonusus** [comment]
You need to download http://snapshot.debian.org/archive/debian/20141009T042436Z/pool/main/libj/libjpeg8/libjpeg8_8d1-2_amd64.deb
THEN
cd Downloads
dpkg -i libjpeg8_8d1-2_amd64.deb
apt-get install monodevelop

**Comment by skyrim20101** [comment]
Thanks for the response.
After doing dpkg -i libjpeg8_8d1-2_amd64.deb im getting a error.
dpkg: error processing archive libjpeg8d1-2_amd64.deb (--install): pre-dependency problem - not installing libjpeg8:amd64.

**Comment by philosofonusus** [comment]
sudo dpkg --configure -a

**Comment by philosofonusus** [comment]
what showing

**Comment by philosofonusus** [comment]
and what system are you using

**Comment by peterpt** [comment]
hey Philosofonusus , i am still trying to figure out here what the heck are you making skyrim doing !!

Skyrim , next time search in closed issues for your problem because we are not here to repeat the same this hundreds of times .

https://github.com/Screetsec/TheFatRat/issues/355
