### ISSUE TITLE
[x] There was an error creating your FUD rat with Powerstager . 

### ISSUE THREAD

**Issue by ranaali12346161** [Screetsec/TheFatRat#386]
[x] There was an error creating your FUD rat with Powerstager .
kindly help me out in this issue.
i am also not having the output folder in thefatrat folder

**Comment by peterpt** [comment]
1st - Output folder is not in fatrat folder , it it in your home directory .
2nd - there is a fudwin.log in your fatrat/logs folder that i want to look , upload it here .

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/issues/391
