### ISSUE TITLE
i cant install fatrat 

### ISSUE THREAD

**Issue by yohankumaresan** [screetsec/TheFatRat#387]
it says 
Configuration file does not exists , run setup.sh first for config .
i have tried running setup and again it gives this error when i run fatrat
i will attach the apt.log file with it
[apt.log](https://github.com/Screetsec/TheFatRat/files/3774708/apt.log)

**Comment by peterpt** [comment]
the problem is that kali does not have anymore mingw32 in their repositories : 
http://http.kali.org/kali/pool/main/m/

only the 64bit , and Fudwin in fatrat needs the 32bit compiler package of mingw .

My advice for you now is to add debian jessie repositories to your /etc/apt/sources.list

deb http://deb.debian.org/debian/ oldoldstable main contrib non-free
deb-src http://deb.debian.org/debian/ oldoldstable main contrib non-free
deb http://deb.debian.org/debian/ oldoldstable-updates main contrib non-free
deb-src http://deb.debian.org/debian/ oldoldstable-updates main contrib non-free

and then install manually mingw32
with apt-get install mingw32 

after that point remove the debian repositories from your sources.list and run again the setup from fatrat .

**Comment by jacobrohit** [comment]
root@kali:~# git clone https://github.com/Screetsec/TheFatRat.git
Cloning into 'TheFatRat'...
remote: Enumerating objects: 16, done.
remote: Counting objects:   6% (1remote: Counting objects:  12% (2remote: Counting objects:  18% (3remote: Counting objects:  25% (4remote: Counting objects:  31% (5remote: Counting objects:  37% (6remote: Counting objects:  43% (7remote: Counting objects:  50% (8remote: Counting objects:  56% (9remote: Counting objects:  62% (1remote: Counting objects:  68% (1remote: Counting objects:  75% (1remote: Counting objects:  81% (1remote: Counting objects:  87% (1remote: Counting objects:  93% (1remote: Counting objects: 100% (1remote: Counting objects: 100% (16/16), done.
remote: Compressing objects:   6%remote: Compressing objects:  12%remote: Compressing objects:  18%remote: Compressing objects:  25%remote: Compressing objects:  31%remote: Compressing objects:  37%remote: Compressing objects:  43%remote: Compressing objects:  50%remote: Compressing objects:  56%remote: Compressing objects:  62%remote: Compressing objects:  68%remote: Compressing objects:  75%remote: Compressing objects:  81%remote: Compressing objects:  87%remote: Compressing objects:  93%remote: Compressing objects: 100%remote: Compressing objects: 100% (16/16), done.
Receiving objects:   1% (140/1390Receiving objects:   2% (279/1390Receiving objects:   3% (418/1390Receiving objects:   4% (557/1390Receiving objects:   4% (682/1390Receiving objects:   4% (684/1390Receiving objects:   5% (696/1390Receiving objects:   5% (751/1390Receiving objects:   5% Receiving objects:  30% (4276/13remote: Total 13909 (delta 4), reused 0 (delta 0), pack-reused 13893
Receiving objects: 100% (13909/13909), 298.43 MiB | 543.00 KiB/s, done.
fatal: unable to open /root/TheFatRat/.git/objects/pack/tmp_pack_dM9u8I: No such file or directory
fatal: index-pack failed

**Comment by jacobrohit** [comment]
root@kali:~# git clone https://github.com/Screetsec/TheFatRat.git
Cloning into 'TheFatRat'...
remote: Enumerating objects: 16, done.
remote: Counting objects:   6% (1remote: Counting objects:  12% (2remote: Counting objects:  18% (3remote: Counting objects:  25% (4remote: Counting objects:  31% (5remote: Counting objects:  37% (6remote: Counting objects:  43% (7remote: Counting objects:  50% (8remote: Counting objects:  56% (9remote: Counting objects:  62% (1remote: Counting objects:  68% (1remote: Counting objects:  75% (1remote: Counting objects:  81% (1remote: Counting objects:  87% (1remote: Counting objects:  93% (1remote: Counting objects: 100% (1remote: Counting objects: 100% (16/16), done.
remote: Compressing objects:   6%remote: Compressing objects:  12%remote: Compressing objects:  18%remote: Compressing objects:  25%remote: Compressing objects:  31%remote: Compressing objects:  37%remote: Compressing objects:  43%remote: Compressing objects:  50%remote: Compressing objects:  56%remote: Compressing objects:  62%remote: Compressing objects:  68%remote: Compressing objects:  75%remote: Compressing objects:  81%remote: Compressing objects:  87%remote: Compressing objects:  93%remote: Compressing objects: 100%remote: Compressing objects: 100% (16/16), done.
Receiving objects:   1% (140/1390Receiving objects:   2% (279/1390Receiving objects:   3% (418/1390Receiving objects:   4% (557/1390Receiving objects:   4% (682/1390Receiving objects:   4% (684/1390Receiving objects:   5% (696/1390Receiving objects:   5% (751/1390Receiving objects:   5% Receiving objects:  30% (4276/13remote: Total 13909 (delta 4), reused 0 (delta 0), pack-reused 13893
Receiving objects: 100% (13909/13909), 298.43 MiB | 543.00 KiB/s, done.
**fatal: unable to open /root/TheFatRat/.git/objects/pack/tmp_pack_dM9u8I: No such file or directory
fatal: index-pack failed**

**Comment by peterpt** [comment]
jacobrohit you should try to clone fatrat to a different directory , like /opt
as an example .
That issue you have is out of our scope to solve it .
