### ISSUE TITLE
The backdoor created by Fatrat tool is detected by windows defender

### ISSUE THREAD

**Issue by hoainam10th123** [Screetsec/TheFatRat#388]
I created a backdoor using the Fatrat tool (1.9.7) but the Windows 8 defender detect it. How to solve this problem?
![dectectvirrus](https://user-images.githubusercontent.com/38690833/67930934-70d2d200-fbf3-11e9-8a4d-06a6eb7a3bd2.jpg)

**Comment by peterpt** [comment]
you cant solve it .
No matter how much we say to not upload to virus total , people always do it , now everyone that is using fatrat face the consequences .
