### ISSUE TITLE
Failed to align recompiled APk in backdoor apk

### ISSUE THREAD

**Issue by jacobrohit** [screetsec/TheFatRat#393]
[*] Running backdoor-apk.sh v0.2.4a on Tue 10 Dec 2019 09:03:59 PM IST
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 2
[*] Decompiling original APK file...done.
[*] Locating smali file to hook in original project...done.
[+] Package where RAT smali files will be injected: com/cdroid/dominoes
[+] Smali file to hook RAT payload: com/cdroid/dominoes/DominoContext.smali
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Injecting helpful Java classes in RAT APK file...done.
[*] Creating new directory in original package for RAT smali files...done.
[+] Inject package path: com/cdroid/dominoes/gexam
[+] Generated new smali class name for MainBroadcastReceiver.smali: Tigvn
[+] Generated new smali class name for MainService.smali: Ounec
[+] Generated new smali class name for Payload.smali: Ocgme
[+] Generated new smali class name for StringObfuscator.smali: Bahlg
[+] Generated new smali method name for StringObfuscator.obfuscate method: upjxo
[+] Generated new smali method name for StringObfuscator.unobfuscate method: ncbce
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
**date: invalid date ‘Sat Sep 26 20:51:24 2511’**
[*] Generating RSA key for signing...done.
[*] Signing recompiled APK...done.
[*] Verifying signed artifacts...done.
[*] Aligning recompiled APK...done.
**[!] Failed to align recompiled APK**

**Comment by peterpt** [comment]
try a different apk , it looks that backdoor apk uses the same date as the original apk you are trying to backdoor .
Use a different apk to test .

**Comment by jacobrohit** [comment]
> try a different apk , it looks that backdoor apk uses the same date as the original apk you are trying to backdoor .
> Use a different apk to test .
same error i used 4 apk 
] Obfuscating const-string values in RAT smali files...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[!] Failed to recompile original project with backdoor

**Comment by peterpt** [comment]
get a chair and sit on it , because i have to test it myself , and since this is not Microsoft support , then i need to have time here to test what you are saying , and i dont know when that will happen .
Most interesting thing is that you are the only one .
Anyway , have faith and upload here the apk so i can test it during this weekend .

**Comment by jacobrohit** [comment]
> get a chair and sit on it , because i have to test it myself , and since this is not Microsoft support , then i need to have time here to test what you are saying , and i dont know when that will happen .
> Most interesting thing is that you are the only one .
> Anyway , have faith and upload here the apk so i can test it during this weekend .

https://apkpure.com/youtube-go/com.google.android.apps.youtube.mango/download?from=details

**Comment by peterpt** [comment]
well i get a different error 
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Lbfa;->a([Ljava/lang/String;)Lbfa;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:917)


These types of errors are out of our scope .
You should try to install the original tool from : 
https://github.com/dana-at-cp/backdoor-apk

and see if same error appears , in case appears then create an issue to the denveloper .
