### ISSUE TITLE
error in creating Fud backdoor using Avoid1.2

### ISSUE THREAD

**Issue by lucifer-sys** [Screetsec/TheFatRat#397]
![Screenshot at 2019-12-13 16-34-08](https://user-images.githubusercontent.com/58629494/70796319-f5566a00-1dc7-11ea-8afb-402232fb3b11.png)
![Screenshot at 2019-12-13 16-44-12](https://user-images.githubusercontent.com/58629494/70796344-069f7680-1dc8-11ea-9f8f-68e173e248d5.png)

Whatever option i choose it shows these kinds of error.!! 
Please help!!

**Comment by peterpt** [comment]
delete that fatrat version and clone the new one .

**Comment by lucifer-sys** [comment]
this happened even after using the new version of fatrat. 
am using 5.3.0-3parrot-amd64

**Comment by peterpt** [comment]
just update you fatrat and everything will be fine .
