### ISSUE TITLE
Cannot create APK 

### ISSUE THREAD

**Issue by 8-ctrl** [Screetsec/TheFatRat#402]
![DeepinScreenshot_20191227192217](https://user-images.githubusercontent.com/59263572/71519683-940dbb00-28de-11ea-9a3a-fc18052d8be9.png)

**Comment by peterpt** [comment]
your metasploit is not working correctly , that means that your metasploit is not running everywhere in your system when you write "msfconsole" or "msfvenom" in your terminal .
To test it , go to your fatrat folder and write msfvenom or msfconsole to see what is the metasploit error .

dont ask here for help on your metasploit issues .

**Comment by Screetsec** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/ISSUES.md
