### ISSUE TITLE
fatal: repository 'https://github.com/Screetset/TheFatRat.git/' not found

### ISSUE THREAD

**Issue by akshayMungalpara2305** [Screetsec/TheFatRat#403]
I am installing TheFatRat in kali of window 10 home but cant install

**Comment by peterpt** [comment]
No : https://github.com/Screetset/TheFatRat.git/
Yes : https://github.com/Screetset/TheFatRat.git

You probably mean a kali VM in windows 10

**Comment by akshayMungalpara2305** [comment]
Yes,  window 10, VM.

**Comment by akshayMungalpara2305** [comment]
App of Microsoft store only cli

**Comment by peterpt** [comment]
Fatrat does not work in windows
