### ISSUE TITLE
Was not possible to install The Packages Labeled (Not Ok) in this list above

### ISSUE THREAD

**Issue by dammikapriyadarshani** [Screetsec/TheFatRat#404]
xterm -> OK                                                                                    
Dns-Utils -> OK                                                                                
Mono-Denvelop Utils -> Not OK                                                                  
GCC -> OK                                                                                      
Apache2 -> OK                                                                                  
gnome-terminal -> Not OK                                                                       
UPX -> OK                                                                                      
Ruby -> OK                                                                                     
Openssl -> OK                                                                                  
Jarsigner -> OK                                                                                
Unzip -> OK                                                                                    
Keytool -> OK                                                                                  
Mingw64 -> OK                                                                                  
Mingw32 -> OK                                                                                  
DX -> OK                                                                                       
Aapt -> OK                                                                                     
Apktool -> OK                                                                                  
Baksmali -> OK                                                                                 
Metasploit -> OK                                                                               
Backdoor-Factory -> OK                                                                         
Searchsploit -> OK                                                                             
Was not possible to install The Packages Labeled (Not Ok) in this list above                   
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)       
before running fatrat setup script again

**Comment by peterpt** [comment]
issue closed due missing file apt.log by user
