### ISSUE TITLE
Was not possible to install The Packages Labeled (Not Ok) in this list above

### ISSUE THREAD

**Issue by dammikapriyadarshani** [screetsec/TheFatRat#405]
xterm -> OK                                                                                    
Dns-Utils -> OK                                                                                
Mono-Denvelop Utils -> Not OK                                                                  
GCC -> OK                                                                                      
Apache2 -> OK                                                                                  
Gnome Terminal -> OK                                                                           
UPX -> OK                                                                                      
Ruby -> OK                                                                                     
Openssl -> OK                                                                                  
Jarsigner -> OK                                                                                
Unzip -> OK                                                                                    
Keytool -> OK                                                                                  
Mingw64 -> OK                                                                                  
Mingw32 -> OK                                                                                  
DX -> OK                                                                                       
Aapt -> OK                                                                                     
Apktool -> OK                                                                                  
Baksmali -> OK                                                                                 
Metasploit -> OK                                                                               
Backdoor-Factory -> OK                                                                         
Searchsploit -> OK                                                                             
Was not possible to install The Packages Labeled (Not Ok) in this list above                   
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)       
before running fatrat setup script again                                                       
root@kali:~/TheFatRat# apt-get remove --purge Mono-Denvelop Utils                              
Reading package lists... Done                                                                  
Building dependency tree                                                                       
Reading state information... Done                                                              
E: Unable to locate package Mono-Denvelop                                                      
E: Unable to locate package Utils
root@kali:~/TheFatRat# apt-get remove --purge Mono-Denvelop Utils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package Mono-Denvelop
E: Unable to locate package Utils

**Comment by dammikapriyadarshani** [comment]
Please give me a solution for this issue. I haven't do anything in this matter. Please help me

**Comment by dammikapriyadarshani** [comment]
[apt.log](https://github.com/Screetsec/TheFatRat/files/4011760/apt.log)

**Comment by peterpt** [comment]
write in your terminal :
apt-get install mono-mcs mono-devel -y

and write here the output of it

**Comment by Gabrielkim1** [comment]
Mine has the same issue and when i wrote

**Comment by rajnikantmahato** [comment]
ARm7l Android  kali linux
rm setupt.sh
wget https://raw.githubusercontent.com/Screetsec/TheFatRat/v1.8.1/setup.sh

Bash setup.sh
its old virsion setup.sh

**Comment by peterpt** [comment]
There is no support for old versions anymore .

**Comment by Maleficio-Hexa** [comment]
install mingw using:
apt-get install mingw-w64
and run again your last command(i think your problem will be solved)

**Comment by REY-AKA-RJDJ0261** [comment]
It says the fix on its own it's "apt-get remove --purge && apt-get autoremove && apt-get install -f"

**Comment by Tougharah** [comment]
xterm -> OK
Dns-Utils -> OK
Mono-Denvelop Utils -> OK
GCC -> OK
Apache2 -> OK
Gnome Terminal -> OK
UPX -> OK
Ruby -> OK
Python2 -> OK
Python3 -> OK
Python3-pip -> OK
Openssl -> OK
Jarsigner -> OK
Unzip -> OK
Keytool -> OK
Zipalign -> OK
mingw-w64 -> Not OK
mingw-32 -> Not OK
DX -> OK
Aapt -> OK
Apktool -> OK
Baksmali -> OK
Metasploit - msfconsole -> OK
Metasploit - msfvenom -> OK
Backdoor-Factory -> OK
Searchsploit -> OK
Was not possible to install The Packages Labeled (Not Ok) in this list above
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)
before running fatrat setup script again

Help me fix that problem of not ok

**Comment by Shawonsheikh90696** [comment]
Same problem

**Comment by Shawonsheikh90696** [comment]
Please help us

**Comment by Shawonsheikh90696** [comment]
Do you solve this problem?

**Comment by okoibraun** [comment]
Run:

sudo apt update
sudo apt upgrade

And then try it again
