### ISSUE TITLE
failed to generate RAT APK file

### ISSUE THREAD

**Issue by gunjivenkatsai** [screetsec/TheFatRat#406]
![Screenshot_2020-01-08_22-34-14](https://user-images.githubusercontent.com/57653494/72035946-58240f80-3267-11ea-9d3f-9a26da0eac65.png)

**Comment by peterpt** [comment]
your metasploit framework is not configured correctly almost for sure .
write msfconsole inside fatrat folder and drop here the output .

**Comment by gunjivenkatsai** [comment]
![Screenshot_2020-01-09_21-59-39](https://user-images.githubusercontent.com/57653494/72122286-63d90a00-332b-11ea-8da5-660ee24bfcc3.png)

**Comment by gunjivenkatsai** [comment]
> your metasploit framework is not configured correctly almost for sure .
> write msfconsole inside fatrat folder and drop here the output .

**Comment by gunjivenkatsai** [comment]
even i cant install that apk in remote device 
its showing "there was a problem with parsing the package"

**Comment by Screetsec** [comment]
Upload detail information - Following intrustcion here : https://github.com/Screetsec/TheFatRat/blob/master/ISSUES.md
