### ISSUE TITLE
There was an error creating your fud rat with powerstager

### ISSUE THREAD

**Issue by Themahmud18** [Screetsec/TheFatRat#409]
i got python 2.7

**Comment by peterpt** [comment]
I am not clairvoyant to guess what is going on there .
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md

**Comment by Themahmud18** [comment]
Working...Traceback (most recent call last):
  File "tools/power.py", line 2962, in <module>
    main(sys.argv[1:])
  File "tools/power.py", line 2949, in main
    compile_source()
  File "tools/power.py", line 2694, in compile_source
    Print.add_name_value("File signature", hashlib.md5(open(output, "rb").read()).hexdigest(), Print.info)
IOError: [Errno 2] No such file or directory: 'powerstager'

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md
