### ISSUE TITLE
output not found 

### ISSUE THREAD

**Issue by noh950** [Screetsec/TheFatRat#41]
When using the embedding android option the backdoored files is not found in the output folder, whereas the no embedded and exe's ones are correctly supplied.

**Comment by peterpt** [comment]
you have to get by yourself the apk where you want to merge the payload .
This means that if you want to merge the payload to the facebook.apk file , then you must first get that working apk from google play or anywhere else , and then use it in fatrat .

**Comment by noh950** [comment]
Where should the backdoored apk file be generated ?

**Comment by peterpt** [comment]
the backdoored apk will be generated in fatrat (option 5)  using the original one that you got from google play or anywhere else .

**Comment by noh950** [comment]
ok thanks a lot

**Comment by Ritwiksharma** [comment]
the backdoor ive created on fatrat is not getting saved at output folder ...and the window of fatrat is showing that it is saved in the output folder

**Comment by Ritwiksharma** [comment]
plzzz help me....
