### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by anukiller** [Screetsec/TheFatRat#411]
___________         __  __________          __
\_   _____/_____  _/  |_\______   \_____  _/  |_
 |    __)  \__  \ \   __\|       _/\__  \ \   __\
 |     \    / __ \_|  |  |    |   \ / __ \_|  |
 \___  /   (____  /|__|  |____|_  /(____  /|__|
     \/         \/              \/      \/
                 ____    ________
                /_   |  /   __   \
                 |   |  \____    /
                 |   |     /    /
                 |___| /\ /____/
                       \/
                                                                                                  Setup Script for FATRAT 1.9.7

 Setup will not proceed because none of these archs were detected

 x86_64|i386|i486|i586|i686|aarch64

 Your linux arch:  armv8l  is not supported

Press any key to continue

**Comment by peterpt** [comment]
The message is clear , this is not an issue .
"Your linux arch: armv8l is not supported"

**Comment by anukiller** [comment]
How to resolve it

**Comment by anukiller** [comment]
How to resolve it

**Comment by anukiller** [comment]
Please help me

**Comment by peterpt** [comment]
Your device architecture is not supported , so there is no way to solve it .

Only these Architectures are supported : 
x86_64|i386|i486|i586|i686|aarch64
