### ISSUE TITLE
wont make a "bat" backdoor with pwndinds

### ISSUE THREAD

**Issue by russianracc** [Screetsec/TheFatRat#413]
Generate Backdoor
  +------------++-------------------------++-----------------------+
  | Name       ||  Descript               || Your Input
  +------------++-------------------------++-----------------------+
  | LHOST      ||  The Listen Addres      || tcp://0.tcp.ngrok.io:15178
  | LPORT      ||  The Listen Ports       || 11730
  | OUTPUTNAME ||  The Filename output    || ues
  | PAYLOAD    ||  Payload To Be Used     || windows/meterpreter/reverse_tcp
  +------------++-------------------------++-----------------------+

[ ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++    ]

cat: powershell_attack.txt: No such file or directory
rm: cannot remove 'unicorn.rc': No such file or directory
mv: cannot stat 'powershell_attack.txt': No such file or directory

There was an error creating the baackdoor

  Press [ENTER] to continue .........     

i keep getting that error after i try to set it up 

Idk what to do any help?

**Comment by peterpt** [comment]
tcp://0.tcp.ngrok.io:15178 is no address for lhost .

**Comment by prince24j** [comment]
please help me with the 


 Generate Backdoor                                                                                 
  +------------++-------------------------++-----------------------+                                
  | Name       ||  Descript               || Your Input                                             
  +------------++-------------------------++-----------------------+                                
  | LHOST      ||  The Listen Addres      || 10.0.2.15                                              
  | LPORT      ||  The Listen Ports       || 8080                                                   
  | OUTPUTNAME ||  The Filename output    || rev_sysopenFR                                          
  | PAYLOAD    ||  Payload To Be Used     || windows/meterpreter/reverse_https                      
  +------------++-------------------------++-----------------------+                                
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
[ ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  ]                           


cat: powershell_attack.txt: No such file or directory
rm: cannot remove 'unicorn.rc': No such file or directory
mv: cannot stat 'powershell_attack.txt': No such file or directory


There was an error creating the baackdoor
