### ISSUE TITLE
Not bypass av

### ISSUE THREAD

**Issue by gnu-like** [Screetsec/TheFatRat#414]
I tested most of the method but could not bypass av.

- [x] **metasploit v5.0.70-dev**

- [x] **fatrat 1.9.7**

**Comment by peterpt** [comment]
2 years ago it bypassed the antivirus , but people to make sure it was working then they uploaded their generated rats to virustotal website , after that point the rats loose the ability to bypass antivirus because they are detected .
There is nothing we can do about it .
