### ISSUE TITLE
TheFatRat

### ISSUE THREAD

**Issue by Gabrielkim1** [screetsec/TheFatRat#415]
[apt.log](https://github.com/Screetsec/TheFatRat/files/4132263/apt.log)
Hey guys. I am having problems installing TheFatRat. This is the final report of installation. I have tried different methods of installing it but all bring me to this. I am new to this and want to learn. Kindly help me.

jarsigner (openjdk-8-jdk)-> Not OK
Unzip -> OK
Keytool -> OK
Mingw64 -> OK
Mingw32 -> OK
DX -> OK
Aapt -> OK
Apktool -> OK
Baksmali -> OK
Metasploit -> OK
Backdoor-factory -> Not OK
Searchsploit -> Not OK
Was not possible to install The Packages Labeled (Not Ok) in this list above
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)
before running fatrat setup script again

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/issues.md

**Comment by Gabrielkim1** [comment]
Sorry
I uploaded the apt.log

**Comment by peterpt** [comment]
add kali repositories to /etc/apt/sources.list file
https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/
