### ISSUE TITLE
can't access TheFatRat_generated apk in root directory due to 2020 version of kali linux.

### ISSUE THREAD

**Issue by lazycheeta** [Screetsec/TheFatRat#421]
Hey, I am unable to access thefatrat generated folder in Root directory because 2020 version of kali linux has desable the permision to access the given folder.
Is thier any way to change the generated apk path or any trick to enable the permission for root directory.
Thanks in adv.

**Comment by peterpt** [comment]
Actually fatrat does not put files directly to root folder , only in case if you are a root .
Fatrat drops the generated files to your home folder .

**Comment by CiCiNL** [comment]
> Actually fatrat does not put files directly to root folder , only in case if you are a root .
> Fatrat drops the generated files to your home folder .

Is it? new Kali version uses non-root user named kali. When generating a file the default output folder is indeed in /root which cannot be accessed... so I have the same issue as Lazycheeta

**Comment by peterpt** [comment]
well , we will not change the code just because kali denvelopers want to kill your access to some dirs .
If you want you can change in your scripts everyline that says :

output="$HOME/Fatrat_Generated"

to

output="your directory/Fatrat_Generated"

fatrat script line 84
backdoorapk script line 714,717,720,725,728 etc....
powerfull.sh script line 124,125 etc...

basically in every script that have these lines : 
$HOME/Fatrat_Generated/

or
~/Fatrat_Generated/

**Comment by CiCiNL** [comment]
in this case I would recommend to add a note stating the change in kali 2020, remove the mention of CEH docs, which will be of no use anymore (i checked) , or add the changes in script in readme file or something to this site.

**Comment by Screetsec** [comment]
you can install kali-grant-root and run dpkg-reconfigure kali-grant-root to configure password-less root rightsm, or you cand added root access like this 
- https://securityboulevard.com/2020/02/setting-up-the-root-account-on-kali-2020/

**Comment by CiCiNL** [comment]
really, I am an ignorant idiot... due to lack of Linux knowledge... in shell just do 'sudo bash' and move the Fatrat_Generated to ~kali use chown if needed 

my apologies for this guys and thanks for the support.

**Comment by 93493** [comment]
> 
> 
> you can install kali-grant-root and run dpkg-reconfigure kali-grant-root to configure password-less root rightsm, or you cand added root access like this
> 
>     * https://securityboulevard.com/2020/02/setting-up-the-root-account-on-kali-2020/

Have the same problem and did this. Still cant access Root Folder. Help?

**Comment by raskin-bond** [comment]
Hi 

> Hey, I am unable to access thefatrat generated folder in Root directory because 2020 version of kali linux has desable the permision to access the given folder.
> Is thier any way to change the generated apk path or any trick to enable the permission for root directory.
> Thanks in adv.

first you access the root directory using below cmd
 > sudo su
> type your password <

and then screen will shown root directory 


bond@bad:~$ sudo su
[sudo] password for bond: 
root@bad:/home/bond# root

after that you enter normal cd cmd and move apk file to home directory 


root@bad:/home/bond# cd /root/
root@bad:~# ls
Fatrat_Generated
root@bad:~# cd Fatrat_Generated
root@bad:~/Fatrat_Generated# ls
app_backdoored.apk  primeoffer.apk
root@bad:~/Fatrat_Generated# mv app_backdoored.apk /home/bond

check the screenshot

 
![Screenshot 2020-07-23 12:13:15](https://user-images.githubusercontent.com/34650372/88411995-e0eb3e80-cda6-11ea-8a32-0e8262b5763d.png)

**Comment by Guardsword** [comment]
jarsigner (default-jdk)-> Not OK                                               
Unzip -> OK                                                                    
keytool -> Not OK  

While installing the FatRat on Kali 2020.2 (VMWare Fusion) I am getting these errors. Mingw64 and 32 were also showing not ok, but then I installed them separately and it is Ok now. 

Can someone help me in fixing this please...!

**Comment by raskin-bond** [comment]
> jarsigner (default-jdk)-> Not OK
> Unzip -> OK
> keytool -> Not OK
> 
> While installing the FatRat on Kali 2020.2 (VMWare Fusion) I am getting these errors. Mingw64 and 32 were also showing not ok, but then I installed them separately and it is Ok now.
> 
> Can someone help me in fixing this please...!

sudo apt-get install openjdk-11-jdk

sudo update-alternatives -config java

change the  0, 1, 2 options separately and check whether jarsigner  will surely work.

For mingw64 issue >>>>>>>

https://www.monodevelop.com/download/   follow the step provided in this link surely this will work.

**Comment by Ozone2** [comment]
> Hey, I am unable to access thefatrat generated folder in Root directory because 2020 version of kali linux has desable the permision to access the given folder.
> Is thier any way to change the generated apk path or any trick to enable the permission for root directory.
> Thanks in adv.

Have you solved your problem, coz i'm having the same problem. If you have then plzzz let me know how did u solved that.

**Comment by Ozone2** [comment]
Coz, reply's on your question didn't seems to be promising.

**Comment by furkan9ne** [comment]
> Merhaba
> 
> > Hey, kali linux'un 2020 sürümü verilen klasöre erişim iznini devre dışı bıraktığından, Kök dizindeki fatrat tarafından oluşturulan klasöre erişemiyorum. 
> > Kök dizine izin vermek için oluşturulan apk yolunu veya herhangi bir hileyi değiştirmenin herhangi bir yolu var mı? 
> > adv'de teşekkürler.
> 
> önce aşağıdaki cmd'yi kullanarak kök dizine erişirsiniz
> 
> > sudo su 
> > şifrenizi yazın <
> 
> ve ardından ekran kök dizini gösterecek
> 
> bond@bad:~$ sudo su [sudo] bağ için parola: root@bad:/home/bond# root
> 
> bundan sonra normal cd cmd girin ve apk dosyasını ana dizine taşıyın
> 
> root@bad:/home/bond# cd /root/ root@bad:~# ls Fatrat_Generated root@bad:~# cd Fatrat_Generated root@bad:~/Fatrat_Generated# ls app_backdoored.apk primeoffer.apk root@bad:~/Fatrat_Generated# mv app_backdoored.apk /home/bond
> 
> ekran görüntüsünü kontrol et
> 
> ![Ekran Görüntüsü 2020-07-23 12:13:15](https://user-images.githubusercontent.com/34650372/88411995-e0eb3e80-cda6-11ea-8a32-0e8262b5763d.png)
hi bro, i'm getting the same error, i couldn't solve it, please help me, i don't have a lot of knowledge, i want to learn thanks to you

**Comment by Playjay826** [comment]
keeps going back to home page'

**Comment by flashbackboi** [comment]
just do
sudo su
THEN DO
thunar 
it will open root folder

**Comment by shotym3sa** [comment]
can some one please help  me install this fatrat the correct way i keep getting errors and cant find correct resportories
