### ISSUE TITLE
Unable to install Fatrat.

### ISSUE THREAD

**Issue by bhaleraosumit7** [Screetsec/TheFatRat#422]
xterm -> OK                                                                
Dns-Utils -> OK                                                            
Mono-Denvelop Utils -> OK                                                  
GCC -> OK                                                                  
Apache2 -> OK                                                              
Gnome Terminal -> OK                                                       
UPX -> OK                                                                  
Ruby -> OK                                                                 
Openssl -> OK                                                              
Jarsigner -> OK                                                            
Unzip -> OK                                                                
Keytool -> OK                                                              
Mingw64 -> OK                                                              
Mingw32 -> OK                                                              
dx -> Not OK                                                               
aapt -> Not OK                                                             
apktool -> Not OK                                                          
Baksmali -> OK                                                             
Metasploit -> OK                                                           
Backdoor-Factory -> OK                                                     
Searchsploit -> OK                                                         
Was not possible to install The Packages Labeled (Not Ok) in this list above                                                                          
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)                                                              
before running fatrat setup script again   
[apt.log](https://github.com/Screetsec/TheFatRat/files/4210200/apt.log)

**Comment by bhaleraosumit7** [comment]
I have also tried by installing dx, aap & apltool but still facing the same issue.

**Comment by peterpt** [comment]
are you executing setup as root ?
Those tools come inside fatrat , and fatrat creates symlinks to /usr/local/sbin folder .
I am not pretty sure because i never made the test if a non root user is able to create a symlink to that folder .

**Comment by peterpt** [comment]
Delete your fatrat git and clone it again and execute setup again , and if the problem presists then post here the apt.log generated by fatrat .

**Comment by bhaleraosumit7** [comment]
Thank you peterpt,

Deleting and cloning it again worked for me.
