### ISSUE TITLE
i cant install TheFatRat

### ISSUE THREAD

**Issue by fatwsh21** [Screetsec/TheFatRat#426]
can you help me please ,, what should i do and i tried 100 time (apt-get install ------)
![Screenshot (116)](https://user-images.githubusercontent.com/61921926/76153577-db82a580-60de-11ea-84c3-6d087aac6a63.png)

**Comment by dhont666** [comment]
Update your kali... i installer and didnt have ant problems oe dependecies
to install...

Apt upgrade && apt -f install

Good luck

Op za 7 mrt. 2020 om 23:49 schreef fatwsh21 <notifications@github.com>
