### ISSUE TITLE
Problem in Fatrat to making malicious android application. cehv10 module 17 lab 4

### ISSUE THREAD

**Issue by str1994** [Screetsec/TheFatRat#429]
*] Running backdoor-apk.sh v0.2.4a on Tue 10 Mar 2020 09:51:45 AM EDT
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 1
[*] Decompiling original APK file...done.
[*] Locating smali file to hook in original project...done.
[!] Failed to locate smali file to hook
 

or

*] Running backdoor-apk.sh v0.2.4a on Tue 10 Mar 2020 09:53:27 AM EDT
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 2
[*] Decompiling original APK file...done.
[*] Locating smali file to hook in original project...done.
[!] Failed to locate smali file to hook

tried both ways but shows same error

**Comment by peterpt** [comment]
backdoor apk was not developed by us , the tool belongs to :
https://github.com/dana-at-cp/backdoor-apk

There is nothing we can do about it .
