### ISSUE TITLE
Showing error

### ISSUE THREAD

**Issue by acinelit** [Screetsec/TheFatRat#43]
![screenshot from 2017-02-22 09-14-51](https://cloud.githubusercontent.com/assets/25943393/23194454/bd818fa6-f8e0-11e6-88f3-c979316f892c.png)
![screenshot from 2017-02-22 09-14-57](https://cloud.githubusercontent.com/assets/25943393/23194455/bd88ef1c-f8e0-11e6-8656-cd810a2ad7de.png)

Using [05]  Backdooring Original apk [Instagram, Line,etc] and then error

**Comment by peterpt** [comment]
I am building a new way for fatrat build the backdoor apk to interact with the new way fatrat instalation works , in meanwhile check if you have java jdk installed , in case you don't have it then install it by using : apt-get install default-jre default-jdk .

Some changes will be made on fatrat on the next version .

**Comment by acinelit** [comment]
I already Install java jdk and still same showing erorr

**Comment by peterpt** [comment]
clone the latest fatrat from git and test it out to see if works on you .
error could be related to missing packages from you OS or you are trying to merge your payload on a hook on your apk that is not possible .

check how i did it in latest fatrat : https://www.youtube.com/watch?v=GKpEQrGUem4
