### ISSUE TITLE
xterm: Xt error: Can't open display: %s

### ISSUE THREAD

**Issue by kushwaharishikesh899** [Screetsec/TheFatRat#436]
[ X ] Mingw-w64 -> not found
Warning: This program is an suid-root program or is being run by the root user.
The full text of the error or warning message cannot be safely formatted
in this environment. You may get a more descriptive message by running the
program as a non-root user or by removing the suid bit on the executable.
xterm: Xt error: Can't open display: %s
xterm: DISPLAY is not set
 [ X ] Mingw-32 -> not found
Warning: This program is an suid-root program or is being run by the root user.
The full text of the error or warning message cannot be safely formatted
in this environment. You may get a more descriptive message by running the
program as a non-root user or by removing the suid bit on the executable.
xterm: Xt error: Can't open display: %s
xterm: DISPLAY is not set

how to fix this error please replay fast it is coming on each and ever tool while installing fatrat please replay fast .

if anybody know how to fix it then please contact me on 
123amankushwaha@gmail.com

**Comment by peterpt** [comment]
fatrat is not able to run on mobile phones , tablets with kali hunter or other os  , remote shells because it needs gui interface to run multiples terminals .
This mean that user must be logged on on a X11 session and be root to run the script .

**Comment by dhgclt** [comment]
https://github.com/dhgclt/xterm-fix-for-kali-nethunter/blob/main/README.md
