### ISSUE TITLE
Cannot install fatrat also i am using kali on virtual box. The problem is down in comment below

### ISSUE THREAD

**Issue by HyperBeasty** [screetsec/TheFatRat#440]
xterm -> Not OK                                                                  
Dns-Utils -> OK                                                                  
Mono-Denvelop Utils -> OK                                                        
GCC -> OK                                                                        
Apache2 -> OK                                                                    
gnome-terminal -> Not OK                                                         
UPX -> OK                                                                        
Ruby -> OK                                                                       
Openssl -> OK                                                                    
jarsigner (default-jdk)-> Not OK                                                 
Unzip -> OK                                                                      
Keytool -> OK                                                                    
mingw-w64 -> Not OK                                                              
Mingw32 -> OK                                                                    
DX -> OK                                                                         
Aapt -> OK                                                                       
Apktool -> OK                                                                    
Baksmali -> OK                                                                   
Metasploit -> OK                                                                 
Backdoor-Factory -> OK                                                           
Searchsploit -> OK                                                               
Was not possible to install The Packages Labeled (Not Ok) in this list above     
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)                                                                          
before running fatrat setup script again                                         
root@kali:/home/beast/TheFatRat#

**Comment by Maxcillius** [comment]
i am getting same error, still searching for solution...

**Comment by Maxcillius** [comment]
I installed FatRat, I just install latest apktool because it was NOT OK in my situation and it is working...
