### ISSUE TITLE
mono-denvelop utils-Not Ok

### ISSUE THREAD

**Issue by r3h3mm** [screetsec/TheFatRat#442]
not being able to install the mono-denvelop utils in both kali and parrot 
have changed the source file and tried but no luck
have run apt-cache search mono-mcs and tried to install using apt-get install mono-mcs
but it does not install the dependencies
![Screen Shot 2020-04-04 at 10 11 31 PM](https://user-images.githubusercontent.com/56667806/78456582-3994af80-76c2-11ea-99ec-c7c2362f541f.png)
![Screen Shot 2020-04-04 at 10 13 06 PM](https://user-images.githubusercontent.com/56667806/78456584-3bf70980-76c2-11ea-9016-7da062911b34.png)

PLEASE HELP

**Comment by peterpt** [comment]
you have to remove all monodevelop installed packages to then install mono-mcs , the reason is that mono-mcs that you are trying to install , or fatrat tries to install have a lower version than your current monodenvelop installed version .
if you write :
**aptitude install mono-mcs**

then  will show what is the problem and how to solve it .
In case you dont have aptitude installed then install it by writing this : apt-get install aptitude

**Comment by bhawanijangid** [comment]
i was also in same in problem with monodevlop(after installing its giving error not installed or not ok ). tried all solution found on all webpages and blogs
but here i m giving u final solution (official from https://www.monodevelop.com/download/#fndtn-download-lin-ubuntu) copy and execute these commands  and then run setup.sh(plz let me know if i m wrong )
**************
sudo apt install apt-transport-https dirmngr
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb https://download.mono-project.com/repo/ubuntu vs-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-vs.list
sudo apt update

**Comment by lester-harris** [comment]
> i was also in same in problem with monodevlop(after installing its giving error not installed or not ok ). tried all solution found on all webpages and blogs
> but here i m giving u final solution (official from https://www.monodevelop.com/download/#fndtn-download-lin-ubuntu) copy and execute these commands and then run setup.sh(plz let me know if i m wrong )
> 
> sudo apt install apt-transport-https dirmngr
> sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
> echo "deb https://download.mono-project.com/repo/ubuntu vs-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-vs.list
> sudo apt update

It worked well for me. Many thanks man.
