### ISSUE TITLE
error when i installing the fatrat

### ISSUE THREAD

**Issue by hasbihismannudin** [Screetsec/TheFatRat#445]
___________         __  __________          __
\_   _____/_____  _/  |_\______   \_____  _/  |_
 |    __)  \__  \ \   __\|       _/\__  \ \   __\
 |     \    / __ \_|  |  |    |   \ / __ \_|  |
 \___  /   (____  /|__|  |____|_  /(____  /|__|
     \/         \/              \/      \/
                 ____    ________
                /_   |  /   __   \
                 |   |  \____    /
                 |   |     /    /
                 |___| /\ /____/
                       \/

          Setup Script for FATRAT 1.9.7

               64Bit OS detected

 Checking type of shell ....
[local]

 [ * ] Checking for internet connection
 [ ✔ ]::[Internet Connection]: CONNECTED!
 [ ✔ ] Xterm.............................[ found ]
 [ ✔ ] Dns-Utils ........................[ found ]
 [ ✔ ] Mono-Denvelop Utils ..............[ found ]
 [ ✔ ] Gcc compiler......................[ found ]
 [ X ] Apache2 -> not found
 [ ! ]    Installing apache2
Warning: This program is an suid-root program or is being run by the root user.
The full text of the error or warning message cannot be safely formatted
in this environment. You may get a more descriptive message by running the
program as a non-root user or by removing the suid bit on the executable.
xterm: Xt error: Can't open display: %s
xterm: DISPLAY is not set
 [ x ] Apache2
 [ ✔ ] Gnome Terminal....................[ found ]
 [ X ] Upx compressor  -> not found
 [ ! ] Installing upx-compressor
Warning: This program is an suid-root program or is being run by the root user.
The full text of the error or warning message cannot be safely formatted
in this environment. You may get a more descriptive message by running the
program as a non-root user or by removing the suid bit on the executable.
xterm: Xt error: Can't open display: %s
xterm: DISPLAY is not set
 [ x ] UPX Compressor
 [ ✔ ] Ruby..............................[ found ]
 [ ✔ ] Openssl...........................[ found ]
 [ ! ] Installing tools dependencies
Warning: This program is an suid-root program or is being run by the root user.
The full text of the error or warning message cannot be safely formatted
in this environment. You may get a more descriptive message by running the
program as a non-root user or by removing the suid bit on the executable.
xterm: Xt error: Can't open display: %s
xterm: DISPLAY is not set
Warning: This program is an suid-root program or is being run by the root user.
The full text of the error or warning message cannot be safely formatted
in this environment. You may get a more descriptive message by running the
program as a non-root user or by removing the suid bit on the executable.
xterm: Xt error: Can't open display: %s
xterm: DISPLAY is not set
 [ ✔ ] Jarsigner (java)..................[ found ]
 [ ✔ ] Unzip.............................[ found ]
 [ ✔ ] Keytool (java)....................[ found ]
 [ ✔ ] Zipalign
 [ ✔ ] Mingw-w64 Compiler................[ found ]
 [ ✔ ] Mingw-32 Compiler.................[ found ]
 [ ✔ ] DX 1.12...........................[ found ]
 [ ✔ ] Aapt v0.2-3544217.................[ found ]
Warning: This program is an suid-root program or is being run by the root user.
The full text of the error or warning message cannot be safely formatted
in this environment. You may get a more descriptive message by running the
program as a non-root user or by removing the suid bit on the executable.
xterm: Xt error: Can't open display: %s
xterm: DISPLAY is not set
 [ ✔ ] Apktool v.2.4.0..................[Installed]
 [ ✔ ] Baksmali v.2.3.3..................[ found ]
 [ ✔ ] Metasploit-Framework..............[ found ]
 [ ✔ ] Backdoor-Factory..................[ found ]
 [ X ] searchsploit  -> not found

 Select one of the options bellow
 +-------------------------------------------------+
 | [ 1 ] Setup Searchsploit Path Manually          |
 | [ 2 ] Install Searchsploit from Kali Repository |
 +-------------------------------------------------+

 Option :

**Comment by hasbihismannudin** [comment]
how to fix this?

**Comment by gert200-3** [comment]
![Uploading 20220804_205502.jpg…]()
Pls help me

**Comment by Mo0oj** [comment]
> _ _**/**_ _/ |_______ _____ _/ |_ | __) __ \ \ **| _/__ \ \ | \ / __ _| | | | \ / __ _| | _ / (**__ /|**| |_**_|_ /(**__ /|**| / / / / ____ ________ /_ | / __ | | ____ / | | / / |_**| /\ /**__/ /
> 
> ```
>       Setup Script for FATRAT 1.9.7
> 
>            64Bit OS detected
> ```
> 
> Checking type of shell .... [local]
> 
> [ * ] Checking for internet connection [ ✔ ]::[Internet Connection]: CONNECTED! [ ✔ ] Xterm.............................[ found ] [ ✔ ] Dns-Utils ........................[ found ] [ ✔ ] Mono-Denvelop Utils ..............[ found ] [ ✔ ] Gcc compiler......................[ found ] [ X ] Apache2 -> not found [ ! ] Installing apache2 Warning: This program is an suid-root program or is being run by the root user. The full text of the error or warning message cannot be safely formatted in this environment. You may get a more descriptive message by running the program as a non-root user or by removing the suid bit on the executable. xterm: Xt error: Can't open display: %s xterm: DISPLAY is not set [ x ] Apache2 [ ✔ ] Gnome Terminal....................[ found ] [ X ] Upx compressor -> not found [ ! ] Installing upx-compressor Warning: This program is an suid-root program or is being run by the root user. The full text of the error or warning message cannot be safely formatted in this environment. You may get a more descriptive message by running the program as a non-root user or by removing the suid bit on the executable. xterm: Xt error: Can't open display: %s xterm: DISPLAY is not set [ x ] UPX Compressor [ ✔ ] Ruby..............................[ found ] [ ✔ ] Openssl...........................[ found ] [ ! ] Installing tools dependencies Warning: This program is an suid-root program or is being run by the root user. The full text of the error or warning message cannot be safely formatted in this environment. You may get a more descriptive message by running the program as a non-root user or by removing the suid bit on the executable. xterm: Xt error: Can't open display: %s xterm: DISPLAY is not set Warning: This program is an suid-root program or is being run by the root user. The full text of the error or warning message cannot be safely formatted in this environment. You may get a more descriptive message by running the program as a non-root user or by removing the suid bit on the executable. xterm: Xt error: Can't open display: %s xterm: DISPLAY is not set [ ✔ ] Jarsigner (java)..................[ found ] [ ✔ ] Unzip.............................[ found ] [ ✔ ] Keytool (java)....................[ found ] [ ✔ ] Zipalign [ ✔ ] Mingw-w64 Compiler................[ found ] [ ✔ ] Mingw-32 Compiler.................[ found ] [ ✔ ] DX 1.12...........................[ found ] [ ✔ ] Aapt v0.2-3544217.................[ found ] Warning: This program is an suid-root program or is being run by the root user. The full text of the error or warning message cannot be safely formatted in this environment. You may get a more descriptive message by running the program as a non-root user or by removing the suid bit on the executable. xterm: Xt error: Can't open display: %s xterm: DISPLAY is not set [ ✔ ] Apktool v.2.4.0..................[Installed] [ ✔ ] Baksmali v.2.3.3..................[ found ] [ ✔ ] Metasploit-Framework..............[ found ] [ ✔ ] Backdoor-Factory..................[ found ] [ X ] searchsploit -> not found
> 
> Select one of the options bellow +-------------------------------------------------+ | [ 1 ] Setup Searchsploit Path Manually | | [ 2 ] Install Searchsploit from Kali Repository | +-------------------------------------------------+
> 
> Option :

I received same error. Add to that, I have macbook pro core i7 
is there any way I can fix it ?
