### ISSUE TITLE
Fat rat set up mono-denvelop not ok 

### ISSUE THREAD

**Issue by aakash272002** [Screetsec/TheFatRat#446]
![Screenshot (22)](https://user-images.githubusercontent.com/63418316/78922540-c3b88b80-7aa7-11ea-865a-e06020030f32.png)

I have been struggling with this one issue for the past few days pls help me fix this

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/ISSUES.md
