### ISSUE TITLE
Internet not working

### ISSUE THREAD

**Issue by samaelstar2402** [screetsec/TheFatRat#448]
I am using ubuntu 18 in my vnc viewer android my vncveiwer chrome browser is working correctly but when I try to install TheFatRat by executing setup.sh it say no internet connection

**Comment by samaelstar2402** [comment]
Please help someone.

**Comment by Curioo** [comment]
Theres no point commenting on your issue for help. The contributors of this project will get to your issue once more pressing issues are resolved.

**Comment by peterpt** [comment]
write netcat in your terminal and post here the output .
setup and fatrat scripts use netcat to connect to google.com on port 80 using netcat , if by some reason netcat is not installed then will go to stage 2 of detection witch is less efective .
2nd stage uses ping util to check google dns , and if that fails then will drop that message you got .
So in case you dont have netcat then write in terminal "apt-get install netcat" and make sure you are connected to internet and no firewalls are blocking your linux tcp connections .
