### ISSUE TITLE
Apache2 can't be found and some file not ok please can you tell me what to do

### ISSUE THREAD

**Issue by derrick120** [Screetsec/TheFatRat#449]
xterm -> OK                                                                             
Dns-Utils -> OK                                                                         
Mono-Denvelop Utils -> OK                                                               
GCC -> OK                                                                               
apache2 -> Not OK                                                                       
Gnome Terminal -> OK                                                                    
UPX -> OK                                                                               
Ruby -> OK                                                                              
Openssl -> OK                                                                           
Jarsigner -> OK                                                                         
Unzip -> OK                                                                             
Keytool -> OK                                                                           
Mingw64 -> OK                                                                           
Mingw32 -> OK                                                                           
dx -> Not OK                                                                            
aapt -> Not OK                                                                          
apktool -> Not OK                                                                       
baksmali -> Not OK                                                                      
Metasploit -> OK                                                                        
Backdoor-Factory -> OK                                                                  
Searchsploit -> OK                                                                      
Was not possible to install The Packages Labeled (Not Ok) in this list above            
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)
before running fatrat setup script again                                                
root@kali:/home/dionwhite/Desktop/TheFatRat-master# sudo apt-get install

**Comment by peterpt** [comment]
apache2 is instalable by kali repository , if you dont have it the it is because your sources.list dont have any repositories to update your OS , or all lines are commented .

**Comment by derrick120** [comment]
Get I get the command to force upgrade it please?

**Comment by peterpt** [comment]
upload apt.log file

**Comment by derrick120** [comment]
Thanks

**Comment by derrick120** [comment]
Still did not work, command not found

**Comment by peterpt** [comment]
in main fatrat folder under "logs" directory there is a file called "apt.log" , upload it to this issue , just pick the file and drag to the text box on this issue .

**Comment by derrick120** [comment]
I still can't find the file maybe I am doing something wrong, please can
you send me the file to install? Thanks
