### ISSUE TITLE
How can I fix apache2??

### ISSUE THREAD

**Issue by derrick120** [Screetsec/TheFatRat#450]
[ * ] Checking for internet connection                                                 
 [ ✔ ]::[Internet Connection]: CONNECTED!                                               
 [ ✔ ] Xterm.............................[ found ]                                      
 [ ✔ ] Dns-Utils ........................[ found ]                                      
 [ ✔ ] Mono-Denvelop Utils ..............[ found ]                                      
 [ ✔ ] Gcc compiler......................[ found ]                                      
 [ X ] Apache2 -> not found                                                             
 [ ! ]    Installing apache2                                                            
Warning: Tried to connect to session manager, Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed                                                                                       
 [ x ] Apache2                                                                          
 [ ✔ ] Gnome Terminal....................[ found ]                                      
 [ ✔ ] UPX Compressor....................[ found ]                                      
 [ ✔ ] Ruby..............................[ found ]                                      
 [ ✔ ] Openssl...........................[ found ]                                      
 [ ! ] Installing tools dependencies                                                    
Warning: Tried to connect to session manager, Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed                                                                                       
Warning: Tried to connect to session manager, Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed

**Comment by peterpt** [comment]
You are running on a terminal window outside a X11 session . Fatrat needs a X11 session not only to work as also to install the tools .
