### ISSUE TITLE
Error when i try to create path for my Apk in Fatrat

### ISSUE THREAD

**Issue by Oforimoses** [screetsec/TheFatRat#452]
Guys am getting this error any help

Enter the path to your android app/game .(ex: /root/downloads/myapp.apk)

Path : /root/Downloads/ofori.apk

File does not exist , make sure you write the right path of it .

**Comment by peterpt** [comment]
if it says "File does not exist , make sure you write the right path of it ." then you probably misspelled some letter in the path to your apk file , if real directory name is "downloads" and you write "Downloads" instead then it will give you an error .

**Comment by MissMinFu** [comment]
i have the some problem,i wonder know have you fix it

**Comment by Joyfernandas** [comment]
Enter the path to your android app/game .(ex: /root/downloads/myapp.apk)

 Path : instagram.apk

 File does not exist , make sure you write the right path of it .
 how to solve this
