### ISSUE TITLE
Can't install properly in wsl system.

### ISSUE THREAD

**Issue by HackingWithMR** [Screetsec/TheFatRat#453]
Well, I am a noob in the penetration testing community. I was trying to -
###  install TheFatRat on WSL based windows 10 Kali Linux App.
Got a lot of errors encountered some with stack-overflow skills but still got some. NEED HELP.
I get this every time I run sudo ./setup.sh 
![image](https://user-images.githubusercontent.com/63785270/79747628-d5165900-832d-11ea-83e3-1b6029e49e28.png)

Well, I installed jdk-14.0.1 as this guy told- [https://www.youtube.com/watch?v=72mz0-98vg8](url)
but why still getting jarsigner error. 
![image](https://user-images.githubusercontent.com/63785270/79748172-cda37f80-832e-11ea-8075-c1d653f4f9f9.png)

Moreover, I don't need Gnome-terminal. Then why it is not working. Please help me so I can fix all issues.

### Log files which were created while TheFatRat installing process:
[apt.log](https://github.com/Screetsec/TheFatRat/files/4503191/apt.log)
[install.log](https://github.com/Screetsec/TheFatRat/files/4503192/install.log)

**Thanks a lot** in advance for helping me. I have been stuck with this problem for several days.
Stay Safe, Stay Home.

**Comment by peterpt** [comment]
you must be a root user to install the packages needed .
Fatrat is not able to install anything without root permission .

**Comment by HackingWithMR** [comment]
> you must be a root user to install the packages needed .
> Fatrat is not able to install anything without root permission .

Sorry, It was a fault not mentioning it I used sudo but didn't work.
outputs the same.

**Comment by RykerPQ** [comment]
You need to get into root first, then install TheFatRat.
You can do into root by either su or sudo -i.

**Comment by HackingWithMR** [comment]
Well let it go. Hacking using windows is annoying and a true pain int the ass.So switched to Kali Linux and things are looking fine. Thanks all for your support.
