### ISSUE TITLE
i can't install FatRat

### ISSUE THREAD

**Issue by BettiouiFarid** [screetsec/TheFatRat#457]
[apt.log](https://github.com/Screetsec/TheFatRat/files/4519125/apt.log)

**Comment by peterpt** [comment]
1st you dont have any repositories in your sources.list , you should look into parrto website and know the repository update links and add them to /etc/apt/sources.list 

2nd , root user is required to install fatrat , and you are only an user .
Root user is the same thing as an full administrator witch have no restrictions in executing anything in the OS .

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md

**Comment by krishpranav** [comment]
Hi 
can i know what is the reason and what issue is coming

**Comment by cruelty1708** [comment]
Do you have Python installed?

**Comment by krishpranav** [comment]
yeah i have python 
i am using parrot os

**Comment by krishpranav** [comment]
so it has python already installed

**Comment by peterpt** [comment]
apt-get remove --purge *mingw-* -y && apt-get autoremove -y && ./setup.sh

**Comment by peterpt** [comment]
apt-get remove --purge *mingw-* -y && apt-get autoremove -y && ./setup.sh

**Comment by peterpt** [comment]
apt-get remove --purge *mingw-* -y && apt-get autoremove -y && ./setup.sh

**Comment by peterpt** [comment]
apt-get remove --purge *mingw-* -y && apt-get autoremove -y && ./setup.sh

**Comment by peterpt** [comment]
apt-get remove --purge *mingw-* -y && apt-get autoremove -y && ./setup.sh

**Comment by MohammedFaiz06** [comment]
> Python has nothing to do to what this user issue have , stop messing around . Recent distributions do not install anymore mingw32 , so you have to remove your current mingw installations and run setup.sh from fatrat , setup from fatrat will use debian jessie repository witch still install mingw32 .
> 
> apt-get remove --purge *mingw-* -y && apt-get autoremove -y && ./setup.sh

I get "E: dpkg was interrupted, you must manually run 'sudo dpkg  --configure -a' to correct the problem

**Comment by Morsmalleo** [comment]
Run the command 
`sudo dpkg --configure -a` to fox the dpkg error 

Then run this command below and print the output here, this will determine if you have any active software repositories to install the packages needed for TheFatRat.

NOTE: By default, Parrot OS's software repositories are located at `/etc/apt/sources.list.d/` under the title `parrot.list`

`cat /etc/apt/sources.list.d/parrot.list`

**Comment by Morsmalleo** [comment]
> > Python has nothing to do to what this user issue have , stop messing around . Recent distributions do not install anymore mingw32 , so you have to remove your current mingw installations and run setup.sh from fatrat , setup from fatrat will use debian jessie repository witch still install mingw32 .
> > apt-get remove --purge _mingw-_ -y && apt-get autoremove -y && ./setup.sh
> 
> I get "E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem

As @peterpt said this has nothing to do with your Python installation! 

All you need to do is simply check your `parrot.list` in the directory `/etc/apt/sources.list.d/` if you see nothing in this file or if there is no file named `parrot.list`, then you have installed the HOME version of Parrot OS, not the Security Version! 

If there is a `parrot.list` file located at `etc/apt/sources.list.d/` and there are software repository mirror links in this file, then you obviously have no idea what you are doing!! 

Follow these simple steps 
`sudo dpkg --configure -a` - to fix the dpkg error you have

`enable and then disable Anonsurf-GTK for parrot OS`
(By default anonsurf for Parrot is enabled at startup, so disable this to prevent interruptions installing pacakges)

`git clone https://github.com/Screetsec/TheFatRat`
`cd TheFatRat`
`chmod +x setup.sh chk_tools update`
`sudo ./setup.sh` 

Then you should be all good
