### ISSUE TITLE
how to solve the error in apk tool

### ISSUE THREAD

**Issue by Thakur679** [Screetsec/TheFatRat#459]
xterm -> OK                                                                                                                                                           
Dns-Utils -> OK                                                                                                                                                       
Mono-Denvelop Utils -> OK                                                                                                                                             
GCC -> OK                                                                                                                                                             
Apache2 -> OK                                                                                                                                                         
Gnome Terminal -> OK                                                                                                                                                  
UPX -> OK                                                                                                                                                             
Ruby -> OK                                                                                                                                                            
Openssl -> OK                                                                                                                                                         
Jarsigner -> OK                                                                                                                                                       
Unzip -> OK                                                                                                                                                           
Keytool -> OK                                                                                                                                                         
Mingw64 -> OK                                                                                                                                                         
Mingw32 -> OK                                                                                                                                                         
DX -> OK                                                                                                                                                              
Aapt -> OK                                                                                                                                                            
apktool -> Not OK                                                                                                                                                     
Baksmali -> OK                                                                                                                                                        
Metasploit -> OK                                                                                                                                                      
Backdoor-Factory -> OK                                                                                                                                                
Searchsploit -> OK                                                                                                                                                    
Was not possible to install The Packages Labeled (Not Ok) in this list above                                                                                          
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)                                                                              
before running fatrat setup script again    
how to solve this
![Screenshot_2020-04-24_03-20-29](https://user-images.githubusercontent.com/64230647/80153125-9a851880-85da-11ea-9d5b-8a671e3851ba.png)

**Comment by areejune** [comment]
I'm having the exact same issue and I have already tried these commands:
apt-get remove --purge apktool -y && apt-get autoremove -y
rm -f /usr/local/sbin/apktool
and executed setup.sh afterwards but it's still not working

**Comment by areejune** [comment]
I have also tried to do it all over with "rm -rf ~/TheFatRat && git clone https://github.com/Screetsec/TheFatRat.git ~/TheFatRat && cd ~/TheFatRat && chmod +x fatrat && chmod +x setup.sh && ./setup.sh" as it was recommended in a previous issue and still
