### ISSUE TITLE
apktool -> Not OK

### ISSUE THREAD

**Issue by fikrih97** [Screetsec/TheFatRat#461]
Hi,
Since the latest update, I can't install fatrat. It will always says "was not possible to install The Packages Label (Not OK)" which is apktool. How do I solve this?
Thank you.

**Comment by sidjad** [comment]
I am also encountering the same apktool issue with new kali linux 2020.2

> Hi,
> Since the latest update, I can't install fatrat. It will always says "was not possible to install The Packages Label (Not OK)" which is apktool. How do I solve this?
> Thank you.

**Comment by sidjad** [comment]
hello @fikrih97 here is solution ==> chmod +x /usr/local/sbin/apktool

**Comment by fikrih97** [comment]
> hello @fikrih97 here is solution ==> chmod +x /usr/local/sbin/apktool

It works! Thank you! Anyway do you know how to create undetectable payload? I've tried so many things with the payload, and still detected by Windows Defender and AV.

**Comment by 93493** [comment]
> 
> 
> hello @fikrih97 here is solution ==> chmod +x /usr/local/sbin/apktool

I used https://ibotpeaches.github.io/Apktool/install/



> 
> 
> > hello @fikrih97 here is solution ==> chmod +x /usr/local/sbin/apktool
> 
> It works! Thank you! Anyway do you know how to create undetectable payload? I've tried so many things with the payload, and still detected by Windows Defender and AV.

I tried so many Rats. They work more or less but the biggest problem is to make them FUD and there are some other problems. They want money for Crypter. Not paying for something server based. So i came across to FatRat but still don't know what it does exactly. Thought its kind of Rat Builder under Linux for Windows and other Systems and generates unique FUDs, but seems so it doesn't.

**Comment by vctrcardoso** [comment]
> > hello @fikrih97 here is solution ==> chmod +x /usr/local/sbin/apktool
> 
> I used https://ibotpeaches.github.io/Apktool/install/
> 
> > > hello @fikrih97 here is solution ==> chmod +x /usr/local/sbin/apktool
> > 
> > 
> > It works! Thank you! Anyway do you know how to create undetectable payload? I've tried so many things with the payload, and still detected by Windows Defender and AV.
> 
> I tried so many Rats. They work more or less but the biggest problem is to make them FUD. They want money for Crypter. Not paying for this. So i came across to FatRat but still don't know what it does exactly. Thought its kind of Rat Builder under Linux for Windows and other Systems and generates everytime a new unique FUD, but seems so it doesnt.
> 
> I have also a problem with the tfstfile. FatRat generates the file in the Root folder and i cant access it.

https://github.com/Screetsec/TheFatRat/issues/462
help me, I have the problem in the dx and aapt not installed

**Comment by peterpt** [comment]
apt-get remove --purge apktool -y && apt-get autoremove -y && rm /usr/local/sbin/apktool

then run setup from fatrat .

Apktool in fatrat it is inside its folder there is only created a symlink to /usr/local/sbin that points to fatrat folder where apktool exists . In previous version the folder was in fatrat "aptool2.4.0" and now it is "apktool2.4.1" so by removing the current symplink from previous version will enable fatrat to create a new symlink with the new corrected path .
Let me know if you find any more issues with this after these steps .

**Comment by peterpt** [comment]
Fixed in last update .
Just clone again the git and run setup
