### ISSUE TITLE
apktool installation not ok

### ISSUE THREAD

**Issue by rajendrasp** [Screetsec/TheFatRat#467]
Hi,

I am trying to install TheFatRat but it is giving me error at the apktool installation step. apktool is not getting installed properly. It is showing as Not ok. I also tried to install apktool manually with "apt-get install apktool" but still it is not able to identify successfully. Please help.
Thanks!

**Comment by rajendrasp** [comment]
![apktool](https://user-images.githubusercontent.com/51284446/80306447-118bfe00-87e1-11ea-879f-5c53a386d216.PNG)

**Comment by peterpt** [comment]
i will fix that issue in not time or inside fatrat folder execute
chmod +x tools/apktool2.4.1/apktool

then run setup.sh again

**Comment by rajendrasp** [comment]
Thanks a lot for the solution. It worked! Thanks again!
