### ISSUE TITLE
Unable to install the "Not ok" labelled packages, gnome-terminal and mono-den elop untils

### ISSUE THREAD

**Issue by GadiHarsha** [screetsec/TheFatRat#473]
![15884471569984819014114703335209](https://user-images.githubusercontent.com/64706368/80874286-13b9f500-8cd8-11ea-9eb1-7e2bbd3116cf.jpg)
 Even after trying basic trouble shoot ita showing unable to locate package,

Please answer me this

**Comment by peterpt** [comment]
Clone the most recent git and read https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md

until the end

**Comment by lylest** [comment]
facing the same problem

**Comment by peterpt** [comment]
Upload atp.log

**Comment by GadiHarsha** [comment]
> Upload apt.log

[apt.log](https://github.com/Screetsec/TheFatRat/files/4847630/apt.log)
