### ISSUE TITLE
Ican only run fatrat in root user....problem

### ISSUE THREAD

**Issue by jennaAz** [screetsec/TheFatRat#475]
Is it possible to change the permission to run the fat rat with a regular user? when i run 
thefatrat
it give me this: 
/usr/share/thefatrat/fatrat: line 36: temp/distro.tmp: Permission denied
/usr/share/thefatrat/fatrat: line 37: temp/codename.tmp: Permission denied
awk: fatal: cannot open file `temp/codename.tmp' for reading: No such file or directory
awk: fatal: cannot open file `temp/distro.tmp' for reading: No such file or directory
awk: fatal: cannot open file `temp/distro.tmp' for reading: No such file or directory
 Must be root to run script

When I run   sudo thefatrat
everything go well. I would like to run it as regular user. I use Manjaro blackarch

**Comment by peterpt** [comment]
only a user with root rights is able to run the script .
