### ISSUE TITLE
Infected my computer

### ISSUE THREAD

**Issue by hexagonTEAM** [Screetsec/TheFatRat#477]
Hello i want to know how to uninstall backdoor from my windows because while testing things i made a mistake and executed the program in my real machine instead of my vm

**Comment by peterpt** [comment]
lol , dont worry , these backdoors dont stay on windows start or windows system boot , they only are active when you click the file , after the file is closed then backdoor closes any connection .
Hopefully all the hard job to put something on windows start to connect to the attacker must be made by hand using mestaploit witch i have serious doubts you have that ability to do it .
So , restart your computer and delete the file you downloaded to test .

**Comment by hexagonTEAM** [comment]
But fatrat use metasploit (Windows defender detecter "meterpreter")

**Comment by hexagonTEAM** [comment]
I wanna enter in contact with the developer because an user used the tool for other purposes than "educational purposes". He had bad intentions and hacked me to steal my passwords.

**Comment by hexagonTEAM** [comment]
Wait, let me correct

**Comment by hexagonTEAM** [comment]
Wait, forget the vm thing, i were talking in the same time in a discord vocal server about other things, but, yes, i was hacked by a minecraft hacker who stole my passwords.

**Comment by peterpt** [comment]
And how can you be sure that was a backdoor made in fatrat ?!!
1st - Your talk makes no sense and you are not sure of anything 
2nd - you can not prove that was a fatrat generated backdoor 
3rd - We take no responsability of what users do with this tool (read main page)

4th - Advice : Change your passwords .

5th - Dont bother us with crapy talk .

**Comment by hexagonTEAM** [comment]
Waut, why can't we talk in discord ?

**Comment by hexagonTEAM** [comment]
I really want to remove that shit(yes i know and i am sure that the hacker used fatrat)

**Comment by peterpt** [comment]
Just install an antivirus and you will be fine .
