### ISSUE TITLE
Using backdoor_apk (creating android files)

- backdooring original apk doesn't work on android 9 and Original 2019-2020 APK files.

### ISSUE THREAD

**Issue by Morsmalleo** [Screetsec/TheFatRat#478]
Hello, i come here today with an issue with getting the payload apk files to work

I back door the original apk file and install it on the victim device just fine, but when I open the backdoored apk file to start the meterpreter session, nothing happens on metasploits end, it still displays "Started listening on:0.0.0.0:4444" and nothing else (0.0.0.0 is the example IP its not the actual IP address I used)

I have tried restarting the phone then opening the backdoored app on the victim device, but I still get the same results

Please help

**Comment by peterpt** [comment]
android device must be on same subnet as attacker device or the atacker mustdot have a router lan between the android and metasploit .

Example :
Ip address of android : 87.123.231.34
attacker ip must be is public ip address and not the lan ip .
Reason is simple , if payload in apk was generated to connect to 192.168.1.40 , then that ip is never a public ip but a lan ip address .

On other way , if android ip address ip is : 192.168.1.32
and attacker have an ip : 192.168.1.40 or any ip on same subnet , then it would work fine .

**Comment by Morsmalleo** [comment]
Ok thank you Peterpt I will give this a try, do you mind if I get back to
you in regards to how the process goes?

**Comment by Morsmalleo** [comment]
Problem solved, Thank you @peterpt
