### ISSUE TITLE
How will the backdoor connect back to me when my ip address changes ?

### ISSUE THREAD

**Issue by moose816a** [Screetsec/TheFatRat#48]
I have installed a backdoor on a remote machine and created a payload and listener with the help of  FATRAT AND METASPLOIT. My IP address is dynamic. My question is when my ip address changes how will the remote machine connect back to me

**Comment by NoorQureshi** [comment]
You have to use No-IP Dns or buy a static from your ISP... or you can use VPS as well..

**Comment by peterpt** [comment]
usually people use their lan ip to configure the local host , witch is wrong and should only be used to test the rat files over LAN . 
Like NoorQureshi told , you have to use a dinamic ip dns hostname .
Infecting strangers computers with RATS is illegal , FATRAT project was developed for test purposes on local lan , if you use it outside your lan then it is your responsibility .

**Comment by shadow-cracker** [comment]
can i use duckdns instead No-Ip??
