### ISSUE TITLE
backdooring original apk is not working 

### ISSUE THREAD

**Issue by HK-dot** [screetsec/TheFatRat#482]
i have gone through all the step perfectly 
i pressed 5 for backdoor creating and i gave my ip and port and i selected reverse tcp option.
and all done perfect app got created . i open  msfconsole and started listener and server got connected. i installed app in my phone which has android version 10 
i open the app but connection dint get established even for 5 min 

does this payload work for android 10 version 
please help

**Comment by vd062** [comment]
I'm also having same problem on Android 9. Payload is binding but not executed even when we open that app. Works fine when raw payload is installed.

**Comment by Forbesgriffin** [comment]
@vd062 Same thing here
