### ISSUE TITLE
error with fatrat 1.9.2 

### ISSUE THREAD

**Issue by killmberp** [screetsec/TheFatRat#484]
[apt.log](https://github.com/Screetsec/TheFatRat/files/4666204/apt.log)
pls help

**Comment by peterpt** [comment]
apt-get remove —purge \*mingw\* -y && apt-get autoremove -y 

Then execute setup from fatrat .

**Comment by killmberp** [comment]
> apt-get remove —purge *mingw* -y && apt-get autoremove -y
> 
> Then execute setup from fatrat .

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'gfortran-mingw-w64-x86-64-win32' for glob '*mingw*'
Note, selecting 'gobjc-mingw-w64-i686-win32' for glob '*mingw*'
Note, selecting 'libnpth-mingw-w64-dev' for glob '*mingw*'
Note, selecting 'mingw-w64-common' for glob '*mingw*'
Note, selecting 'gfortran-mingw-w64-x86-64-posix' for glob '*mingw*'
Note, selecting 'mingw-w64-tools' for glob '*mingw*'
Note, selecting 'gobjc-mingw-w64-i686-posix' for glob '*mingw*'
Note, selecting 'gnat-mingw-w64-x86-64' for glob '*mingw*'
Note, selecting 'gobjc-mingw-w64-x86-64' for glob '*mingw*'
Note, selecting 'gdb-mingw-w64-target' for glob '*mingw*'
Note, selecting 'libksba-mingw-w64-dev' for glob '*mingw*'
Note, selecting 'mingw-w64-i686-dev' for glob '*mingw*'
Note, selecting 'gcc-mingw-w64-base' for glob '*mingw*'
Note, selecting 'gfortran-mingw-w64' for glob '*mingw*'
Note, selecting 'gcc-mingw-w64-i686' for glob '*mingw*'
Note, selecting 'gcc-mingw-w64-bootstrap' for glob '*mingw*'
Note, selecting 'g++-mingw-w64' for glob '*mingw*'
Note, selecting 'libz-mingw-w64-dev' for glob '*mingw*'
Note, selecting 'libgcrypt-mingw-w64-dev' for glob '*mingw*'
Note, selecting 'g++-mingw-w64-i686' for glob '*mingw*'
Note, selecting 'gfortran-mingw-w64-i686-win32' for glob '*mingw*'
Note, selecting 'gfortran-mingw-w64-i686-posix' for glob '*mingw*'
Note, selecting 'gcc-mingw-w64-x86-64-win32-runtime' for glob '*mingw*'
Note, selecting 'gobjc-mingw-w64' for glob '*mingw*'
Note, selecting 'gcc-mingw-w64' for glob '*mingw*'
Note, selecting 'gfortran-mingw-w64-i686' for glob '*mingw*'
Note, selecting 'gcc-mingw-w64-x86-64-posix-runtime' for glob '*mingw*'
Note, selecting 'g++-mingw-w64-x86-64' for glob '*mingw*'
Note, selecting 'mingw-w64-dev' for glob '*mingw*'
Note, selecting 'gnat-mingw-w64-i686-win32' for glob '*mingw*'                    
Note, selecting 'gdb-mingw-w64' for glob '*mingw*'
Note, selecting 'binutils-mingw-w64' for glob '*mingw*'
Note, selecting 'gobjc-mingw-w64-i686' for glob '*mingw*'
Note, selecting 'binutils-mingw-w64-x86-64' for glob '*mingw*'
Note, selecting 'gnat-mingw-w64-i686-posix' for glob '*mingw*'
Note, selecting 'mingw-w64' for glob '*mingw*'
Note, selecting 'gobjc++-mingw-w64-x86-64-win32' for glob '*mingw*'
Note, selecting 'mingw-w64-x86-64-dev' for glob '*mingw*'
Note, selecting 'gobjc++-mingw-w64-x86-64-posix' for glob '*mingw*'
Note, selecting 'gcc-mingw-w64-i686-win32' for glob '*mingw*'
Note, selecting 'gcc-mingw-w64-i686-posix' for glob '*mingw*'
Note, selecting 'libpthreads-mingw-w64' for glob '*mingw*'
Note, selecting 'libassuan-mingw-w64-dev' for glob '*mingw*'
Note, selecting 'gnat-mingw-w64-i686' for glob '*mingw*'
Note, selecting 'gnat-mingw-w64' for glob '*mingw*'
Note, selecting 'pkg-config-mingw-w64-x86-64' for glob '*mingw*'
Note, selecting 'gcc-mingw-w64-i686-posix-runtime' for glob '*mingw*'
Note, selecting 'gobjc++-mingw-w64-x86-64' for glob '*mingw*'
Note, selecting 'gcc-mingw-w64-x86-64-win32' for glob '*mingw*'
Note, selecting 'gcc-mingw-w64-x86-64-posix' for glob '*mingw*'
Note, selecting 'gobjc++-mingw-w64' for glob '*mingw*'
Note, selecting 'g++-mingw-w64-x86-64-win32' for glob '*mingw*'
Note, selecting 'gobjc++-mingw-w64-i686-win32' for glob '*mingw*'
Note, selecting 'g++-mingw-w64-x86-64-posix' for glob '*mingw*'
Note, selecting 'gobjc++-mingw-w64-i686-posix' for glob '*mingw*'
Note, selecting 'gcc-mingw-w64-i686-win32-runtime' for glob '*mingw*'
Note, selecting 'gobjc-mingw-w64-x86-64-win32' for glob '*mingw*'
Note, selecting 'pkg-config-mingw-w64-i686' for glob '*mingw*'
Note, selecting 'gnat-mingw-w64-x86-64-win32' for glob '*mingw*'
Note, selecting 'gcc-mingw-w64-x86-64' for glob '*mingw*'
Note, selecting 'libgpg-error-mingw-w64-dev' for glob '*mingw*'
Note, selecting 'gobjc-mingw-w64-x86-64-posix' for glob '*mingw*'
Note, selecting 'g++-mingw-w64-i686-win32' for glob '*mingw*'
Note, selecting 'libz-mingw-w64' for glob '*mingw*'
Note, selecting 'gnat-mingw-w64-x86-64-posix' for glob '*mingw*'
Note, selecting 'binutils-mingw-w64-i686' for glob '*mingw*'
Note, selecting 'g++-mingw-w64-i686-posix' for glob '*mingw*'
Note, selecting 'gfortran-mingw-w64-x86-64' for glob '*mingw*'
Note, selecting 'gobjc++-mingw-w64-i686' for glob '*mingw*'
Package 'gcc-mingw-w64-bootstrap' is not installed, so not removed
Package 'libpthreads-mingw-w64' is not installed, so not removed
Package 'mingw-w64-dev' is not installed, so not removed
Note, selecting 'mingw-w64-tools' instead of 'pkg-config-mingw-w64-i686'
Note, selecting 'mingw-w64-tools' instead of 'pkg-config-mingw-w64-x86-64'
E: Unable to locate package —purge

**Comment by peterpt** [comment]
apt-get remove --purge \*mingw\* -y && apt-get autoremove -y
