### ISSUE TITLE
chk_tools Saying everything works but...

### ISSUE THREAD

**Issue by anonhff** [screetsec/TheFatRat#486]
I ran chk_tools.sh and it outputs that everything is installed correctly and that all dependencies are met, however upon running fatrat, it hangs at "Checking..." and provides no error messages what so ever. Just stalls forever. 

I'm using Kali 2020.2 on a live boot usb with persistence. Ran as root user (sudo bash, cd TheFatRat to run setup, and ran into no issues during installation), and am running fatrat as root user also.
![Screenshot_2020-05-23_17-39-54](https://user-images.githubusercontent.com/65826947/82737500-ebdf0f80-9d20-11ea-8841-ee89e6323219.png)

**Comment by peterpt** [comment]
you have a problem with your netcat tool .
Your netcat is unable to connect to google to check for internet .
Maybe if you downgrade its version may solve the issue .
