### ISSUE TITLE
jarsigner (default-jdk)-> Not OK while installing TheFatRat

### ISSUE THREAD

**Issue by aviralharsh** [Screetsec/TheFatRat#489]
all the other packages installed except jarsigner. Please update solution asap. Thanks

**Comment by dodik87** [comment]
You can install it manually: apt-get install default-jdk if you are using debian system

**Comment by alwaqassharif** [comment]
<img width="586" alt="Screenshot_2" src="https://user-images.githubusercontent.com/66223353/84613484-1f244280-ae78-11ea-9df8-9c8be7dde2c3.png">

**Comment by alwaqassharif** [comment]
plz help me to remove this error while fatrat installation. I am so much worried.

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md#if-nothing-works-

**Comment by bala205king** [comment]
I have many issuses in installing the fatrat app in kali linux in virtual 

-

**Comment by sahariear401** [comment]
jarsigner (openjdk-8-jdk)-> Not OK
