### ISSUE TITLE
All the backdoors are now getting detected by windows defender ? How to solve this issue ?

### ISSUE THREAD

**Issue by moose816a** [Screetsec/TheFatRat#49]

**Comment by peterpt** [comment]
Antivirus companies are always developing new search techniques to find patters in files to detect virus , the same way virus creators also develop others techniques to hide their virus .
Fatrat use multiples tools to create the rat files , and when those external tools get updated with new techniques then fatrat will be able to hide your payload in the file you are distributing .
Avoid using virus total to test your rat files , and make sure you are testing the real backdoor camouflaged file .
Use https://virusscan.jotti.org/ to test your files .

**Comment by bootvis** [comment]
To add to the excellent comment from peterpt. Unfortunately for this project, Jotti has changed their privacy policy a while ago. It literally states: 

> We store files you send in for scanning and share these with anti-malware companies. We do this to help anti-malware companies improve the detection accuracy of their security products. We treat your files confidentially and we trust the anti-malware companies we share your files with will do the same, but obviously we cannot exercise control over third parties or make promises on their behalf. Your files will be analyzed (and thus read) by security analysts. If you do not want other people or companies reading your files, please do not send these files in for scanning. Files are not shared with entities outside the anti-virus/security industry.

Although there are plenty other alternatives around, I suggest setting up your own AV testing sandbox lab environment would be the best solution. That way your level of control is as extensive as your imagination, endurance and operational skills.

**Comment by peterpt** [comment]
Use : http://nodistribute.com/
