### ISSUE TITLE
Error For Create A Rat. TheFatRat

### ISSUE THREAD

**Issue by GRATIX12** [screetsec/TheFatRat#492]
Good evening!

I have an error when creating a rat can you help me?

Error :
The error is displayed at the moment when I execute the command "fatrat" then "2" then "1" then I enter "LHOST" and "LPORT" after I enter the name of the app, it asks me icon and that's when an error occured!

Error:

"[*] Building your powerstage rat for windows with the following values ."

And

"[x] There was an error creating your FUD rat with powerstage"

Can you help me ?

**Comment by peterpt** [comment]
run chk_tools inside fatrat folder to see what is wrong .
chk_tools will tell you if you have any incorrect version installed when running fatrat .

./chk_tools

**Comment by GRATIX12** [comment]
Hi,

When I execute the command "./chk_tools" (I am on root) its puts me this error:

"-bash: ./chk_tools: Permission denied"

**Comment by W4r10k** [comment]
chmod +x chk_tools 
./chk_tools

**Comment by GRATIX12** [comment]
> chmod + x chk_tools
> ./chk_tools

Hi,

I made the command "./chk_tools" and its give me this:

https://pastebin.com/ZSrfqNEQ

Thank you.

**Comment by W4r10k** [comment]
install mingw-w64 compiler manually

sudo apt-get update -y
sudo apt-get install -y mingw-w64

./chk_tools

**Comment by peterpt** [comment]
just to be sure : 
1st - pip install names
2nd - run setup from fatrat , i have no idea how you got fatrat running because according to check tools the packages are not installed , and when that happens it does not run by default .
