### ISSUE TITLE
Checking Dx (Apk Req.)....................[x] Incorrect Version for apk builder in Fatrat.

### ISSUE THREAD

**Issue by Kapil231** [Screetsec/TheFatRat#495]
I encountered this error while troubleshooting through chk_tools.
I tried its solution, removed the dx package and installed it manually.
Then I completely removed the fatrat and installed it again but the problem remains.

When I run the application  generated through fatrat, It doesn't ask for any permissions and I am not receiving any reverse connection from my android phone.

**Comment by peterpt** [comment]
1st . the check tools only tells you to uninstall it using apt
2nd it never told you to install it again .
3rd setup from fatrat does that for you

**Comment by Kapil231** [comment]
I had already performed these steps.
apt-get remove --purge dx
chmod +x setup.sh && ./setup.sh


But it's still not working...

**Comment by peterpt** [comment]
did you (rm /usr/local/sbin/dx) ?

Problem is because you already installed fatrat before and symlink is probably in /usr/local/sbin directory .

**Comment by Kapil231** [comment]
First i removed it from directory(usr/local/sbin/dx), and then installed it again.

**Comment by peterpt** [comment]
Upload apt.log to here

**Comment by Kapil231** [comment]
[apt.log](https://github.com/Screetsec/TheFatRat/files/4712102/apt.log)

**Comment by peterpt** [comment]
apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y

**Comment by Kapil231** [comment]
If i choose option 2) use old fatrat method, then backdoor is generated but not working.
When I install the backdoor on my android phone, it doesn't ask for any permissions nor am i getting any reverse connection.
