### ISSUE TITLE
PROBLEM WITH MONO DEVLOP UTILS IN FAT RAT

### ISSUE THREAD

**Issue by kevin-grey** [Screetsec/TheFatRat#497]
Can anybody please help me out. Having some problem downloading Fat Rat dependencies. Also I wanted help regarding the "Apk builder" which it shows as incorrect version.

![2020-06-01_13-48-51-ba43656ea646781f34f7cf58b49e4989](https://user-images.githubusercontent.com/66263730/83422736-994fd280-a447-11ea-9bfd-cf711ae3a158.png)
![2020-06-01_13-41-16-ab11f02e7c272645633800feebc90151](https://user-images.githubusercontent.com/66263730/83422761-a40a6780-a447-11ea-91c9-b733413ac2b2.png)

**Comment by net-war** [comment]
I’m having same issue. I tried sudo apt-get install all dependencies , nothing worked. I tried every command listed in this Issues section, nothing worked. My last sudo apt-get install command froze system

**Comment by peterpt** [comment]
upload apt.log

**Comment by net-war** [comment]
> upload apt.log

I did this , it is listed copy and pasted into the results above

**Comment by peterpt** [comment]
Just upgrade your system because it looks you installed it long time ago and did not get any update .

**Comment by net-war** [comment]
Ok which command to update do you know? Thanks.

**Comment by peterpt** [comment]
Google it , this is not stack exchange .
