### ISSUE TITLE
Not get proper install

### ISSUE THREAD

**Issue by drag30** [Screetsec/TheFatRat#499]
xterm -> OK                                                                          
Dns-Utils -> OK                                                                      
Mono-Denvelop Utils -> OK                                                            
GCC -> OK                                                                            
Apache2 -> OK                                                                        
Gnome Terminal -> OK                                                                 
UPX -> OK                                                                            
Ruby -> OK                                                                           
Openssl -> OK                                                                        
jarsigner (default-jdk)-> Not OK                                                     
Unzip -> OK                                                                          
Keytool -> OK                                                                        
Mingw64 -> OK                                                                        
Mingw32 -> OK                                                                        
DX -> OK                                                                             
Aapt -> OK                                                                           
Apktool -> OK                                                                        
Baksmali -> OK                                                                       
Metasploit -> OK                                                                     
Backdoor-Factory -> OK                                                               
Searchsploit -> OK                                                                   
Was not possible to install The Packages Labeled (Not Ok) in this list above         
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)                                                                                  
before running fatrat setup script again                                             
root@kali:/home/kali/Desktop/TheFatRat#

**Comment by peterpt** [comment]
apt-get install default-jdk default-jre -y
