### ISSUE TITLE
Fatrat not working

### ISSUE THREAD

**Issue by Kapil231** [Screetsec/TheFatRat#500]
I raised an issue "Checking Dx (Apk Req.)....................[x] Incorrect Version for apk builder in Fatrat. #495" and was closed by the collaborator after giving solution as to run
 "apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y" this command.
But when I executed this command, It shows me two more errors while running chk_tools.
![Screenshot from 2020-06-02 17-59-54](https://user-images.githubusercontent.com/66197179/83670134-b0ee9e80-a5a0-11ea-80b9-86333748380a.png)

**Comment by peterpt** [comment]
write in terminal "dx --version" and show me the output .
My guess is that the problem is that first line that should not appear "Picked up java OPTIONS ....." .
However do what i told you and show me the output of it .

**Comment by peterpt** [comment]
Ok , delete that fatrat directory you have in your linux and clone again fatrat to your hard disk from github and everything will be fine .

**Comment by Kapil231** [comment]
I have already done it twice, removed the directory from the linux and cloned it again, but the problem remains the same...

**Comment by peterpt** [comment]
well if that doesn`t work for you then it will be better if you give up and dont use fatrat , because there is nothing else we can do .
In alternative you should try to fix that "picked up _java_options_" line when you execute any java script , google for the problem and fix it .

**Comment by Picadi0** [comment]
how did u fix the mingw problem
