### ISSUE TITLE
not installed shows (not ok) 

### ISSUE THREAD

**Issue by Blacking0007** [Screetsec/TheFatRat#501]
xterm-not ok
Mono-denvelop utils-not ok
gnome-terminal-not ok
jarsigner(default-jdk)-not ok
mingw-w64-not ok
mingw-32-not ok
backdoor-factory not ok

all this shows not ok and the  fatrat was not possible to install.

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/ISSUES.md
