### ISSUE TITLE
Fatrat backdoor doesn't ask any permissions while installing on android phone

### ISSUE THREAD

**Issue by Kapil231** [Screetsec/TheFatRat#502]
I created backdoor using fatrat but when i am installing it on my android device, it doesn't ask for any permissions and so i am not getting any reverse connection. 
I tried both options
 1) using backdoor 
 2) using old fatrat method.

**Comment by peterpt** [comment]
Apk back door is not 100% reliable .
Maybe you get more luck with an older version .
