### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by martinssssssss** [screetsec/TheFatRat#504]
How can I fix this issue? This happens when I try to install "TheFatRat"
 
![Screenshot 2020-06-08 10:13:52](https://user-images.githubusercontent.com/66221656/84040825-1b248c00-a971-11ea-8046-65f012fae516.png)

**Comment by peterpt** [comment]
1st run chk_tools in fatrat directory
2nd upload apt.log

**Comment by martinssssssss** [comment]
> 1st run chk_tools in fatrat directory
> 2nd upload apt.log

Can you show me exactly what it looks like with commands

**Comment by peterpt** [comment]
It is not any good installing scripts in linux without understanding the linux basic commands .
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md#if-nothing-works-

**Comment by martinssssssss** [comment]
> It is not any good installing scripts in linux without understanding the linux basic commands .
> https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md#if-nothing-works-

Thank you

**Comment by ayushontop** [comment]
Well, whats the issue ?

**Comment by ayushontop** [comment]
I think you should install the packages which shows "not ok " in front of it. If it doesn't work try to install pakafe manually
