### ISSUE TITLE
Issue Installing

### ISSUE THREAD

**Issue by Number91** [Screetsec/TheFatRat#506]
## Issue:

Unable to install the file _**"jarsigner (default-jdk)"**_

### Fat Rat Information

Version: 1.9.7

### Description of issue
Everything goes through, every single file says: **[  found  ]**.  Except jarsigner...   see what it does it as follows:

[  x  ] Jarsigner (java) -> not found  
[  !  ] Installing Java
[  x  ] Jarsigner

Please note: There were other files before and after that its just showing files pertaining to the issue.

and then: when it shows the page with the blue text, it says **_"Try this:"_** but it doesn't work :(

## Ending

Please help me solve this, I am new to Linux and very confused, it would mean a lot.

**Comment by peterpt** [comment]
run chk_tools script inside fatrat folder

**Comment by Number91** [comment]
> run chk_tools script inside fatrat folder

THANK YOU SO MUCH!!! YOU'RE GREAT!
