### ISSUE TITLE
I can't finish the installation because of "mingw-w64", "mingw-32"and, "jarsigner (default-jdk)" please help!

### ISSUE THREAD

**Issue by pullingteef** [screetsec/TheFatRat#510]
![image](https://user-images.githubusercontent.com/66924637/84617377-b602f600-ae9c-11ea-94f0-3e90543c2bb2.png)

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md#if-nothing-works-

**Comment by pullingteef** [comment]
Yea but there isn't any explanation.
