### ISSUE TITLE
Mingw32 and 64 not installing. Tried every method i've seen including ones on here

### ISSUE THREAD

**Issue by VectorO20** [Screetsec/TheFatRat#511]
Top two screenshots are error messages i get when i try running ./setup.sh and the third screenshot is what if get if i ignore the NOT OK error and run fatrat. I've tried to run chmod +x ./chk_tools && ./chk_tools but it still doesnt work, ive tried to change the repositories (see source list screenshot) and it still doesnt work. The problem started originally after i ran chmod +x ./chk_tools && ./chk_tools to try and fix an issue with jarsigner (initially the only thing that said NOT OK was jarsigner) and it recommended solutions for me to fix jarsigner AND ming 32 and 64 so i ran the solutions and jarsigner was fixed but then the issue with the mingw started and i havent been able to fix it since. 
 Any help would be appreciated, thanks.

![Annotation 2020-06-17 200500](https://user-images.githubusercontent.com/67118373/85053279-28702080-b192-11ea-9109-8e3c3f099d9d.png)

![Annotation 2020-06-17 200529](https://user-images.githubusercontent.com/67118373/85053238-1d1cf500-b192-11ea-9ef9-5f447950b24b.png)

![Annotation 2020-06-17 195907](https://user-images.githubusercontent.com/67118373/85053274-260dc680-b192-11ea-8b0b-1a71f1ff7b18.png)

![image](https://user-images.githubusercontent.com/67118373/85053535-90bf0200-b192-11ea-8d1c-b2ecf1e9d527.png)

**Comment by peterpt** [comment]
mingw is not installed from kali repositories , but from debian jessie .
