### ISSUE TITLE
Backdoored apk not working

### ISSUE THREAD

**Issue by Kapil231** [Screetsec/TheFatRat#513]
When i created a raw backdoor using msfvenom, it asks for permissions while installing on my android device and works well.
But when i use Backdoor original apk, FatRat successfully creates the backdoored apk, but while installing it on my device, it doesn't asks for any permissions and i am not getting any reverse connection. 
I tried this with multiple apps and with multiple port nos.

**Comment by peterpt** [comment]
backdoor apk does not work all the time .
fell free to clone the original script directly from the maintainer at https://github.com/dana-at-cp/backdoor-apk  and build your backdoor from there .

**Comment by brogamer2004** [comment]
Thanks for help

сб, 20 июн. 2020 г. в 10:57, peterpt <notifications@github.com>:
