### ISSUE TITLE
Binding to other files

### ISSUE THREAD

**Issue by Mehran** [Screetsec/TheFatRat#52]
Very nice project , would you please add file binder ? it Can combine out put with other file with 100% Fud ?

Thanks .

**Comment by peterpt** [comment]
Most of the open source binders are detected on antivirus , witch means that after you merge the 2 files into 1 , most of antivirus detect right away that there are 2 exe in one file , and bring up the alarm to user .
Anyway , if you (or anyone) find any good binder open source updated regularly then drop here the link for us to check it out .
If the binder works fine without issues and is not detected by every antivirus on the market , we will test it and probably add it to the next fatrat version .
