### ISSUE TITLE
pelase help me to solve it on Fatrat >>> GCC not ok

### ISSUE THREAD

**Issue by castile-kents** [Screetsec/TheFatRat#521]
term -> OK
Dns-Utils -> OK
Mono-Denvelop Utils -> OK
gcc -> Not OK
Apache2 -> OK
Gnome Terminal -> OK
UPX -> OK
Ruby -> OK

**Comment by peterpt** [comment]
you did not solve yet your problem because you didn`t look into troubleshoot file inside fatrat .
