### ISSUE TITLE
Few Packeges Are not getting installed on any kali version

### ISSUE THREAD

**Issue by HarhsKS** [Screetsec/TheFatRat#522]
The Error is :+1:   

> 
> xterm -> OK
> Dns-Utils -> OK
> Mono-Denvelop Utils -> Not OK
> GCC -> OK
> Apache2 -> OK
> gnome-terminal -> Not OK
> UPX -> OK
> Ruby -> OK
> Openssl -> OK
> jarsigner (default-jdk)-> Not OK
> Unzip -> OK
> Keytool -> OK
> mingw-w64 -> Not OK
> mingw-32 -> Not OK
> DX -> OK
> Aapt -> OK
> Apktool -> OK
> Baksmali -> OK
> Metasploit -> OK
> Backdoor-factory -> Not OK
> Searchsploit -> OK
> Was not possible to install The Packages Labeled (Not Ok) in this list above
> Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)
> before running fatrat setup script again

pls help i have tried all the solutions on all the Kali versions ......

**Comment by peterpt** [comment]
"Few Packeges Are not getting installed on any kali version"

Because you dont have any update repository configured in sources.list .

**Comment by HarhsKS** [comment]
> "Few Packeges Are not getting installed on any kali version"
> 
> Because you dont have any update repository configured in sources.list .

You are correct, Thanks it worked

**Comment by HarhsKS** [comment]
For who are still facing this, visit 
https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/
to find the latest version of kali repositories
