### ISSUE TITLE
Failed to locate smali file to hook

### ISSUE THREAD

**Issue by alexanderajju** [Screetsec/TheFatRat#523]
| OUTPUTNAME ||  The Filename output    || app_backdoor.apk
  | PAYLOAD    ||  Payload To Be Used     || android/meterpreter/reverse_tcp
  +------------++-------------------------++-----------------------+

          ________
         / ______ \
         || _  _ ||
         ||| || |||          AAAAAA   PPPPPPP   KKK  KKK
         |||_||_|||         AAA  AAA  PPP  PPP  KKK KKK
         || _  _o|| (o)     AAA  AAA  PPP  PPP  KKKKKK
         ||| || |||         AAAAAAAA  PPPPPPPP  KKK KKK
         |||_||_|||         AAA  AAA  PPP       KKK  KKK
         ||______||         AAA  AAA  PPP       KKK  KKK
        /__________\
________|__________|__________________________________________
       /____________\
       |____________|            Dana James Traversie

[*] Running backdoor-apk.sh v0.2.4a on Mon 06 Jul 2020 04:59:36 PM IST
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 2
[*] Decompiling original APK file...done.
[*] Locating smali file to hook in original project...done.
[!] Failed to locate smali file to hook

**Comment by bkstephen** [comment]
From what I saw from other replies, the apk backdoor is outdated and no longer works properly (?) as a temporary solution I made my own simple script to hide payloads in APK files here https://github.com/bkstephen/android_apk_and_payload_combiner

Feel free to use it.

**Comment by shadow1666** [comment]
The same Problem here ,anybody can help

**Comment by peterpt** [comment]
Delete your fatrat directory and clone again from github .
You will find in the new cloned directory apks that were tested .

**Comment by Riad015** [comment]
> The same Problem here ,anybody can help

Did you solve it?
