### ISSUE TITLE
[x] There was an error creating your FUD rat with Powerstage . TheFatRat

### ISSUE THREAD

**Issue by GRATIX12** [Screetsec/TheFatRat#524]
Hello,

I wanted to create a Rat with Fudwin on TheFatRat!
But after putting the icon that I wanted it displays the "LPORT" "LHOST" etc that I had put and then: "[x] There was an error creating your FUD rat with Powerstage." in red.

Unfortunately, I don't know where it came from!
Can you help me ?

Please.

**Comment by peterpt** [comment]
read the troubleshoot file .
