### ISSUE TITLE
[x]::[warning]:this script require apktool to work  [!]::Run setup.sh to install apktool

### ISSUE THREAD

**Issue by ahmaddax** [Screetsec/TheFatRat#528]
hi guys, so i'm new to this thing and i got an error out of blue and trying to figure this out.

[!]::[Check Dependencies]:
 [✔]::[Distro]: Kali
 [✔]::[Release]: kali-rolling
 [✔]::[Check User]: root
 [✔]::[Terminal]: local
 [✔]::[Internet Connection]: CONNECTED!
 [✔]::[Apache2 Server Kali ]: Installation found!
 [✔]::[Ruby]: Installation found!
 [x]::[warning]:this script require apktool to work

[!]::Run setup.sh to install apktool 

what should i do now?

**Comment by peterpt** [comment]
[!]::Run setup.sh to install apktool

**Comment by ahmaddax** [comment]
> [!]::Run setup.sh to install apktool

yeh this is the problem
 
i don't know what code to type.

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat#installation
