### ISSUE TITLE
Configuration file does not exists, run setup.sh first for config

### ISSUE THREAD

**Issue by zahir4322** [screetsec/TheFatRat#530]

**Comment by youremailaddress** [comment]
I‘ve met this issue too. For me that's because my system do not support "apt-get" or "apt-cache". So the shell cannot install libs that was needed, try "yum" or something else. Hope it do help.

**Comment by noni97** [comment]
fix it ? Configuration file does not exists, run setup.sh first for config .

**Comment by gowthamraju716** [comment]
What imwas the solution for it

**Comment by gowthamraju716** [comment]
What was the solution for it

**Comment by gowthamraju716** [comment]
> I‘ve met this issue too. For me that's because my system do not support "apt-get" or "apt-cache". So the shell cannot install libs that was needed, try "yum" or something else. Hope it do help.

How
