### ISSUE TITLE
Can't install mono

### ISSUE THREAD

**Issue by KrisCoder1** [screetsec/TheFatRat#535]
i cannot seem to install mono because it says it has not been found with apt-get install mono-devel and the other one. Does anybody have a solution?
Sorry, i can't remember the second mono name.

**Comment by vishweshravichandran** [comment]
check your sources.list  Repositories (/etc/apt/sources.list)

**Comment by KrisCoder1** [comment]
I’ve done that, but what do i have to so now? Im still new to Kali Linux

**Comment by KrisCoder1** [comment]
Nvm i got it, thanks for your comment though!

**Comment by mamria33** [comment]
> Nvm i got it, thanks for your comment though!

I have same issue, sorry i did not work out, shall I add? and add WHAT? in  /etc/apt/sources.list

**Comment by KrisCoder1** [comment]
Try running all of these commands

sudo apt install apt-transport-https dirmngr gnupg ca-certificates

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

echo "deb https://download.mono-project.com/repo/debian stable-buster main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list

sudo apt update

sudo apt install mono-devel

sudo apt install mono-complete

**Comment by peterpt** [comment]
your repositories should be empty , and that is the reason why you can not install mono-mcs & mono-devel 

mono-mcs exists in every debian repository and also in kali repository : 
https://packages.debian.org/search?keywords=mono-mcs
https://packages.debian.org/search?keywords=mono-devel
http://http.kali.org/kali/pool/main/m/mono/

Only people without any experience in linux come here speaking about installation issues , instead looking into how can they update their linux distribution .
