### ISSUE TITLE
Was not possible to install The Packages Labeled (Not Ok) in this list above

### ISSUE THREAD

**Issue by mamria33** [screetsec/TheFatRat#537]
Mono-Denvelop Utils -> Not OK                                                                                         
gnome-terminal -> Not OK                                                                                              
jarsigner (default-jdk)-> Not OK                                                                                      
mingw-w64 -> Not OK                                                                                                   
mingw-32 -> Not OK                                                                                                    
Backdoor-factory -> Not OK   

I have tried apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f Then run ./setup.sh again, but same issue is there!!

Any help, Please!

**Comment by peterpt** [comment]
navigate thru close issues and you will find your answer , we are not parrots to repeat everyday always the same thing .

**Comment by Morsmalleo** [comment]
if you are running a linux system try the following 


for Mingw-w64 all I did was the following

**kali@kali:~ sudo apt install mingw-w64**

and it installed, as for gnome terminal, jarsigner, I'm not to sure maybe try the following 

**kali@kali:~ sudo apt install gnome-terminal jarsigner**

as for Mingw-32 all I had to do was edit the **/etc/apt/sources.list** file and add the following lines

deb http://old.kali.org/kali sana main non-free contrib
deb-src http://old.kali.org/kali sana main non-free contrib

you can do this by typing the following into the terminal

**kali@kali:~ sudo nano /etc/apt/sources.list**

and you should have the following come up in your terminal
![FatRat fix 1](https://user-images.githubusercontent.com/64344168/100598448-ba955c80-32cc-11eb-94b1-a7db7d959367.png)


once this comes up use the arrow keys to scroll to the bottom underneath where it says **# Additional line for source packages**
and press Ctrl + Shift + V to paste the new sources into the sources.list file, or you can right click on click paste, its upto you, once you've done that it should look something like this 
![FatRat fix 2](https://user-images.githubusercontent.com/64344168/100598669-0e07aa80-32cd-11eb-9788-a9c641bc330d.png)

once you've done that press Ctrl + O to save the changes and then press Ctrl + X to exit
