### ISSUE TITLE
Failed to locate smali file to hook

### ISSUE THREAD

**Issue by devilmen80** [Screetsec/TheFatRat#539]
Hello I have this problem when try to execute backdoor original. 

Also if I try old method payload is injected but doesn'work on my Android phone.

I'm running javajdk 14. 

If I try with version 8 I get "failed to align apk" 

Solutions??

Thanks.

**Comment by the-zed-1998** [comment]
Me too have the same problem.
I tried this on a Flappy Bird v1.3 apk.

**Comment by devilmen80** [comment]
I spend lot of time...I think this program don't work...and stop. Problem is backdor-apk.
I try to download it and I got same result.
Now I resolved with a simply command of Msfvenom.
I get session of meterpreter for at least 5 minutes even if then session is stopped and therr is now way to go back.
Anyway msfvenom work big with injection . Regards

**Comment by peterpt** [comment]
Delete your fatrat directory and clone again from github .
You will find in the new cloned directory apks that were tested .
