### ISSUE TITLE
Payloads are getting detected by Windows Antivirus

### ISSUE THREAD

**Issue by jepunband** [screetsec/TheFatRat#540]
hello.. payloads are getting detected by windows anti virus. Is there a way to create FUD payloads?

thanks

**Comment by krishpranav** [comment]
Hi jepunband, 
there is an option for creating payload using veil on fatrat 
so please check it out

**Comment by ricko2991** [comment]
Hi, where exactly

**Comment by peterpt** [comment]
https://github.com/Veil-Framework/Veil
