### ISSUE TITLE
Option number 3 , needs to be updated.

### ISSUE THREAD

**Issue by jepunband** [Screetsec/TheFatRat#541]
hi, selecting option [3] does not give you the option to set platform and arch .. it auto-generates by itself.

[-] Generating Metasploit payload, please wait...

[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++     ]
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x86 from the payload

**Comment by peterpt** [comment]
Everything is fine because when you select the payload first it automatically detects what you need . This way msf will not output an error if selected arch was x86 and payload selection was for Linux .
