### ISSUE TITLE
mingw-w64 and mingw-32 Not Installes on Kali Linux (TheFatRat)

### ISSUE THREAD

**Issue by RubenAvMtz** [Screetsec/TheFatRat#542]
xterm -> OK                                                                
Dns-Utils -> OK                                                            
Mono-Denvelop Utils -> OK                                                  
GCC -> OK                                                                  
Apache2 -> OK                                                              
Gnome Terminal -> OK                                                       
UPX -> OK                                                                  
Ruby -> OK                                                                 
Openssl -> OK                                                              
Jarsigner -> OK                                                            
Unzip -> OK                                                                
Keytool -> OK                                                              
mingw-w64 -> Not OK                                                        
mingw-32 -> Not OK                                                         
DX -> OK                                                                   
Aapt -> OK                                                                 
Apktool -> OK                                                              
Baksmali -> OK                                                             
Metasploit -> OK                                                           
Backdoor-Factory -> OK                                                     
Searchsploit -> OK                                                         
Was not possible to install The Packages Labeled (Not Ok) in this list above                                                                          
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)                                                              
before running fatrat setup script again  

That is what FatRat shows, I've been searching for days for a way to install everything but I just can't install it, Can someone help me? Plz
(Sorry for my english, is not my native language)

**Comment by peterpt** [comment]
read troubleshoot and issues files
