### ISSUE TITLE
Problem when installing FatRat

### ISSUE THREAD

**Issue by V3x1Dev** [screetsec/TheFatRat#546]
When I run the setup and it starts to install I get this error message for certain tools:

 [ X ] Apache2 -> not found                                                             
 [ ! ]    Installing apache2                                                            
Warning: Tried to connect to session manager, Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed                                                                                       
 [ x ] Apache2                       

This is what I get when I run ./chk_tools : 
https://pastebin.com/QJ8HQ0Ey

**Comment by peterpt** [comment]
Make sure you have in your path environment this path /usr/local/sbin

**Comment by V3x1Dev** [comment]
I've added it to $PATH and reran the setup.sh, Apache2 still says fails and the warning messages still comes up, though the rest of the failed items have installed, but fatrat still doesn't work
---------------------------------------------
echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin
---------------------------------------------
chmod +x setup.sh && ./setup.sh
https://pastebin.com/PKp554v4
---------------------------------------------
./chk_tools
https://pastebin.com/FmDphQ5F
---------------------------------------------

**Comment by peterpt** [comment]
run in a terminal :
apt-get remove --purge apache2 && apt-get autoremove -y && apt-get install apache2

**Comment by brokeboy070** [comment]
Pls I need help, fatrat couldn't start😪
