### ISSUE TITLE
There was a problem copying your apk file to final destination 

### ISSUE THREAD

**Issue by tesfaa** [Screetsec/TheFatRat#547]
When I try to backdoor original apk it asks me for Lport and Lhost after I set two of them and enter the path of the apk it says there was a problem copying your apk file to final destination I am using backdoor version 1.9.7 please help

**Comment by peterpt** [comment]
there is a problem in the code , that is a bug .
If you run fatrat inside its directory then this problem will not happen .

**Comment by peterpt** [comment]
Delete your fatrat directory and clone again from github .
You will find in the new cloned directory apks that were tested .

**Comment by exkali77** [comment]
bende işe yaradı
