### ISSUE TITLE
run setup.sh

### ISSUE THREAD

**Issue by vjsaairam** [screetsec/TheFatRat#548]
when i open the fatrat it checks all the connectivity and finally shows apk tool is not available run setup.sh.......i done it many times but it doesnt shows anything......?

**Comment by peterpt** [comment]
read troubleshooting and issues file

**Comment by vjsaairam** [comment]
How to fix this..?

**Comment by V3rB0se** [comment]
> when i open the fatrat it checks all the connectivity and finally shows apk tool is not available run setup.sh.......i done it many times but it doesnt shows anything......?

same

**Comment by V3rB0se** [comment]
`uname -a`

> Linux kali 5.7.0-kali1-amd64 #1 SMP Debian 5.7.6-1kali2 (2020-07-01) x86_64 GNU/Linux

`apktool --version`

> Apktool v2.4.1 - a tool for reengineering Android apk files
> with smali v2.3.4 and baksmali v2.3.```
4


-- -- +=[(c) 2016-2017 | dracos-linux.org | Linuxsec.org | Hacker Indonesia 
-- -- +=[ Author: Screetsec < Edo Maland >  ]=+ -- -- 
 
 [!]::[Check Dependencies]:
 [✔]::[Distro]: Kali
 [✔]::[Release]: kali-rolling
 [✔]::[Check User]: root
 [✔]::[Terminal]: local
 [✔]::[Internet Connection]: CONNECTED!
 [✔]::[Apache2 Server Kali ]: Installation found!
 [✔]::[Ruby]: Installation found!
 [x]::[warning]:this script require apktool to work

[!]::Run setup.sh to install apktool

**Comment by REY-AKA-RJDJ0261** [comment]
U should use "apt-get dist-upgrade && apt-get update && apt-get upgrade && apt-get install -f"

**Comment by peterpt** [comment]
do like this :
- delete your fatrat folder
- remove apktool from /usr/local/sbin folder
- Clone fatrat again and run setup

My guess is that you previously installed fatrat in a different directory before and the apktool symlink inside /usr/local/sbin folder is pointing out to a different no existent directory of your previous fatrat installation .
