### ISSUE TITLE
[x] There was an error creating your FUD rat with Powerstager .

### ISSUE THREAD

**Issue by smatolt** [Screetsec/TheFatRat#549]
Things I tried : 
- cd tools && rm power.py && wget https://raw.githubusercontent.com/Screetsec/TheFatRat/master/tools/power.py && chmod +x power.py
- pip install names
- apt-get install python3 python3-setuptools binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 gcc-mingw-w64-i686 gcc-mingw-w64-x86-64
It still dont work.
Need Help !

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md
https://github.com/Screetsec/TheFatRat/blob/master/ISSUES.md

These 2 files exist just for people like you .
They will give you an idea on where is the issue and how to make sure .
and if you run chktools inside fatrat then it will say what is good and what is wrong .

**Comment by smatolt** [comment]
Ok thank you ill try it out !
