### ISSUE TITLE
When I try to install FatRat, The setup file is not installing some tools...

### ISSUE THREAD

**Issue by Miguel3112M** [screetsec/TheFatRat#550]
The setup file is not installing mingw32, mingw64, jarsgniger, and apktools...but when i run it say me that i doesn't have apktools and said me to run the setup script another time...i tried running the setup script for 7 times...but it did not install those tools....I`m including the log files too....please help me as soon as possible....[
[apt.log](https://github.com/Screetsec/TheFatRat/files/5303818/apt.log)
[install.log](https://github.com/Screetsec/TheFatRat/files/5303819/install.log)

](url)

**Comment by mickiticki** [comment]
I have the same issue

**Comment by REY-AKA-RJDJ0261** [comment]
Bro if it's resulting in error try "apt-get install -f" and try again and tell me results

**Comment by peterpt** [comment]
looks like python-pip and mingw32 are missing .
apt-get install python-pip should solve one issue .
mingw the chktools script tells you what to do to fix it .

**Comment by mickiticki** [comment]
The way i resolve it: 
`
sudo apt-get update

sudo apt-get install openjdk-11-jdk

sudo apt-get install -y mingw-w64

sudo apt-get install apktool

`

**Comment by peterpt** [comment]
`The way i resolve it:`

No it is not .

**Comment by Forbesgriffin** [comment]
> The setup file is not installing mingw32, mingw64, jarsgniger, and apktools...but when i run it say me that i doesn't have apktools and said me to run the setup script another time...i tried running the setup script for 7 times...but it did not install those tools....I`m including the log files too....please help me as soon as possible....[
> [apt.log](https://github.com/Screetsec/TheFatRat/files/5303818/apt.log)
> [install.log](https://github.com/Screetsec/TheFatRat/files/5303819/install.log)
> 
> ](url)

I've the same issue

**Comment by mickiticki** [comment]
> 
> 
> `The way i resolve it:`
> 
> No it is not .

Works for me

**Comment by Forbesgriffin** [comment]
> > `The way i resolve it:`
> > No it is not .
> 
> Works for me

I tried using your solution but all I got was 

Unable to locate package .......

**Comment by peterpt** [comment]
you will have to add jessie repository to your sources.list to solve mingw32 problem
kali does not install mingw32 anymore , troubleshoot and issues files explain that , but it is more easier to create an issue that was already solved more than 10 times here .
If you look into closed issues you will find your solution .

**Comment by reyaansh0261** [comment]
Guys Wait
Stop Adding Different OS repositories

**Comment by reyaansh0261** [comment]
> > > `The way i resolve it:`
> > > No it is not .
> > 
> > 
> > Works for me
> 
> I tried using your solution but all I got was
> 
> Unable to locate package .......

Your Repositories are Broken And You Need to move to main branch of the os!!!!

**Comment by brokeboy070** [comment]
> you will have to add jessie repository to your sources.list to solve mingw32 problem kali does not install mingw32 anymore , troubleshoot and issues files explain that , but it is more easier to create an issue that was already solved more than 10 times here . If you look into closed issues you will find your solution .

I have added it what is next sir
![Screenshot_20211204-061442](https://user-images.githubusercontent.com/94995263/144698186-f7990c84-6fd8-49b2-a6c9-68749376a221.png)
