### ISSUE TITLE
Script not working after successful install

### ISSUE THREAD

**Issue by trjom1010** [screetsec/TheFatRat#551]
Kali 5.8 from official website
User - root
TheFatRat - 1.9.7
Metasploit - 5.0.101

All packages are installed correctly according to chk_tools. All dependencies check out when loading.

Options 1-9 don't have any effect. The screen blinks after pressing enter.

This happens in gnome-terminal as well as xterm.

There are no logs regarding this error in /logs/ (msploit.log and fudwin.log are missing)

**Comment by REY-AKA-RJDJ0261** [comment]
Try to send "dmesg" logs (after trying it again) and I have a question did u force shutdown the system while using it from the power button??? If yes you need to reinstall the os it corrupts the files never power shutdown any linux os!!!

**Comment by REY-AKA-RJDJ0261** [comment]
U can try "apt-get install -f"

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md
https://github.com/Screetsec/TheFatRat/blob/master/ISSUES.md

Without the logs and just with your nice chat we are unable to reproduce your error , we are not clairvoyants to guess , that is not a common error except if you are like many using a mobile device .
