### ISSUE TITLE
Fatrat says its outputing into /root/fatrat_generated/

### ISSUE THREAD

**Issue by TheMakeAWishKid** [Screetsec/TheFatRat#556]
fat rat is saying that for example a simple msfvenom file is created for windows(this happens for all backdoors/payloads) it says the file was created correctly and put into the file but in fact the folder is empty! after attempting to see if it was being placed into the wrong folder the file didnt even exist on my system?

**Comment by ricko2991** [comment]
Do not put the TheFatRat folder in a folder that contains spaces eg "**fatrat folder**". This will make it difficult for fatrat to find the path.

**Comment by TheMakeAWishKid** [comment]
should i remove it? as of right now this is the fatrat path
![Screenshot from 2020-10-14 09-41-08](https://user-images.githubusercontent.com/59181568/96012577-7a077f80-0e01-11eb-84a2-8a241fe27b2a.png)

**Comment by TheMakeAWishKid** [comment]
![Screenshot from 2020-10-14 09-42-37](https://user-images.githubusercontent.com/59181568/96012694-9c999880-0e01-11eb-88c7-f54a72faf527.png)
this is where the files are supposed to be landing but there is never and actual output of the file

**Comment by ricko2991** [comment]
What os u use?

**Comment by kanishkcs** [comment]
Sorry??

Did I sended Any Mail ? Regarding Fatrat?

Coz i didnt understand what are u asking

**Comment by ricko2991** [comment]
Ok. Done.

Pada tanggal Kam, 15 Okt 2020 7.39 AM, kanishk kashyap <
notifications@github.com> menulis:

> Sorry??
>
> Did I sended Any Mail ? Regarding Fatrat?
>
> Coz i didnt understand what are u asking
>

**Comment by Hedi-M-Sharif** [comment]
I have same issue.
OS: Kali Linux
Version: 2020.4
* There's no space in the path.

**Comment by Uxtral** [comment]
Hi , I have the same problem, I work on kali linux and the program saved in fatrat_generated in home or in root but all is empty , the program never saved nothing please I need some answers..

**Comment by peterpt** [comment]
Delete your fatrat directory and clone again from github .
You will find in the new cloned directory apks that were tested .

**Comment by furkan9ne** [comment]
hello i don't have output file what can i do?

**Comment by Darkprincie** [comment]
how can i change the folder were my fatrat saves back doors IN KALI
