### ISSUE TITLE
Backdoor Apk not working 

### ISSUE THREAD

**Issue by Forbesgriffin** [Screetsec/TheFatRat#557]
Backdoor apk isn't opening, it automatically force stops when launching. Normal payload generated works normal but backdoored apk doesn't _Bind failed address already in use......_ 

- P.S ,I'm connected to the same network as the victim 

> Running kali on VirtualBox

> Network type : Bridged

**Comment by peterpt** [comment]
"Bind failed address already in use"
you can not execute 2 same backdoors on a single device because as soon as you execute the first one it will open a tcp port and then the 2nd is unable to open the same tcp port because  that port was already opened by the first backdoor .
Same thing applies to metasploit listeners , you can not set 2 sessions of metasploit listening on same tcp port .

**Comment by Forbesgriffin** [comment]
> "Bind failed address already in use"
> you can not execute 2 same backdoors on a single device because as soon as you execute the first one it will open a tcp port and then the 2nd is unable to open the same tcp port because that port was already opened by the first backdoor .
> Same thing applies to metasploit listeners , you can not set 2 sessions of metasploit listening on same tcp port .

When I executed my saved listener, it started a reverse TCP but no sessions were created. So, i tried typing _run_ again, that's when it showed **Bind failed address already in use**. Also, my backdoor apk also crashes on start. 

- P.S raw payload generated works fine but backdoor-ed apk doesn't 

If I may ask, is there any way to launch the backdoor-ed apk without it crashing on start because I think that's why a session couldn't be created.

**Comment by peterpt** [comment]
backdoor apk is created with a tool outside metasploit framework , sometimes work and others times not .
 try using the original script at https://github.com/dana-at-cp/backdoor-apk
if it still does not work then there is nothing we can do .

**Comment by Forbesgriffin** [comment]
@peterpt Ok, quick question tho. My meterpreter sessions dies on opening. If i may ask, is there any way to make it stable XD 

-Android version 9

**Comment by peterpt** [comment]
Never happened to me , try a different payload , use only reverse payloads

**Comment by Forbesgriffin** [comment]
> Never happened to me , try a different payload , use only reverse payloads
I did xD didn't work, still got the same thing. I'ma close this issue now
