### ISSUE TITLE
Please help!! 

### ISSUE THREAD

**Issue by cutiemn** [screetsec/TheFatRat#558]
I am completely new at all of this! First time using kali linux and fatrat. I keep getting these things listed as not ok. Please help. 
![fatrat](https://user-images.githubusercontent.com/73140472/96510958-f47e3800-1223-11eb-886c-adfebace023f.PNG)

**Comment by peterpt** [comment]
run chk_tools inside fatrat folder

**Comment by Krook9d** [comment]
same issue for mingw here, even with the jessie repo

**Comment by peterpt** [comment]
`same issue for mingw here, even with the jessie repo`

You must remove and purge your current mingw installation and then install mingw from jessie repository , best way is to add an "#" behind each repository that is not debian jessie and leave only jessie repository in sources.list .
then 
apt-get clean && apt-get clean cache && apt-get update

then only after this point you are able to install correctly mingw from jessie repository .

**Comment by hackingwhangjuncomputer** [comment]
I get the same error in the same environment!!!!!!!!!!!!
