### ISSUE TITLE
can't find app_backdoor.apk

### ISSUE THREAD

**Issue by jalelab** [Screetsec/TheFatRat#559]
Your RAT apk was successfully builded and signed , it is located here :
 ~/Fatrat_Generated/app_backdoor.apk
but i can't find it

**Comment by ananth3156** [comment]
> Your RAT apk was successfully builded and signed , it is located here :
> ~/Fatrat_Generated/app_backdoor.apk
> but i can't find it

bro it will in root folder...USe the command sudo -i enter root and locate the folder i am damn sure about it

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md#how-to-access-root-folder-on-kali-202021

**Comment by moraesnicol** [comment]
find ~/Fatrat_Generated
