### ISSUE TITLE
Nochange in meterpreter session after installing payload apk

### ISSUE THREAD

**Issue by ananth3156** [Screetsec/TheFatRat#560]
i generated a payload apk and opened metaspoilt for listening.It tells starting tcp some thing.by next i installed the apk and also opened it but no changes .there were no sessions opened and i am damn sure i done everything right like setting up the LHOST,PAYLOAD and LPORT.Also in my virtual machine i enabled brigded adapater too also tried in NAT but no changes.help me to prosper

**Comment by peterpt** [comment]
make sure your android device is connected to the same network subnet where your metasploit listener is running .

**Comment by ananth3156** [comment]
both are connected to same wifi...But its is of no use right..if i need to send the apk to some one they maybe far away from use..i think connections may not the be problem

**Comment by kanishkcs** [comment]
ananth Use port forwading .

**Comment by peterpt** [comment]
if the metasploit listener is not running on your public ip then it is not possible for the backdoor to connect to your local lan ip address .
I already explained that here before , you just dont want to give the trouble to read closed issues .
