### ISSUE TITLE
jarsigner nor installing

### ISSUE THREAD

**Issue by pleasehelpm3** [Screetsec/TheFatRat#561]
when i am running the setup only jarsigner is not getting installed , tell me how  to manually install itt
please anyone

**Comment by kanishkcs** [comment]
install open jdk ,go on official website and u can install it from there

**Comment by peterpt** [comment]
apt-get install default-jdk default-jre

**Comment by Electro-Hacker** [comment]
thank you @peterpt 
It worked

**Comment by Morsmalleo** [comment]
Close this issue as it has been resolved
