### ISSUE TITLE
Configuration file does not exists, run setup.sh first for config

### ISSUE THREAD

**Issue by Ar3ry** [screetsec/TheFatRat#563]
Whenever I run fatrat it throws me this error -"Configuration file does not exists, run setup.sh first for config"

Help me fix this.My logs are -

[apt.log](https://github.com/Screetsec/TheFatRat/files/5540362/apt.log)

[install.log](https://github.com/Screetsec/TheFatRat/files/5540363/install.log)
[setup.log](https://github.com/Screetsec/TheFatRat/files/5540364/setup.log)

Note:I've installed jdk,mingw

**Comment by kanishkcs** [comment]
go to Your Fatrat Download folder
and
Run
install.sh

file again

**Comment by peterpt** [comment]
mingw32 can only be installed with jessie repositories
if you run chk_tools inside fatrat folder it will say where is the problem
