### ISSUE TITLE
required packages are not installed

### ISSUE THREAD

**Issue by Mcalle25** [screetsec/TheFatRat#565]
when I run the command "./setup.sh" the necessary packages are not installed, such as apktool, mingw32, mingw64, python2-dev and if I try to install it by my own will, I get an error saying that the version of the package  It's incorrect

**Comment by fabinho347** [comment]
yes moi aussi ça me met la même chose apktool j'ai reussit a regler le probleme en installant

**Comment by Morsmalleo** [comment]
try adding these to your sources.list file in /etc/apt, I did this and it worked for me, however some of the packages i had to install via **sudo apt install**

add these lines to the **# Additional line for source packages** you can do this with the following 

**sudo nano /etc/apt/sources.list**

once you've done that the following below should pop up in the terminal

![Fat Rat fix 1](https://user-images.githubusercontent.com/64344168/100709322-e0c60580-337b-11eb-9b8d-3994c8264d2a.png)

once this open copy and paste these lines below this sentence like shown in the screenshot below

deb http://ftp.us.debian.org/debian stretch main         
deb http://security.debian.org/debian-security stretch/updates main
deb http://old.kali.org/kali sana main non-free contrib
deb-src http://old.kali.org/kali sana main non-free contrib

![Fat Rat fix 2](https://user-images.githubusercontent.com/64344168/100709365-f89d8980-337b-11eb-9420-832389b8880f.png)


after you've done that just simply 

**sudo apt update && sudo apt dist-upgrade && install mingw32 mingw-64 python2-dev default-jdk apktool**

and you should be fine

**Comment by Morsmalleo** [comment]
`Sudo apt-get install apktool` to fix the Apktool problem

To fix the mingw problem, Add this to your sources.list file to install mingw32 and mingw-w64

`Deb http://ftp.debian.org/debian Jessie main contrib non- free` 

Only the Jessie repo installs the correct versions of mingw
Which I believe they are 4.9.1 and 8.0.0

As for python-dev do the following 

`sudo apt install aptitude`

`sudo aptitude install libpython-stdlib`
`sudo aptitude install libpython2.7` (type n then hit enter when prompted, then type y then hit enter when prompted again)

`sudo aptitude install python-dev`

**Comment by fabinho347** [comment]
Bonjour j’ai un problème je n’arrive pas à créer un payload sa m’affiche se message d’erreur [cid:D15DF50A-4890-4AA9-8DC0-4622D6BFF932-L0-001]

Envoyé de mon iPhone

Le 6 janv. 2021 à 04:11, Morsmalleo <notifications@github.com> a écrit :

﻿

Sudo apt-get install apktool to fix the Apktool problem

To fix the mingw problem, Add this to your sources.list file to install mingw32 and mingw-w64

Deb http://ftp.debian.org/debian Jessie main contrib non- free

Only the Jessie repo installs the correct versions of mingw
Which I believe they are 4.9.1 and 8.0.0

As for python-dev do the following

sudo apt install aptitude

sudo aptitude install libpython-stdlib
sudo aptitude install libpython2.7 (type n then hit enter when prompted, then type y then hit enter when prompted again)

sudo aptitude install python-dev

**Comment by peterpt** [comment]
dont install apktool via apt-get because fatrat looks for a specific version and it does not matter if it is installed or not , apktool is inside fatrat/tools folder .

**Comment by Morsmalleo** [comment]
> dont install apktool via apt-get because fatrat looks for a specific version and it does not matter if it is installed or not , apktool is inside fatrat/tools folder 

Yeah was just about to post what you said there, because I forgot to add it to my comment, my apologies
