### ISSUE TITLE
fatrat command not found 

### ISSUE THREAD

**Issue by sassafras420** [screetsec/TheFatRat#569]
fatrat command not found after successful install

**Comment by peterpt** [comment]
your path environment must include this path : /usr/local/sbin

on terminal if you write :
cd /usr/local/sbin && fatrat

 it will run 
unless you deleted the original directory from where it was installed .

**Comment by Hack19** [comment]
no my friend doesnt work

**Comment by Hack19** [comment]
the only tutorial that works for me
https://www.youtube.com/watch?v=NqcsJZNWpiE

**Comment by khannavaish** [comment]
Fat Rat isnt working after successful installation

**Comment by khannavaish** [comment]
Error : Command not found
