### ISSUE TITLE
The payload is detectable

### ISSUE THREAD

**Issue by zisis912** [screetsec/TheFatRat#573]
I tried making a fud backdoor with PwnWinds, then picked 1 for bat file + powershell, but when i run the powershell script on my windows machine, it says that it is malicious and has been blocked from running. The only av i have is windows defender, which i have set to make an exception on the entire C:/ drive because it annoys me. 
![image](https://user-images.githubusercontent.com/65046191/101239976-bb772580-36f4-11eb-82e0-80f27b8e23c9.png)
Also, I know this has nothing to do with fatrat, but when i try to use a port under 1024 msfconsole says permission denied, even if I have done sudo msfconsole, so if anyone knows a way to set the port to 80 tell me

**Comment by peterpt** [comment]
meterpreter/reversehttp = port80 or 8080
meterpreter/reversehttps = port 443 or 8443

**Comment by zisis912** [comment]
oh ok, but can you help me with my actual problem?

**Comment by peterpt** [comment]
no , you can thank all other users from before for your payload be detected .
It looks that even if we create a banner in the tool to not upload the backdoors to virus total , many users from before did just that just to see if they were detected .
After that point virus total was able to analyze the mutex of the backdoors created by fatrat and add them to their database witch is also shared with many other antivirus platforms .

**Comment by WongWai95** [comment]
Yes, it is inevitable.
Thx for yr repository anyway.

**Comment by Morsmalleo** [comment]
@peterpt I have tested the payloads built with Powerstager, and Windows 10 virus protection doesn't detect it, so there's a bit of positive for TheFatRat being completely FUD, still yet to test payloads built with PwnWinds

**Comment by robin113x** [comment]
use own python tools for creating payloads or use veil evsions payloads..
