### ISSUE TITLE
Problem Installing the tool.

### ISSUE THREAD

**Issue by EbotRawley** [screetsec/TheFatRat#576]
**My command :**
~ $ git clone https://github.com/Screetsec/TheFatRat.git

**Respond :**

Cloning into 'TheFatRat'...
fatal: unable to access 'https://github.com/Screetsec/TheFatRat.git/': OpenSSL SSL_connect: Connection reset by peer in connection to github.com:443

Please what can I do to proceed??

**Comment by Morsmalleo** [comment]
this might help you 

https://stackoverflow.com/questions/18356502/github-failed-to-connect-to-github-443-windows-failed-to-connect-to-github

**Comment by CaptainNemo-it** [comment]
have you a static ip on your machine ? if yes this is the problem
