### ISSUE TITLE
NOT AN ISSUE! Just a Workarounds guide on problems with tools installing for TheFatRat after running ./setup.sh

### ISSUE THREAD

**Issue by Morsmalleo** [Screetsec/TheFatRat#578]
**TheFatRat Installation & Workarounds guide**

**DISCLAIMER:** These Workarounds have only been tested on Kali Linux 2020.4 for Virtualbox

**Follow the steps below to install TheFatRat**
⦁	git clone https://github.com/Screetsec/TheFatRat
⦁	cd TheFatRat
⦁	chmod +x setup.sh
⦁	chmod +x chk_tools
⦁	sudo ./setup.sh 

**The following packages will fail to install** 
⦁	Jarsigner
⦁	Mingw-32
⦁	Mingw-64
⦁	lib32z1
⦁	lib32ncurses5
⦁	Python-dev
⦁	Python-pip

**Follow the below fixes to install the packages that didn't/won't install in the FatRat Setup**

**Jarsigner Fix** 
To install Jarsigner, follow the below steps and make sure your Kali repo is **ACTIVE** in your sources.list file and any other repo you have is **INACTIVE** by making sure they have been marked with a #

⦁	sudo apt-get update 
⦁	sudo apt-get install default-jdk default-jre

**lib32z1 Fix**
⦁	sudo apt-get install lib32z1

**Python-pip Fix**
To install python-pip you can simply install python3-pip
⦁	sudo apt-get install python3-pip

**Mingw32 & Mingw-w64 fix**
To install the correct versions of *mingw* (4.9.1 + 3.2.0) follow the below steps

⦁	add this line to your sources.list file 

`deb http://ftp.debian.org/debian Jessie main contrib non-free`

⦁	deactivate your Kali repo's as well as any other repo you have by marking it with a # next to where it reads "deb/deb-src" 
        leaving only the Jessie repo active, then save the changes

⦁	sudo apt-get update 
⦁	sudo apt-get install mingw32 mingw-w64

**Python-dev Fix**
To install Python-dev for TheFatRat follow the below steps and make sure the Jessie repo in your sources.list file is **ACTIVE** and any other repo you have is **INACTIVE** by making sure they have been marked with a # next to where it reads "deb/deb-src"

⦁	sudo apt-get install aptitude 
⦁	sudo aptitude install python-dev ( when prompted, type `n` then hit `Enter` key, then when prompted a second time, type `y`    then hit the `Enter` key

⦁	sudo apt-get install python-dev (it should already have been installed by **Aptitude** this is just to confirm it has been installed)

**Lib32ncurses5 fix**
To install lib32ncurses5 for TheFatRat follow the below steps and make sure that the Jessie repo in your sources.list file is **ACTIVE** and any other repo you have is **INACTIVE** by making sure they have been marked with a #. libncurses5 works in replacement of lib32ncurses5 but we will install lib32ncurses5 just to make sure everything runs properly
⦁	sudo apt-get update 
⦁	sudo apt-get install libncurses5
                                                                                                                                                

**You can follow the final fix below to be able to launch TheFatRat from your Whisker Applications Menu or your Desktop**

**HOW TO LAUNCH FATRAT FROM THE WHISKER MENU & FROM YOUR DESKTOP**
Once everything is installed and working properly, you can now edit the application launcher that was automatically installed to /usr/share/applications/ during TheFatRat setup, to launch fatrat from the Whisker Applications Menu. 

**To do this just follow the steps below;**
⦁	Click on the Whisker Menu located in the top left-hand corner of the screen
⦁	In the search box type "TheFatRat"
⦁	Right click "TheFatRat" application 
⦁	Click on "Edit Application"

A small window for editing the application will then pop up, once this has appeared there will be 4 boxes available to type in, 
They are labelled as such 
~ Name
~ Comment
~ Command
~ Working Directory 

**There will also be 2 check-boxes and an Icon box, check boxes are labelled with a *
- **Icon**
- **OPTIONS:**  * Use Startup notification 
                          * Run in terinal

**In the Command box, remove the current command that is present, and then copy and paste one of the following command shown below.**

 gnome-terminal -t "TheFatRat 1.9.7" --geometry=600x630 -e "sudo fatrat"
 gnome-terminal -t "TheFatRat 1.9.7" -e "sudo fatrat"

**Then uncheck the "Run in terminal" box, leave everything else alone, and click save** 
Then Open the Whisker applications menu, type FatRat and click on the launcher, FatRat will now launch from the applications Menu and from your desktop.

NOTE: If anyone has any other errors with tools for TheFatRat not installing after running ./setup.sh multiple times, let me know and I will find a fix and add it to this fix list

**Comment by peterpt** [comment]
You see , that will not fix the problem because if you look into the code here at line 522 : 
https://github.com/Screetsec/TheFatRat/blob/master/setup.sh

We already added the jessie repository , the problem is that user already have a more recent version installed and it needs to uninstalled to install this one from jessie .
But then you will have a new problem ahead , witch is when user returns to his original repositories and after doing apt-get upgrade , i will update that mingw version needed for fatrat , and then they will come here again posting an issue because it was updated and they did not notice , that point is when they tell that they are unable to create a backdoor with fudwin .
The best way to solve this is to remove fudwin from fatrat , this way it will avoid all problems with mingw .
Only noobs without any knowledge in linux come here with issues about installing packages , by default those people who installed kali and think they are already an hacker , and they want to make a backdoor to infect someone they know just to prove they are hackers . This tool was not made with those purposes .

**Comment by Morsmalleo** [comment]
> You see , that will not fix the problem because if you look into the code here at line 522 :
> https://github.com/Screetsec/TheFatRat/blob/master/setup.sh
> 
> We already added the jessie repository , the problem is that user already have a more recent version installed and it needs to uninstalled to install this one from jessie .
> But then you will have a new problem ahead , witch is when user returns to his original repositories and after doing apt-get upgrade , i will update that mingw version needed for fatrat , and then they will come here again posting an issue because it was updated and they did not notice , that point is when they tell that they are unable to create a backdoor with fudwin .
> The best way to solve this is to remove fudwin from fatrat , this way it will avoid all problems with mingw .
> Only noobs without any knowledge in linux come here with issues about installing packages , by default those people who installed kali and think they are already an hacker , and they want to make a backdoor to infect someone they know just to prove they are hackers . This tool was not made with those purposes .

Do you know what, that was the one thing I never tried, was purging mingw completely from my Kali, and running ./setup.sh, omg you'd think with my all my knowledge of Kali I would've tried that, but nope I didn't, yes I already knew that the Debian Jessie repository was included in the setup of TheFatRat however it just skipping the installation of mingw32 and mingw-w64, which now obviously because of more up to date version of *mingw*, my apologies on that part!  Yes I see on here a lot of people, creating issues with installing packages when running `./setup.sh` I thought there was a bug skipping the installation of some packages such as *mingw* but obviously not, I mean the fixes above have worked for me 100%, but now I know why the installation of *mingw* so thank you very much @peterpt for pointing that out. Yes I also see a lot of people running an `apt-get upgrade -y` after the correct versions of mingw has installed and then coming here to post an issue about it, I have stated in other issues on here that the correct versions of *mingw* are (correct me if I'm wrong) 4.9.1 & 8.0.0, for me I managed to stop the upgrade of *mingw* and python-dev by holding the packages back by running the command `sudo apt-mark hold *mingw*`*python-dev.

The fixes above but as you noted they are not really fixes as the Debian Jessie repository is already included with TheFatRat setup. However now I am hoping that people that see this won't post anymore stupid issues

**Comment by Morsmalleo** [comment]
I have run ./setup.sh without any versions of mingw installed and it just keeps skipping the installation, everytime, I have run `sudo apt-get remove --purge *mingw* && sudo apt-get autoremove -y` multiple times but TheFatRat just skips the installation process of *mingw* altogether, so therefore I had to add the Jessie repository to my sources.list and install mingw via `sudo apt-get install *mingw* I will post photos below so you know what I mean

**Comment by Morsmalleo** [comment]
Ok @peterpt as you can see in the screenshots, I have no installations of *mingw* at all, I purged *mingw* from my Kali completely and took the screenshots to show you what happens when TheFatRat tries to install *mingw*.

 As you can see from the 2 screenshots below, I have no mingw installation at all, 
![TheFatRat *mingw* installation skip problem ](https://user-images.githubusercontent.com/64344168/103850703-febb1000-5075-11eb-8545-00fc2c150980.png)
![TheFatRat *mingw* installation skip problem 2](https://user-images.githubusercontent.com/64344168/103851100-ebf50b00-5076-11eb-97c4-130955b09a75.png)

this is what happens with *mingw* during TheFatRat setup (./setup.sh)
![Mingw installation skipped](https://user-images.githubusercontent.com/64344168/103851168-15ae3200-5077-11eb-9630-7c75bfc2927c.png)
![MINGW SKIPED ](https://user-images.githubusercontent.com/64344168/103851180-1d6dd680-5077-11eb-8940-56e1352b586b.png)

as you can see it completely skips the installation of *mingw* altogether, no matter how many times you run `sudo apt-get remove --purge *mingw* && sudo apt-get autoremove -y` and no matter how many times you run `sudo ./setup.sh` it just keeps on skipping the installation of *mingw* altogether, hence why I posted these fixes above, because they seem to be the only thing that fixes these problems

**Comment by peterpt** [comment]
just to prove you are wrong about mingw , and at same time how to prevent mingw updates to avoid issues in fudwin option in fatrat .

I made this video specifically for you , but thanks for helping others around here .

https://www.youtube.com/watch?v=J5cf1_csR10

**Comment by Morsmalleo** [comment]
This should explain the problem I am having with mingw being skipped everytime I run setup.sh insideTheFatRat folder 
the only way I can get around this is by adding the debian jessie repo to my sources.list and installing mingw32 and mingw-w64 from the terminal with `apt-get install mingw32 mingw-w64` and then stopping any upgrades for them by typing in my terminal `sudo apt-mark hold *mingw`

https://user-images.githubusercontent.com/64344168/104539723-18b3a000-55ec-11eb-9e14-409a1f73bbf5.mp4

**Comment by peterpt** [comment]
inside fatrat folder over a terminal write these commands : 
rm setup.sh && wget https://github.com/Screetsec/TheFatRat/blob/master/setup.sh && chmod +x setup.sh && ./setup.sh

and let me know if the problem continues .

**Comment by Morsmalleo** [comment]
Problem with the new `setup.sh` file, ran the commands you told me to, multiple times just to confirm, I keep getting the error,
`./setup.sh: 8: Syntax error: newline unexpected`

Screenshot below

![Not Working](https://user-images.githubusercontent.com/64344168/104796617-c27a6480-5785-11eb-8e64-ec49f1f51eef.png)

**Comment by peterpt** [comment]
oopppss , my bad .
use this link instead with wget command : 
https://raw.githubusercontent.com/Screetsec/TheFatRat/master/setup.sh

**Comment by peterpt** [comment]
if you do this after i wrote this message then check in logs folder inside fatrat and upload here the file aptdebug.log if you still have the same issue installing mingw from jessie repository

**Comment by Morsmalleo** [comment]
Problem with Mingw-w64 and Mingw-32 being skipped during the setup of TheFatRat is still persisting, along with the same packages listed in my workarounds above, still being skipped as well. The same problem for the packages `Mingw32, Mingw-w64, Jarsigner, Python-dev, Python-pip & lib32z1` all being skipped during setup, still persists. 
Screenshot below for more details

screenshot was taken after running the following commands in a terminal over TheFatRat folder 
`sudo rm setup.sh && sudo wget https://raw.githubusercontent.com/Screetsec/TheFatRat/master/setup.sh && sudo chmod +x setup.sh && sudo ./setup.sh`

![Still not working with the same packages](https://user-images.githubusercontent.com/64344168/104829976-99baa380-5847-11eb-95ef-ad531b679fa9.png)

**Comment by peterpt** [comment]
ok , it looks that default-jdk & jre must be installed using kali and not jessie repository , this is easy to fix in setup .
I need to make some changes in setup.sh to know if mingw is hanged by the java installation .
I will let you know when i do them .

**Comment by Morsmalleo** [comment]
> ok , it looks that default-jdk & jre must be installed using kali and not jessie repository , this is easy to fix in setup .
> I need to make some changes in setup.sh to know if mingw is hanged by the java installation .
> I will let you know when i do them .

Ok no problem, also we have the same problem with Powerstager, it tells me there no module named "names" when ive run `pip install names` & `sudo pip install names` I've even tried `pip3 install names` and `sudo pip3 install names` but it keeps telling me that its not installed, however when I run `python3 power.py` inside the "Tools" folder of FatRat it works, but when running `python power.py` even with sudo, it tells me there is no module named "names" installed but there is, I've run `pip uninstall names && sudo pip uninstall names && pip install names && sudo pip install names` numerous times now, I think powerstager only works with python3 but I could be wrong

**Comment by Morsmalleo** [comment]
@peterpt Issue with mingw being skipped during installation even after the Jessie debug you added to setup.sh

**Comment by peterpt** [comment]
I already made the changes here (my computer) in setup but i did not yet had time to upload it to github , right now i am on windows , when i boot into linux i will upload the file .
Best luck will be next weekend , lots of stuff to do here .

**Comment by peterpt** [comment]
i already uploaded the new setup script , make sure you download the new version before executing it .
This version will only install mingw from jessie repo , all other packages are or from original repositories or from kali .

**Comment by Morsmalleo** [comment]
@peterpt I will test it and get back to you, haven't had a lot of time to test the new setup.sh, but will let you know the outcome as soon as I have

**Comment by Morsmalleo** [comment]
@peterpt mingw32 and mingw-w64 skip with Kali Linux is still present, it does however install default-jdk for me now but the skip happening with mingw32 and mingw-w64 is still present

**Comment by peterpt** [comment]
i need the aptdebug.log

**Comment by Morsmalleo** [comment]
> i need the aptdebug.log

I will upload ASAP

**Comment by Morsmalleo** [comment]
OK sorry it took me so long to get back to you on this, so yes the mingw skip as seen in the video above in the previous discussion comments, is still happening, even on the new Kali Linux 20201.1 amd64 release for virtualbox, I have taken screenshots of all the logs after running `setup.sh` inside `/home/kali/Toolbox/TheFatRat/`. Screenshots below.

**aptdebug.log**
![aptdebug log](https://user-images.githubusercontent.com/64344168/109410947-85041c00-796c-11eb-8676-b128de7b74b1.png)

**apt.log 1**
![apt log 1](https://user-images.githubusercontent.com/64344168/109410950-86cddf80-796c-11eb-9f89-c61ed244f5d8.png)

**apt.log 2**
![apt log 2](https://user-images.githubusercontent.com/64344168/109410952-87ff0c80-796c-11eb-8220-7cd032049821.png)

**check**
![check 0](https://user-images.githubusercontent.com/64344168/109410956-8897a300-796c-11eb-93ab-fe8ab57418ae.png)

**install.log**
![install log](https://user-images.githubusercontent.com/64344168/109410957-89303980-796c-11eb-8520-6eeba2087ba9.png)

**setup.log**
![setup log](https://user-images.githubusercontent.com/64344168/109410958-89c8d000-796c-11eb-8395-e3af26b131cc.png)

**Comment by peterpt** [comment]
just upload aptdebug.log file here , dont put print screens

**Comment by Morsmalleo** [comment]
In that case the aptdebug.log displays the following 

`Ign 1: deb http://deb.debian.org/debian Jessie InRelease
Get 2: deb http://deb.debian.org/debian Jessie Release [77.3 kB]
Get 3: deb http://deb.debian.org/debian Jessie Release.gpg [1,652 B]
Get 4: deb http://deb.debian.org/debian Jessie/main amd64 Packages [6,818 kB]
Get 5: deb http://deb.debian.org/debian Jessie/main Translation-en [6,581 kB]
Get 6: deb http://deb.debian.org/debian Jessie/main amd64 Contents (deb) [27.3 MB]
Get 7: deb http://deb.debian.org/debian Jessie/contrib amd64 Packages [49.8 kB]
Get 8: deb http://deb.debian.org/debian Jessie/contrib Translation-en [38.3 kB]
Get 9: deb http://deb.debian.org/debian Jessie/contrib amd64 Contents (deb) [88.2 kB]
Get 10: deb http://deb.debian.org/debian Jessie/non-free amd64 Packages [83.2 kB]
Get 11: deb http://deb.debian.org/debian Jessie/non-free Translation-en [72.0 kB]
Get 12: deb http://deb.debian.org/debian Jessie/non-free amd64 Contents (deb) [780 kB]
Fetched 39.9 MB in 28s [1,402 kB/s]
Reading package lists...`

**Comment by peterpt** [comment]
well , i am buildind a kali 2021 VM to check what is happening because with those logs i am unable to anything .
I will let you know when i get some results .

**Comment by peterpt** [comment]
well . it looks you were right , it seems that pushing \*mingw\* to apt will conflict with actual installed packages not directly connected to mingw . This happened because this mingw version is an old version , and libc6 is pretty recent .
I believe i found a way to get this working , i am testing it out and i will update the repository as soon and i get it fixed .

**Comment by peterpt** [comment]
Ok , everything should work fine now .
Just clone the new git and remove your old fatrat folder

**Comment by Morsmalleo** [comment]
Ok thanks @peterpt testing now

**Comment by Morsmalleo** [comment]
@peterpt problem with mingw being skipped completely has been fixed :) cheers mate, you're a legend

**Comment by peterpt** [comment]
Delete your current version of fatrat and clone it again , i made a few fixes in setup to correct debian jessie repository key missing .
Follow the new instructions in readme file before running setup .

If you have any issues then create a new topic , this one will be locked
