### ISSUE TITLE
host: error while loading shared libraries: libdns.so.1605: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by usman6643ali** [screetsec/TheFatRat#579]
![Screenshot (257)](https://user-images.githubusercontent.com/77117097/103921823-c29ab480-5134-11eb-9c46-b6b995048db0.png)
![Screenshot (256)](https://user-images.githubusercontent.com/77117097/103922158-3046e080-5135-11eb-899b-8d55e1b5af8a.png)

A.o.a to all,
every time when i run the fatrat, it give the following error. 
kindly give some solution.

Thanks in advance.

**Comment by peterpt** [comment]
probably some issue with your package dns-utils  , most likely the commands dig and host that fatrat uses .
write in your terminal : dig +short myip.opendns.com @resolver1.opendns.com

this will provide your ip address , in case that error appears here then you should downgrade your dns-utils package .

In case it does not appear here then get your ip from that command and write again in your terminal replacing the letters "yourip" in the command with the ip number you got from last command : 
host yourip | awk '{print $5}' | sed 's/.$//'

This error is not even near fatrat or related to it , i am just replying to give you a clew to where the problem may be so you can fix it by yorself .

**Comment by varunsahu258** [comment]
@peterpt That does not solve My Problem 
After Running This Command
host xxx.xxx.xx.xxx | awk '{print $5}' | sed 's/.$//'
Same Error Comes
host: error while loading shared libraries: libdns.so.1605: cannot open shared object file: No such file or directory

**Comment by peterpt** [comment]
That is why i told that problem is not related to fatrat , best way is to remove dns-utils from your system and then install it again (i think) .
Or search google for a solution .

**Comment by RyanNgCT** [comment]
I'm also having a similar problem after I installed dnsutils[
![Screenshot 2021-01-26 202637](https://user-images.githubusercontent.com/48358569/105844866-dab77280-6014-11eb-9b86-d65245a50a09.png)
](url)

**Comment by peterpt** [comment]
https://eitwebguru.com/fix-error-while-loading-shared-libraries-libdns-so-22/

Basically is the same issue as you have , witch means that file libdns.so should exist already in your system but with a different extension , all you have to do is to look for it and copy it to the requested file name by the tool .
Look for solutions dont come here asking for help because that is a problem with a package and not with fatrat directly , this git is only for fatrat issues and not general linux issues .

**Comment by parker2k2** [comment]
After trying lots of various solutions to try and fix this problem, even going as far as manually downloading the rpm package for libdns.so.1605 and installing as it did seem to be missing from my libs paths, nothing seemed to solve the problem. 

Eventually solved it by running  "apt reinstall bind9-host" immediately worked after that.

**Comment by AzatAgaly** [comment]
THIS SOLUTION WORKED FOR ME:
sudo apt-get update
sudo apt-get install host
host -h

If this solution doesn't work, repeat the same process as root.

**Comment by azuax** [comment]
> After trying lots of various solutions to try and fix this problem, even going as far as manually downloading the rpm package for libdns.so.1605 and installing as it did seem to be missing from my libs paths, nothing seemed to solve the problem.
> 
> Eventually solved it by running "apt reinstall bind9-host" immediately worked after that.

This worked for me, thanks!

**Comment by rodrigodinizedubr** [comment]
Thank you for share!
