### ISSUE TITLE
Error in injecting Backdoor apk

### ISSUE THREAD

**Issue by Hamada1224** [Screetsec/TheFatRat#580]
I got this error in the photo , am in latest version of fatrat
![Screenshot from 2021-01-07 07-29-55](https://user-images.githubusercontent.com/65217637/104045908-e834c600-51e7-11eb-888e-893176d3d533.png)

**Comment by peterpt** [comment]
jarsigner belongs to default-jdk and default-jre  that must be installed

What does chk_tools says ?

**Comment by Hamada1224** [comment]
what is chk_tools ?
i tried to install default-jdk but it failed

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md

**Comment by peterpt** [comment]
Delete your fatrat directory and clone again from github .
You will find in the new cloned directory apks that were tested .
