### ISSUE TITLE
Installation error. Unable to remove package

### ISSUE THREAD

**Issue by pritam3196** [Screetsec/TheFatRat#582]
I tried installing the latest version of thefatrat but the jarsigner(java) is not getting installed. I tried the command 

```
apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f
```

that is returned at the end of the installation but then it say that it was not able to locate the package.

I tried ,jarsigner\(default-jdk\),jarsigner, jarsigner\(java\),Jarsigner, Jarsigner(\java\), in place of 'packagename'.

I have attached the apt.log file [apt.log](https://github.com/Screetsec/TheFatRat/files/5826162/apt.log)

**Comment by dakinrin** [comment]
Unsubscribe

**Comment by pritam3196** [comment]
Solved it. Had to manually install jarsigner.

```
apt-get install default-jdk
```

**Comment by Morsmalleo** [comment]
Close this issue as it has been resolved
