### ISSUE TITLE
Problem creating payload with powerstage

### ISSUE THREAD

**Issue by devilmen80** [screetsec/TheFatRat#583]
Hello when I install payload in windows i get advise from windows that it is not able to open this file bcuz of different system.
I tryed another option to create payload but i don't get any session of meterpreter it seems not to work.

**Comment by peterpt** [comment]
Takes a while to work , it is not instant the connection .

**Comment by devilmen80** [comment]
Thanks for reply.

I will try again. Anyway when I try to use powerstage and move payload to windows it says me that is impossible to open the file.

**Comment by peterpt** [comment]
The default message that powerstage uses is compatibility error , witch leads the target thinking that the exe is not for that version of windows , while at same time opens a backdoor to the attacker .
Powerstager takes a while to bypass all windows security before it connects to the attacker .
Best way is always compile a 32bit exe instead 64bit , and the reason is simple , 32bit works in 32bit OS and 64bitOS while if compiled in 64bit only will work in 64bit os systems .

**Comment by devilmen80** [comment]
Mate thanks for reply.
Now I'm trying and finally I get meterpreter sessions but they are all died and I don't know why.
Thanks for your help

**Comment by devilmen80** [comment]
More details

I am running kali linux 20.04 64bit with windows 10 in Oracle box. I disabled windows firewall but sessions of Meterpreter are all died.

**Comment by peterpt** [comment]
not quite sure what the problem may be .

**Comment by devilmen80** [comment]
Thanks. I will try tomorrow again. I have not disabled totally the firewall but i allowed the execution of the same in the system. Could be it the problem?

**Comment by devilmen80** [comment]
> Thanks. I will try tomorrow again. I have not disabled totally the firewall but i allowed the execution of payload (bcuz windows firewall sees it)in the system. Could be it the problem?

**Comment by peterpt** [comment]
most likely . Because firewall detects the outgoing connection and blocks it .
not sure if it will work but try using an http or https payload witch uses port 80 or 443 for communication .

**Comment by devilmen80** [comment]
Thanks mate for reply as usually. But reverse http or https can work over the lan??

**Comment by peterpt** [comment]
yes
