### ISSUE TITLE
the remote end hung up unexpectedly fatal: early EOF fatal: index-pack failed

### ISSUE THREAD

**Issue by chotosite** [Screetsec/TheFatRat#585]
git clone command shows the following error: the remote end hung up unexpectedly fatal: early EOF fatal: index-pack failed.

I also tried: sudo git clone "https://github.com/Screetsec/TheFatRat.git" --depth 1
but faced the same error. Help please. Thank you.

**Comment by aneeshsharma** [comment]
Please provide more info about the system you are using (the OS particularly) as it seems to be a problem with `git` itself and not the repository.
Also, are you sure that this issue occurs when cloning this repository and not with every repository you try to clone?
Try cloning some other repository just to be sure.

[This thread on stackoverflow](https://stackoverflow.com/questions/21277806/fatal-early-eof-fatal-index-pack-failed) might be relevant to your issue.

**Comment by chotosite** [comment]
I found the solution it's because of bad internet connection

**Comment by osamashabbir66** [comment]
> I found the solution it's because of bad internet connection

Great :)

**Comment by bondythegreat** [comment]
i got same issue. just realised my isp somehow behaving by blocking me on this. vpn solves the problem
