### ISSUE TITLE
What do I input for lhost.

### ISSUE THREAD

**Issue by CodeChamp24** [Screetsec/TheFatRat#586]
I have tried public ip and the ipv4 mentioned when you run fatrat. I am not sure which one i need to use. Both don't seem to work though because when I run msfconsole and input the same lhost and lport and click on the app on my phone nothing happens.
This is on kali linux on virtualbox.
I know barely anything about hacking just some knowledge on bash commands and simple programming languages.

**Comment by peterpt** [comment]
ipv4 is to be used on local lan , this means that the target device must be on the same network .
public ip is to be used if the target device is not on same network , but for public ip to work you must be directly connected to internet with a dhcp ip from your ISP and not your lan router to work .

**Comment by CodeChamp24** [comment]
So if the targets device is connected to the same wifi I am, I should use ipv4?

**Comment by peterpt** [comment]
sure , same wi-fi means local lan or same network

**Comment by CodeChamp24** [comment]
I tried my wifi ip for lhost and it didn't connect, it changed the lhost to 0.0.0.0 when running. Same with public ip. What am I doing wrong?

**Comment by peterpt** [comment]
your local host is not surely 0.0.0.0 , most likely 192.168.something.something .

fatrat shows you the lan ip and is that ip that you must use , however if you are running on an dhcp server it means that when you probably disconnect and reconnect again you will have a new ip address that could be the same or not the one you configured for the backdoor .

**Comment by CodeChamp24** [comment]
I tried the ip with 192.168 at the beginning in msfconsole again and it still didn't work.
I did 'set lhost 192.168-'

**Comment by peterpt** [comment]
your ip address is not surely 192.168 only , in fact you are unable to even create a backdoor with that half ip .

https://en.wikipedia.org/wiki/IPv4#Addressing

**Comment by CodeChamp24** [comment]
I said I used the ip address with 192.168 at the BEGINNING and then typed in the rest of my ip.

**Comment by CodeChamp24** [comment]
I used the ip address with 192.168 at the BEGINNING and then typed in the rest of my ip. It still never worked.

**Comment by peterpt** [comment]
what is your local ip address and what is the ip of the phone .

Note : You can write the full ips addresses because your are on local area network .

**Comment by CodeChamp24** [comment]
192.168.0.11 local ip
192.168.0.14 phone ip

**Comment by peterpt** [comment]
can you do the same backdoor again with new updated fatrat ?
make sure you write the approriate port where phone will call , just for test .
If it is an apk you are backdooring and if it is less that 30M then upload it to here so i can test it .

**Comment by CodeChamp24** [comment]
'approriate port where phone will call'
What do you mean by this?

**Comment by peterpt** [comment]
usually people use 4444 or 7777 , a low port to avoid disconnections an problem with communications

**Comment by CodeChamp24** [comment]
what should I enter for lhost ip when i run fatrat? Also where is the updated fatrat.

**Comment by keethesh** [comment]
> what should I enter for lhost ip when i run fatrat? Also where is the updated fatrat.

The lhost IP should be the local IP of the computer from where you'll be listening for connections (in this case the IP of your computer with Kali Linux)

**Comment by CodeChamp24** [comment]
Thank you, also what lhost should I enter for msfconsole's lhost. I tried my laptops local ip but it said it failed to bind to that ip and instead binded to 0.0.0.0

**Comment by keethesh** [comment]
> Thank you, also what lhost should I enter for msfconsole's lhost. I tried my laptops local ip but it said it failed to bind to that ip and instead binded to 0.0.0.0

That's an error with Metasploit now. A quick google search will give you plenty of solutions

**Comment by CodeChamp24** [comment]
I've fixed the issue now. It was with my virtualbox settings. I had it on NAT instead of Bridging Adapter. Thanks for the help. In the end it wasn't anything to do with the software and it was just my lame virtualbox skills. :)


NAT gives the virtualbox a special local ip which goes 10.0..... and so on. 
Whereas bridging connects your laptop local ip with virtualbox (I think). It came up with 192.168.0.30 instead of my mac address 192.168.0.11 but it works anyway.

**Comment by gitau254-m** [comment]
ip adress in fatrat not showing
