### ISSUE TITLE
ERROR DE MINGW-64 Y MINGW32 HELP

### ISSUE THREAD

**Issue by andersonjqc** [Screetsec/TheFatRat#595]
![VirtualBox_kali linux _12_03_2021_23_32_50](https://user-images.githubusercontent.com/71105993/111019165-731e7200-838b-11eb-9692-df2289fbfb9b.png)
![VirtualBox_kali linux _12_03_2021_23_33_51](https://user-images.githubusercontent.com/71105993/111019166-73b70880-838b-11eb-841c-f1c683872be1.png)

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md
