### ISSUE TITLE
the backdoored apk failed to start

### ISSUE THREAD

**Issue by JohnGithub917** [screetsec/TheFatRat#596]
use msfvenom to generate the payload, android/meterpreter/reverse_tcp
the original apk is 109.5MB 
i got the backdoored apk, and it can allow the premissions when running but failed to load the main ui, then it crashes.

**Comment by peterpt** [comment]
are you using the latest fatrat ?
The new fatrat tests your apk before doing anything with it ahead .
If apk can not be used then it will drop a message .

**Comment by JohnGithub917** [comment]
@peterpt yes, i use 1.9.7, the test can pass.

**Comment by peterpt** [comment]
no , 2.5.0 version have the same problem , and fatrat was programmed to use 2.4.0 version , even if you uninstall or remove the symlinks from 2.4.0 version inside /usr/local/sbin from apktool and install manually or by apt the 2.5.0 fatrat will always say that apktool is missing .

There is no solution from apktool developers at this time for many decompiled issues in some apks .
