### ISSUE TITLE
Was as not possible to install The Packages Labeled 

### ISSUE THREAD

**Issue by diyanhassan** [screetsec/TheFatRat#597]
xterm -> OK
Dns-Utils -> OK
Mono-Denvelop Utils -> OK
GCC -> OK
Apache2 -> OK
Gnome Terminal -> OK
UPX -> OK
Ruby -> OK
Python3 -> OK
Python3-pip -> OK
Openssl -> OK
Jarsigner -> OK
Unzip -> OK
Keytool -> OK
Zipalign -> Not OK
Mingw64 -> OK
Mingw32 -> OK
DX -> OK
Aapt -> OK
Apktool -> OK
Baksmali -> OK
Metasploit -> OK
Backdoor-Factory -> OK
Searchsploit -> OK
Was not possible to install The Packages Labeled (Not Ok) in this list above
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)
before running fatrat setup script again

I have tried all methods but unable to use TheFatRat kindly help me........

**Comment by peterpt** [comment]
rm /usr/local/sbin/zipalign

and then run setup again

**Comment by exjade** [comment]
Same problem here
xterm -> OK                                                                           
Dns-Utils -> OK                                                                       
Mono-Denvelop Utils -> OK                                                             
GCC -> OK                                                                             
Apache2 -> OK                                                                         
Gnome Terminal -> OK                                                                  
UPX -> OK                                                                             
Ruby -> OK                                                                            
Python3 -> OK                                                                         
Python3-pip -> OK                                                                     
Openssl -> OK                                                                         
Jarsigner -> OK                                                                       
Unzip -> OK                                                                           
Keytool -> OK                                                                         
Zipalign -> OK                                                                        
mingw-w64 -> Not OK                                                                   
mingw-32 -> Not OK                                                                    
DX -> OK                                                                              
Aapt -> OK                                                                            
Apktool -> OK                                                                         
Baksmali -> OK                                                                        
Metasploit -> OK                                                                      
Backdoor-Factory -> OK                                                                
Searchsploit -> OK                                                                    
Was not possible to install The Packages Labeled (Not Ok) in this list above          
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)                                                                                    
before running fatrat setup script again                                              
                                                                                      
![Screenshot 2021-03-19 03:46:22](https://user-images.githubusercontent.com/21164242/111768862-b7b37d00-8865-11eb-966c-98b602f8ff82.png)

**Comment by exjade** [comment]
> rm /usr/local/sbin/zipalign
> 
> and then run setup again

i tried but it didnt work return same problem

**Comment by jafarnajah** [comment]
> > rm /usr/local/sbin/zipalign
> > and then run setup again
> 
> i tried but it didnt work return same problem

me2

**Comment by peterpt** [comment]
diffrent people must create different thread issues .
I wrote the zipalign fix for the first post and not for all others below .
You all have to stop mixing your issues with others if the problem is not the same .

**Comment by manthan100** [comment]
Same problem is with me please help
