### ISSUE TITLE
Having issues with installing MingW 64/32 and Python-Dev not working

### ISSUE THREAD

**Issue by Vendetta0510** [screetsec/TheFatRat#600]
Whenever I try to install MingW 64 it doesn't work I use the command `"apt-get remove --purge mingw-w64 && apt-get autoremove && apt-get install -f"`
![Screenshot 2021-03-25 12:40:23](https://user-images.githubusercontent.com/81365717/112474515-a38ce580-8d67-11eb-8361-91f2ac69c182.png)
This is the output, running `cd TheFatRat chmod +x chk_tools ./chk_tools` then outputs this:
![Screenshot 2021-03-25 12:45:16](https://user-images.githubusercontent.com/81365717/112474813-fc5c7e00-8d67-11eb-9107-df7e9ea2efa7.png)
The solution says to input the command `chmod +x setup.sh && ./setup.sh` and this is what that outputs:
![Screenshot 2021-03-25 12:49:04](https://user-images.githubusercontent.com/81365717/112475266-860c4b80-8d68-11eb-9b66-6670822a8566.png)
This then recommends to run the command `"apt-get remove --purge <packagename>&& apt-get autoremove && apt-get install -f"` which leads me back to where I started.

The other issue is python-dev, running `cd TheFatRat chmod +x chk_tools ./chk_tools` recommends to input the command `a
pt-get install python-dev`. Running this command outputs the following:
![Screenshot 2021-03-25 12:52:30](https://user-images.githubusercontent.com/81365717/112475684-fca94900-8d68-11eb-9d7d-244a9b194b7b.png)
It downloads `'python-dev-is-python2'` instead, is there any way to fix this?

Sorry if I have made a simple/beginner mistake I am relatively new to hacking

**Comment by peterpt** [comment]
where is the log file created by fatrat ?
setup.log
apt.log
aptdebug.log

You surely do not believe that we will guess what is your problem there by showing screen captures right ?

**Comment by exjade** [comment]
```
try this
apt-get install python-dev
apt-get install mingw-w64 

```

**Comment by Morsmalleo** [comment]
Install python-dev from debian Jessie repo with aptitude

**Comment by bladea24** [comment]
Thanks a lot @Morsmalleo this definitely solved the problem

**Comment by Morsmalleo** [comment]
> Thanks a lot @Morsmalleo this definitely solved the problem

You're welcome :) I love unofficially working with TheFatRat devs on here so a lot of these fixes came from then as well as some I discovered myself
