### ISSUE TITLE
Resize: Time out occurred "When trying & click for to Listen to that Rat I did installed "

### ISSUE THREAD

**Issue by tomanak86** [screetsec/TheFatRat#603]
In menu when I entered "09" ( Load/Create auto listeners) to load a Saved Listener that matched with my .apk payload , I will receive nothing Only Time and returning to main Menu of TheFatRat ===> Resize: Time out occurred

I checked my IP address with that port I want to forward , I mean Port is Open and IP is Correct
Where is problem ?
Shouldn't I use VPN ? 
I Tested with Local IP 127.0.0.1:5432&443 ,, and Public IP too , But Same Problem ... Resize: Time out occurred

**Comment by peterpt** [comment]
127.0.0.1 is your own local system , you must use lan ip , and dont worry about resize command .

**Comment by xy0893** [comment]
Oh, it will be killed by Android antivirus software.  Can a membership
version be made?  Let fewer users use it to support Android 11 devices and
bypass all anti-virus software

peterpt ***@***.***> 于 2021年4月8日周四 03:31写道：

**Comment by ZoomGC** [comment]
> 127.0.0.1 is your own local system , you must use lan ip , and dont worry about resize command .

When you say to not worry about it, it makes no sense, as it is still an error that is PREVENTING us from using meterpreter's listener, so how do we fix it, or am i missing something, as my saved listener doesn't seem to load as it brings me back to TheFatRat's Menu where it then asks me to input a number for more options such as backdoors using msfvenom and such, also when running a linux .elf file should anything happen or does it get loaded into memory instead, thanks in advance

-ZoomGC
