### ISSUE TITLE
This app built for older version of android problem

### ISSUE THREAD

**Issue by atifzaman49** [screetsec/TheFatRat#604]
Hello I'm facing problem after making a payload or whenever i embed a Payload with original app and after installing that app on my phone the original app started and payload not start and show the error that this app built for older version of android any idea how to make payload for letest android version phones?

**Comment by atifzaman49** [comment]
@Screetsec  please have a look of my issue

**Comment by Morsmalleo** [comment]
I'm pretty sure thats what its supposed to do, is output that error, I've seen that on most of TheFatRats APK payloads as well as Windows payloads. it outputs a compatibility error, but then gives you a backdoor session, you would have to wait a little bit for the backdoor to open, try again, but wait for a bit to see if a backdoor opens, if it doesn't then come back here

**Comment by Morsmalleo** [comment]
I've been testing TheFatRat quite a lot because its one of my favorite tools, so I don't mind helping out when the devs are busy :)

**Comment by jcbrave** [comment]
@Morsmalleo Please I have same problem please check your Email inbox there I briefly discuss my problem please solve it for me please.

**Comment by jcbrave** [comment]
@atifzaman49 Brother did you find a Solution?
