### ISSUE TITLE
msfconsole 

### ISSUE THREAD

**Issue by derrick120** [screetsec/TheFatRat#605]
Why I'm i seeing this whenever I start metasploit is this an issue because sessions no longer work pls help

**Comment by derrick120** [comment]
I mean this: Using configured payload generic/shell_reverse_tcp

**Comment by Morsmalleo** [comment]
You are launching metasploit from TheFatRat which is a bit buggy at the moment launch msfconsole normally and configure the listener to work with the payload for TheFatRat
