### ISSUE TITLE
not installed dont know the problem alredy installed mingw-w64 and mingw 32 in my system 

### ISSUE THREAD

**Issue by lokeesh** [screetsec/TheFatRat#606]
![Screenshot_2021-04-18_01_29_16](https://user-images.githubusercontent.com/44634770/115125682-77bbf300-9fe7-11eb-80d4-4745d1a224e9.png)

**Comment by lokeesh** [comment]
hlep me please .... hope this will work on android 10 and above ...waiting for you replly buddy

**Comment by nanilito** [comment]
> hlep me please .... hope this will work on android 10 and above ...waiting for you replly buddy

hi bro, I had the same problem but I found the solution, 
open the terminal with sudo su
cd TheFatRat
apt-get install mingw-w64
and is ready to use
I hope u can fix it:)
(sorry my english is not good)

**Comment by Morsmalleo** [comment]
You need to install mingw32 and mingw-w64 from the Debian Jessie repo and it can't be installed from the latest repos of Kali or debian
