### ISSUE TITLE
fatrat mingw 64 bit & mingw 32 bit not found error

### ISSUE THREAD

**Issue by mtvbp2020** [screetsec/TheFatRat#610]
![fatrat_03](https://user-images.githubusercontent.com/83900491/117564666-cfbbb600-b0ca-11eb-9b9f-2d5cf70dacdd.JPG)
![fatrat_04](https://user-images.githubusercontent.com/83900491/117564669-d0ece300-b0ca-11eb-958d-e9a17c94b534.JPG)

help me to solve this error Zipalign & Mingw64 & Mingw32 are not ok  , iam in beginner level someone help me to solve this

**Comment by Morsmalleo** [comment]
To fix the zipalign error run this
`Sudo apt install zipalign`

To fix the mingw error run TheFatRat installer again
`sudo ./setup.sh` 

Let us know if the problem persists

**Comment by mtvbp2020** [comment]
> To fix the zipalign error run this in a terminal
> `sudo apt install zipalign`
> 
> To fix the mingw error run TheFatRat installer again
> `sudo ./setup.sh` 
> 
> Let us know if the problem persists
> 
> 

Solved thank you 😊

**Comment by shane89420** [comment]
It won't let me install backdoor factory and Ming 64 how to fix??
