### ISSUE TITLE
Unable to install Mingw-w32 / Mingw-w64 during the auto setup. 

### ISSUE THREAD

**Issue by archidote** [screetsec/TheFatRat#616]
To correct that, put into your setup.sh only :

apt install -y mingw-w64  

package Mingw-w32 is not anymore available. 

Best regards,

**Comment by LIBRARYY** [comment]
apt install mingw-w64 did it for me

**Comment by archidote** [comment]
Hum.. strange 
Maybe you have other deb repositorys than me ?

**Comment by peterpt** [comment]
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CBF8D6FD518E17E1 7638D0442B90D010

then run setup.sh

**Comment by nephelim59** [comment]
you had to install the fastrat in root

**Comment by Afluente** [comment]
https://github.com/Zeranoe/mingw-w64-build.git
fix it with this, clone and install
