### ISSUE TITLE
TheFatRat On KaliPI 64Bit ARM .

### ISSUE THREAD

**Issue by methlabzq** [Screetsec/TheFatRat#617]
Hey There . 

I tried to setup TheFatRat on my RPI 4B 8GB with ARM64 Kali on it . 

The problem im facing is 2 missing dependency .. 

Mingw-w64
Mingw-32 

Is there any workaround , or troubleshooting method which allow me to Install those packages without any problem ? 

Im using TheFatRat on various OS without issue . 
Im just curious if there is a way to do it on RPI 4 ? 

Thank you for Your time , and i appreciate your great work . :) 

Yours sincerely,
Methlab

**Comment by peterpt** [comment]
mingw32 can only be installed using jessie repository from debian , setup script does that for normal x86_64 linux systems in line 710 of setup.sh 
https://github.com/Screetsec/TheFatRat/blob/master/setup.sh
 , i never try it on an arm 64 device .

running ./chk_tools on fatrat folder may give you an idea of what to do to fix it .

**Comment by methlabzq** [comment]
I tried chk_tool but gave me no usefull information in this case for troubleshooting :( 

The architecture is seems OK for the setup script. 
Maybe is there a method i can bypass that check , And make the script running without mingw32 ? 

I can do the Whole Metasploit method manually with no problem , The only thing i wanted from the Script is the "Evasion" module , To Bypass single Anti Viruses or Windows Defender Live Protection . (Especially WinDefend) 

After i get the meterpreter session i got no problem with PE ( Privilage Escalation ) and using the Post Modules or so . 

My Problem is with Delivering the Payload , I tried many many things , like creating custom payload with Encoders , like xor or xor_dynamic . Excluding parts with MSFVENOM payload generator .  But somehow the Defender got me all the time. 

TBH im still a little nab . Also i dont want to seems like a ScriptKiddie . 
So i thought its time for learn the hard way 
Im only using what i learned on my Windows10 PC .

**Comment by methlabzq** [comment]
I found the following packages in the Repo , 

Maybe any of these can help my issue ? 

 binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 g++-mingw-w64 g++-mingw-w64-i686
  g++-mingw-w64-i686-posix g++-mingw-w64-i686-win32 g++-mingw-w64-x86-64
  g++-mingw-w64-x86-64-posix g++-mingw-w64-x86-64-win32 gcc-mingw-w64 gcc-mingw-w64-base
  gcc-mingw-w64-i686 gcc-mingw-w64-i686-posix gcc-mingw-w64-i686-posix-runtime
  gcc-mingw-w64-i686-win32 gcc-mingw-w64-i686-win32-runtime gcc-mingw-w64-x86-64
  gcc-mingw-w64-x86-64-posix gcc-mingw-w64-x86-64-posix-runtime gcc-mingw-w64-x86-64-win32
  gcc-mingw-w64-x86-64-win32-runtime ??

**Comment by methlabzq** [comment]
chk_tools gave me no usefull info for troubleshooting . 

But installing the mingw packages manually and it seems everything working as intended

**Comment by methlabzq** [comment]
Yes i can Confirm its working on ARM 64 RPI 4B without any problem :) 

Thanks for the Great Script

**Comment by methlabzq** [comment]
Solved by workaround
