### ISSUE TITLE
Unable to Find the generated backdoored_apk

### ISSUE THREAD

**Issue by ayaan-47** [screetsec/TheFatRat#620]
The output of the generated apk is python 3 app_backdoored.apk. I am unable to find this directory in my kali machine. How do i change the output directory.

**Comment by O-XiXu** [comment]
Why you don't try './setup.sh' again?
it will ask you again about output directory.
but with default settings it should be in home directory, try it with
'cd ~' and 'ls' to find it, Hope work!

**Comment by shane89420** [comment]
Go to root account there will be a folder named fatrat generated
