### ISSUE TITLE
mingw32 - Does not exist in user repository

### ISSUE THREAD

**Issue by freeminder9237** [screetsec/TheFatRat#622]
mingw32 - Does not exist in user repository

**Comment by shane89420** [comment]
Apt install mingw32

**Comment by Morsmalleo** [comment]
mingw needs to be installed from the Debian Jessie software repo, run the **`setup.sh`** file again.
If that doesn't fix your problem then check for the following files listed below in the **`/etc/apt/trusted.gpg.d/`** directory 

- **`debian-archive-jessie-automatic`**
- **`debian-archive-jessie-security-automatic`**
- **`debian-archive-jessie-stable`**

if you can't find them, then you will need to reinstall them using my drive link below
**`https://drive.google.com/drive/folders/1F8tXNO0bTUNkPV9kCK6xzWiNM7aoAadH?usp=sharing`**

Download the folder, then to reinstall them use the following commands listed below in a terminal
**`sudo cp trusted.gpg.d /etc/apt/`**
**`sudo apt-get update`**
**`cd TheFatRat && clear && sudo ./setup,sh`**
**`rm -rf trusted.gpg.d`**

the mingw installation may fail again, so if it does run it again and it should tell you that both **`mingw-w64`** & **`mingw-32`** have been installed

**Comment by peterpt** [comment]
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CBF8D6FD518E17E1 7638D0442B90D010

then run setup
