### ISSUE TITLE
Unable to generate backdoor on Fatrat using PwnWinds

### ISSUE THREAD

**Issue by AfridiEshrak** [screetsec/TheFatRat#627]
When I try to use option 6 from the main menu (Create Fud Backdoor 100% with PwnWinds) & try to create a bat file+Powershell,
It's showing 

**

cat: powershell_attack.txt: file or directory not found
rm: cannot remove 'unicorn.rc' : No such file or directory
mv:  cannot start 'powershell_attack.txt' : No such file or directory

There was an error creating backdoor

**

But it’s not showing that error when I am using any other option from the main menu to creating payloads.

**Comment by peterpt** [comment]
that error is related to your default version of python , witch is probably 3.xx while the script that does that job works with python 2.7

**Comment by AfridiEshrak** [comment]
How it can be solved!?

**Comment by Morsmalleo** [comment]
I will see it I can recreate the problem you are having and see if I can determine a work around for it

**Comment by Morsmalleo** [comment]
I can't seem to recreate your problem mate, 
 I've done all the same steps you've done,

Chose the option `[06] Create FUD Backdoor 1000% with PwnWinds` from TheFatRat menu

Chose the method "[01] Create a bat file+Powershell (FUD 100%)" from the PwnWinds menu

Typed my IP address and port number 

Then I tested each of the 6 Payload options you are offered to use and all of them built just fine, 

And I'm using the latest Python3 version as well.

What OS are you running LINUX or WINDOWS

**Comment by AfridiEshrak** [comment]
I am using Kali Linux 2021.2

**Comment by Morsmalleo** [comment]
that's very weird, that's the same version of Kali that I am running.

run these command in terminal and copy and paste the output here

**`apt-cache policy python-dev`**
**`apt-cache policy python3`**
**`apt-cache policy python3-pip`**

**Comment by peterpt** [comment]
there are a few reasons for this problem to happen :

**1st - python wrong version **

to check if script runs outside fatrat run these commands inside your fatrat folder

**cd tools && python trusted_2_6.py**

if it is ok then it should show you this output

![trusted](https://user-images.githubusercontent.com/7487321/126077621-27762fb4-528d-4acd-a7a8-c20e939f370d.jpg)


**2nd - This script requires msfvenom to work properly** 

Inside the script there is a line calling msfvenom to build the payload : 
![msfvenom](https://user-images.githubusercontent.com/7487321/126077827-2875daf7-9f7a-47ef-93ef-b5bbcee7b821.jpg)

If msfvenom or metasploit is not working properly outside its directory then you will never be able to do anything with fatrat .

To test write this line in your terminal inside fatrat folder

**msfvenom**

if it is ok then you will see something like this : 
![msfv1](https://user-images.githubusercontent.com/7487321/126077933-98e0640a-de1f-4ba9-895f-4f0af6b9b897.jpg)


3rd - Domains are not permitted in payloads , you must use your ip address , something like "mydomain.com" will not work .


Testing here : 

![payload](https://user-images.githubusercontent.com/7487321/126078176-f60f3cba-c471-4651-a270-79717f6cdadf.jpg)


I created a brand new kali VM to test this and it works perfect .
