### ISSUE TITLE
Option 2 (create fud 100% backdoor) .exe not responding in win 10 64bit

### ISSUE THREAD

**Issue by t-1559-t** [Screetsec/TheFatRat#63]
So i have done FUD backdoor in exe file named powerfull.exe and when i try to execute it in my win 10 compuer it opens black shell (like it should) but very soon after that win says powerfull.exe stopped working.  I disabled my AV and UAC but same problem.
Anyone have any solution for this? my fatrat is latest possible version

**Comment by EinderJam** [comment]
I have the same problem,with Win10 x64,with fresh install of TheFatRat

**Comment by Eztharia** [comment]
+1 Same

**Comment by peterpt** [comment]
update fatrat to latest version and user powerstager in Fudwin menu .
