### ISSUE TITLE
failed to install FatRat on kali-linux-2021.2.-virtual box-amd64

### ISSUE THREAD

**Issue by atkrsoft** [screetsec/TheFatRat#631]
Ruby -> OK                                                                   
Python3 -> OK                                                                
Python3-Pip -> OK                                                            
Openssl -> OK                                                                
Jarsigner -> OK                                                              
Unzip -> OK                                                                  
Keytool -> OK                                                                
mingw-w64 -> Not OK                                                          
mingw-32 -> Not OK                                                           
DX -> OK                                                                     
Aapt -> OK                                                                   
Apktool -> OK                                                                
Baksmali -> OK                                                               
Metasploit -> OK                                                             
Backdoor-factory -> OK                                                       
Searchsploit -> OK                                                           
Was not possible to install The Packages Labeled (Not Ok) in this list above 
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)                                                                  
before running fatrat setup script agai

**Comment by SBNMOH** [comment]
TYPE IN ---------- sudo apt-get update 

                  
then sudo apt-get install mingw-64 -y

**Comment by Morsmalleo** [comment]
This problem has been fixed so just simply run the setup script again and it should work if it doesn't then post back here and let me know, the mingw version you need needs to come from Debian Jessie, it can't be installed from any other repo

**Comment by flub71** [comment]
@Morsmalleo I had the same issue today - I just manually installed the package using apt-get.

But the script does not install them.

I only just noticed that your comment above shows that I should only use the version from Debian Jessie.. Oops!
