### ISSUE TITLE
thefat rat

### ISSUE THREAD

**Issue by santhosh0000000** [screetsec/TheFatRat#634]
xterm -> Not OK
Dns-Utils -> OK
Mono-Denvelop Utils -> OK
GCC -> OK
Apache2 -> OK
Gnome Terminal -> OK
UPX -> OK
Ruby -> OK
Python3 -> OK
Python3-pip -> OK
Openssl -> OK
Jarsigner -> OK
Unzip -> OK
Keytool -> OK
Zipalign -> Not OK
Mingw64 -> OK
Mingw32 -> OK
DX -> OK
Aapt -> OK
Apktool -> OK
Baksmali -> OK
Metasploit -> OK
Backdoor-Factory -> OK
Searchsploit -> OK
Was not possible to install The Packages Labeled (Not Ok) in this list above
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)
before running fatrat setup script again

**Comment by Morsmalleo** [comment]
sudo apt install xterm
