### ISSUE TITLE
Does it work on Fedora? --idontlikedebian

### ISSUE THREAD

**Issue by mrdeepmind** [screetsec/TheFatRat#637]
Hello! I just wanted to give a shot to TheFatRat and as I saw in update file 
line: 67 apt-get install netcat -y > /dev/null 2>&1
and
line:82 apt-get install git -y > /dev/null 2>&1 

I wanted to change all the apt-get and apt-cache strings to make it work on Fedora but I kinda felt like it can break my lovely Fedora, so I wanted to ask you that; Do I have to have Debian to run THeFatRat? 

Thanks in advance! Have a good day!

**Comment by peterpt** [comment]
https://github.com/screetsec/TheFatRat/issues/587
