### ISSUE TITLE
A pull request

### ISSUE THREAD

**Issue by peterpt** [Screetsec/TheFatRat#64]
I was unable to create the pull request from my git to yours because there are massive changes in my git that crashes my firefox when git is analyzing the differences .
FatRat is originally your creation , so in good faith i believe that i should send you a pull request everytime some good changes are made .

FatRat becomes FatRat 1.9beta 
and the changes are : 
- APK (5) rat rebuild totally changed .
(adapted backdoor-apk script to fatrat to both work together)
- APKS have a new payload hiding method in rat apk to not be detected .

- Apktool will not be installed no more by setup.sh , the same thing applies to : dx , zipalign
(apktool on debian repo is 2.2.1 , and that version have a bug that gives error on compiling the apks , so , apktool and android tools were updated to latest version 25.0.2 and embeded in (tools) directory of fatrat .
- Some other changes were made but i can not remember everything now because i have been doing the changes since beginning of last week .

The only way that i see for you to merge my git to yours is : 
-cloning my git to your hard disc
-Enter hidden directory .git in my git and change from : 
**https://github.com/peterpt/TheFatRat**
to
**https://github.com/Screetsec/TheFatRat**

and then over the terminal do a git push to your account , so all files can be changed .

If you do not want to merge then there is no problem .

Anyway , here are the new changes  
https://www.youtube.com/watch?v=Nj7AFEBjvdQ

**Comment by Screetsec** [comment]
clean up your file in peterpt/thefatrat ,  like log,bug and trash . i will download your files and uploads som files to my github  . for backdoor apk thankyou for contirbute a

**Comment by Screetsec** [comment]
why you put createapk in outside ? i suggest put create apk on /tools/

and give alias
backdoorapk='tools/createapk' # exec script path

**Comment by peterpt** [comment]
Hi , thanks for pointing out the log folder , somehow when i updated the last time i forgot to clean that folder .
If i change the location of createapk file to inside tools , then all script paths must be rebuild because that script was made to start looking for files after that directory path point  .

i already cleared the log folder , all other folders are from fatrat originally  except : 
"list" folder = where createapk goes get names to hide the real payload in rat apk .
"java" folder = contains files that are needed to be copied during the rat apk creation
"temp" folder = where all rat apk temporary files are created .

**Comment by peterpt** [comment]
Just another thing , if you find any bug on my changes then let me know , because from this minute i could not found any error executing fatrat or any of its current scripts or even the new apkcreate script .

The changes  i made in last 15 minutes where the only minor bugs i found in apkcreate where path variable was not written properly for that script current path variable set .

**Comment by peterpt** [comment]
sorry for last hour changes , i just had to update readme.md in main directory because pictures were still from 1.8 version , and i also updated the tutorial video link related to how to create a rat apk .
Everything is finished now .

**Comment by Screetsec** [comment]
will be update

**Comment by peterpt** [comment]
i know , but now i got another idea to implement .
Everyday that passes by i remember things to implement .
I will see if i can implement in backdoor embeded menu a zenity popup with a window with user file explorer for user browse the app apk file .
This way we will avoid manual write paths errors .

**Comment by peterpt** [comment]
ok , on my git , zenity will popup from now on everytime user selects an apk rat .
-Zenity will popup a file browser that only shows files with extension (apk)
-Zenity will popup a window to user write the LHOST and LPORT variables .

This idea just came up this morning to implement , and it is finished .
Until you update your git with all these changes in my git i will not make any more updates to the code .

**Comment by Screetsec** [comment]
dont use zenity to much { Graphic user interface ) , why im not using gui in located file and set flhost ? because i want thiss tool >>  old school style .

**Comment by Screetsec** [comment]
if you want create that , sure no problem . but . i suggest you , when you use use zenity for another features .the tools iits noot beatiful again :p

**Comment by peterpt** [comment]
yeah , i know .
But i think that options like these where user have to write a path to a file manually , is better to use zenity file browser option to avoid errors .
And yes you are right , too much zenity will break break fatrat original interface .

**Comment by Screetsec** [comment]
android-sdk-25 ( larger file ? am i right ?

**Comment by peterpt** [comment]
yes , and that folder contains sub-folders with libraries and all the android tools , so apktool does not have to depend on system old incompatible tools .
I think that just that folder have near 100M .

**Comment by Screetsec** [comment]
200 mb ?

**Comment by peterpt** [comment]
android-sdk-25 : 246Mb
apktool2.2.2 : 8.1Mb
proguard 5.3.2  : 7Mb 

the reason why android sdk is so big is because an apk is not for only a particular device or resolution .
And android sdk to compile those rat apks must have the libraries for that specific device .

Anyway , if users install this package from apk , it will be downloaded from google or any other mirror because of its size .

look here at the file tools_r25.2.5-linux.zip in one of the android repositories .
http://mirrors.neusoft.edu.cn/android/repository/

**Comment by Screetsec** [comment]
done dude :p , check now my repo

**Comment by peterpt** [comment]
add in main fatrat folder on the **readme.md** the credits to : 
https://github.com/dana-at-cp/backdoor-apk

also , **remove the docker** , because it will not work if user relies on docker to install fatrat , without running setup.sh the config.path will be not created , and if config.path is not created then noting will work and every script in fatrat will say to user execute setup.sh

Change picture of fatrat on readme.md , the current picture is still at 1.8 version .

**Comment by Screetsec** [comment]
lets discuss in email dude , this issue will be close
