### ISSUE TITLE
 [x]::[not root]: You need to be [root] to run this script.       What does it mean?

### ISSUE THREAD

**Issue by startovacie** [screetsec/TheFatRat#640]
i ran the startup script :
$ chmod +x setup.sh && ./setup.sh

Error in the title showed up:
 [x]::[not root]: You need to be [root] to run this script.

Can someone please help me out?

**Comment by dlhowellgr** [comment]
I believe it's referring to root access i.e permission

**Comment by Morsmalleo** [comment]
sudo ./setup.sh

**Comment by Raeeskhan1** [comment]
sudo chmod +x setup.sh && ./setup.sh
or 
su root 
chmod +x setup.sh && ./setup.sh

**Comment by Raeeskhan1** [comment]
you have to be a root user that's why you are facing the problem

sudo chmod +x setup.sh && ./setup.sh
or
su root
chmod +x setup.sh && ./setup.sh

**Comment by P3rt4f** [comment]
or just:
sudo su
chmod +x setup.sh
./setup.sh

**Comment by motaznewx** [comment]
sudo bash setup.sh 🙂

**Comment by Folasayo-Samuel** [comment]
@P3rt4f
``sudo su``  works for me.

**Comment by OmorOrNot** [comment]
what about windows

**Comment by lalodev1234** [comment]
I don't understand but you just have to redo the script with sudo?

**Comment by Morsmalleo** [comment]
> I don't understand but you just have to redo the script with sudo?

If you don't understand the use of `sudo` then you shouldn't be here

**Comment by ab-7x** [comment]
who found another way to resolve this probleme without sudo ?

**Comment by Abomide1206** [comment]
this is what my command on kali telling me ─$ sudo apt update
[sudo] password for kali: 

sxSorry, try again.
[sudo] password for kali: 
csxaxssSorry, try again.
[sudo] password for kali: 
ksudo: 3 incorrect password attempts

**Comment by Abomide1206** [comment]
──(kali㉿kali)-[~/TheFatRat]
└─$ ./setup.sh

 
 [x]::[not root]: You need to be [root] to run this script.
 please how can i be root?????

**Comment by Abomide1206** [comment]
kali㉿kali)-[~/TheFatRat]
└─$ sudo ls -al /root
[sudo] password for kali: 
tSorry, try again.
[sudo] password for kali: 
toaSorry, try again.
[sudo] password for kali: 
tosudo: 3 incorrect password attempts
what is the password????
