### ISSUE TITLE
Can't start TheFatRat

### ISSUE THREAD

**Issue by miles8morales8** [screetsec/TheFatRat#642]
so, I have been trying to install this since morning and still can't! I used all the commands to install it correctly but I don't know why it is showing some errors. I have attached some screenshots that might explain this situation better : 

![1](https://user-images.githubusercontent.com/76535242/132535729-97e601d5-1326-47b1-a45c-c348ee510ce7.png)
![2](https://user-images.githubusercontent.com/76535242/132535735-cb91c93a-a977-40b0-9e72-4fb721270141.png)
![3](https://user-images.githubusercontent.com/76535242/132535739-443372d0-5e55-411b-b4a7-bd358331d23e.png)
![4](https://user-images.githubusercontent.com/76535242/132535741-040ad12d-2e33-4887-9d36-2eb72ee833f5.png)
![5](https://user-images.githubusercontent.com/76535242/132536606-c9bfcb26-6d66-4bc1-b901-f549d42ba8ab.png)

How can I fix this?

**Comment by peterpt** [comment]
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CBF8D6FD518E17E1 7638D0442B90D010

Then run ./chk_tools 
inside fatrat folder .

**Comment by miles8morales8** [comment]
> 
> 
> sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CBF8D6FD518E17E1 7638D0442B90D010
> 
> Then run ./chk_tools
> inside fatrat folder .

Heyy thanks !! TheFatRat is working now .
