### ISSUE TITLE
i need helpe

### ISSUE THREAD

**Issue by skreetz** [screetsec/TheFatRat#650]
xterm -> OK
Dns-Utils -> OK
Mono-Denvelop Utils -> OK
GCC -> OK
Apache2 -> OK
Gnome Terminal -> OK
UPX -> OK
Ruby -> OK
Python3 -> OK
Python3-pip -> OK
Openssl -> OK
Jarsigner -> OK
Unzip -> OK
Keytool -> OK
Zipalign -> Not OK
Mingw64 -> OK
Mingw32 -> OK
dx -> Not OK
aapt -> Not OK
apktool -> Not OK
Baksmali -> OK
Metasploit -> OK
Backdoor-Factory -> OK
Searchsploit -> OK

User path environment
-----------------------------------
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/jdk1.8.0_281/bin:/usr/lib/jvm/jdk1.8.0_281/db/bin:/usr/lib/jvm/jdk1.8.0_281/jre/bin"
-----------------------------------
User current repositories
-----------------------------------
#deb http://http.kali.org/kali kali-rolling main non-free contrib
#deb http://http.kali.org/kali kali-rolling main non-free contrib
-----------------------------------
-----------------------------------
Linux skreetz 5.14.0-kali2-amd64 #1 SMP Debian 5.14.9-2kali1 (2021-10-04) x86_64 GNU/Linux

**Comment by Morsmalleo** [comment]
Run this commands in your terminal to Install all of the missing dependencies

`sudo apt-get Install zipalign aapt apktool dx -y`

**Comment by skreetz** [comment]
> Run this command in your terminal to Install all of the missing dependencies
> 
> `sudo apt-get install zipalign aapt apktool dx -y`
> 
> Then Run the setup again `sudo ./setup.sh`

it's installed but, don't open

**Comment by peterpt** [comment]
Those particular packages come with fatrat , installing them will not solve anything .
You probably had installed fatrat previously in a different directory and the symlinks to those packages were still pointing to that old directory .

apt remove --purge zipalign aapt apktool dx -y && rm /usr/local/sbin/apktool && rm /usr/local/sbin/zipalign && rm /usr/local/sbin/aapt && rm /usr/local/sbin/dx

then run setup again from fatrat
