### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by RatJul** [screetsec/TheFatRat#652]
Hi guys i'm new user of github and kali linux too. I try to understand how to use this operating system so sorry if my question is idiot. 
I want to install the fat rat so i follow instructions i did git clone... cd TheFatRat, chmod +x setup.sh && ./setup.sh
but i've a problem with Python3-Pip
I try to install with apt-get install i try to upgrade with apt-get upgrade but nothing works.
When i launch i've

xterm -> OK
Dns-Utils -> OK
Mono-Denvelop Utils -> OK
GCC -> OK
Apache2 -> OK
Gnome Terminal -> OK
UPX -> OK
Ruby -> OK
Python3 -> OK
Python3-Pip -> Not OK
Openssl -> OK
Jarsigner -> OK
Unzip -> OK
Keytool -> OK
Zipalign -> OK
Mingw64 -> OK
Mingw32 -> OK
DX -> OK
Aapt -> OK
Apktool -> OK
Baksmali -> OK
Metasploit -> OK
Backdoor-Factory -> OK
Searchsploit -> OK
Was not possible to install The Packages Labeled (Not Ok) in this list above
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)
before running fatrat setup script again

I try apt-get remove --purge Python3-Pip && apt-get autoremove && apt-get install -f but that doesn't work.
If someone can help me... Thanks

**Comment by Morsmalleo** [comment]
This is an easy one to fix, just open up your terminal in Kali, and type the command `sudo apt update && sudo apt install python3-pip -y` then you run the `setup.sh` file inside TheFatRat folder again and it should be all goods 🙂

**Comment by RatJul** [comment]
i tried and the package can't be download idon't understand. I will show you:
sudo apt update && sudo apt install Python3-Pip -y
Hit:1 https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch InRelease
Get:3 https://download.docker.com/linux/debian stretch InRelease [44.8 kB]     
Get:2 http://archive-4.kali.org/kali kali-rolling InRelease [30.6 kB]          
Err:2 http://archive-4.kali.org/kali kali-rolling InRelease                    
  The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
Reading package lists... Done
N: Skipping acquire of configured file 'stable/binary-i386/Packages' as repository 'https://download.docker.com/linux/debian stretch InRelease' doesn't support architecture 'i386'
W: GPG error: http://archive-4.kali.org/kali kali-rolling InRelease: The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
E: The repository 'http://http.kali.org/kali kali-rolling InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

thanks for your help

**Comment by RatJul** [comment]
i start to think that the problem is not in the fat rat installation but i miss a package in my computer, i'm not sure

**Comment by Morsmalleo** [comment]
Ok what you need to do is either remove the repository `http://archive-4.kali.org/kali` from your sources.list or figure out how the add the pubkeys for it, as it's says in your comment, that release has not been signed so it's blocking your from updating and upgrading

**Comment by Morsmalleo** [comment]
It also looks like the repository `http://http.kali.org/kali` isn't signed either so do the same with this one as well, either figure out how to sign it by adding the pub-keys or remove it

**Comment by RatJul** [comment]
I'm using kali linux

**Comment by RatJul** [comment]
But idk more about version etc...

**Comment by RatJul** [comment]
i find my kernel version
root@thp3:~# uname -a
Linux thp3 4.14.0-kali3-amd64 #1 SMP Debian 4.14.17-1kali1 (2018-02-16) x86_64 GNU/Linux

**Comment by Morsmalleo** [comment]
Send me a screenshot of your `sources.list` file it should be located in the `/etc/apt/` directory. I will help you from there

**Comment by Morsmalleo** [comment]
> so if i understand i have to do a apt install http://archive-4.kali.org/kali ? and same for the other link? (or delete them)

You need to delete them

**Comment by Morsmalleo** [comment]
> so if i understand i have to do a apt install http://archive-4.kali.org/kali ? and same for the other link? (or delete them)

But first send screenshot of your `sources.list` file located at `/etc/apt/` directory

**Comment by RatJul** [comment]
root@thp3:~# cat /etc/apt/sources.list
# 

# deb cdrom:[Debian GNU/Linux 2018.1 _Kali-rolling_ - Official Snapshot amd64 LIVE/INSTALL Binary 20180126-21:23]/ kali-last-snapshot contrib main non-free

#deb cdrom:[Debian GNU/Linux 2018.1 _Kali-rolling_ - Official Snapshot amd64 LIVE/INSTALL Binary 20180126-21:23]/ kali-last-snapshot contrib main non-free

deb http://http.kali.org/kali kali-rolling main non-free contrib
# deb-src http://http.kali.org/kali kali-rolling main non-free contrib

i believe that's what you ask but i'm not sure

**Comment by Morsmalleo** [comment]
> root@thp3:~# cat /etc/apt/sources.list
> 
> # deb cdrom:[Debian GNU/Linux 2018.1 _Kali-rolling_ - Official Snapshot amd64 LIVE/INSTALL Binary 20180126-21:23]/ kali-last-snapshot contrib main non-free
> #deb cdrom:[Debian GNU/Linux 2018.1 _Kali-rolling_ - Official Snapshot amd64 LIVE/INSTALL Binary 20180126-21:23]/ kali-last-snapshot contrib main non-free
> 
> deb http://http.kali.org/kali kali-rolling main non-free contrib
> 
> # deb-src http://http.kali.org/kali kali-rolling main non-free contrib
> i believe that's what you ask but i'm not sure

Screenshot pls

**Comment by RatJul** [comment]
![image](https://user-images.githubusercontent.com/95176108/144077217-fc828d5a-d0cd-4a9a-8e8a-0474b429c916.png)

**Comment by Morsmalleo** [comment]
You must install the latest Kali archive keyring

**Comment by RatJul** [comment]
but how i do?

**Comment by Morsmalleo** [comment]
`sudo apt install kali-archive-keyring`

**Comment by RatJul** [comment]
![image](https://user-images.githubusercontent.com/95176108/144218292-21405125-ceff-454c-85c1-4050e5c5fc47.png)

**Comment by RatJul** [comment]
i think that's wrong "2 not upgraded"

**Comment by RatJul** [comment]
![image](https://user-images.githubusercontent.com/95176108/144218565-ed2513af-a685-4842-af4c-bcec327dcef9.png)

**Comment by Morsmalleo** [comment]
Ok copy and paste, or type this for me in your terminal and run it 

`sudo mousepad /etc/apt/sources.list`
If you do not have mousepad installed then type the command 
`sudo apt install mousepad && sudo mousepad /etc/apt/sources.list`

**Comment by RatJul** [comment]
![image](https://user-images.githubusercontent.com/95176108/144224536-fcc62203-cdca-4670-abef-656cb36fcf01.png)

**Comment by RatJul** [comment]
i find!! that was a problem with my keyring archive you were true, i download a new archive and i update my keyring packages everything is okay! now i need to come back to thefatrat

**Comment by RatJul** [comment]
oh no, i've a new problem :(

**Comment by RatJul** [comment]
![image](https://user-images.githubusercontent.com/95176108/144230134-001efb09-30aa-4184-ba02-1584aab836a5.png)

**Comment by RatJul** [comment]
i try to run fatrat and everything is ok! thank you so much!

**Comment by RatJul** [comment]
i don't know what was the problem but it don't seems really important

**Comment by peterpt** [comment]
why do you have so many repositories for kali where only 1 of them will upgrade kali distribution ?

Multiple repositories will break your linux distribution .
I think you should remove that microsoft repository and that debian stretch repository and have only kali in your sources.list , and then do apt-get upgrade

However i surelly believe that those repositories i told you are not in sources.list file  but instead inside the folder /etc/apt/sources.list.d/ directory .

write in your terminal : cd /etc/apt/sources.list.d && ls

and tell me what files are inside that folder .
