### ISSUE TITLE
When u exit the tool it autoremove itself?

### ISSUE THREAD

**Issue by czonta96** [screetsec/TheFatRat#653]
Are we joking?

**Comment by Morsmalleo** [comment]
This does not detail much at all, be more specific please

**Comment by czonta96** [comment]
I pressed CTRL+C to just shutdown TheFatRat but when I tried to open it again it just disappeared from the system
I know there are a lots of idiots uploading TheFatRat's artifacts on VirusTotal but this is too much, if I'm forced to reinstall it everytime I want to just shut it down this is going to drain a lot of hard disk storage for nothing

There is a string somewhere I can edit from myself to remove the auto-uninstall feature?

**Comment by Morsmalleo** [comment]
This should not be happening at all, I've never heard of this happening with TheFatRat, first time I have heard of it happening at all to be honest. I'll call on the Devs for this one

**Comment by Morsmalleo** [comment]
@peterpt any chance of some light shed on this one if you have time mate?

**Comment by czonta96** [comment]
I will try to fix issue on myself, I was just reporting error.
I noticed FUD backdoors from this tool dont connect back to my listener despite everything seems to be fine
It's tool error ?

**Comment by Morsmalleo** [comment]
> I will try to fix issue on myself, I was just reporting error. I noticed FUD backdoors from this tool dont connect back to my listener despite everything seems to be fine It's tool error ?

They do connect back it just takes time due to the encryption and evasion techniques used

**Comment by peterpt** [comment]
"@peterpt any chance of some light shed on this one if you have time mate?"
No .
That user probably have an environment issue or have other fatrat installations spread over the system , this can confuse the symlinks created by fatrat .

Pressing CTRL+C during fatrat will execute the function "ctrl_c" on line 1168 of fatrat code in :
https://github.com/screetsec/TheFatRat/blob/master/fatrat

Witch is saying "goodbye" and stop postgresql , metasploit & apache2 services .
Nothing else .

**Comment by Morsmalleo** [comment]
> I will try to fix issue on myself, I was just reporting error. I noticed FUD backdoors from this tool dont connect back to my listener despite everything seems to be fine It's tool error ?

Peterpt has provided you your answer
