### ISSUE TITLE
help me if someone have this video

### ISSUE THREAD

**Issue by saliman43** [screetsec/TheFatRat#659]
**help me if someone have this video**

TheFatRat - Hacking Over WAN - Embedding Payload in Original Android APK - Without Port Forwarding
Plz Help Me to find this video tnx

**Comment by coderscoding** [comment]
Howw? It's not possible without port forwarding when u want over WAN. Or else make your IP available over Internet so you don't need Port Forwarding.

**Comment by saliman43** [comment]
> Howw? It's not possible without port forwarding when u want over WAN. Or else make your IP available over Internet so you don't need Port Forwarding.

just need this video TheFatRat - Hacking Over WAN - Embedding Payload in Original Android APK 
I search on YouTube but YouTube block it

**Comment by saliman43** [comment]
> Howw? It's not possible without port forwarding when u want over WAN. Or else make your IP available over Internet so you don't need Port Forwarding.

I know it is impossible but I want to see this video that is in documentation of the fat rat
here is link https://www.youtube.com/watch?v=XLNigYZ5-fM 
it is block by YouTube if you have plz send me
