### ISSUE TITLE
installed python-dev with the methods here https://github.com/screetsec/TheFatRat/issues/578, but checktools can't find it

### ISSUE THREAD

**Issue by anAverageGithubUser** [screetsec/TheFatRat#663]

**Comment by anAverageGithubUser** [comment]
screen shot 1:
![image](https://user-images.githubusercontent.com/68261264/147190471-34caa4ee-42ec-430e-bc4c-15d1dd5d6df8.png)

**Comment by anAverageGithubUser** [comment]
I think python-dev wasn't installed after installing libpython2.7-stdlib

**Comment by anAverageGithubUser** [comment]
I am using kali linux 2021.4 in an virtual machine

**Comment by peterpt** [comment]
check tools run this command to check if python dev is installed : 
apt-cache policy python-dev

Run yourself this command in your terminal , if there is nothing ahead after (Installed:) in output then you dont have python-dev installed surelly .
