### ISSUE TITLE
Unable to recompile apk due to the lack of the apktool parameter `--use-aapt2`   

### ISSUE THREAD

**Issue by legilimency31** [screetsec/TheFatRat#666]
**Problem :** After choosing to Embed a Metasploit Payload in an original .apk files, i got this error :

```
Testing your apk before next step ...Error
Apktool in unable to recompile this apk
```
**Explanation of the cause of the problem** : Seems related to the usage of `--use-aapt1` instead of `--use-aapt2` during recompilation, according to [this](https://github.com/rapid7/metasploit-framework/issues/11320) metasploit issue. And according to [this](https://github.com/iBotPeaches/Apktool/issues/1978) apktool issue, the usage of `--use-aapt2` as a parameter can solve this failure to recompile. And indeed, i coulndt recompile with `sudo apktool b app.apk`, but i could with `sudo apktool b --use-aapt2 app.apk`.

**Cause of the problem :** The problem, i think, is that, just as the metasploit [issue](https://github.com/rapid7/metasploit-framework/issues/11320), FatRat dosent allow to select `--use-aapt2` as a parameter when recompiling, so apktool fails just as it failed when i didnt typed the `--use-aapt2` parameter to recompile an apk. 

Questions :
Is this (need of `--use-aapt2` paramenter from apktool) an situation caused by the specific apk that im rebuilding  ? Or is it a general problem for all apks ? And more important : There is a way to solve this problem ?

**Comment by peterpt** [comment]
fatrat sends your apk to apktool first to decompile and recompile it again without any payload , if apktool is unable to recompile your apk without the payload then less chances will had to compile it with it .
only the payload for apk is generated by metasploit , all the other processes , decompile , merge , recompile and sign are not made by metasploit but by apktool itself with android sdk tools inside fatrat folders .

**Comment by peterpt** [comment]
I will investigate this further as soon as i get sometime here , however you should check if that recompiled apk file is installing , recompiling does not mean it will work .

**Comment by leitowin80-maker** [comment]
como genero la apk entonces manualmente
