### ISSUE TITLE
The FatRat Installation Issue (mingw-32 Error) 

### ISSUE THREAD

**Issue by yarzarshwewin** [screetsec/TheFatRat#667]
Hi, 

Currently, I'm facing installation issue with the FATRAT. 
I've referenced the below links and tried to follow up but still have issue.
After following up with the thread, i could able to install mingw-x64.
But mingw-32 still have an issue as the screenshot attached.

https://github.com/Screetsec/TheFatRat/issues/244
https://stackoverflow.com/questions/63920766/thefatrat-installation-issues-mingw-32-%E2%86%92not-ok-mingw-w64-%E2%86%92-not-ok
https://giters.com/screetsec/TheFatRat/issues/600

I've attached the all the logs and screenshot for your reference.
Thanks in advance for your support.

[apt.log](https://github.com/screetsec/TheFatRat/files/7852786/apt.log)
[aptdebug.log](https://github.com/screetsec/TheFatRat/files/7852788/aptdebug.log)
![FATRAT-mingw32](https://user-images.githubusercontent.com/97425450/149089602-45d6bfff-5f97-4f10-bc4d-70868f520006.png)

**Comment by sinbad08** [comment]
a have the same problem , i cant install mingw23 and mingw64 .

**Comment by Morsmalleo** [comment]
Mingw32 and mingw-w64 need to be installed from the Debian Jessie software repo for Kali run these commands below to I stall the correct version of mingw which from memory is 9.4.1

#### First install the Pubkeys 
-     git clone https://GitHub.com/Morsmalleo/Kali-Jessie-Keys && cd Kali-Jessie-Keys
-     cp debian-archive-jessie-automatic.gpg  debian-archive-jessie-security-automatic.gpg debian-archive-jessie-stable.gpg /etc/apt/trusted.gpg.d

#### Now add the mirrors
-     touch deb.list && echo "deb http://deb.debian.org/debian jessie main contrib non-free" >> deb.list
-     mv deb.list /etc/apt/sources.list.d/

#### Install mingw32 and mingw-w64 from Jessie
- sudo apt-get install -t jessie mingw32* mingw-w64*

If you have any problems with packages being I stalled from other mirrors other than the Jessie mirror then youll need to comment out other apt repositories by editing the `sources.list` file as well as any other `*.list` file, and marking the `http` mirrors with a `#` next to where it would read `deb/deb-src`

**Comment by peterpt** [comment]
Remove your current fatrat installation , clone it again and follow the instructions in readme file .

**Comment by yarzarshwewin** [comment]
@Morsmalleo Thank you so much for your support. I've followed with your instructions but after I run the following command below, the error 

**E: The value 'jessie' is invalid for APT::Default-Release as such a release is not available in the sources**

Install mingw32 and mingw-w64 from Jessie
sudo apt-get install -t jessie mingw32* mingw-w64*

**Comment by Morsmalleo** [comment]
> @Morsmalleo Thank you so much for your support. I've followed with your instructions but after I run the following command below, the error
> 
> **E: The value 'jessie' is invalid for APT::Default-Release as such a release is not available in the sources**
> 
> Install mingw32 and mingw-w64 from Jessie sudo apt-get install -t jessie mingw32* mingw-w64*
> 
> My Sourcelist is as below. ![Screenshot_2022-01-26_18_40_59](https://user-images.githubusercontent.com/97425450/151270582-b3267b06-cd2b-48be-be6b-66938dcc19c2.png)

Oops my bad, I don't think using the `*` for the packages works so try this instead

    sudo apt install -t jessie mingw32 mingw-w64 -y

**Comment by yarzarshwewin** [comment]
@Morsmalleo the result is as below.
![Screenshot_2022-01-26_19_22_20](https://user-images.githubusercontent.com/97425450/151274491-038e8e76-99d0-468c-bdd3-6650728c7e89.png)

**Comment by Morsmalleo** [comment]
Did you run `sudo apt update` after running the first set of commands??

**Comment by Morsmalleo** [comment]
Try this 

    sudo apt update && Sudo apt install -t jessie mingw32 mingw-w64 -y

**Comment by yarzarshwewin** [comment]
@Morsmalleo Thank you so much for your support. It's working now. 👍 💯

**Comment by Morsmalleo** [comment]
> @Morsmalleo Thank you so much for your support. It's working now. 👍 💯

No problem 😃

**Comment by yarzarshwewin** [comment]
@sinbad08 bro you may reference this. I'm not sure if you have a similar issue or not. For me, it works100%.
