### ISSUE TITLE
There was an error creating the baackdoor  

### ISSUE THREAD

**Issue by ydecl** [screetsec/TheFatRat#669]
![屏幕截图 2022-01-17 124709](https://user-images.githubusercontent.com/53930390/149709556-edcfcd02-bc49-43b9-9d78-9a03c1b651cd.png)

一直提示这个

**Comment by martdev123** [comment]
thefatrat coding is old, you have to look for newest hacking tools
i opened recently a repository with a signature-changing toolkit for kali

**Comment by gieuci0x** [comment]
Which one android remote access could you recommend guys?

**Comment by peterpt** [comment]
Be explicit in witch option you used in fatrat , selection of payload .
