### ISSUE TITLE
setup.sh

### ISSUE THREAD

**Issue by whismerilh** [Screetsec/TheFatRat#67]
hello, in Kali-rolling the setup.sh doesn't works error:
Setup Detected that your previous run was interrupted in middle , fixing your original repositories list .
Your Original repository list was recovered. ;) ..... beginning setup

Cleaning previous repositories cache & updating your repository .

./setup.sh: ligne 49: erreur de syntaxe près du symbole inattendu « fi »
./setup.sh: ligne 49: `fi'

have you got a solution, please ?

**Comment by Screetsec** [comment]
wkwkwkww , forgot delte some line sorry  .. now donee
check this out 
https://github.com/Screetsec/TheFatRat/commit/14f173afdb2e1fd75a8b0fc714f1a0c9782c056f

**Comment by whismerilh** [comment]
thank you , you're the best.
