### ISSUE TITLE
Youtube Videos Taken Down

### ISSUE THREAD

**Issue by yarzarshwewin** [screetsec/TheFatRat#672]
Dear Author,

Thank you very much for your effort.
Is it possible to upload the video on another hosting such as the video below, youtube has take down.
Bind FUD Payload with JPG and Hack over WAN with TheFatRat
Please kindly share us via new source.
Thanks in advance.

**Comment by Morsmalleo** [comment]
YouTube won't allow videos like this, even with all my AhMyth videos from my updated version of AhMyth, I've battled YouTube for ages about them taking videos down that don't even show any hacking of any device, YouTube are just sensitive bastards, I'm sure there will be another video around like that 🙂

**Comment by yarzarshwewin** [comment]
I mean can share on google drive or some kind of repository that's free. Since I'm new, i'm not so familiar with the practices here. I'm sry if i misinterpret.

**Comment by Morsmalleo** [comment]
That's ok mate, I misinterpret things myself when it comes to this sort of stuff, don't stress, so you were trying to watch a video of Binding a FUD FatRat payload with a JPG file is this correct???
