### ISSUE TITLE
Listener for avoid

### ISSUE THREAD

**Issue by arnav7633** [screetsec/TheFatRat#676]
Hey! Once I start a rat made with avoid option what payload I select is msfconsole?

**Comment by peterpt** [comment]
windows/meterpreter/reverse_tcp

**Comment by arnav7633** [comment]
Thanks for the response!
But I am having a issue that the application cannot be run  on my PC I am running windows 10 latest version

**Comment by peterpt** [comment]
yes i notice that yesterday when i try to use the payload on a 32bit and on a 64bit windows machine , Avoid 1st option is not working , others did not tried yet .
That payload from avoid is supposed to work on windows and linux , on windows forget it , linux did not tried yet . Edo wrote avoid code in fatrat and i have no idea where did he got the c lines of code in that option , my guess is that those c codes are incompatible with windows , not sure .
https://github.com/screetsec/TheFatRat/blob/master/fatrat
The payload for avoid can be read in line 5447
and the C code i am speaking is between line 5682 and 5697 .

No idea when they will be fixed .

**Comment by MATRIX-hc2** [comment]
i have the same proplem man can you fix it please i will be thanks

**Comment by peterpt** [comment]
there is no way to fix this for now
