### ISSUE TITLE
TfeFatRat No output folder when creating rat

### ISSUE THREAD

**Issue by furkan9ne** [screetsec/TheFatRat#678]
hello friends, when using the fat rat program, there is no output folder, the viruses that I created do not appear, I tried every way, please help me, I'm about to go crazy

**Comment by peterpt** [comment]
If you did not selected any specific output folder for fatrat generated payloads during setup then all files will be in /root/fatrat_generated  folder by default . If you want them in any specific other folder than this one the run setup again and at some point in setup it will ask you where do you want fatrat generated files .

**Comment by furkan9ne** [comment]
hi bro, can you help me by connecting to my computer remotely because i am
trying hard and i am not getting any results

1 Şub 2022 Sal 11:39 tarihinde peterpt ***@***.***> şunu
yazdı:

**Comment by peterpt** [comment]
It looks that for what you need there is no need for fatrat .
rdesktop app installed in linux can easily connect to a windows machine , all you have to do is to activate remote desktop in windows .
Search microsoft in how to activate remote desktop in windows .

**Comment by peterpt** [comment]
You came to the wrong place , this is not a school for linux here , and in here we deal only with fatrat code issues or bugs . Your question does not have anything related to any of those things i said before . Next time when you run setup from fatrat read carefully what each question means .
