### ISSUE TITLE
Apktool in unable to recompile this apk error

### ISSUE THREAD

**Issue by 001zahi** [screetsec/TheFatRat#680]
### When I Backdoor an apk in FatRat its showing up 

#Enter the path to your android app/game .(ex: /root/downloads/myapp.apk)

 Path : /home/zahi/Downloads/Instagram.apk

Testing your apk before next step ...Error
**Apktool in unable to recompile this apk**

Press [ENTER] key to return to menu

**Comment by 001zahi** [comment]
**_### how to solve it_**

**Comment by peterpt** [comment]
If there was a way to solve it then we already had fix it , that issue is related to apktool that is unable to recompile the selected user apk .
