### ISSUE TITLE
Can't use microsploit

### ISSUE THREAD

**Issue by wildandotid** [Screetsec/TheFatRat#69]
I use microsploit for creating microsoft office backdoor.
I found this error after creating [2] The Microsoft Office Macro on Windows :
mv: cannot stat ‘/home/silentc0ders/.msf4/local/wwww.docm’: No such file or directory

TheFatRat 1.9.2

**Comment by peterpt** [comment]
I made some changes in fatrat today that will help us identify what is the cause of the error .
you have to wait until Original Fatrat repository here gets updated with latest changes .

**Comment by Screetsec** [comment]
@peterpt thanks will be merge , do clean pull request wkkw
