### ISSUE TITLE
i try to install the tool but i am missing the gnome-terminal and when I try to install that well..

### ISSUE THREAD

**Issue by ManusuperJ** [Screetsec/TheFatRat#690]
xterm -> OK
Dns-Utils -> OK
Mono-Denvelop Utils -> OK
GCC -> OK
Apache2 -> OK
gnome-terminal -> Not OK
UPX -> OK
Ruby -> OK
Python2 -> OK
Python3 -> OK
Python3-pip -> OK
Openssl -> OK
Jarsigner -> OK
Unzip -> OK
Keytool -> OK
Zipalign -> OK
mingw-w64 -> Not OK
mingw-32 -> Not OK
DX -> OK
Aapt -> OK
Apktool -> OK
Baksmali -> OK
Metasploit -> OK
Backdoor-Factory -> OK
Searchsploit -> OK
Was not possible to install The Packages Labeled (Not Ok) in this list above
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)
before running fatrat setup script again

and this is the output when i try to install it..

oot@vps-b993d428:/home/juan/Random/TheFatRat# sudo apt-get install gnome-terminal
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package gnome-terminal is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gnome-terminal' has no installation candidate

Can somebody help me?

**Comment by peterpt** [comment]
you never updated your OS , your repository list file should have no sources for updates , depending on witch linux OS you are using , search on their website witch are the repositories that you should add to sources.list file , then update and upgrade your distribution and after all that run setup from fatrat .
