### ISSUE TITLE
error -- help!!!

### ISSUE THREAD

**Issue by verico1** [Screetsec/TheFatRat#70]
____ _               _    _                   
  / ___| |__   ___  ___| | _(_)_ __   __ _             
 | |   | '_ \ / _ \/ __| |/ / | '_ \ / _\ |            
 | |___| | | |  __/ (__|   <| | | | | (_| |  _   _   _ 
  \____|_| |_|\___|\___|_|\_\_|_| |_|\__/ | (_) (_) (_)
                                        |___/    
-- -- +=[(c) 2016-2017 | dracos-linux.org | Linuxsec.org | Hacker Indonesia 
-- -- +=[ Author: Screetsec < Edo Maland >  ]=+ -- -- 
 
[!]::[Check Dependencies]:
[✔]::[Distro]: ubuntu
[✔]::[Check User]: root
[✔]::[Internet Connection]: connected!
[✔]::[Apache2 Server ubuntu ]: installation found!
[✔]::[Ruby]: installation found!
[✔]::[Apktool]: installation found!
[✔]::[Aapt]: installation found!
[✔]::[Msfconsole]: installation found!
[✔]::[Msfvenom]: installation found!
[✔]::[Zenity]: installation found!
[x]::[warning]:this script require mingw32 or 64 installed to work

[!]::Run setup.sh to install ming32
verico@oem-Aspire-V5-571G:~/Desktop/TheFatRat$

**Comment by peterpt** [comment]
ok , thanks for letting us know .
It looks that we have to change a bit the setup.sh and install that package under kali repository .
your current Os repository must have that package with other name .

**Comment by Screetsec** [comment]
@verico1 first do chmod +x  and then running setup.sh thanks

**Comment by verico1** [comment]
@Screetsec 

___________         __  __________          __    
\_   _____/_____  _/  |_\______   \_____  _/  |_  
 |    __)  \__  \ \   __\|       _/\__  \ \   __\ 
 |     \    / __ \_|  |  |    |   \ / __ \_|  |   
 \___  /   (____  /|__|  |____|_  /(____  /|__|   
     \/         \/              \/      \/        
                 ____    ________                 
                /_   |  /   __   \                
                 |   |  \____    /                
                 |   |     /    /                 
                 |___| /\ /____/                  
                       \/                         

          Setup Script for FATRAT 1.9       
 [ ✔ ] Xterm.............................[ found ]
 [ ✔ ] Zenity............................[ found ]
 [ ✔ ] Gcc compiler......................[ found ]
 [ X ] mingw32 compiler  -> not found 
 [ ! ]   Installing Mingw32 
 [ ✔ ] Done installing .... 
 [ ✔ ] Monodevelop ......................[ found ]
 [ ✔ ] Apache2 ..........................[ found ]
 [ ✔ ] Gnome Terminal....................[ found ]
 [ ✔ ] UPX Compressor....................[ found ]
 [ ✔ ] Ruby..............................[ found ]
 [ ✔ ] Jarsigner (java)..................[ found ]
 [ ✔ ] Unzip.............................[ found ]
 [ ✔ ] Keytool (java)....................[ found ]
 [ ! ] Installing dedendencies for ruby script
 [ ✔ ] Done installing ....
 [ ✔ ] Zipalign 
 [ ✔ ] Proguard 
^C [ ✔ ] Dx & Aapt.........................[ found ]
 [ ✔ ] Apktool 2.2.2.....................[ found ]
 [ ✔ ] Dex2Jar...........................[ found ]
 [ ✔ ] Metasploit-Framework..............[ found ]
 [ X ] backdoor-factory  -> not found 


(zenity:22675): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(zenity:22675): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(zenity:22675): Gtk-WARNING **: Theme parsing error: gtk.css:70:34: The style property GtkCheckButton:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(zenity:22675): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by verico1** [comment]
@Screetsec 

I think I need to : mingw32 or 64
[x]::[warning]:this script require mingw32 or 64 installed to work

[!]::Run setup.sh to install ming32
verico@oem-Aspire-V5-571G:~/Desktop/TheFatRat$

**Comment by peterpt** [comment]
did you wrote git pull on your fatrat directory ?

Best way to fix this : 
remove your fatrat directory

clone again
and execute setup.sh

**Comment by verico1** [comment]
@peterpt 

So again I download ?
You sure will be okay ?

**Comment by peterpt** [comment]
yes , it will be fine .

**Comment by verico1** [comment]
@peterpt

Thankful
