### ISSUE TITLE
.

### ISSUE THREAD

**Issue by gumbobrot** [Screetsec/TheFatRat#701]
.

**Comment by Morsmalleo** [comment]
This should have been fixed Ages ago, I'm not sure why it's happening... 

@peterpt

**Comment by senortrashcan** [comment]
Ran into the same issue. running "apt-get remove --purge mingw-w64 && apt-get autoremove && apt-get install -f" didn't work for me either. Any ideas?

**Comment by senortrashcan** [comment]
Ran into the same issue. running "apt-get remove --purge mingw-w64 && apt-get autoremove && apt-get install -f" didn't work for me either. Any ideas?

**Comment by Morsmalleo** [comment]
I'll run everyone through the manual way of doing this 


### Step 1: Create a Deb.list file

    touch deb.list
#
### Step 2: echo the Jessie repository mirror into the deb.list file 

    echo "deb http://deb.debian.org/debian jessie main contrib non-free" >> deb.list
#
### Step 3: move the Deb.list file to `/etc/apt/sources.list.d/`

    mv deb.list /etc/apt/sources.list.d/
#
### Step 4: grab the old Kali Jessie keys from GitHub

    git clone https://GitHub.com/Morsmalleo/Kali-Jessie-Keys
#
### Step 5: Move all 3 files inside the `Kali-Jessie-Keys` folder to `/etc/apt/trusted.gpg.d/` 

    mv Kali-Jessie-Keys/{debian-archive-jessie-automatic.gpg,debian-archive-jessie-security-automatic.gpg,debian-archive-jessie-stable.gpg} /etc/apt/trusted.gpg.d/
#
### Step 6: Run an update and hash out other repositories in your `sources.list` by marking them with a # symbol next to where it would read `deb/deb-src` so they don't interfere with the later installation of mingw for TheFatRat

    apt-get update && mousepad /etc/apt/sources.list

your sources.list file should look something like the example below, doesn't matter if the link I've used works or not it's just an example of what your sources.list file should look like

#### EXAMPLE
`# deb http://kali.download.org/Kali rolling main contrib non-free`
#
### Step 7: Install Mingw 

    apt-get install -t jessie mingw32 mingw-w64

**Comment by Morsmalleo** [comment]
> I'll run everyone through the manual way of doing this, copy the quick use commands from below to do it correctly
> 
> **Step 1:** Create a Deb.list file
> 
> ```
> touch deb.list
> ```
> 
> **Step 2:** echo the Jessie repository mirror into the deb.list file
> 
> ```
> echo "deb http://deb.debian.org/debian jessie main contrib non-free" >> deb.list
> ```
> 
> **Step 3:** move the Deb.list file to `/etc/apt/sources.list.d/`
> 
> ```
> mv deb.list /etc/apt/sources.list.d/
> ```
> 
> **Step 4:** grab the old Kali Jessie keys from GitHub
> 
> ```
> git clone https://GitHub.com/Morsmalleo/Kali-Jessie-Keys
> ```
> 
> **Step 5:** Move all 3 files inside the `Kali-Jessie-Keys` folder to `/etc/apt/trusted.gpg.d/`
> 
> ```
> mv Kali-Jessie-Keys/{debian-archive-jessie-automatic.gpg,debian-archive-jessie-security-automatic.gpg,debian-archive-jessie-stable.gpg} /etc/apt/trusted.gpg.d/
> ```
> 
> **Step 6:** hash out other repositories in your `sources.list` by marking them with a `#` symbol next to where it would read `deb/deb-src` so they don't interfere with the later installation of mingw for TheFatRat
> 
> ```
> mousepad /etc/apt/sources.list
> ```
> 
> your sources.list file should look something like the example below, doesn't matter if the link I've used works or not it's just an example of what your sources.list file should look like
> 
> #### EXAMPLE
> `# deb http://kali.download.org/Kali rolling main contrib non-free`
> 
> **Step 7:** Run an update to activate the Jessie repository and deactivate the ones you commented out before using the `#` symbol, and then Install Mingw
> 
> ```
> apt-get update && apt-get install -t jessie mingw32 mingw-w64
> ```

For the record this problem should have already been fixed Ages ago I'm not sure why it's come back up again

**Comment by Morsmalleo** [comment]
For the record this issue was saved ages ago with updates to the coding, so I'm not sure why it's come back up again, I'll recreate the issue on a new Kali VM  if possible and report it to the Devs, I live to help 😊

**Comment by ghost** [comment]
hey

> For the record this issue was solved ages ago with updates to the coding, so I'm not sure why it's come back up again, I'll recreate the issue on a new Kali VM if possible and report it to the Devs, I live to help blush



> I'll run everyone through the manual way of doing this, copy the quick use commands from below to do it correctly
> 
> **Step 1:** Create a Deb.list file
> 
> ```
> touch deb.list
> ```
> 
> **Step 2:** echo the Jessie repository mirror into the deb.list file
> 
> ```
> echo "deb http://deb.debian.org/debian jessie main contrib non-free" >> deb.list
> ```
> 
> **Step 3:** move the Deb.list file to `/etc/apt/sources.list.d/`
> 
> ```
> mv deb.list /etc/apt/sources.list.d/
> ```
> 
> **Step 4:** grab the old Kali Jessie keys from GitHub
> 
> ```
> git clone https://GitHub.com/Morsmalleo/Kali-Jessie-Keys
> ```
> 
> **Step 5:** Move all 3 files inside the `Kali-Jessie-Keys` folder to `/etc/apt/trusted.gpg.d/`
> 
> ```
> mv Kali-Jessie-Keys/{debian-archive-jessie-automatic.gpg,debian-archive-jessie-security-automatic.gpg,debian-archive-jessie-stable.gpg} /etc/apt/trusted.gpg.d/
> ```
> 
> **Step 6:** hash out other repositories in your `sources.list` by marking them with a `#` symbol next to where it would read `deb/deb-src` so they don't interfere with the later installation of mingw for TheFatRat
> 
> ```
> mousepad /etc/apt/sources.list
> ```
> 
> your sources.list file should look something like the example below, doesn't matter if the link I've used works or not it's just an example of what your sources.list file should look like
> #### EXAMPLE
> 
> `# deb http://kali.download.org/Kali rolling main contrib non-free`
> 
> **Step 7:** Run an update to activate the Jessie repository and deactivate the ones you commented out before using the `#` symbol, and then Install Mingw
> 
> ```
> apt-get update && apt-get install -t jessie mingw32 mingw-w64
> ```

i got this
`┌─[root@The-Concierge-of-Crime]─[/home/raymond/Desktop/TheFatRat]
└──╼ #apt-get update && apt-get install -t jessie mingw32 mingw-w64
Hit:1 https://deb.parrot.sh/parrot lts InRelease
Hit:2 https://deb.parrot.sh/parrot parrot InRelease
Hit:3 https://deb.parrot.sh/direct/parrot parrot-security InRelease
Ign:4 http://deb.debian.org/debian jessie InRelease
Hit:5 https://deb.parrot.sh/parrot parrot-backports InRelease
Get:6 http://deb.debian.org/debian jessie Release [77.3 kB]
Get:7 http://deb.debian.org/debian jessie Release.gpg [1,652 B]
Ign:7 http://deb.debian.org/debian jessie Release.gpg
Reading package lists... Done
W: GPG error: http://deb.debian.org/debian jessie Release: The following signatures were invalid: REVKEYSIG 7638D0442B90D010 Debian Archive Automatic Signing Key (8/jessie) <ftpmaster@debian.org> EXPKEYSIG CBF8D6FD518E17E1 Jessie Stable Release Key <debian-release@lists.debian.org> 75DDC3C4A499F1A18CB5F3C8CBF8D6FD518E17E1
E: The repository 'http://deb.debian.org/debian jessie Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by Morsmalleo** [comment]
You haven't followed all the instructions properly, you are missing the Pubkeys, follow the steps below

-     git clone https://GitHub.com/Morsmalleo/Kali-Jessie-Keys
-     mv Kali-Jessie-Keys/{debian-archive-jessie-automatic.gpg,debian-archive-jessie-security-automatic.gpg,debian-archive-jessie-stable.gpg} /etc/apt/trusted.gpg.d
-     apt-get update && apt-get install mingw32 mingw-w64

Before you run the update and install mingw, Make sure you comment out other apt repositories in your `sources.list` file by marking them with `#`, if using `nano` on Kali, the repository link should turn blue signifying it is indeed hashed out.

**Comment by bilbo-v** [comment]
> You haven't followed all the instructions properly, you are missing the Pubkeys, follow the steps below
> 
>     * ```
>       git clone https://GitHub.com/Morsmalleo/Kali-Jessie-Keys
>       ```
> 
>     * ```
>       mv Kali-Jessie-Keys/{debian-archive-jessie-automatic.gpg,debian-archive-jessie-security-automatic.gpg,debian-archive-jessie-stable.gpg} /etc/apt/trusted.gpg.d
>       ```
> 
>     * ```
>       apt-get update && apt-get install -t jessie mingw32 mingw-w64
>       ```
> 
> 
> Before you run the update and install mingw, Make sure you comment out other apt repositories in your `sources.list` file by marking them with `#`, if using `nano` on Kali, the repository link should turn blue signifying it is indeed hashed out.

encountered same problem

**Comment by crackplatoonbd** [comment]
tried everything possible , still same problem
