### ISSUE TITLE
No module named 'names'

### ISSUE THREAD

**Issue by MaJoRX0** [Screetsec/TheFatRat#702]
`Traceback (most recent call last):
  File "/home/x5oc/TheFatRat/tools/power.py", line 19, in <module>
    import names
ModuleNotFoundError: No module named 'names'
`

**Comment by Morsmalleo** [comment]
Run the command below based on your user level type (i.e if you are root user or not)

As Root User

    $ pip3 install names

As Non-root user

    $ sudo pip3 install names

**Comment by MaJoRX0** [comment]
> Run the command below based on your user level type (i.e if you are root user or not)
> 
> As Root User
> 
> ```
> $ pip3 install names
> ```
> 
> As Non-root user
> 
> ```
> $ sudo pip3 install names
> ```

I tried it before it already installed but it still shows my this error

`┌──(x5oc㉿x5oc)-[~/TheFatRat/logs]
└─$ pip3 install names                                 
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: names in /home/x5oc/.local/lib/python3.9/site-packages (0.3.0)
`

**Comment by Morsmalleo** [comment]
Type command 

    pip -v 

And post the output here

**Comment by MaJoRX0** [comment]
> Type command
> 
> ```
> pip -v 
> ```
> 
> And post the output here

are u sure pip -v ? it shows the commands list and options

**Comment by Morsmalleo** [comment]
Oops my bad 

    pip --version 

That should work

**Comment by MaJoRX0** [comment]
> 

`pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.9)
`

**Comment by Morsmalleo** [comment]
Ok I think I see the problem, I THINK...

run this command first

    pip uninstall names

TheFatRat is a root application, so `names` must be install in the root directory, running this command should do it

    sudo pip3 install names 

Make sure you run it with `sudo`

**Comment by MaJoRX0** [comment]
> ```
> sudo pip3 install names 
> ```

well, thank you it did work.
I have another question about where I can test the files it seems www.nodistribute.com is down rn

**Comment by Morsmalleo** [comment]
You're most welcome! 

I am not to sure on that one give me 1 minute and I'll do some research

**Comment by Morsmalleo** [comment]
Yeah I'm not to sure man on that one man sorry, as for nodistribute I have no idea what's happening, maybe they're doing maintenance or maybe it's been shut down, not sure.

**Comment by Morsmalleo** [comment]
Please close this issue as it has been resolved.
