### ISSUE TITLE
Sessions

### ISSUE THREAD

**Issue by Hamlet3211** [Screetsec/TheFatRat#738]
When I connect to my tablet at home it works instantly. When I try to connect to a person phone across town(my bro for testing) it won't find it.

**Comment by Hamlet3211** [comment]
I should be able to connect to any phone that has the payload correct?

**Comment by peterpt** [comment]
when the payload is generated you probably used your internal network ip address , this means that the payload when it starts it will connect to that ip , but if the victim device it is on a different network then you will never be able to get it connected to you on a different network . For that to work you must use your public ip address assigned by your internet provider to the payload , and then you have to configure your isp router to forward any outside connections from a specific port to your ip address inside your network , it should work , but i never tested it that way .
