### ISSUE TITLE
Failed to embed a Backdoor on Original apk file

### ISSUE THREAD

**Issue by 5P4D3** [Screetsec/TheFatRat#75]
[!] Failed to recompile original project with backdoor

**Comment by peterpt** [comment]
without more details we are unable to help you .

**Comment by 5P4D3** [comment]
what kind of details is needed ? ill make a screen shot mateys.

**Comment by 5P4D3** [comment]
![failed](https://cloud.githubusercontent.com/assets/18681023/24088742/2e360d0c-0d69-11e7-89ff-3cb53b211b90.png)

**Comment by peterpt** [comment]
what does your apk.log file say ?
check in /log directory

**Comment by 5P4D3** [comment]
cant find the log file.. what is the default log directory?
