### ISSUE TITLE
ROOT ISSUE

### ISSUE THREAD

**Issue by flashbackboi** [Screetsec/TheFatRat#794]
IT keeps saying on parrot os u need to be root how to fix plz help me

**Comment by Morsmalleo** [comment]
Switch to your root account on Parrot OS
```
sudo su
```

**Comment by flashbackboi** [comment]
> Switch to your root account on Parrot OS
> 
> ```
> sudo su
> ```
> 
> Then run the setup script
> 
> ```
> ./setup.sh
> ```

thx worked thx man don't close issue maybe it will help other ppl

**Comment by Morsmalleo** [comment]
> > Switch to your root account on Parrot OS
> > ```
> > sudo su
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then run the setup script
> > ```
> > ./setup.sh
> > ```
> 
> thx worked thx man don't close issue maybe it will help other ppl

Glad I could help. You have to close the issue because the problem has been solved for you, if people can't take the time to read closed issues for solutions then that's their problem

**Comment by flashbackboi** [comment]
> > > Switch to your root account on Parrot OS
> > > ```
> > > sudo su
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Then run the setup script
> > > ```
> > > ./setup.sh
> > > ```
> > 
> > 
> > thx worked thx man don't close issue maybe it will help other ppl
> 
> Glad I could help. You have to close the issue because the problem has been solved for you, if people can't take the time to read closed issues for solutions then that's their problem

k man

**Comment by flashbackboi** [comment]
ggs to anyone who did read this
