### ISSUE TITLE
Failed to Add File Size on File Pumper Features :v [11]

### ISSUE THREAD

**Issue by HabilMoonz** [Screetsec/TheFatRat#81]
on The FatRat new version 1.9.2. Codename : Whistle.
When I try to feature File Pumper. If successful in running. but when I look into the payload that I created, the file size has not changed. nothing happened.

**Comment by z3rone** [comment]
I check the fatrat script on the section File Pumper, in the variable $pump call tools/pump.py but on this directory the file empty. Maybe you must tell the file to developer :3

**Comment by Screetsec** [comment]
wkwkwk done , im forgot to upload pump.py

**Comment by Screetsec** [comment]
[pump.py.zip](https://github.com/Screetsec/TheFatRat/files/871733/pump.py.zip)


extract this file and copy this file into folder 

Thefatrat/tools
