### ISSUE TITLE
Application has stopped unexpectedly (bacdoor apk new method)

### ISSUE THREAD

**Issue by rumpelll** [Screetsec/TheFatRat#82]
![screenshot_2017-03-29_04-14-27](https://cloud.githubusercontent.com/assets/26754573/24434161/89baccde-1436-11e7-9618-70115afb6851.png)

Using "backdoor apk new method" (dana).
Testing: Browsers, games app;
Android 2.3.3 and 6.0.1;
 and have the same error.

**Comment by peterpt** [comment]
That issue was already reported in backdoor-apk original repository .
In some apks that can happen , i personally also had the same issue in some apks .

https://github.com/dana-at-cp/backdoor-apk/issues/74

Try to install only the payload generated by metasploit to see if it works .

**Comment by rumpelll** [comment]
Thanks, its problem x32 system (I suspect it), in x64 works without problem.
