### ISSUE TITLE
Failed to locate smali file to hook

### ISSUE THREAD

**Issue by mondgott** [Screetsec/TheFatRat#84]
[*] Decompiling RAT APK file...
 done.
 [*] Decompiling original APK file...
 done.
 [*] Merging permissions of original and payload projects...
 done.
 [*] Running proguard on RAT APK file...
 done.
 [*] Decompiling obfuscated RAT APK file...
 done.
 [*] Creating new directories in original project for RAT smali files...
 done.
 [*] Copying RAT smali files to new directories in original project...
 done.
 [*] Fixing RAT smali files...
 done.
 [*] Obfuscating const-string values in RAT smali files...
 done.
 [*] Locating smali file to hook in original project...
 done.
 [!] Failed to locate smali file to hook

i dont know how to fix this someone can help me?

**Comment by peterpt** [comment]
You have 2 options to compile the apk .
- New backdoor-apk method
- Use old fatrat method

For what you are posting , it looks that you are using the new method .
Use old method , witch will provide you a list of hook points for you to choose .
