### ISSUE TITLE
fatal: destination path 'TheFatRat' already exists and is not an empty directory    

### ISSUE THREAD

**Issue by SopaOwner** [Screetsec/TheFatRat#86]
git clone *URL* and that warning jumps, please help

**Comment by peterpt** [comment]
"Git clone" is used only when you are retrieving fatrat for the first time .

"git pull" is used when you already have fatrat installed in your system , and this comand will do only an update .

You should learn how to work with git before posting simple things as bugs witch are no bugs at all but your lack of knowledge to work with git .

**Comment by SopaOwner** [comment]
Thanks bro...
