### ISSUE TITLE
Failed to Decompile Original APK

### ISSUE THREAD

**Issue by rooks00** [Screetsec/TheFatRat#89]
![fatrat](https://cloud.githubusercontent.com/assets/17588025/24909195/8ebdedf6-1ee0-11e7-952f-dac57aa2a090.png)

I triied it with 5 different APKs. Still get the same error.
What's wrong?

**Comment by peterpt** [comment]
post full apk.log in logs folder on pastebin.com and drop here the link .
Also make sure you are using an original google play apk .

**Comment by rooks00** [comment]
I just renamed that apk. Is that the cause?
And from where can i get original google play apk? I tried apkmirror and it seemed legit.
Thanks for your help!
[WPS.zip](https://github.com/Screetsec/TheFatRat/files/913897/WPS.zip)

**Comment by peterpt** [comment]
i will give a quick look tomorrow to your apk .
You can get google play apks by installing them directly on your android device and then use apk extractor to grab the installed apk .

Apk extractor is also available on google play for installation

**Comment by peterpt** [comment]
Your apk was compiled sucefully in old fatrat method .
Next time try both methods before posting it as a bug .

https://s7.postimg.org/sk6wqsvwr/wps.png

**Comment by rooks00** [comment]
Okay... Thanks for everything.
I'll be careful next time.

**Comment by rooks00** [comment]
Still couldn't make it work. I'm trying android/meterpreter/reverse_tcp .
Tried both old and new method. They're not working for me.

**Comment by rooks00** [comment]
![f1](https://cloud.githubusercontent.com/assets/17588025/24973868/fffb530c-1fdd-11e7-9a26-e68b4077c9fe.png)
![f2](https://cloud.githubusercontent.com/assets/17588025/24973870/0017a304-1fde-11e7-8374-c3149d6288e3.png)
![f3](https://cloud.githubusercontent.com/assets/17588025/24973869/000cdffa-1fde-11e7-9b50-bd040c2cc8bb.png)

**Comment by peterpt** [comment]
Extract first your apk with unzip , the file you uploaded it is in a compressed file .

**Comment by rooks00** [comment]
I think you know that we can only select .apk files when that choice comes up. I extracted the exact zip I uploaded here, then I tried both, new and old, methods on that extracted apk file. Not working.
I'll try it with a different apk and post here.

**Comment by peterpt** [comment]
lets try one thing .
download this file and copy it to /root/.local/share/apktool/framework/1.apk
[1.zip](https://github.com/Screetsec/TheFatRat/files/918832/1.zip)

steps : 
- download the file to anywhere your linux computer .
- Then open terminal and go to the folder where you download this file and write these commands.

mv 1.zip 1.apk 
cp 1.apk  /root/.local/share/apktool/framework/

Then try fatrat again .

**Comment by rooks00** [comment]
It made some progress but still threw an error.
It wasn't working with the old method. And with the new method, the output is shown in the pic.
![f](https://cloud.githubusercontent.com/assets/17588025/24996556/ea03366e-2050-11e7-860e-71d8a8dd77cf.png)
could you do me a favor and make the malicious apk with the LPORT and LHOST as shown in pic?
(android/meterpreter/reverse_tcp)

**Comment by peterpt** [comment]
wait . you will be able to do it by yourself .
I am trying to figure out what is going on there

**Comment by rooks00** [comment]
setup.log
https://pastebin.com/rzAjdDSB

now I'll follow your advice and set up fatrat again.
I'll be back with an update.

**Comment by rooks00** [comment]
Everything is working now. Seems like the main problem was of 1.apk created by apktool.
It's working flawlessly now. Thanks for your help.

**Comment by peterpt** [comment]
great , have fun using fatrat

**Comment by rooks00** [comment]
New problem.... i backdoored 3 different apks and each one of them keeps stopping after installation.

**Comment by peterpt** [comment]
in some apks that could happen , that could be related to a few issues : 
read here : 
https://github.com/dana-at-cp/backdoor-apk/issues/100

and here : 
https://github.com/Screetsec/TheFatRat/issues/82

**Comment by shivsah** [comment]
I'm also having the same issue doesn't works in neither the new or the old method... 
I've got 2 apps for testing Instagram and ShareIt both downloaded from Play Store with the help of apps.evozi
I even tried backdoor-apk even that failed. 
I have already rm -rf TheFatRat
and git cloned it again still no progress...

**Comment by rooks00** [comment]
@shivsah Can you upload a picture of your terminal.
Also, execute this command and tell me the size of 1.apk file present in that directory.

nautilus  /root/.local/share/apktool/framework/

**Comment by shivsah** [comment]
The size is 50 bytes

________________________________

**Comment by shivsah** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/17703895/25115390/9a16da58-2423-11e7-9778-2ebf1c02b864.png)

**Comment by peterpt** [comment]
remove 1.apk file from /root/.local/share/apktool/framework directory using this command .

rm /root/.local/share/apktool/framework/1.apk

My guess for that to happen is that you problably had before an old version of apktool .
Fatrat removes the program itself , but does not remove the android framwork (1.apk) .
What may be happening is that you are using an android framework from an old version into the new apktool 2.2.2 of fatrat .

Removing the file shall solve the issue .

**Comment by shivsah** [comment]
The newer method fails but the old fatrat one works... Thanks for the help...

________________________________

**Comment by shivsah** [comment]
Sorry even the older one failed...I've compressed and uploaded the logs
[logs.zip](https://github.com/Screetsec/TheFatRat/files/927456/logs.zip)

**Comment by rooks00** [comment]
@shivsah try this solution which was provided by peterpt

> download this file and copy it to /root/.local/share/apktool/framework/1.apk
1.zip

steps :

    download the file to anywhere your linux computer .
    Then open terminal and go to the folder where you download this file and write these commands.

mv 1.zip 1.apk
cp 1.apk /root/.local/share/apktool/framework/

Then try fatrat again .

**Comment by peterpt** [comment]
watch this video in 1 hour .
I am currently uploading it .
https://youtu.be/qqFORedd-oE

**Comment by innoroam** [comment]
hi

i see this when try to use payload  after updated kali

negotiated tlv encryption

**Comment by rocky2496** [comment]
help me 
error problem
[run.log](https://github.com/Screetsec/TheFatRat/files/1422307/run.log)

**Comment by JadeAldemir** [comment]
Anyone can tell me to how to fix failed to decompile original Apk In fatrat

**Comment by haxor123456789** [comment]
Failed to decompile original APK file

**Comment by yamitha** [comment]
same failed decompile original apk file

**Comment by kernal1234** [comment]
file does not exist,make sure you wrie the write path of it

**Comment by kernal1234** [comment]
what is that bro i download many apps facing the same error make me tensede what should i do now

**Comment by peterpt** [comment]
Apk merging tools are not working properly , create the apk payload to test in your devices , and stop scrapping the graveyard .
https://www.youtube.com/watch?v=PfUaCz-nzsU
