### ISSUE TITLE
backdoor-factory  -> not found

### ISSUE THREAD

**Issue by ylot0** [Screetsec/TheFatRat#9]
systems:  ubuntu14.04LTS
sudo apt-get update
sudo apt-get install backdoor-factory
No software package found

Prompt during installation backdoor-factory  -> not found。

please

**Comment by Screetsec** [comment]
running setup.sh

**Comment by ylot0** [comment]
TKS

**Comment by joharashu0** [comment]
hey, i have a error.
backdoor-factory -> not ok
how to solve this?

**Comment by peterpt** [comment]
According to kali repository , backdoor factory still exists and it is available to download by apt .
http://http.kali.org/kali/pool/main/b/

This means that your repositories are empty .
Try to figure what is the problem now from what i just told here .

**Comment by joharashu0** [comment]
Can you tell me how to solve this problem?

**Comment by peterpt** [comment]
https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/
