### ISSUE TITLE
What about a protection against stupid people?

### ISSUE THREAD

**Issue by BernardoLima** [Screetsec/TheFatRat#90]
It's sad to see such a great tool being ruined by fucking stupid people that uploads the stubs to online AV websites that distribute samples.

What about implementing an anti stupid people system?
I mean it's open-source but these idiots wouldn't be able to even modify it.

**Comment by peterpt** [comment]
We could do it , but we will not do it .
All we had to do was just to implement an automatic command to write in hosts file the domain address of most av online websites and redirect them to 127.0.0.1 , but user was unable to connect to those websites anymore unless he deleted the hosts file .

We know how to do that , but we will not implement that option .
