### ISSUE TITLE
Ubunutu Question

### ISSUE THREAD

**Issue by shadowman007** [Screetsec/TheFatRat#95]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Can I use thefatrat on ubuntu 16.04 (xenial)?
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJY+U5qAAoJEHJOJVSmaCzpBXoP/1mC4ilIzCL7BYwu5LZIejkk
pLhEzUk2zo9o2GRTR4Oripgu/Xq0fcbuFRlLzAmf/44u3GFZ+O4Z3oRMzTZ09KAE
KAwHEzhNaV58eX4MNPArFtSHmmUnivOpjif6jmG+55KldU+u9xtsi2tWwRGmubPT
/Vvl4rKqG/kY09ajWwfrZH+AZMnHtCA2RppWAwmRoqU0DDPLNcnbXsHWS0aSzcNY
Tq2+ljFOABGavvUMAXQRtZXhaeBIV9KZ+WAeGjJqMtStAkbf0SE23nLa8EatzF5d
bT+cETmRC3kR98Hz8ebyUtrsob/X3gugHSYmbpz+r3FJXZnN7rHJQesIVbEcmZf3
0ZEKgQANmb2W6nHSGCFw4z2ytOWw073hZq94lJYow2UPJTgnhqL2K+WM3VTtyW+r
faXDgiGwkeZVat6JiyGjDS36RjUYyc8XpfbpbliVtjGhaoIBBKx+FnN2Rq80p09A
j6CECKfy+yJ/a0z1s7dVb+oCoOOhmK8pxKyDxaznlvHmYnVWOUNmmwtww9IvNvGB
J/jy+1DMJTx3GgCmuvBpid2Rh/SCP9BxzQ16l9tfyuz6+5epYDdtwyciLGvoYyBe
jYkDih68tMLCNLgA/TR0whDJ1ZZJbEY5I2PLiTYIy1cxfd2NATksGGQGTLHnSfX8
T3AHWnke9YxbzrGKACCH
=w4Ip
-----END PGP SIGNATURE-----

**Comment by peterpt** [comment]
Fatrat works on any debian based distribution .
Specially Ubuntu .
