### ISSUE TITLE
I NEED HELP! (zenity:2089): Gtk-WARNING **: Theme parsing error....

### ISSUE THREAD

**Issue by Rayber1996** [Screetsec/TheFatRat#97]
I use KALI-LINUX 2016.2 on VMware Workstation, I hope that's not the problem.

When I run the file (setup.sh) install some libraries but it stops and throws this.

What can be the solution to this? Please be as detailed as possible in your response since I am new to this and thank you

(zenity:2089): Gtk-WARNING **: Theme parsing error: gtk-contained.css:1525:72: Using one color stop with linear-gradient() is deprecated.

(zenity:2089): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2142:9: Not using units is deprecated. Assuming 'px'.

(zenity:2089): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2142:9: Expected a string.

(zenity:2089): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2549:72: Using one color stop with linear-gradient() is deprecated.

(zenity:2089): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2560:74: Using one color stop with linear-gradient() is deprecated.

(zenity:2089): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2569:71: Using one color stop with linear-gradient() is deprecated.

(zenity:2089): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2578:74: Using one color stop with linear-gradient() is deprecated.

(zenity:2089): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2877:55: Using one color stop with linear-gradient() is deprecated.

(zenity:2089): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3842:8: not a number

(zenity:2089): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3842:17: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(zenity:2089): Gtk-WARNING **: Theme parsing error: gtk-contained.css:4079:14: not a number

(zenity:2089): Gtk-WARNING **: Theme parsing error: gtk-contained.css:4079:14: Expected a string.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:255:67: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:264:69: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:272:72: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:310:54: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:476:68: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:489:70: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:501:67: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:512:70: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:523:68: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:533:70: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:544:67: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:554:70: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:574:72: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:584:72: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:597:69: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:657:72: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:667:74: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:678:58: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:688:72: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:747:71: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:757:73: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:768:58: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:778:72: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:1287:68: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:1296:70: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:1305:67: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:1314:70: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:1525:72: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2142:9: Not using units is deprecated. Assuming 'px'.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2142:9: Expected a string.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2549:72: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2560:74: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2569:71: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2578:74: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2877:55: Using one color stop with linear-gradient() is deprecated.

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3842:8: not a number

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3842:17: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:4079:14: not a number

(zenity:2106): Gtk-WARNING **: Theme parsing error: gtk-contained.css:4079:14: Expected a string.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
 Instalation completed

**Comment by peterpt** [comment]
get a print screen  and post here .
By default zenity popup a bunch of warnings when it is called without some specific terms , but it goes true without any issue .
Maybe you got a new version or an old , just put the print screen here .

**Comment by peterpt** [comment]
It looks that you have a very recent zenity 3.22 , which contains a few bugs .
(this is not a fatrat issue , this is a zenity bug)

~KAli rooling repo
http://http.kali.org/kali/pool/main/z/zenity/

however kali sana have the version 3.14.0
http://old.kali.org/kali/pool/main/z/zenity/

Resuming : those are warnings only and there should be no problem at all .

**Comment by Rayber1996** [comment]
Thank you, you're absolutely right.

Whenever that window appeared I did not try to open the fatrat, now I try and load all the libraries without problems, it's strange but it works!

**Comment by peterpt** [comment]
best way to get rid of those errors is to uninstall zenity by apt-get and compile it from the source code of 3.14 .
Because if you use apt-get to install a program , then next time there is a new version , the system automatically will upgrade your current version .
But if you do it from source code then dpkg will not have information that zenity is installed , and will not upgrade your current source code installation version .

But this last option could be very challenging and it requires some knowledge in linux to compile also 3.14 dependencies , so , avoid it .

other alternative is to invoke apt to install a specific version of zenity .
ex: apt-get install zenity=3.14.0-1

this will work if you have kali sana repositories in your sources list , but if you have only rooling repo links then it will say that version was not found .
However , this will also not work for many long because as long as you have roolling repo in sources list , when you invoke apt-get upgrade or apt-get dist-upgrade , the system will automatically override the 3.14 to 3.22 version .

It is better for you to let is stay as it is right now .
